catch {set_db {port:proj_sorter/in_signature[31]} .original_name {in_signature[31]}}
catch {set_db {port:proj_sorter/in_signature[30]} .original_name {in_signature[30]}}
catch {set_db {port:proj_sorter/in_signature[29]} .original_name {in_signature[29]}}
catch {set_db {port:proj_sorter/in_signature[28]} .original_name {in_signature[28]}}
catch {set_db {port:proj_sorter/in_signature[27]} .original_name {in_signature[27]}}
catch {set_db {port:proj_sorter/in_signature[26]} .original_name {in_signature[26]}}
catch {set_db {port:proj_sorter/in_signature[25]} .original_name {in_signature[25]}}
catch {set_db {port:proj_sorter/in_signature[24]} .original_name {in_signature[24]}}
catch {set_db {port:proj_sorter/in_signature[23]} .original_name {in_signature[23]}}
catch {set_db {port:proj_sorter/in_signature[22]} .original_name {in_signature[22]}}
catch {set_db {port:proj_sorter/in_signature[21]} .original_name {in_signature[21]}}
catch {set_db {port:proj_sorter/in_signature[20]} .original_name {in_signature[20]}}
catch {set_db {port:proj_sorter/in_signature[19]} .original_name {in_signature[19]}}
catch {set_db {port:proj_sorter/in_signature[18]} .original_name {in_signature[18]}}
catch {set_db {port:proj_sorter/in_signature[17]} .original_name {in_signature[17]}}
catch {set_db {port:proj_sorter/in_signature[16]} .original_name {in_signature[16]}}
catch {set_db {port:proj_sorter/in_signature[15]} .original_name {in_signature[15]}}
catch {set_db {port:proj_sorter/in_signature[14]} .original_name {in_signature[14]}}
catch {set_db {port:proj_sorter/in_signature[13]} .original_name {in_signature[13]}}
catch {set_db {port:proj_sorter/in_signature[12]} .original_name {in_signature[12]}}
catch {set_db {port:proj_sorter/in_signature[11]} .original_name {in_signature[11]}}
catch {set_db {port:proj_sorter/in_signature[10]} .original_name {in_signature[10]}}
catch {set_db {port:proj_sorter/in_signature[9]} .original_name {in_signature[9]}}
catch {set_db {port:proj_sorter/in_signature[8]} .original_name {in_signature[8]}}
catch {set_db {port:proj_sorter/in_signature[7]} .original_name {in_signature[7]}}
catch {set_db {port:proj_sorter/in_signature[6]} .original_name {in_signature[6]}}
catch {set_db {port:proj_sorter/in_signature[5]} .original_name {in_signature[5]}}
catch {set_db {port:proj_sorter/in_signature[4]} .original_name {in_signature[4]}}
catch {set_db {port:proj_sorter/in_signature[3]} .original_name {in_signature[3]}}
catch {set_db {port:proj_sorter/in_signature[2]} .original_name {in_signature[2]}}
catch {set_db {port:proj_sorter/in_signature[1]} .original_name {in_signature[1]}}
catch {set_db {port:proj_sorter/in_signature[0]} .original_name {in_signature[0]}}
catch {set_db {port:proj_sorter/in_index[6]} .original_name {in_index[6]}}
catch {set_db {port:proj_sorter/in_index[5]} .original_name {in_index[5]}}
catch {set_db {port:proj_sorter/in_index[4]} .original_name {in_index[4]}}
catch {set_db {port:proj_sorter/in_index[3]} .original_name {in_index[3]}}
catch {set_db {port:proj_sorter/in_index[2]} .original_name {in_index[2]}}
catch {set_db {port:proj_sorter/in_index[1]} .original_name {in_index[1]}}
catch {set_db {port:proj_sorter/in_index[0]} .original_name {in_index[0]}}
catch {set_db port:proj_sorter/rst_n .original_name rst_n}
catch {set_db port:proj_sorter/end_sorting .original_name end_sorting}
catch {set_db port:proj_sorter/clk .original_name clk}
catch {set_db {port:proj_sorter/out_smallest_idx[0][6]} .original_name {out_smallest_idx[0][6]}}
catch {set_db {port:proj_sorter/out_smallest_idx[0][5]} .original_name {out_smallest_idx[0][5]}}
catch {set_db {port:proj_sorter/out_smallest_idx[0][4]} .original_name {out_smallest_idx[0][4]}}
catch {set_db {port:proj_sorter/out_smallest_idx[0][3]} .original_name {out_smallest_idx[0][3]}}
catch {set_db {port:proj_sorter/out_smallest_idx[0][2]} .original_name {out_smallest_idx[0][2]}}
catch {set_db {port:proj_sorter/out_smallest_idx[0][1]} .original_name {out_smallest_idx[0][1]}}
catch {set_db {port:proj_sorter/out_smallest_idx[0][0]} .original_name {out_smallest_idx[0][0]}}
catch {set_db {port:proj_sorter/out_smallest_idx[1][6]} .original_name {out_smallest_idx[1][6]}}
catch {set_db {port:proj_sorter/out_smallest_idx[1][5]} .original_name {out_smallest_idx[1][5]}}
catch {set_db {port:proj_sorter/out_smallest_idx[1][4]} .original_name {out_smallest_idx[1][4]}}
catch {set_db {port:proj_sorter/out_smallest_idx[1][3]} .original_name {out_smallest_idx[1][3]}}
catch {set_db {port:proj_sorter/out_smallest_idx[1][2]} .original_name {out_smallest_idx[1][2]}}
catch {set_db {port:proj_sorter/out_smallest_idx[1][1]} .original_name {out_smallest_idx[1][1]}}
catch {set_db {port:proj_sorter/out_smallest_idx[1][0]} .original_name {out_smallest_idx[1][0]}}
catch {set_db {port:proj_sorter/out_smallest_idx[2][6]} .original_name {out_smallest_idx[2][6]}}
catch {set_db {port:proj_sorter/out_smallest_idx[2][5]} .original_name {out_smallest_idx[2][5]}}
catch {set_db {port:proj_sorter/out_smallest_idx[2][4]} .original_name {out_smallest_idx[2][4]}}
catch {set_db {port:proj_sorter/out_smallest_idx[2][3]} .original_name {out_smallest_idx[2][3]}}
catch {set_db {port:proj_sorter/out_smallest_idx[2][2]} .original_name {out_smallest_idx[2][2]}}
catch {set_db {port:proj_sorter/out_smallest_idx[2][1]} .original_name {out_smallest_idx[2][1]}}
catch {set_db {port:proj_sorter/out_smallest_idx[2][0]} .original_name {out_smallest_idx[2][0]}}
catch {set_db {port:proj_sorter/out_smallest_idx[3][6]} .original_name {out_smallest_idx[3][6]}}
catch {set_db {port:proj_sorter/out_smallest_idx[3][5]} .original_name {out_smallest_idx[3][5]}}
catch {set_db {port:proj_sorter/out_smallest_idx[3][4]} .original_name {out_smallest_idx[3][4]}}
catch {set_db {port:proj_sorter/out_smallest_idx[3][3]} .original_name {out_smallest_idx[3][3]}}
catch {set_db {port:proj_sorter/out_smallest_idx[3][2]} .original_name {out_smallest_idx[3][2]}}
catch {set_db {port:proj_sorter/out_smallest_idx[3][1]} .original_name {out_smallest_idx[3][1]}}
catch {set_db {port:proj_sorter/out_smallest_idx[3][0]} .original_name {out_smallest_idx[3][0]}}
catch {set_db port:proj_sorter/sort_valid .original_name sort_valid}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][index][0]/Q} .original_name {smallest_idx_curr[0].index[0]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][index][1]/Q} .original_name {smallest_idx_curr[0].index[1]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][index][2]/Q} .original_name {smallest_idx_curr[0].index[2]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][index][3]/Q} .original_name {smallest_idx_curr[0].index[3]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][index][4]/Q} .original_name {smallest_idx_curr[0].index[4]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][index][5]/Q} .original_name {smallest_idx_curr[0].index[5]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][index][6]/Q} .original_name {smallest_idx_curr[0].index[6]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][0]/Q} .original_name {smallest_idx_curr[0].signature[0]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][1]/Q} .original_name {smallest_idx_curr[0].signature[1]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][2]/Q} .original_name {smallest_idx_curr[0].signature[2]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][3]/Q} .original_name {smallest_idx_curr[0].signature[3]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][4]/Q} .original_name {smallest_idx_curr[0].signature[4]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][5]/Q} .original_name {smallest_idx_curr[0].signature[5]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][6]/Q} .original_name {smallest_idx_curr[0].signature[6]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][7]/Q} .original_name {smallest_idx_curr[0].signature[7]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][8]/Q} .original_name {smallest_idx_curr[0].signature[8]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][9]/Q} .original_name {smallest_idx_curr[0].signature[9]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][10]/Q} .original_name {smallest_idx_curr[0].signature[10]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][11]/Q} .original_name {smallest_idx_curr[0].signature[11]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][12]/Q} .original_name {smallest_idx_curr[0].signature[12]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][13]/Q} .original_name {smallest_idx_curr[0].signature[13]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][14]/Q} .original_name {smallest_idx_curr[0].signature[14]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][15]/Q} .original_name {smallest_idx_curr[0].signature[15]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][16]/Q} .original_name {smallest_idx_curr[0].signature[16]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][17]/Q} .original_name {smallest_idx_curr[0].signature[17]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][18]/Q} .original_name {smallest_idx_curr[0].signature[18]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][19]/Q} .original_name {smallest_idx_curr[0].signature[19]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][20]/Q} .original_name {smallest_idx_curr[0].signature[20]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][21]/Q} .original_name {smallest_idx_curr[0].signature[21]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][22]/Q} .original_name {smallest_idx_curr[0].signature[22]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][23]/Q} .original_name {smallest_idx_curr[0].signature[23]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][24]/Q} .original_name {smallest_idx_curr[0].signature[24]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][25]/Q} .original_name {smallest_idx_curr[0].signature[25]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][26]/Q} .original_name {smallest_idx_curr[0].signature[26]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][27]/Q} .original_name {smallest_idx_curr[0].signature[27]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][28]/Q} .original_name {smallest_idx_curr[0].signature[28]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][29]/Q} .original_name {smallest_idx_curr[0].signature[29]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][30]/Q} .original_name {smallest_idx_curr[0].signature[30]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[0][signature][31]/Q} .original_name {smallest_idx_curr[0].signature[31]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][index][0]/Q} .original_name {smallest_idx_curr[1].index[0]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][index][1]/Q} .original_name {smallest_idx_curr[1].index[1]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][index][2]/Q} .original_name {smallest_idx_curr[1].index[2]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][index][3]/Q} .original_name {smallest_idx_curr[1].index[3]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][index][4]/Q} .original_name {smallest_idx_curr[1].index[4]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][index][5]/Q} .original_name {smallest_idx_curr[1].index[5]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][index][6]/Q} .original_name {smallest_idx_curr[1].index[6]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][0]/Q} .original_name {smallest_idx_curr[1].signature[0]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][1]/Q} .original_name {smallest_idx_curr[1].signature[1]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][2]/Q} .original_name {smallest_idx_curr[1].signature[2]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][3]/Q} .original_name {smallest_idx_curr[1].signature[3]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][4]/Q} .original_name {smallest_idx_curr[1].signature[4]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][5]/Q} .original_name {smallest_idx_curr[1].signature[5]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][6]/Q} .original_name {smallest_idx_curr[1].signature[6]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][7]/Q} .original_name {smallest_idx_curr[1].signature[7]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][8]/Q} .original_name {smallest_idx_curr[1].signature[8]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][9]/Q} .original_name {smallest_idx_curr[1].signature[9]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][10]/Q} .original_name {smallest_idx_curr[1].signature[10]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][11]/Q} .original_name {smallest_idx_curr[1].signature[11]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][12]/Q} .original_name {smallest_idx_curr[1].signature[12]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][13]/Q} .original_name {smallest_idx_curr[1].signature[13]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][14]/Q} .original_name {smallest_idx_curr[1].signature[14]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][15]/Q} .original_name {smallest_idx_curr[1].signature[15]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][16]/Q} .original_name {smallest_idx_curr[1].signature[16]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][17]/Q} .original_name {smallest_idx_curr[1].signature[17]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][18]/Q} .original_name {smallest_idx_curr[1].signature[18]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][19]/Q} .original_name {smallest_idx_curr[1].signature[19]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][20]/Q} .original_name {smallest_idx_curr[1].signature[20]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][21]/Q} .original_name {smallest_idx_curr[1].signature[21]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][22]/Q} .original_name {smallest_idx_curr[1].signature[22]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][23]/Q} .original_name {smallest_idx_curr[1].signature[23]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][24]/Q} .original_name {smallest_idx_curr[1].signature[24]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][25]/Q} .original_name {smallest_idx_curr[1].signature[25]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][26]/Q} .original_name {smallest_idx_curr[1].signature[26]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][27]/Q} .original_name {smallest_idx_curr[1].signature[27]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][28]/Q} .original_name {smallest_idx_curr[1].signature[28]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][29]/Q} .original_name {smallest_idx_curr[1].signature[29]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][30]/Q} .original_name {smallest_idx_curr[1].signature[30]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[1][signature][31]/Q} .original_name {smallest_idx_curr[1].signature[31]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][index][0]/Q} .original_name {smallest_idx_curr[2].index[0]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][index][1]/Q} .original_name {smallest_idx_curr[2].index[1]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][index][2]/Q} .original_name {smallest_idx_curr[2].index[2]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][index][3]/Q} .original_name {smallest_idx_curr[2].index[3]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][index][4]/Q} .original_name {smallest_idx_curr[2].index[4]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][index][5]/Q} .original_name {smallest_idx_curr[2].index[5]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][index][6]/Q} .original_name {smallest_idx_curr[2].index[6]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][0]/Q} .original_name {smallest_idx_curr[2].signature[0]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][1]/Q} .original_name {smallest_idx_curr[2].signature[1]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][2]/Q} .original_name {smallest_idx_curr[2].signature[2]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][3]/Q} .original_name {smallest_idx_curr[2].signature[3]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][4]/Q} .original_name {smallest_idx_curr[2].signature[4]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][5]/Q} .original_name {smallest_idx_curr[2].signature[5]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][6]/Q} .original_name {smallest_idx_curr[2].signature[6]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][7]/Q} .original_name {smallest_idx_curr[2].signature[7]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][8]/Q} .original_name {smallest_idx_curr[2].signature[8]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][9]/Q} .original_name {smallest_idx_curr[2].signature[9]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][10]/Q} .original_name {smallest_idx_curr[2].signature[10]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][11]/Q} .original_name {smallest_idx_curr[2].signature[11]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][12]/Q} .original_name {smallest_idx_curr[2].signature[12]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][13]/Q} .original_name {smallest_idx_curr[2].signature[13]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][14]/Q} .original_name {smallest_idx_curr[2].signature[14]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][15]/Q} .original_name {smallest_idx_curr[2].signature[15]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][16]/Q} .original_name {smallest_idx_curr[2].signature[16]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][17]/Q} .original_name {smallest_idx_curr[2].signature[17]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][18]/Q} .original_name {smallest_idx_curr[2].signature[18]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][19]/Q} .original_name {smallest_idx_curr[2].signature[19]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][20]/Q} .original_name {smallest_idx_curr[2].signature[20]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][21]/Q} .original_name {smallest_idx_curr[2].signature[21]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][22]/Q} .original_name {smallest_idx_curr[2].signature[22]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][23]/Q} .original_name {smallest_idx_curr[2].signature[23]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][24]/Q} .original_name {smallest_idx_curr[2].signature[24]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][25]/Q} .original_name {smallest_idx_curr[2].signature[25]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][26]/Q} .original_name {smallest_idx_curr[2].signature[26]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][27]/Q} .original_name {smallest_idx_curr[2].signature[27]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][28]/Q} .original_name {smallest_idx_curr[2].signature[28]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][29]/Q} .original_name {smallest_idx_curr[2].signature[29]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][30]/Q} .original_name {smallest_idx_curr[2].signature[30]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[2][signature][31]/Q} .original_name {smallest_idx_curr[2].signature[31]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][index][0]/Q} .original_name {smallest_idx_curr[3].index[0]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][index][1]/Q} .original_name {smallest_idx_curr[3].index[1]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][index][2]/Q} .original_name {smallest_idx_curr[3].index[2]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][index][3]/Q} .original_name {smallest_idx_curr[3].index[3]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][index][4]/Q} .original_name {smallest_idx_curr[3].index[4]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][index][5]/Q} .original_name {smallest_idx_curr[3].index[5]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][index][6]/Q} .original_name {smallest_idx_curr[3].index[6]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][0]/Q} .original_name {smallest_idx_curr[3].signature[0]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][1]/Q} .original_name {smallest_idx_curr[3].signature[1]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][2]/Q} .original_name {smallest_idx_curr[3].signature[2]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][3]/Q} .original_name {smallest_idx_curr[3].signature[3]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][4]/Q} .original_name {smallest_idx_curr[3].signature[4]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][5]/Q} .original_name {smallest_idx_curr[3].signature[5]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][6]/Q} .original_name {smallest_idx_curr[3].signature[6]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][7]/Q} .original_name {smallest_idx_curr[3].signature[7]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][8]/Q} .original_name {smallest_idx_curr[3].signature[8]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][9]/Q} .original_name {smallest_idx_curr[3].signature[9]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][10]/Q} .original_name {smallest_idx_curr[3].signature[10]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][11]/Q} .original_name {smallest_idx_curr[3].signature[11]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][12]/Q} .original_name {smallest_idx_curr[3].signature[12]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][13]/Q} .original_name {smallest_idx_curr[3].signature[13]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][14]/Q} .original_name {smallest_idx_curr[3].signature[14]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][15]/Q} .original_name {smallest_idx_curr[3].signature[15]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][16]/Q} .original_name {smallest_idx_curr[3].signature[16]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][17]/Q} .original_name {smallest_idx_curr[3].signature[17]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][18]/Q} .original_name {smallest_idx_curr[3].signature[18]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][19]/Q} .original_name {smallest_idx_curr[3].signature[19]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][20]/Q} .original_name {smallest_idx_curr[3].signature[20]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][21]/Q} .original_name {smallest_idx_curr[3].signature[21]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][22]/Q} .original_name {smallest_idx_curr[3].signature[22]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][23]/Q} .original_name {smallest_idx_curr[3].signature[23]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][24]/Q} .original_name {smallest_idx_curr[3].signature[24]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][25]/Q} .original_name {smallest_idx_curr[3].signature[25]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][26]/Q} .original_name {smallest_idx_curr[3].signature[26]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][27]/Q} .original_name {smallest_idx_curr[3].signature[27]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][28]/Q} .original_name {smallest_idx_curr[3].signature[28]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][29]/Q} .original_name {smallest_idx_curr[3].signature[29]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][30]/Q} .original_name {smallest_idx_curr[3].signature[30]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_curr_reg[3][signature][31]/Q} .original_name {smallest_idx_curr[3].signature[31]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][index][0]/Q} .original_name {smallest_idx_next[0].index[0]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][index][1]/Q} .original_name {smallest_idx_next[0].index[1]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][index][2]/Q} .original_name {smallest_idx_next[0].index[2]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][index][3]/Q} .original_name {smallest_idx_next[0].index[3]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][index][4]/Q} .original_name {smallest_idx_next[0].index[4]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][index][5]/Q} .original_name {smallest_idx_next[0].index[5]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][index][6]/Q} .original_name {smallest_idx_next[0].index[6]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][0]/Q} .original_name {smallest_idx_next[0].signature[0]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][1]/Q} .original_name {smallest_idx_next[0].signature[1]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][2]/Q} .original_name {smallest_idx_next[0].signature[2]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][3]/Q} .original_name {smallest_idx_next[0].signature[3]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][4]/Q} .original_name {smallest_idx_next[0].signature[4]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][5]/Q} .original_name {smallest_idx_next[0].signature[5]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][6]/Q} .original_name {smallest_idx_next[0].signature[6]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][7]/Q} .original_name {smallest_idx_next[0].signature[7]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][8]/Q} .original_name {smallest_idx_next[0].signature[8]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][9]/Q} .original_name {smallest_idx_next[0].signature[9]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][10]/Q} .original_name {smallest_idx_next[0].signature[10]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][11]/Q} .original_name {smallest_idx_next[0].signature[11]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][12]/Q} .original_name {smallest_idx_next[0].signature[12]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][13]/Q} .original_name {smallest_idx_next[0].signature[13]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][14]/Q} .original_name {smallest_idx_next[0].signature[14]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][15]/Q} .original_name {smallest_idx_next[0].signature[15]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][16]/Q} .original_name {smallest_idx_next[0].signature[16]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][17]/Q} .original_name {smallest_idx_next[0].signature[17]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][18]/Q} .original_name {smallest_idx_next[0].signature[18]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][19]/Q} .original_name {smallest_idx_next[0].signature[19]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][20]/Q} .original_name {smallest_idx_next[0].signature[20]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][21]/Q} .original_name {smallest_idx_next[0].signature[21]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][22]/Q} .original_name {smallest_idx_next[0].signature[22]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][23]/Q} .original_name {smallest_idx_next[0].signature[23]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][24]/Q} .original_name {smallest_idx_next[0].signature[24]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][25]/Q} .original_name {smallest_idx_next[0].signature[25]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][26]/Q} .original_name {smallest_idx_next[0].signature[26]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][27]/Q} .original_name {smallest_idx_next[0].signature[27]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][28]/Q} .original_name {smallest_idx_next[0].signature[28]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][29]/Q} .original_name {smallest_idx_next[0].signature[29]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][30]/Q} .original_name {smallest_idx_next[0].signature[30]/q}}
catch {set_db {pin:proj_sorter/smallest_idx_next_reg[0][signature][31]/Q} .original_name {smallest_idx_next[0].signature[31]/q}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][index][0]} .original_name {{smallest_idx_curr[0].index[0]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][index][1]} .original_name {{smallest_idx_curr[0].index[1]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][index][2]} .original_name {{smallest_idx_curr[0].index[2]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][index][3]} .original_name {{smallest_idx_curr[0].index[3]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][index][4]} .original_name {{smallest_idx_curr[0].index[4]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][index][5]} .original_name {{smallest_idx_curr[0].index[5]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][index][6]} .original_name {{smallest_idx_curr[0].index[6]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][0]} .original_name {{smallest_idx_curr[0].signature[0]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][1]} .original_name {{smallest_idx_curr[0].signature[1]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][2]} .original_name {{smallest_idx_curr[0].signature[2]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][3]} .original_name {{smallest_idx_curr[0].signature[3]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][4]} .original_name {{smallest_idx_curr[0].signature[4]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][5]} .original_name {{smallest_idx_curr[0].signature[5]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][6]} .original_name {{smallest_idx_curr[0].signature[6]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][7]} .original_name {{smallest_idx_curr[0].signature[7]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][8]} .original_name {{smallest_idx_curr[0].signature[8]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][9]} .original_name {{smallest_idx_curr[0].signature[9]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][10]} .original_name {{smallest_idx_curr[0].signature[10]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][11]} .original_name {{smallest_idx_curr[0].signature[11]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][12]} .original_name {{smallest_idx_curr[0].signature[12]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][13]} .original_name {{smallest_idx_curr[0].signature[13]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][14]} .original_name {{smallest_idx_curr[0].signature[14]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][15]} .original_name {{smallest_idx_curr[0].signature[15]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][16]} .original_name {{smallest_idx_curr[0].signature[16]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][17]} .original_name {{smallest_idx_curr[0].signature[17]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][18]} .original_name {{smallest_idx_curr[0].signature[18]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][19]} .original_name {{smallest_idx_curr[0].signature[19]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][20]} .original_name {{smallest_idx_curr[0].signature[20]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][21]} .original_name {{smallest_idx_curr[0].signature[21]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][22]} .original_name {{smallest_idx_curr[0].signature[22]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][23]} .original_name {{smallest_idx_curr[0].signature[23]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][24]} .original_name {{smallest_idx_curr[0].signature[24]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][25]} .original_name {{smallest_idx_curr[0].signature[25]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][26]} .original_name {{smallest_idx_curr[0].signature[26]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][27]} .original_name {{smallest_idx_curr[0].signature[27]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][28]} .original_name {{smallest_idx_curr[0].signature[28]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][29]} .original_name {{smallest_idx_curr[0].signature[29]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][30]} .original_name {{smallest_idx_curr[0].signature[30]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[0][signature][31]} .original_name {{smallest_idx_curr[0].signature[31]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][index][0]} .original_name {{smallest_idx_curr[1].index[0]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][index][1]} .original_name {{smallest_idx_curr[1].index[1]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][index][2]} .original_name {{smallest_idx_curr[1].index[2]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][index][3]} .original_name {{smallest_idx_curr[1].index[3]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][index][4]} .original_name {{smallest_idx_curr[1].index[4]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][index][5]} .original_name {{smallest_idx_curr[1].index[5]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][index][6]} .original_name {{smallest_idx_curr[1].index[6]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][0]} .original_name {{smallest_idx_curr[1].signature[0]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][1]} .original_name {{smallest_idx_curr[1].signature[1]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][2]} .original_name {{smallest_idx_curr[1].signature[2]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][3]} .original_name {{smallest_idx_curr[1].signature[3]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][4]} .original_name {{smallest_idx_curr[1].signature[4]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][5]} .original_name {{smallest_idx_curr[1].signature[5]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][6]} .original_name {{smallest_idx_curr[1].signature[6]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][7]} .original_name {{smallest_idx_curr[1].signature[7]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][8]} .original_name {{smallest_idx_curr[1].signature[8]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][9]} .original_name {{smallest_idx_curr[1].signature[9]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][10]} .original_name {{smallest_idx_curr[1].signature[10]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][11]} .original_name {{smallest_idx_curr[1].signature[11]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][12]} .original_name {{smallest_idx_curr[1].signature[12]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][13]} .original_name {{smallest_idx_curr[1].signature[13]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][14]} .original_name {{smallest_idx_curr[1].signature[14]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][15]} .original_name {{smallest_idx_curr[1].signature[15]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][16]} .original_name {{smallest_idx_curr[1].signature[16]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][17]} .original_name {{smallest_idx_curr[1].signature[17]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][18]} .original_name {{smallest_idx_curr[1].signature[18]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][19]} .original_name {{smallest_idx_curr[1].signature[19]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][20]} .original_name {{smallest_idx_curr[1].signature[20]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][21]} .original_name {{smallest_idx_curr[1].signature[21]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][22]} .original_name {{smallest_idx_curr[1].signature[22]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][23]} .original_name {{smallest_idx_curr[1].signature[23]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][24]} .original_name {{smallest_idx_curr[1].signature[24]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][25]} .original_name {{smallest_idx_curr[1].signature[25]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][26]} .original_name {{smallest_idx_curr[1].signature[26]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][27]} .original_name {{smallest_idx_curr[1].signature[27]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][28]} .original_name {{smallest_idx_curr[1].signature[28]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][29]} .original_name {{smallest_idx_curr[1].signature[29]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][30]} .original_name {{smallest_idx_curr[1].signature[30]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[1][signature][31]} .original_name {{smallest_idx_curr[1].signature[31]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][index][0]} .original_name {{smallest_idx_curr[2].index[0]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][index][1]} .original_name {{smallest_idx_curr[2].index[1]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][index][2]} .original_name {{smallest_idx_curr[2].index[2]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][index][3]} .original_name {{smallest_idx_curr[2].index[3]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][index][4]} .original_name {{smallest_idx_curr[2].index[4]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][index][5]} .original_name {{smallest_idx_curr[2].index[5]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][index][6]} .original_name {{smallest_idx_curr[2].index[6]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][0]} .original_name {{smallest_idx_curr[2].signature[0]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][1]} .original_name {{smallest_idx_curr[2].signature[1]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][2]} .original_name {{smallest_idx_curr[2].signature[2]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][3]} .original_name {{smallest_idx_curr[2].signature[3]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][4]} .original_name {{smallest_idx_curr[2].signature[4]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][5]} .original_name {{smallest_idx_curr[2].signature[5]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][6]} .original_name {{smallest_idx_curr[2].signature[6]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][7]} .original_name {{smallest_idx_curr[2].signature[7]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][8]} .original_name {{smallest_idx_curr[2].signature[8]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][9]} .original_name {{smallest_idx_curr[2].signature[9]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][10]} .original_name {{smallest_idx_curr[2].signature[10]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][11]} .original_name {{smallest_idx_curr[2].signature[11]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][12]} .original_name {{smallest_idx_curr[2].signature[12]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][13]} .original_name {{smallest_idx_curr[2].signature[13]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][14]} .original_name {{smallest_idx_curr[2].signature[14]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][15]} .original_name {{smallest_idx_curr[2].signature[15]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][16]} .original_name {{smallest_idx_curr[2].signature[16]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][17]} .original_name {{smallest_idx_curr[2].signature[17]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][18]} .original_name {{smallest_idx_curr[2].signature[18]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][19]} .original_name {{smallest_idx_curr[2].signature[19]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][20]} .original_name {{smallest_idx_curr[2].signature[20]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][21]} .original_name {{smallest_idx_curr[2].signature[21]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][22]} .original_name {{smallest_idx_curr[2].signature[22]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][23]} .original_name {{smallest_idx_curr[2].signature[23]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][24]} .original_name {{smallest_idx_curr[2].signature[24]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][25]} .original_name {{smallest_idx_curr[2].signature[25]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][26]} .original_name {{smallest_idx_curr[2].signature[26]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][27]} .original_name {{smallest_idx_curr[2].signature[27]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][28]} .original_name {{smallest_idx_curr[2].signature[28]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][29]} .original_name {{smallest_idx_curr[2].signature[29]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][30]} .original_name {{smallest_idx_curr[2].signature[30]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[2][signature][31]} .original_name {{smallest_idx_curr[2].signature[31]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][index][0]} .original_name {{smallest_idx_curr[3].index[0]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][index][1]} .original_name {{smallest_idx_curr[3].index[1]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][index][2]} .original_name {{smallest_idx_curr[3].index[2]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][index][3]} .original_name {{smallest_idx_curr[3].index[3]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][index][4]} .original_name {{smallest_idx_curr[3].index[4]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][index][5]} .original_name {{smallest_idx_curr[3].index[5]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][index][6]} .original_name {{smallest_idx_curr[3].index[6]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][0]} .original_name {{smallest_idx_curr[3].signature[0]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][1]} .original_name {{smallest_idx_curr[3].signature[1]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][2]} .original_name {{smallest_idx_curr[3].signature[2]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][3]} .original_name {{smallest_idx_curr[3].signature[3]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][4]} .original_name {{smallest_idx_curr[3].signature[4]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][5]} .original_name {{smallest_idx_curr[3].signature[5]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][6]} .original_name {{smallest_idx_curr[3].signature[6]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][7]} .original_name {{smallest_idx_curr[3].signature[7]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][8]} .original_name {{smallest_idx_curr[3].signature[8]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][9]} .original_name {{smallest_idx_curr[3].signature[9]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][10]} .original_name {{smallest_idx_curr[3].signature[10]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][11]} .original_name {{smallest_idx_curr[3].signature[11]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][12]} .original_name {{smallest_idx_curr[3].signature[12]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][13]} .original_name {{smallest_idx_curr[3].signature[13]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][14]} .original_name {{smallest_idx_curr[3].signature[14]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][15]} .original_name {{smallest_idx_curr[3].signature[15]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][16]} .original_name {{smallest_idx_curr[3].signature[16]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][17]} .original_name {{smallest_idx_curr[3].signature[17]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][18]} .original_name {{smallest_idx_curr[3].signature[18]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][19]} .original_name {{smallest_idx_curr[3].signature[19]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][20]} .original_name {{smallest_idx_curr[3].signature[20]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][21]} .original_name {{smallest_idx_curr[3].signature[21]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][22]} .original_name {{smallest_idx_curr[3].signature[22]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][23]} .original_name {{smallest_idx_curr[3].signature[23]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][24]} .original_name {{smallest_idx_curr[3].signature[24]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][25]} .original_name {{smallest_idx_curr[3].signature[25]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][26]} .original_name {{smallest_idx_curr[3].signature[26]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][27]} .original_name {{smallest_idx_curr[3].signature[27]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][28]} .original_name {{smallest_idx_curr[3].signature[28]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][29]} .original_name {{smallest_idx_curr[3].signature[29]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][30]} .original_name {{smallest_idx_curr[3].signature[30]}}}
catch {set_db {inst:proj_sorter/smallest_idx_curr_reg[3][signature][31]} .original_name {{smallest_idx_curr[3].signature[31]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][index][0]} .original_name {{smallest_idx_next[0].index[0]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][index][1]} .original_name {{smallest_idx_next[0].index[1]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][index][2]} .original_name {{smallest_idx_next[0].index[2]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][index][3]} .original_name {{smallest_idx_next[0].index[3]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][index][4]} .original_name {{smallest_idx_next[0].index[4]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][index][5]} .original_name {{smallest_idx_next[0].index[5]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][index][6]} .original_name {{smallest_idx_next[0].index[6]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][0]} .original_name {{smallest_idx_next[0].signature[0]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][1]} .original_name {{smallest_idx_next[0].signature[1]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][2]} .original_name {{smallest_idx_next[0].signature[2]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][3]} .original_name {{smallest_idx_next[0].signature[3]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][4]} .original_name {{smallest_idx_next[0].signature[4]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][5]} .original_name {{smallest_idx_next[0].signature[5]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][6]} .original_name {{smallest_idx_next[0].signature[6]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][7]} .original_name {{smallest_idx_next[0].signature[7]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][8]} .original_name {{smallest_idx_next[0].signature[8]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][9]} .original_name {{smallest_idx_next[0].signature[9]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][10]} .original_name {{smallest_idx_next[0].signature[10]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][11]} .original_name {{smallest_idx_next[0].signature[11]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][12]} .original_name {{smallest_idx_next[0].signature[12]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][13]} .original_name {{smallest_idx_next[0].signature[13]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][14]} .original_name {{smallest_idx_next[0].signature[14]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][15]} .original_name {{smallest_idx_next[0].signature[15]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][16]} .original_name {{smallest_idx_next[0].signature[16]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][17]} .original_name {{smallest_idx_next[0].signature[17]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][18]} .original_name {{smallest_idx_next[0].signature[18]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][19]} .original_name {{smallest_idx_next[0].signature[19]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][20]} .original_name {{smallest_idx_next[0].signature[20]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][21]} .original_name {{smallest_idx_next[0].signature[21]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][22]} .original_name {{smallest_idx_next[0].signature[22]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][23]} .original_name {{smallest_idx_next[0].signature[23]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][24]} .original_name {{smallest_idx_next[0].signature[24]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][25]} .original_name {{smallest_idx_next[0].signature[25]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][26]} .original_name {{smallest_idx_next[0].signature[26]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][27]} .original_name {{smallest_idx_next[0].signature[27]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][28]} .original_name {{smallest_idx_next[0].signature[28]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][29]} .original_name {{smallest_idx_next[0].signature[29]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][30]} .original_name {{smallest_idx_next[0].signature[30]}}}
catch {set_db {inst:proj_sorter/smallest_idx_next_reg[0][signature][31]} .original_name {{smallest_idx_next[0].signature[31]}}}
