
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point in_data[1] in_data[1] -type PI PI
add mapped point in_data[0] in_data[0] -type PI PI
add mapped point start start -type PI PI

//output ports
add mapped point out_fragment[255] out_fragment[255] -type PO PO
add mapped point out_fragment[254] out_fragment[254] -type PO PO
add mapped point out_fragment[253] out_fragment[253] -type PO PO
add mapped point out_fragment[252] out_fragment[252] -type PO PO
add mapped point out_fragment[251] out_fragment[251] -type PO PO
add mapped point out_fragment[250] out_fragment[250] -type PO PO
add mapped point out_fragment[249] out_fragment[249] -type PO PO
add mapped point out_fragment[248] out_fragment[248] -type PO PO
add mapped point out_fragment[247] out_fragment[247] -type PO PO
add mapped point out_fragment[246] out_fragment[246] -type PO PO
add mapped point out_fragment[245] out_fragment[245] -type PO PO
add mapped point out_fragment[244] out_fragment[244] -type PO PO
add mapped point out_fragment[243] out_fragment[243] -type PO PO
add mapped point out_fragment[242] out_fragment[242] -type PO PO
add mapped point out_fragment[241] out_fragment[241] -type PO PO
add mapped point out_fragment[240] out_fragment[240] -type PO PO
add mapped point out_fragment[239] out_fragment[239] -type PO PO
add mapped point out_fragment[238] out_fragment[238] -type PO PO
add mapped point out_fragment[237] out_fragment[237] -type PO PO
add mapped point out_fragment[236] out_fragment[236] -type PO PO
add mapped point out_fragment[235] out_fragment[235] -type PO PO
add mapped point out_fragment[234] out_fragment[234] -type PO PO
add mapped point out_fragment[233] out_fragment[233] -type PO PO
add mapped point out_fragment[232] out_fragment[232] -type PO PO
add mapped point out_fragment[231] out_fragment[231] -type PO PO
add mapped point out_fragment[230] out_fragment[230] -type PO PO
add mapped point out_fragment[229] out_fragment[229] -type PO PO
add mapped point out_fragment[228] out_fragment[228] -type PO PO
add mapped point out_fragment[227] out_fragment[227] -type PO PO
add mapped point out_fragment[226] out_fragment[226] -type PO PO
add mapped point out_fragment[225] out_fragment[225] -type PO PO
add mapped point out_fragment[224] out_fragment[224] -type PO PO
add mapped point out_fragment[223] out_fragment[223] -type PO PO
add mapped point out_fragment[222] out_fragment[222] -type PO PO
add mapped point out_fragment[221] out_fragment[221] -type PO PO
add mapped point out_fragment[220] out_fragment[220] -type PO PO
add mapped point out_fragment[219] out_fragment[219] -type PO PO
add mapped point out_fragment[218] out_fragment[218] -type PO PO
add mapped point out_fragment[217] out_fragment[217] -type PO PO
add mapped point out_fragment[216] out_fragment[216] -type PO PO
add mapped point out_fragment[215] out_fragment[215] -type PO PO
add mapped point out_fragment[214] out_fragment[214] -type PO PO
add mapped point out_fragment[213] out_fragment[213] -type PO PO
add mapped point out_fragment[212] out_fragment[212] -type PO PO
add mapped point out_fragment[211] out_fragment[211] -type PO PO
add mapped point out_fragment[210] out_fragment[210] -type PO PO
add mapped point out_fragment[209] out_fragment[209] -type PO PO
add mapped point out_fragment[208] out_fragment[208] -type PO PO
add mapped point out_fragment[207] out_fragment[207] -type PO PO
add mapped point out_fragment[206] out_fragment[206] -type PO PO
add mapped point out_fragment[205] out_fragment[205] -type PO PO
add mapped point out_fragment[204] out_fragment[204] -type PO PO
add mapped point out_fragment[203] out_fragment[203] -type PO PO
add mapped point out_fragment[202] out_fragment[202] -type PO PO
add mapped point out_fragment[201] out_fragment[201] -type PO PO
add mapped point out_fragment[200] out_fragment[200] -type PO PO
add mapped point out_fragment[199] out_fragment[199] -type PO PO
add mapped point out_fragment[198] out_fragment[198] -type PO PO
add mapped point out_fragment[197] out_fragment[197] -type PO PO
add mapped point out_fragment[196] out_fragment[196] -type PO PO
add mapped point out_fragment[195] out_fragment[195] -type PO PO
add mapped point out_fragment[194] out_fragment[194] -type PO PO
add mapped point out_fragment[193] out_fragment[193] -type PO PO
add mapped point out_fragment[192] out_fragment[192] -type PO PO
add mapped point out_fragment[191] out_fragment[191] -type PO PO
add mapped point out_fragment[190] out_fragment[190] -type PO PO
add mapped point out_fragment[189] out_fragment[189] -type PO PO
add mapped point out_fragment[188] out_fragment[188] -type PO PO
add mapped point out_fragment[187] out_fragment[187] -type PO PO
add mapped point out_fragment[186] out_fragment[186] -type PO PO
add mapped point out_fragment[185] out_fragment[185] -type PO PO
add mapped point out_fragment[184] out_fragment[184] -type PO PO
add mapped point out_fragment[183] out_fragment[183] -type PO PO
add mapped point out_fragment[182] out_fragment[182] -type PO PO
add mapped point out_fragment[181] out_fragment[181] -type PO PO
add mapped point out_fragment[180] out_fragment[180] -type PO PO
add mapped point out_fragment[179] out_fragment[179] -type PO PO
add mapped point out_fragment[178] out_fragment[178] -type PO PO
add mapped point out_fragment[177] out_fragment[177] -type PO PO
add mapped point out_fragment[176] out_fragment[176] -type PO PO
add mapped point out_fragment[175] out_fragment[175] -type PO PO
add mapped point out_fragment[174] out_fragment[174] -type PO PO
add mapped point out_fragment[173] out_fragment[173] -type PO PO
add mapped point out_fragment[172] out_fragment[172] -type PO PO
add mapped point out_fragment[171] out_fragment[171] -type PO PO
add mapped point out_fragment[170] out_fragment[170] -type PO PO
add mapped point out_fragment[169] out_fragment[169] -type PO PO
add mapped point out_fragment[168] out_fragment[168] -type PO PO
add mapped point out_fragment[167] out_fragment[167] -type PO PO
add mapped point out_fragment[166] out_fragment[166] -type PO PO
add mapped point out_fragment[165] out_fragment[165] -type PO PO
add mapped point out_fragment[164] out_fragment[164] -type PO PO
add mapped point out_fragment[163] out_fragment[163] -type PO PO
add mapped point out_fragment[162] out_fragment[162] -type PO PO
add mapped point out_fragment[161] out_fragment[161] -type PO PO
add mapped point out_fragment[160] out_fragment[160] -type PO PO
add mapped point out_fragment[159] out_fragment[159] -type PO PO
add mapped point out_fragment[158] out_fragment[158] -type PO PO
add mapped point out_fragment[157] out_fragment[157] -type PO PO
add mapped point out_fragment[156] out_fragment[156] -type PO PO
add mapped point out_fragment[155] out_fragment[155] -type PO PO
add mapped point out_fragment[154] out_fragment[154] -type PO PO
add mapped point out_fragment[153] out_fragment[153] -type PO PO
add mapped point out_fragment[152] out_fragment[152] -type PO PO
add mapped point out_fragment[151] out_fragment[151] -type PO PO
add mapped point out_fragment[150] out_fragment[150] -type PO PO
add mapped point out_fragment[149] out_fragment[149] -type PO PO
add mapped point out_fragment[148] out_fragment[148] -type PO PO
add mapped point out_fragment[147] out_fragment[147] -type PO PO
add mapped point out_fragment[146] out_fragment[146] -type PO PO
add mapped point out_fragment[145] out_fragment[145] -type PO PO
add mapped point out_fragment[144] out_fragment[144] -type PO PO
add mapped point out_fragment[143] out_fragment[143] -type PO PO
add mapped point out_fragment[142] out_fragment[142] -type PO PO
add mapped point out_fragment[141] out_fragment[141] -type PO PO
add mapped point out_fragment[140] out_fragment[140] -type PO PO
add mapped point out_fragment[139] out_fragment[139] -type PO PO
add mapped point out_fragment[138] out_fragment[138] -type PO PO
add mapped point out_fragment[137] out_fragment[137] -type PO PO
add mapped point out_fragment[136] out_fragment[136] -type PO PO
add mapped point out_fragment[135] out_fragment[135] -type PO PO
add mapped point out_fragment[134] out_fragment[134] -type PO PO
add mapped point out_fragment[133] out_fragment[133] -type PO PO
add mapped point out_fragment[132] out_fragment[132] -type PO PO
add mapped point out_fragment[131] out_fragment[131] -type PO PO
add mapped point out_fragment[130] out_fragment[130] -type PO PO
add mapped point out_fragment[129] out_fragment[129] -type PO PO
add mapped point out_fragment[128] out_fragment[128] -type PO PO
add mapped point out_fragment[127] out_fragment[127] -type PO PO
add mapped point out_fragment[126] out_fragment[126] -type PO PO
add mapped point out_fragment[125] out_fragment[125] -type PO PO
add mapped point out_fragment[124] out_fragment[124] -type PO PO
add mapped point out_fragment[123] out_fragment[123] -type PO PO
add mapped point out_fragment[122] out_fragment[122] -type PO PO
add mapped point out_fragment[121] out_fragment[121] -type PO PO
add mapped point out_fragment[120] out_fragment[120] -type PO PO
add mapped point out_fragment[119] out_fragment[119] -type PO PO
add mapped point out_fragment[118] out_fragment[118] -type PO PO
add mapped point out_fragment[117] out_fragment[117] -type PO PO
add mapped point out_fragment[116] out_fragment[116] -type PO PO
add mapped point out_fragment[115] out_fragment[115] -type PO PO
add mapped point out_fragment[114] out_fragment[114] -type PO PO
add mapped point out_fragment[113] out_fragment[113] -type PO PO
add mapped point out_fragment[112] out_fragment[112] -type PO PO
add mapped point out_fragment[111] out_fragment[111] -type PO PO
add mapped point out_fragment[110] out_fragment[110] -type PO PO
add mapped point out_fragment[109] out_fragment[109] -type PO PO
add mapped point out_fragment[108] out_fragment[108] -type PO PO
add mapped point out_fragment[107] out_fragment[107] -type PO PO
add mapped point out_fragment[106] out_fragment[106] -type PO PO
add mapped point out_fragment[105] out_fragment[105] -type PO PO
add mapped point out_fragment[104] out_fragment[104] -type PO PO
add mapped point out_fragment[103] out_fragment[103] -type PO PO
add mapped point out_fragment[102] out_fragment[102] -type PO PO
add mapped point out_fragment[101] out_fragment[101] -type PO PO
add mapped point out_fragment[100] out_fragment[100] -type PO PO
add mapped point out_fragment[99] out_fragment[99] -type PO PO
add mapped point out_fragment[98] out_fragment[98] -type PO PO
add mapped point out_fragment[97] out_fragment[97] -type PO PO
add mapped point out_fragment[96] out_fragment[96] -type PO PO
add mapped point out_fragment[95] out_fragment[95] -type PO PO
add mapped point out_fragment[94] out_fragment[94] -type PO PO
add mapped point out_fragment[93] out_fragment[93] -type PO PO
add mapped point out_fragment[92] out_fragment[92] -type PO PO
add mapped point out_fragment[91] out_fragment[91] -type PO PO
add mapped point out_fragment[90] out_fragment[90] -type PO PO
add mapped point out_fragment[89] out_fragment[89] -type PO PO
add mapped point out_fragment[88] out_fragment[88] -type PO PO
add mapped point out_fragment[87] out_fragment[87] -type PO PO
add mapped point out_fragment[86] out_fragment[86] -type PO PO
add mapped point out_fragment[85] out_fragment[85] -type PO PO
add mapped point out_fragment[84] out_fragment[84] -type PO PO
add mapped point out_fragment[83] out_fragment[83] -type PO PO
add mapped point out_fragment[82] out_fragment[82] -type PO PO
add mapped point out_fragment[81] out_fragment[81] -type PO PO
add mapped point out_fragment[80] out_fragment[80] -type PO PO
add mapped point out_fragment[79] out_fragment[79] -type PO PO
add mapped point out_fragment[78] out_fragment[78] -type PO PO
add mapped point out_fragment[77] out_fragment[77] -type PO PO
add mapped point out_fragment[76] out_fragment[76] -type PO PO
add mapped point out_fragment[75] out_fragment[75] -type PO PO
add mapped point out_fragment[74] out_fragment[74] -type PO PO
add mapped point out_fragment[73] out_fragment[73] -type PO PO
add mapped point out_fragment[72] out_fragment[72] -type PO PO
add mapped point out_fragment[71] out_fragment[71] -type PO PO
add mapped point out_fragment[70] out_fragment[70] -type PO PO
add mapped point out_fragment[69] out_fragment[69] -type PO PO
add mapped point out_fragment[68] out_fragment[68] -type PO PO
add mapped point out_fragment[67] out_fragment[67] -type PO PO
add mapped point out_fragment[66] out_fragment[66] -type PO PO
add mapped point out_fragment[65] out_fragment[65] -type PO PO
add mapped point out_fragment[64] out_fragment[64] -type PO PO
add mapped point out_fragment[63] out_fragment[63] -type PO PO
add mapped point out_fragment[62] out_fragment[62] -type PO PO
add mapped point out_fragment[61] out_fragment[61] -type PO PO
add mapped point out_fragment[60] out_fragment[60] -type PO PO
add mapped point out_fragment[59] out_fragment[59] -type PO PO
add mapped point out_fragment[58] out_fragment[58] -type PO PO
add mapped point out_fragment[57] out_fragment[57] -type PO PO
add mapped point out_fragment[56] out_fragment[56] -type PO PO
add mapped point out_fragment[55] out_fragment[55] -type PO PO
add mapped point out_fragment[54] out_fragment[54] -type PO PO
add mapped point out_fragment[53] out_fragment[53] -type PO PO
add mapped point out_fragment[52] out_fragment[52] -type PO PO
add mapped point out_fragment[51] out_fragment[51] -type PO PO
add mapped point out_fragment[50] out_fragment[50] -type PO PO
add mapped point out_fragment[49] out_fragment[49] -type PO PO
add mapped point out_fragment[48] out_fragment[48] -type PO PO
add mapped point out_fragment[47] out_fragment[47] -type PO PO
add mapped point out_fragment[46] out_fragment[46] -type PO PO
add mapped point out_fragment[45] out_fragment[45] -type PO PO
add mapped point out_fragment[44] out_fragment[44] -type PO PO
add mapped point out_fragment[43] out_fragment[43] -type PO PO
add mapped point out_fragment[42] out_fragment[42] -type PO PO
add mapped point out_fragment[41] out_fragment[41] -type PO PO
add mapped point out_fragment[40] out_fragment[40] -type PO PO
add mapped point out_fragment[39] out_fragment[39] -type PO PO
add mapped point out_fragment[38] out_fragment[38] -type PO PO
add mapped point out_fragment[37] out_fragment[37] -type PO PO
add mapped point out_fragment[36] out_fragment[36] -type PO PO
add mapped point out_fragment[35] out_fragment[35] -type PO PO
add mapped point out_fragment[34] out_fragment[34] -type PO PO
add mapped point out_fragment[33] out_fragment[33] -type PO PO
add mapped point out_fragment[32] out_fragment[32] -type PO PO
add mapped point out_fragment[31] out_fragment[31] -type PO PO
add mapped point out_fragment[30] out_fragment[30] -type PO PO
add mapped point out_fragment[29] out_fragment[29] -type PO PO
add mapped point out_fragment[28] out_fragment[28] -type PO PO
add mapped point out_fragment[27] out_fragment[27] -type PO PO
add mapped point out_fragment[26] out_fragment[26] -type PO PO
add mapped point out_fragment[25] out_fragment[25] -type PO PO
add mapped point out_fragment[24] out_fragment[24] -type PO PO
add mapped point out_fragment[23] out_fragment[23] -type PO PO
add mapped point out_fragment[22] out_fragment[22] -type PO PO
add mapped point out_fragment[21] out_fragment[21] -type PO PO
add mapped point out_fragment[20] out_fragment[20] -type PO PO
add mapped point out_fragment[19] out_fragment[19] -type PO PO
add mapped point out_fragment[18] out_fragment[18] -type PO PO
add mapped point out_fragment[17] out_fragment[17] -type PO PO
add mapped point out_fragment[16] out_fragment[16] -type PO PO
add mapped point out_fragment[15] out_fragment[15] -type PO PO
add mapped point out_fragment[14] out_fragment[14] -type PO PO
add mapped point out_fragment[13] out_fragment[13] -type PO PO
add mapped point out_fragment[12] out_fragment[12] -type PO PO
add mapped point out_fragment[11] out_fragment[11] -type PO PO
add mapped point out_fragment[10] out_fragment[10] -type PO PO
add mapped point out_fragment[9] out_fragment[9] -type PO PO
add mapped point out_fragment[8] out_fragment[8] -type PO PO
add mapped point out_fragment[7] out_fragment[7] -type PO PO
add mapped point out_fragment[6] out_fragment[6] -type PO PO
add mapped point out_fragment[5] out_fragment[5] -type PO PO
add mapped point out_fragment[4] out_fragment[4] -type PO PO
add mapped point out_fragment[3] out_fragment[3] -type PO PO
add mapped point out_fragment[2] out_fragment[2] -type PO PO
add mapped point out_fragment[1] out_fragment[1] -type PO PO
add mapped point out_fragment[0] out_fragment[0] -type PO PO
add mapped point out_wait out_wait -type PO PO

//inout ports




//Sequential Pins
add mapped point u_counter/out_index[14]/q u_counter/out_index_reg[14]/Q -type DFF DFF
add mapped point u_counter/out_index[13]/q u_counter/out_index_reg[13]/Q -type DFF DFF
add mapped point u_counter/out_index[12]/q u_counter/out_index_reg[12]/Q -type DFF DFF
add mapped point u_counter/out_index[11]/q u_counter/out_index_reg[11]/Q -type DFF DFF
add mapped point u_counter/out_index[9]/q u_counter/out_index_reg[9]/Q -type DFF DFF
add mapped point u_counter/out_index[10]/q u_counter/out_index_reg[10]/Q -type DFF DFF
add mapped point u_counter/out_index[8]/q u_counter/out_index_reg[8]/Q -type DFF DFF
add mapped point u_counter/out_index[7]/q u_counter/out_index_reg[7]/Q -type DFF DFF
add mapped point u_counter/out_index[6]/q u_counter/out_index_reg[6]/Q -type DFF DFF
add mapped point u_counter/out_index[5]/q u_counter/out_index_reg[5]/Q -type DFF DFF
add mapped point u_counter/out_index[4]/q u_counter/out_index_reg[4]/Q -type DFF DFF
add mapped point u_counter/out_index[3]/q u_counter/out_index_reg[3]/Q -type DFF DFF
add mapped point u_counter/out_index[2]/q u_counter/out_index_reg[2]/Q -type DFF DFF
add mapped point u_counter/out_index[1]/q u_counter/out_index_reg[1]/Q -type DFF DFF
add mapped point u_counter/out_index[0]/q u_counter/out_index_reg[0]/Q -type DFF DFF
add mapped point u_counter/count_enabled/q u_counter/count_enabled_reg/Q -type DFF DFF
add mapped point u_counter/start_prev/q u_counter/start_prev_reg/Q -type DFF DFF
add mapped point u_fm/waddr[4]/q u_fm/waddr_reg[4]/Q -type DFF DFF
add mapped point u_fm/waddr[3]/q u_fm/waddr_reg[3]/Q -type DFF DFF
add mapped point u_fm/waddr[2]/q u_fm/waddr_reg[2]/Q -type DFF DFF
add mapped point u_fm/waddr[1]/q u_fm/waddr_reg[1]/Q -type DFF DFF
add mapped point u_fm/waddr[0]/q u_fm/waddr_reg[0]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
