
// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Aug 11 2024 13:49:26 UTC (Aug 11 2024 13:49:26 UTC)

// Verification Directory fv/proj_extender 

module RC_CG_MOD(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  PREICG_X0P5B_A9TR RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test),
       .ECK (ck_out));
endmodule

module proj_extender(in_fragment, \in_kmer_indices[0] ,
     \in_kmer_indices[1] , \in_kmer_indices[2] , \in_kmer_indices[3] ,
     valid_indices, rst_n, clk, out_index, out_gfm);
  input [15:0] in_fragment;
  input [6:0] \in_kmer_indices[0] , \in_kmer_indices[1] ,
       \in_kmer_indices[2] , \in_kmer_indices[3] ;
  input valid_indices, rst_n, clk;
  output [7:0] out_index, out_gfm;
  wire [15:0] in_fragment;
  wire [6:0] \in_kmer_indices[0] , \in_kmer_indices[1] ,
       \in_kmer_indices[2] , \in_kmer_indices[3] ;
  wire valid_indices, rst_n, clk;
  wire [7:0] out_index, out_gfm;
  wire [6:0] \in_kmer_indices_r[0] ;
  wire [6:0] \in_kmer_indices_r[3] ;
  wire [6:0] \in_kmer_indices_r[2] ;
  wire [6:0] \in_kmer_indices_r[1] ;
  wire [0:0] frag_parts_idx;
  wire [1:0] indices_idx;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, rc_gclk;
  RC_CG_MOD RC_CG_HIER_INST0(.enable (valid_indices), .ck_in (clk),
       .ck_out (rc_gclk), .test (1'b0));
  XNOR2_X0P7M_A9TL g576__2398(.A (n_36), .B (n_30), .Y (out_index[5]));
  XNOR2_X0P7M_A9TL g577__5107(.A (n_33), .B (n_28), .Y (out_index[3]));
  XOR2_X0P7M_A9TL g578__6260(.A (n_35), .B (n_31), .Y (out_index[6]));
  NOR2XB_X1M_A9TL g579__4319(.A (n_35), .BN (n_31), .Y (out_index[7]));
  OAI21B_X1M_A9TL g580__8428(.A0 (n_32), .A1 (n_34), .B0N (n_36), .Y
       (out_index[4]));
  AND2_X1M_A9TL g581__5526(.A (n_32), .B (n_34), .Y (n_36));
  NAND3_X1M_A9TL g582__6783(.A (n_34), .B (n_30), .C (n_32), .Y (n_35));
  AND3_X1M_A9TL g583__3680(.A (n_28), .B (n_29), .C (out_index[1]), .Y
       (n_34));
  OAI21B_X1M_A9TL g584__1617(.A0 (n_29), .A1 (out_index[1]), .B0N
       (n_33), .Y (out_index[2]));
  AND2_X1M_A9TL g585__2802(.A (n_29), .B (out_index[1]), .Y (n_33));
  AND2_X1M_A9TL g586__1705(.A (n_27), .B (n_24), .Y (n_32));
  AOI221_X1M_A9TL g587__5122(.A0 (\in_kmer_indices_r[0] [6]), .A1
       (n_7), .B0 (\in_kmer_indices_r[3] [6]), .B1 (n_8), .C0 (n_18),
       .Y (n_31));
  AND2_X1M_A9TL g588__8246(.A (n_26), .B (n_20), .Y (out_index[1]));
  NAND2_X1M_A9TL g589__7098(.A (n_21), .B (n_19), .Y (out_index[0]));
  AND2_X1M_A9TL g590__6131(.A (n_23), .B (n_17), .Y (n_30));
  AND2_X1M_A9TL g591__1881(.A (n_16), .B (n_15), .Y (n_29));
  AND2_X1M_A9TL g592__5115(.A (n_22), .B (n_25), .Y (n_28));
  AND2_X1M_A9TL g595__7482(.A (n_11), .B (n_12), .Y (out_gfm[0]));
  NOR2_X1B_A9TL g596__4733(.A (n_11), .B (n_12), .Y (out_gfm[3]));
  NOR2_X1B_A9TL g597__6161(.A (n_14), .B (n_13), .Y (out_gfm[7]));
  AND2_X1M_A9TL g600__9315(.A (n_14), .B (n_13), .Y (out_gfm[4]));
  AOI22_X1M_A9TL g601__9945(.A0 (\in_kmer_indices_r[2] [4]), .A1 (n_9),
       .B0 (\in_kmer_indices_r[3] [4]), .B1 (n_8), .Y (n_27));
  AOI22_X1M_A9TL g602__2883(.A0 (\in_kmer_indices_r[1] [1]), .A1
       (n_10), .B0 (\in_kmer_indices_r[3] [1]), .B1 (n_8), .Y (n_26));
  AOI22_X1M_A9TL g603__2346(.A0 (\in_kmer_indices_r[0] [3]), .A1 (n_7),
       .B0 (\in_kmer_indices_r[1] [3]), .B1 (n_10), .Y (n_25));
  AOI22_X1M_A9TL g604__1666(.A0 (\in_kmer_indices_r[0] [4]), .A1 (n_7),
       .B0 (\in_kmer_indices_r[1] [4]), .B1 (n_10), .Y (n_24));
  AOI22_X1M_A9TL g605__7410(.A0 (\in_kmer_indices_r[2] [5]), .A1 (n_9),
       .B0 (\in_kmer_indices_r[3] [5]), .B1 (n_8), .Y (n_23));
  AOI22_X1M_A9TL g606__6417(.A0 (\in_kmer_indices_r[2] [3]), .A1 (n_9),
       .B0 (\in_kmer_indices_r[3] [3]), .B1 (n_8), .Y (n_22));
  AOI22_X1M_A9TL g607__5477(.A0 (\in_kmer_indices_r[1] [0]), .A1
       (n_10), .B0 (\in_kmer_indices_r[2] [0]), .B1 (n_9), .Y (n_21));
  AOI22_X1M_A9TL g608__2398(.A0 (\in_kmer_indices_r[0] [1]), .A1 (n_7),
       .B0 (\in_kmer_indices_r[2] [1]), .B1 (n_9), .Y (n_20));
  AOI22_X1M_A9TL g609__5107(.A0 (\in_kmer_indices_r[0] [0]), .A1 (n_7),
       .B0 (\in_kmer_indices_r[3] [0]), .B1 (n_8), .Y (n_19));
  AO22_X1M_A9TL g610__6260(.A0 (\in_kmer_indices_r[1] [6]), .A1 (n_10),
       .B0 (\in_kmer_indices_r[2] [6]), .B1 (n_9), .Y (n_18));
  AOI22_X1M_A9TL g611__4319(.A0 (\in_kmer_indices_r[0] [5]), .A1 (n_7),
       .B0 (\in_kmer_indices_r[1] [5]), .B1 (n_10), .Y (n_17));
  AOI22_X1M_A9TL g612__8428(.A0 (\in_kmer_indices_r[1] [2]), .A1
       (n_10), .B0 (\in_kmer_indices_r[2] [2]), .B1 (n_9), .Y (n_16));
  AOI22_X1M_A9TL g613__5526(.A0 (\in_kmer_indices_r[0] [2]), .A1 (n_7),
       .B0 (\in_kmer_indices_r[3] [2]), .B1 (n_8), .Y (n_15));
  AOI22_X2M_A9TL g616__6783(.A0 (in_fragment[3]), .A1 (n_6), .B0
       (in_fragment[7]), .B1 (frag_parts_idx), .Y (n_14));
  AOI22_X2M_A9TL g617__3680(.A0 (in_fragment[2]), .A1 (n_6), .B0
       (in_fragment[6]), .B1 (frag_parts_idx), .Y (n_13));
  AOI22_X2M_A9TL g620__1617(.A0 (in_fragment[0]), .A1 (n_6), .B0
       (in_fragment[4]), .B1 (frag_parts_idx), .Y (n_12));
  AOI22_X2M_A9TL g621__2802(.A0 (in_fragment[1]), .A1 (n_6), .B0
       (in_fragment[5]), .B1 (frag_parts_idx), .Y (n_11));
  NOR2XB_X2M_A9TL g622__1705(.A (indices_idx[1]), .BN (indices_idx[0]),
       .Y (n_10));
  NOR2XB_X2M_A9TL g623__5122(.A (indices_idx[0]), .BN (indices_idx[1]),
       .Y (n_9));
  AND2_X1M_A9TL g624__8246(.A (indices_idx[0]), .B (indices_idx[1]), .Y
       (n_8));
  NOR2_X2M_A9TL g625__7098(.A (indices_idx[0]), .B (indices_idx[1]), .Y
       (n_7));
  INV_X4M_A9TL g626(.A (frag_parts_idx), .Y (n_6));
  NOR2XB_X1M_A9TL g2__6131(.A (n_13), .BN (n_14), .Y (out_gfm[5]));
  NOR2XB_X1M_A9TL g627__1881(.A (n_14), .BN (n_13), .Y (out_gfm[6]));
  NOR2XB_X1M_A9TL g628__5115(.A (n_11), .BN (n_12), .Y (out_gfm[2]));
  NOR2XB_X1M_A9TL g629__7482(.A (n_12), .BN (n_11), .Y (out_gfm[1]));
  DFFRPQ_X1M_A9TL \indices_idx_reg[1] (.R (n_2), .CK (clk), .D (n_5),
       .Q (indices_idx[1]));
  XOR2_X0P7M_A9TL g358__4733(.A (n_3), .B (indices_idx[1]), .Y (n_5));
  DFFRPQ_X1M_A9TL \indices_idx_reg[0] (.R (n_2), .CK (clk), .D (n_4),
       .Q (indices_idx[0]));
  ADDH_X1M_A9TL g360__6161(.A (frag_parts_idx), .B (indices_idx[0]),
       .CO (n_3), .S (n_4));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[1][4] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[1] [4]), .Q
       (\in_kmer_indices_r[1] [4]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[0][1] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[0] [1]), .Q
       (\in_kmer_indices_r[0] [1]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[0][2] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[0] [2]), .Q
       (\in_kmer_indices_r[0] [2]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[0][3] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[0] [3]), .Q
       (\in_kmer_indices_r[0] [3]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[3][5] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[3] [5]), .Q
       (\in_kmer_indices_r[3] [5]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[0][4] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[0] [4]), .Q
       (\in_kmer_indices_r[0] [4]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[0][5] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[0] [5]), .Q
       (\in_kmer_indices_r[0] [5]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[0][6] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[0] [6]), .Q
       (\in_kmer_indices_r[0] [6]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[3][1] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[3] [1]), .Q
       (\in_kmer_indices_r[3] [1]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[1][0] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[1] [0]), .Q
       (\in_kmer_indices_r[1] [0]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[1][1] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[1] [1]), .Q
       (\in_kmer_indices_r[1] [1]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[1][2] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[1] [2]), .Q
       (\in_kmer_indices_r[1] [2]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[1][3] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[1] [3]), .Q
       (\in_kmer_indices_r[1] [3]));
  DFFRPQ_X2M_A9TL \frag_parts_idx_reg[0] (.R (n_2), .CK (clk), .D
       (n_1), .Q (frag_parts_idx));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[2][5] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[2] [5]), .Q
       (\in_kmer_indices_r[2] [5]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[1][6] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[1] [6]), .Q
       (\in_kmer_indices_r[1] [6]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[2][0] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[2] [0]), .Q
       (\in_kmer_indices_r[2] [0]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[0][0] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[0] [0]), .Q
       (\in_kmer_indices_r[0] [0]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[2][2] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[2] [2]), .Q
       (\in_kmer_indices_r[2] [2]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[2][3] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[2] [3]), .Q
       (\in_kmer_indices_r[2] [3]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[2][4] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[2] [4]), .Q
       (\in_kmer_indices_r[2] [4]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[1][5] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[1] [5]), .Q
       (\in_kmer_indices_r[1] [5]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[2][6] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[2] [6]), .Q
       (\in_kmer_indices_r[2] [6]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[3][0] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[3] [0]), .Q
       (\in_kmer_indices_r[3] [0]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[2][1] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[2] [1]), .Q
       (\in_kmer_indices_r[2] [1]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[3][3] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[3] [3]), .Q
       (\in_kmer_indices_r[3] [3]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[3][4] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[3] [4]), .Q
       (\in_kmer_indices_r[3] [4]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[3][2] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[3] [2]), .Q
       (\in_kmer_indices_r[3] [2]));
  A2DFFQ_X0P5M_A9TL \in_kmer_indices_r_reg[3][6] (.CK (rc_gclk), .A
       (1'b1), .B (\in_kmer_indices[3] [6]), .Q
       (\in_kmer_indices_r[3] [6]));
  INV_X0P5M_A9TL g390(.A (rst_n), .Y (n_2));
  INV_X1M_A9TL g391(.A (frag_parts_idx), .Y (n_1));
endmodule

