
// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Aug  9 2024 12:47:30 UTC (Aug  9 2024 12:47:30 UTC)

// Verification Directory fv/proj_sorter 

module add_unsigned(A, B, Z);
  input [2:0] A;
  input B;
  output [2:0] Z;
  wire [2:0] A;
  wire B;
  wire [2:0] Z;
  wire n_8, n_12, n_15, n_17, n_21, n_23;
  xor g1 (Z[0], A[0], B);
  nand g2 (n_8, A[0], B);
  nand g11 (n_15, n_12, A[1]);
  xnor g17 (Z[1], n_12, n_21);
  xnor g19 (Z[2], n_17, n_23);
  not g23 (n_12, n_8);
  not g24 (n_21, A[1]);
  not g25 (n_23, A[2]);
  not g26 (n_17, n_15);
endmodule

module sub_unsigned(A, B, Z);
  input [2:0] A, B;
  output [2:0] Z;
  wire [2:0] A, B;
  wire [2:0] Z;
  wire n_10, n_11, n_13, n_17, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_29, n_30, n_31;
  not g2 (n_10, B[2]);
  not g3 (n_11, B[1]);
  not g4 (n_13, B[0]);
  xor g1 (n_31, A[0], n_13);
  nand g6 (n_20, n_17, B[0]);
  nor g7 (n_19, A[1], n_11);
  nand g8 (n_22, A[1], n_11);
  nor g9 (n_24, A[2], n_10);
  nand g10 (n_27, A[2], n_10);
  not g11 (n_21, n_19);
  nand g12 (n_23, n_20, n_21);
  nand g13 (n_25, n_22, n_23);
  not g14 (n_26, n_24);
  nand g17 (n_29, n_21, n_22);
  xnor g18 (Z[1], n_20, n_29);
  nand g19 (n_30, n_26, n_27);
  xnor g20 (Z[2], n_25, n_30);
  not g21 (n_17, A[0]);
  not g23 (Z[0], n_31);
endmodule

module lt_unsigned(A, B, Z);
  input [31:0] A, B;
  output Z;
  wire [31:0] A, B;
  wire Z;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_131, n_132, n_133, n_135, n_136, n_137, n_138, n_139;
  wire n_140, n_141, n_142, n_143, n_144, n_145, n_146, n_147;
  wire n_148, n_149, n_150, n_151, n_152, n_153, n_154, n_155;
  wire n_156, n_157, n_158, n_159, n_160, n_161, n_162, n_163;
  wire n_164, n_165, n_166, n_167, n_168, n_169, n_170, n_171;
  wire n_172, n_173, n_174, n_175, n_176, n_177, n_178, n_179;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_190, n_191, n_192, n_193, n_194, n_195;
  wire n_196, n_197, n_198, n_199, n_200, n_201, n_202, n_203;
  wire n_204, n_205, n_206, n_207, n_208, n_209, n_210, n_211;
  wire n_212, n_213, n_214, n_215, n_216, n_217, n_218, n_219;
  wire n_220, n_221, n_222, n_223, n_224, n_225, n_226, n_227;
  wire n_228, n_231, n_232, n_233, n_234, n_237, n_239, n_240;
  wire n_241, n_242, n_243, n_244, n_247, n_249, n_250, n_251;
  wire n_252, n_253, n_254, n_257, n_259, n_260, n_261, n_262;
  wire n_263, n_264, n_267, n_269, n_270, n_271, n_272, n_273;
  wire n_274, n_277, n_279, n_280, n_281, n_282, n_283, n_284;
  wire n_287, n_289, n_290, n_291, n_292, n_293, n_294, n_297;
  wire n_299, n_300, n_301, n_302, n_303, n_304, n_312, n_313;
  wire n_314, n_315, n_316, n_319, n_327, n_328, n_329, n_330;
  wire n_331, n_334, n_342, n_343, n_344, n_345, n_346, n_349;
  wire n_357, n_358, n_359, n_360, n_361, n_380, n_381, n_382;
  wire n_383, n_386, n_414, n_415, n_416, n_417, n_418, n_419;
  wire n_467, n_468, n_469, n_470;
  not g2 (n_99, B[31]);
  not g3 (n_100, B[30]);
  not g4 (n_101, B[29]);
  not g5 (n_102, B[28]);
  not g6 (n_103, B[27]);
  not g7 (n_104, B[26]);
  not g8 (n_105, B[25]);
  not g9 (n_106, B[24]);
  not g10 (n_107, B[23]);
  not g11 (n_108, B[22]);
  not g12 (n_109, B[21]);
  not g13 (n_110, B[20]);
  not g14 (n_111, B[19]);
  not g15 (n_112, B[18]);
  not g16 (n_113, B[17]);
  not g17 (n_114, B[16]);
  not g18 (n_115, B[15]);
  not g19 (n_116, B[14]);
  not g20 (n_117, B[13]);
  not g21 (n_118, B[12]);
  not g22 (n_119, B[11]);
  not g23 (n_120, B[10]);
  not g24 (n_121, B[9]);
  not g25 (n_122, B[8]);
  not g26 (n_123, B[7]);
  not g27 (n_124, B[6]);
  not g28 (n_125, B[5]);
  not g29 (n_126, B[4]);
  not g30 (n_127, B[3]);
  not g31 (n_128, B[2]);
  not g32 (n_129, B[1]);
  not g34 (Z, n_131);
  nand g35 (n_136, n_133, B[0]);
  nor g36 (n_135, A[1], n_129);
  nand g37 (n_138, A[1], n_129);
  nor g38 (n_145, A[2], n_128);
  nand g39 (n_140, A[2], n_128);
  nor g40 (n_141, A[3], n_127);
  nand g41 (n_142, A[3], n_127);
  nor g42 (n_151, A[4], n_126);
  nand g43 (n_146, A[4], n_126);
  nor g44 (n_147, A[5], n_125);
  nand g45 (n_148, A[5], n_125);
  nor g46 (n_157, A[6], n_124);
  nand g47 (n_152, A[6], n_124);
  nor g48 (n_153, A[7], n_123);
  nand g49 (n_154, A[7], n_123);
  nor g50 (n_163, A[8], n_122);
  nand g51 (n_158, A[8], n_122);
  nor g52 (n_159, A[9], n_121);
  nand g53 (n_160, A[9], n_121);
  nor g54 (n_168, A[10], n_120);
  nand g55 (n_164, A[10], n_120);
  nor g56 (n_98, A[11], n_119);
  nand g57 (n_165, A[11], n_119);
  nor g58 (n_174, A[12], n_118);
  nand g59 (n_169, A[12], n_118);
  nor g60 (n_170, A[13], n_117);
  nand g61 (n_171, A[13], n_117);
  nor g62 (n_180, A[14], n_116);
  nand g63 (n_175, A[14], n_116);
  nor g64 (n_176, A[15], n_115);
  nand g65 (n_177, A[15], n_115);
  nor g66 (n_186, A[16], n_114);
  nand g67 (n_181, A[16], n_114);
  nor g68 (n_182, A[17], n_113);
  nand g69 (n_183, A[17], n_113);
  nor g70 (n_192, A[18], n_112);
  nand g71 (n_187, A[18], n_112);
  nor g72 (n_188, A[19], n_111);
  nand g73 (n_189, A[19], n_111);
  nor g74 (n_132, A[20], n_110);
  nand g75 (n_193, A[20], n_110);
  nor g76 (n_194, A[21], n_109);
  nand g77 (n_195, A[21], n_109);
  nor g78 (n_203, A[22], n_108);
  nand g79 (n_198, A[22], n_108);
  nor g80 (n_199, A[23], n_107);
  nand g81 (n_200, A[23], n_107);
  nor g82 (n_209, A[24], n_106);
  nand g83 (n_204, A[24], n_106);
  nor g84 (n_205, A[25], n_105);
  nand g85 (n_206, A[25], n_105);
  nor g86 (n_215, A[26], n_104);
  nand g87 (n_210, A[26], n_104);
  nor g88 (n_211, A[27], n_103);
  nand g89 (n_212, A[27], n_103);
  nor g90 (n_221, A[28], n_102);
  nand g91 (n_216, A[28], n_102);
  nor g92 (n_217, A[29], n_101);
  nand g93 (n_218, A[29], n_101);
  nor g94 (n_227, A[30], n_100);
  nand g95 (n_222, A[30], n_100);
  nor g96 (n_223, A[31], n_99);
  nand g97 (n_224, A[31], n_99);
  not g98 (n_137, n_135);
  nand g99 (n_139, n_136, n_137);
  nand g100 (n_228, n_138, n_139);
  nor g101 (n_143, n_140, n_141);
  not g102 (n_144, n_142);
  nor g103 (n_232, n_143, n_144);
  nor g104 (n_231, n_145, n_141);
  nor g105 (n_149, n_146, n_147);
  not g106 (n_150, n_148);
  nor g107 (n_234, n_149, n_150);
  nor g108 (n_237, n_151, n_147);
  nor g109 (n_155, n_152, n_153);
  not g110 (n_156, n_154);
  nor g111 (n_241, n_155, n_156);
  nor g112 (n_239, n_157, n_153);
  nor g113 (n_161, n_158, n_159);
  not g114 (n_162, n_160);
  nor g115 (n_244, n_161, n_162);
  nor g116 (n_247, n_163, n_159);
  nor g117 (n_166, n_164, n_98);
  not g118 (n_167, n_165);
  nor g119 (n_251, n_166, n_167);
  nor g120 (n_249, n_168, n_98);
  nor g121 (n_172, n_169, n_170);
  not g122 (n_173, n_171);
  nor g123 (n_254, n_172, n_173);
  nor g124 (n_257, n_174, n_170);
  nor g125 (n_178, n_175, n_176);
  not g126 (n_179, n_177);
  nor g127 (n_261, n_178, n_179);
  nor g128 (n_259, n_180, n_176);
  nor g129 (n_184, n_181, n_182);
  not g130 (n_185, n_183);
  nor g131 (n_264, n_184, n_185);
  nor g132 (n_267, n_186, n_182);
  nor g133 (n_190, n_187, n_188);
  not g134 (n_191, n_189);
  nor g135 (n_271, n_190, n_191);
  nor g136 (n_269, n_192, n_188);
  nor g137 (n_196, n_193, n_194);
  not g138 (n_197, n_195);
  nor g139 (n_274, n_196, n_197);
  nor g140 (n_277, n_132, n_194);
  nor g141 (n_201, n_198, n_199);
  not g142 (n_202, n_200);
  nor g143 (n_281, n_201, n_202);
  nor g144 (n_279, n_203, n_199);
  nor g145 (n_207, n_204, n_205);
  not g146 (n_208, n_206);
  nor g147 (n_284, n_207, n_208);
  nor g148 (n_287, n_209, n_205);
  nor g149 (n_213, n_210, n_211);
  not g150 (n_214, n_212);
  nor g151 (n_291, n_213, n_214);
  nor g152 (n_289, n_215, n_211);
  nor g153 (n_219, n_216, n_217);
  not g154 (n_220, n_218);
  nor g155 (n_294, n_219, n_220);
  nor g156 (n_297, n_221, n_217);
  nor g157 (n_225, n_222, n_223);
  not g158 (n_226, n_224);
  nor g159 (n_301, n_225, n_226);
  nor g160 (n_299, n_227, n_223);
  nand g164 (n_233, n_231, n_228);
  nand g165 (n_304, n_232, n_233);
  not g171 (n_240, n_239);
  nor g172 (n_242, n_234, n_240);
  not g173 (n_243, n_241);
  nor g174 (n_314, n_242, n_243);
  nand g175 (n_312, n_237, n_239);
  not g181 (n_250, n_249);
  nor g182 (n_252, n_244, n_250);
  not g183 (n_253, n_251);
  nor g184 (n_316, n_252, n_253);
  nand g185 (n_319, n_247, n_249);
  not g191 (n_260, n_259);
  nor g192 (n_262, n_254, n_260);
  not g193 (n_263, n_261);
  nor g194 (n_328, n_262, n_263);
  nand g195 (n_327, n_257, n_259);
  not g201 (n_270, n_269);
  nor g202 (n_272, n_264, n_270);
  not g203 (n_273, n_271);
  nor g204 (n_331, n_272, n_273);
  nand g205 (n_334, n_267, n_269);
  not g211 (n_280, n_279);
  nor g212 (n_282, n_274, n_280);
  not g213 (n_283, n_281);
  nor g214 (n_343, n_282, n_283);
  nand g215 (n_342, n_277, n_279);
  not g221 (n_290, n_289);
  nor g222 (n_292, n_284, n_290);
  not g223 (n_293, n_291);
  nor g224 (n_346, n_292, n_293);
  nand g225 (n_349, n_287, n_289);
  not g231 (n_300, n_299);
  nor g232 (n_302, n_294, n_300);
  not g233 (n_303, n_301);
  nor g234 (n_358, n_302, n_303);
  nand g235 (n_357, n_297, n_299);
  not g244 (n_313, n_312);
  nand g245 (n_315, n_304, n_313);
  nand g246 (n_361, n_314, n_315);
  nor g260 (n_329, n_327, n_316);
  not g261 (n_330, n_328);
  nor g262 (n_381, n_329, n_330);
  nor g263 (n_380, n_319, n_327);
  nor g277 (n_344, n_342, n_331);
  not g278 (n_345, n_343);
  nor g279 (n_383, n_344, n_345);
  nor g280 (n_386, n_334, n_342);
  nor g294 (n_359, n_357, n_346);
  not g295 (n_360, n_358);
  nor g296 (n_416, n_359, n_360);
  nor g297 (n_414, n_349, n_357);
  nand g315 (n_382, n_380, n_361);
  nand g316 (n_419, n_381, n_382);
  not g352 (n_415, n_414);
  nor g353 (n_417, n_383, n_415);
  not g354 (n_418, n_416);
  nor g355 (n_469, n_417, n_418);
  nand g356 (n_467, n_386, n_414);
  not g397 (n_468, n_467);
  nand g398 (n_470, n_419, n_468);
  nand g399 (n_131, n_469, n_470);
  not g480 (n_133, A[0]);
endmodule

module bmux(ctl, in_0, in_1, z);
  input ctl;
  input [31:0] in_0, in_1;
  output [31:0] z;
  wire ctl;
  wire [31:0] in_0, in_1;
  wire [31:0] z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0[31]), .data1 (in_1[31]), .z
       (z[31]));
  CDN_bmux2 g2(.sel0 (ctl), .data0 (in_0[30]), .data1 (in_1[30]), .z
       (z[30]));
  CDN_bmux2 g3(.sel0 (ctl), .data0 (in_0[29]), .data1 (in_1[29]), .z
       (z[29]));
  CDN_bmux2 g4(.sel0 (ctl), .data0 (in_0[28]), .data1 (in_1[28]), .z
       (z[28]));
  CDN_bmux2 g5(.sel0 (ctl), .data0 (in_0[27]), .data1 (in_1[27]), .z
       (z[27]));
  CDN_bmux2 g6(.sel0 (ctl), .data0 (in_0[26]), .data1 (in_1[26]), .z
       (z[26]));
  CDN_bmux2 g7(.sel0 (ctl), .data0 (in_0[25]), .data1 (in_1[25]), .z
       (z[25]));
  CDN_bmux2 g8(.sel0 (ctl), .data0 (in_0[24]), .data1 (in_1[24]), .z
       (z[24]));
  CDN_bmux2 g9(.sel0 (ctl), .data0 (in_0[23]), .data1 (in_1[23]), .z
       (z[23]));
  CDN_bmux2 g10(.sel0 (ctl), .data0 (in_0[22]), .data1 (in_1[22]), .z
       (z[22]));
  CDN_bmux2 g11(.sel0 (ctl), .data0 (in_0[21]), .data1 (in_1[21]), .z
       (z[21]));
  CDN_bmux2 g12(.sel0 (ctl), .data0 (in_0[20]), .data1 (in_1[20]), .z
       (z[20]));
  CDN_bmux2 g13(.sel0 (ctl), .data0 (in_0[19]), .data1 (in_1[19]), .z
       (z[19]));
  CDN_bmux2 g14(.sel0 (ctl), .data0 (in_0[18]), .data1 (in_1[18]), .z
       (z[18]));
  CDN_bmux2 g15(.sel0 (ctl), .data0 (in_0[17]), .data1 (in_1[17]), .z
       (z[17]));
  CDN_bmux2 g16(.sel0 (ctl), .data0 (in_0[16]), .data1 (in_1[16]), .z
       (z[16]));
  CDN_bmux2 g17(.sel0 (ctl), .data0 (in_0[15]), .data1 (in_1[15]), .z
       (z[15]));
  CDN_bmux2 g18(.sel0 (ctl), .data0 (in_0[14]), .data1 (in_1[14]), .z
       (z[14]));
  CDN_bmux2 g19(.sel0 (ctl), .data0 (in_0[13]), .data1 (in_1[13]), .z
       (z[13]));
  CDN_bmux2 g20(.sel0 (ctl), .data0 (in_0[12]), .data1 (in_1[12]), .z
       (z[12]));
  CDN_bmux2 g21(.sel0 (ctl), .data0 (in_0[11]), .data1 (in_1[11]), .z
       (z[11]));
  CDN_bmux2 g22(.sel0 (ctl), .data0 (in_0[10]), .data1 (in_1[10]), .z
       (z[10]));
  CDN_bmux2 g23(.sel0 (ctl), .data0 (in_0[9]), .data1 (in_1[9]), .z
       (z[9]));
  CDN_bmux2 g24(.sel0 (ctl), .data0 (in_0[8]), .data1 (in_1[8]), .z
       (z[8]));
  CDN_bmux2 g25(.sel0 (ctl), .data0 (in_0[7]), .data1 (in_1[7]), .z
       (z[7]));
  CDN_bmux2 g26(.sel0 (ctl), .data0 (in_0[6]), .data1 (in_1[6]), .z
       (z[6]));
  CDN_bmux2 g27(.sel0 (ctl), .data0 (in_0[5]), .data1 (in_1[5]), .z
       (z[5]));
  CDN_bmux2 g28(.sel0 (ctl), .data0 (in_0[4]), .data1 (in_1[4]), .z
       (z[4]));
  CDN_bmux2 g29(.sel0 (ctl), .data0 (in_0[3]), .data1 (in_1[3]), .z
       (z[3]));
  CDN_bmux2 g30(.sel0 (ctl), .data0 (in_0[2]), .data1 (in_1[2]), .z
       (z[2]));
  CDN_bmux2 g31(.sel0 (ctl), .data0 (in_0[1]), .data1 (in_1[1]), .z
       (z[1]));
  CDN_bmux2 g32(.sel0 (ctl), .data0 (in_0[0]), .data1 (in_1[0]), .z
       (z[0]));
endmodule

module bmux_30(ctl, in_0, in_1, z);
  input ctl, in_0, in_1;
  output z;
  wire ctl, in_0, in_1;
  wire z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0), .data1 (in_1), .z (z));
endmodule

module bmux_43(ctl, in_0, in_1, z);
  input ctl;
  input [4:0] in_0, in_1;
  output [4:0] z;
  wire ctl;
  wire [4:0] in_0, in_1;
  wire [4:0] z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0[4]), .data1 (in_1[4]), .z
       (z[4]));
  CDN_bmux2 g2(.sel0 (ctl), .data0 (in_0[3]), .data1 (in_1[3]), .z
       (z[3]));
  CDN_bmux2 g3(.sel0 (ctl), .data0 (in_0[2]), .data1 (in_1[2]), .z
       (z[2]));
  CDN_bmux2 g4(.sel0 (ctl), .data0 (in_0[1]), .data1 (in_1[1]), .z
       (z[1]));
  CDN_bmux2 g5(.sel0 (ctl), .data0 (in_0[0]), .data1 (in_1[0]), .z
       (z[0]));
endmodule

module proj_sorter(in_signature, in_index, \out_smallest_idx[0] ,
     \out_smallest_idx[1] , \out_smallest_idx[2] , \out_smallest_idx[3]
     , rst_n, end_sorting, sort_valid, clk);
  input [31:0] in_signature;
  input [4:0] in_index;
  input rst_n, end_sorting, clk;
  output [4:0] \out_smallest_idx[0] , \out_smallest_idx[1] ,
       \out_smallest_idx[2] , \out_smallest_idx[3] ;
  output sort_valid;
  wire [31:0] in_signature;
  wire [4:0] in_index;
  wire rst_n, end_sorting, clk;
  wire [4:0] \out_smallest_idx[0] , \out_smallest_idx[1] ,
       \out_smallest_idx[2] , \out_smallest_idx[3] ;
  wire sort_valid;
  wire [3:0] count_signatures_smaller_than;
  wire [2:0] position_smaller_than;
  wire [2:0] new_position_long;
  wire [31:0] \smallest_idx_curr[0][signature] ;
  wire [31:0] \smallest_idx_curr[1][signature] ;
  wire [31:0] \smallest_idx_curr[2][signature] ;
  wire [31:0] \smallest_idx_curr[3][signature] ;
  wire [31:0] \smallest_idx_next[0][signature] ;
  wire [31:0] \smallest_idx_next[1][signature] ;
  wire [31:0] \smallest_idx_next[2][signature] ;
  wire [31:0] \smallest_idx_next[3][signature] ;
  wire [4:0] \smallest_idx_next[0][index] ;
  wire [4:0] \smallest_idx_next[1][index] ;
  wire [4:0] \smallest_idx_next[2][index] ;
  wire [4:0] \smallest_idx_next[3][index] ;
  wire n_173, n_174, n_175, n_176, n_177, n_178, n_179, n_180;
  wire n_181, n_182, n_183, n_184, n_185, n_186, n_187, n_188;
  wire n_189, n_190, n_191, n_192, n_193, n_194, n_195, n_196;
  wire n_197, n_198, n_199, n_200, n_201, n_202, n_203, n_204;
  wire n_205, n_206, n_207, n_208, n_209, n_210, n_211, n_212;
  wire n_213, n_214, n_215, n_216, n_217, n_218, n_219, n_220;
  wire n_221, n_222, n_223, n_224, n_225, n_226, n_227, n_228;
  wire n_229, n_230, n_231, n_232, n_233, n_234, n_235, n_236;
  wire n_237, n_238, n_239, n_240, n_241, n_242, n_243, n_244;
  wire n_245, n_246, n_247, n_248, n_249, n_250, n_251, n_252;
  wire n_253, n_254, n_255, n_256, n_257, n_258, n_259, n_260;
  wire n_261, n_262, n_263, n_264, n_265, n_266, n_267, n_268;
  wire n_269, n_270, n_271, n_272, n_273, n_274, n_275, n_276;
  wire n_277, n_278, n_279, n_280, n_281, n_282, n_283, n_284;
  wire n_285, n_286, n_287, n_288, n_289, n_290, n_291, n_292;
  wire n_293, n_294, n_295, n_296, n_297, n_298, n_299, n_300;
  wire n_301, n_302, n_303, n_304, n_305, n_306, n_307, n_308;
  wire n_309, n_310, n_311, n_312, n_313, n_314, n_315, n_316;
  wire n_317, n_318, n_319, n_320, n_321, n_322, n_323, n_324;
  wire n_325, n_326, n_327, n_328, n_329, n_330, n_331, n_332;
  wire n_333, n_336, n_337, n_338, n_339, n_340, n_878, n_879;
  wire n_880, n_881, n_882, n_883, n_884, n_885, n_886, n_887;
  wire n_888, n_894, n_897, n_900, \position_smaller_than[0]_348 ,
       \position_smaller_than[0]_352 , \position_smaller_than[1]_345 ,
       \position_smaller_than[1]_349 ;
  wire \position_smaller_than[1]_353 , \position_smaller_than[2]_346 ,
       \position_smaller_than[2]_350 , \position_smaller_than[2]_354 ;
  add_unsigned add_41_35_I2(.A ({2'b0,
       count_signatures_smaller_than[0]}), .B
       (count_signatures_smaller_than[1]), .Z
       ({\position_smaller_than[2]_346 , \position_smaller_than[1]_345
       , position_smaller_than[0]}));
  add_unsigned add_41_35_I3(.A ({\position_smaller_than[2]_346 ,
       \position_smaller_than[1]_345 , position_smaller_than[0]}), .B
       (count_signatures_smaller_than[2]), .Z
       ({\position_smaller_than[2]_350 , \position_smaller_than[1]_349
       , \position_smaller_than[0]_348 }));
  add_unsigned add_41_35_I4(.A ({\position_smaller_than[2]_350 ,
       \position_smaller_than[1]_349 , \position_smaller_than[0]_348
       }), .B (count_signatures_smaller_than[3]), .Z
       ({\position_smaller_than[2]_354 , \position_smaller_than[1]_353
       , \position_smaller_than[0]_352 }));
  sub_unsigned sub_55_43(.A (3'b100), .B
       ({\position_smaller_than[2]_354 , \position_smaller_than[1]_353
       , \position_smaller_than[0]_352 }), .Z (new_position_long));
  lt_unsigned lt_40_68_I1(.A (in_signature), .B
       (\smallest_idx_curr[0][signature] ), .Z (n_208));
  lt_unsigned lt_40_68_I2(.A (in_signature), .B
       (\smallest_idx_curr[1][signature] ), .Z (n_243));
  lt_unsigned lt_40_68_I3(.A (in_signature), .B
       (\smallest_idx_curr[2][signature] ), .Z (n_278));
  lt_unsigned lt_40_68_I4(.A (in_signature), .B
       (\smallest_idx_curr[3][signature] ), .Z (n_279));
  bmux \mux_smallest_idx_curr[0][signature]_78_41 (.ctl (n_174), .in_0
       (\smallest_idx_next[0][signature] ), .in_1 (in_signature), .z
       ({n_207, n_206, n_205, n_204, n_203, n_202, n_201, n_200, n_199,
       n_198, n_197, n_196, n_195, n_194, n_193, n_192, n_191, n_190,
       n_189, n_188, n_187, n_186, n_185, n_184, n_183, n_182, n_181,
       n_180, n_179, n_178, n_177, n_176}));
  bmux_30 mux_40_68(.ctl (n_208), .in_0 (1'b0), .in_1 (1'b1), .z
       (count_signatures_smaller_than[0]));
  bmux \mux_smallest_idx_next[1][signature]_42_39 (.ctl (n_210), .in_0
       (\smallest_idx_curr[0][signature] ), .in_1
       (\smallest_idx_curr[1][signature] ), .z
       (\smallest_idx_next[1][signature] ));
  bmux \mux_smallest_idx_curr[1][signature]_78_41 (.ctl (n_209), .in_0
       (\smallest_idx_next[1][signature] ), .in_1 (in_signature), .z
       ({n_242, n_241, n_240, n_239, n_238, n_237, n_236, n_235, n_234,
       n_233, n_232, n_231, n_230, n_229, n_228, n_227, n_226, n_225,
       n_224, n_223, n_222, n_221, n_220, n_219, n_218, n_217, n_216,
       n_215, n_214, n_213, n_212, n_211}));
  bmux_30 mux_40_23(.ctl (n_243), .in_0 (1'b0), .in_1 (1'b1), .z
       (count_signatures_smaller_than[1]));
  bmux \mux_smallest_idx_next[2][signature]_42_39 (.ctl (n_245), .in_0
       (\smallest_idx_curr[1][signature] ), .in_1
       (\smallest_idx_curr[2][signature] ), .z
       (\smallest_idx_next[2][signature] ));
  bmux \mux_smallest_idx_curr[2][signature]_78_41 (.ctl (n_244), .in_0
       (\smallest_idx_next[2][signature] ), .in_1 (in_signature), .z
       ({n_277, n_276, n_275, n_274, n_273, n_272, n_271, n_270, n_269,
       n_268, n_267, n_266, n_265, n_264, n_263, n_262, n_261, n_260,
       n_259, n_258, n_257, n_256, n_255, n_254, n_253, n_252, n_251,
       n_250, n_249, n_248, n_247, n_246}));
  bmux_30 mux_40_27(.ctl (n_278), .in_0 (1'b0), .in_1 (1'b1), .z
       (count_signatures_smaller_than[2]));
  bmux_30 mux_40_29(.ctl (n_279), .in_0 (1'b0), .in_1 (1'b1), .z
       (count_signatures_smaller_than[3]));
  bmux \mux_smallest_idx_next[3][signature]_42_39 (.ctl (n_281), .in_0
       (\smallest_idx_curr[2][signature] ), .in_1
       (\smallest_idx_curr[3][signature] ), .z
       (\smallest_idx_next[3][signature] ));
  bmux \mux_smallest_idx_curr[3][signature]_78_41 (.ctl (n_280), .in_0
       (\smallest_idx_next[3][signature] ), .in_1 (in_signature), .z
       ({n_313, n_312, n_311, n_310, n_309, n_308, n_307, n_306, n_305,
       n_304, n_303, n_302, n_301, n_300, n_299, n_298, n_297, n_296,
       n_295, n_294, n_293, n_292, n_291, n_290, n_289, n_288, n_287,
       n_286, n_285, n_284, n_283, n_282}));
  bmux_43 \mux_smallest_idx_curr[0][index]_78_41 (.ctl (n_174), .in_0
       (\smallest_idx_next[0][index] ), .in_1 (in_index), .z ({n_318,
       n_317, n_316, n_315, n_314}));
  bmux_43 \mux_smallest_idx_next[1][index]_42_39 (.ctl (n_210), .in_0
       (\out_smallest_idx[0] ), .in_1 (\out_smallest_idx[1] ), .z
       (\smallest_idx_next[1][index] ));
  bmux_43 \mux_smallest_idx_curr[1][index]_78_41 (.ctl (n_209), .in_0
       (\smallest_idx_next[1][index] ), .in_1 (in_index), .z ({n_323,
       n_322, n_321, n_320, n_319}));
  bmux_43 \mux_smallest_idx_next[2][index]_42_39 (.ctl (n_245), .in_0
       (\out_smallest_idx[1] ), .in_1 (\out_smallest_idx[2] ), .z
       (\smallest_idx_next[2][index] ));
  bmux_43 \mux_smallest_idx_curr[2][index]_78_41 (.ctl (n_244), .in_0
       (\smallest_idx_next[2][index] ), .in_1 (in_index), .z ({n_328,
       n_327, n_326, n_325, n_324}));
  bmux_43 \mux_smallest_idx_next[3][index]_42_39 (.ctl (n_281), .in_0
       (\out_smallest_idx[2] ), .in_1 (\out_smallest_idx[3] ), .z
       (\smallest_idx_next[3][index] ));
  bmux_43 \mux_smallest_idx_curr[3][index]_78_41 (.ctl (n_280), .in_0
       (\smallest_idx_next[3][index] ), .in_1 (in_index), .z ({n_333,
       n_332, n_331, n_330, n_329}));
  bmux_30 mux_67_25(.ctl (end_sorting), .in_0 (1'b0), .in_1 (1'b1), .z
       (sort_valid));
  not g3 (n_173, rst_n);
  and g4 (n_174, n_336, n_337);
  and g5 (n_209, n_338, n_337);
  and g6 (n_244, n_339, n_337);
  and g7 (n_280, n_340, n_337);
  CDN_latch \smallest_idx_next_reg[0][index][0] (.d
       (\out_smallest_idx[0] [0]), .ena (n_175), .aclr (1'b0), .apre
       (1'b0), .q (\smallest_idx_next[0][index] [0]));
  CDN_latch \smallest_idx_next_reg[0][index][1] (.d
       (\out_smallest_idx[0] [1]), .ena (n_175), .aclr (1'b0), .apre
       (1'b0), .q (\smallest_idx_next[0][index] [1]));
  CDN_latch \smallest_idx_next_reg[0][index][2] (.d
       (\out_smallest_idx[0] [2]), .ena (n_175), .aclr (1'b0), .apre
       (1'b0), .q (\smallest_idx_next[0][index] [2]));
  CDN_latch \smallest_idx_next_reg[0][index][3] (.d
       (\out_smallest_idx[0] [3]), .ena (n_175), .aclr (1'b0), .apre
       (1'b0), .q (\smallest_idx_next[0][index] [3]));
  CDN_latch \smallest_idx_next_reg[0][index][4] (.d
       (\out_smallest_idx[0] [4]), .ena (n_175), .aclr (1'b0), .apre
       (1'b0), .q (\smallest_idx_next[0][index] [4]));
  CDN_latch \smallest_idx_next_reg[0][signature][0] (.d
       (\smallest_idx_curr[0][signature] [0]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature] [0]));
  CDN_latch \smallest_idx_next_reg[0][signature][1] (.d
       (\smallest_idx_curr[0][signature] [1]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature] [1]));
  CDN_latch \smallest_idx_next_reg[0][signature][2] (.d
       (\smallest_idx_curr[0][signature] [2]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature] [2]));
  CDN_latch \smallest_idx_next_reg[0][signature][3] (.d
       (\smallest_idx_curr[0][signature] [3]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature] [3]));
  CDN_latch \smallest_idx_next_reg[0][signature][4] (.d
       (\smallest_idx_curr[0][signature] [4]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature] [4]));
  CDN_latch \smallest_idx_next_reg[0][signature][5] (.d
       (\smallest_idx_curr[0][signature] [5]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature] [5]));
  CDN_latch \smallest_idx_next_reg[0][signature][6] (.d
       (\smallest_idx_curr[0][signature] [6]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature] [6]));
  CDN_latch \smallest_idx_next_reg[0][signature][7] (.d
       (\smallest_idx_curr[0][signature] [7]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature] [7]));
  CDN_latch \smallest_idx_next_reg[0][signature][8] (.d
       (\smallest_idx_curr[0][signature] [8]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature] [8]));
  CDN_latch \smallest_idx_next_reg[0][signature][9] (.d
       (\smallest_idx_curr[0][signature] [9]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature] [9]));
  CDN_latch \smallest_idx_next_reg[0][signature][10] (.d
       (\smallest_idx_curr[0][signature] [10]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature]
       [10]));
  CDN_latch \smallest_idx_next_reg[0][signature][11] (.d
       (\smallest_idx_curr[0][signature] [11]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature]
       [11]));
  CDN_latch \smallest_idx_next_reg[0][signature][12] (.d
       (\smallest_idx_curr[0][signature] [12]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature]
       [12]));
  CDN_latch \smallest_idx_next_reg[0][signature][13] (.d
       (\smallest_idx_curr[0][signature] [13]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature]
       [13]));
  CDN_latch \smallest_idx_next_reg[0][signature][14] (.d
       (\smallest_idx_curr[0][signature] [14]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature]
       [14]));
  CDN_latch \smallest_idx_next_reg[0][signature][15] (.d
       (\smallest_idx_curr[0][signature] [15]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature]
       [15]));
  CDN_latch \smallest_idx_next_reg[0][signature][16] (.d
       (\smallest_idx_curr[0][signature] [16]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature]
       [16]));
  CDN_latch \smallest_idx_next_reg[0][signature][17] (.d
       (\smallest_idx_curr[0][signature] [17]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature]
       [17]));
  CDN_latch \smallest_idx_next_reg[0][signature][18] (.d
       (\smallest_idx_curr[0][signature] [18]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature]
       [18]));
  CDN_latch \smallest_idx_next_reg[0][signature][19] (.d
       (\smallest_idx_curr[0][signature] [19]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature]
       [19]));
  CDN_latch \smallest_idx_next_reg[0][signature][20] (.d
       (\smallest_idx_curr[0][signature] [20]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature]
       [20]));
  CDN_latch \smallest_idx_next_reg[0][signature][21] (.d
       (\smallest_idx_curr[0][signature] [21]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature]
       [21]));
  CDN_latch \smallest_idx_next_reg[0][signature][22] (.d
       (\smallest_idx_curr[0][signature] [22]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature]
       [22]));
  CDN_latch \smallest_idx_next_reg[0][signature][23] (.d
       (\smallest_idx_curr[0][signature] [23]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature]
       [23]));
  CDN_latch \smallest_idx_next_reg[0][signature][24] (.d
       (\smallest_idx_curr[0][signature] [24]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature]
       [24]));
  CDN_latch \smallest_idx_next_reg[0][signature][25] (.d
       (\smallest_idx_curr[0][signature] [25]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature]
       [25]));
  CDN_latch \smallest_idx_next_reg[0][signature][26] (.d
       (\smallest_idx_curr[0][signature] [26]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature]
       [26]));
  CDN_latch \smallest_idx_next_reg[0][signature][27] (.d
       (\smallest_idx_curr[0][signature] [27]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature]
       [27]));
  CDN_latch \smallest_idx_next_reg[0][signature][28] (.d
       (\smallest_idx_curr[0][signature] [28]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature]
       [28]));
  CDN_latch \smallest_idx_next_reg[0][signature][29] (.d
       (\smallest_idx_curr[0][signature] [29]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature]
       [29]));
  CDN_latch \smallest_idx_next_reg[0][signature][30] (.d
       (\smallest_idx_curr[0][signature] [30]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature]
       [30]));
  CDN_latch \smallest_idx_next_reg[0][signature][31] (.d
       (\smallest_idx_curr[0][signature] [31]), .ena (n_175), .aclr
       (1'b0), .apre (1'b0), .q (\smallest_idx_next[0][signature]
       [31]));
  CDN_flop \smallest_idx_curr_reg[0][index][0] (.clk (clk), .d (n_314),
       .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173), .srd
       (1'b0), .q (\out_smallest_idx[0] [0]));
  CDN_flop \smallest_idx_curr_reg[0][index][1] (.clk (clk), .d (n_315),
       .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173), .srd
       (1'b0), .q (\out_smallest_idx[0] [1]));
  CDN_flop \smallest_idx_curr_reg[0][index][2] (.clk (clk), .d (n_316),
       .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173), .srd
       (1'b0), .q (\out_smallest_idx[0] [2]));
  CDN_flop \smallest_idx_curr_reg[0][index][3] (.clk (clk), .d (n_317),
       .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173), .srd
       (1'b0), .q (\out_smallest_idx[0] [3]));
  CDN_flop \smallest_idx_curr_reg[0][index][4] (.clk (clk), .d (n_318),
       .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173), .srd
       (1'b0), .q (\out_smallest_idx[0] [4]));
  CDN_flop \smallest_idx_curr_reg[0][signature][0] (.clk (clk), .d
       (n_176), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [0]));
  CDN_flop \smallest_idx_curr_reg[0][signature][1] (.clk (clk), .d
       (n_177), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [1]));
  CDN_flop \smallest_idx_curr_reg[0][signature][2] (.clk (clk), .d
       (n_178), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [2]));
  CDN_flop \smallest_idx_curr_reg[0][signature][3] (.clk (clk), .d
       (n_179), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [3]));
  CDN_flop \smallest_idx_curr_reg[0][signature][4] (.clk (clk), .d
       (n_180), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [4]));
  CDN_flop \smallest_idx_curr_reg[0][signature][5] (.clk (clk), .d
       (n_181), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [5]));
  CDN_flop \smallest_idx_curr_reg[0][signature][6] (.clk (clk), .d
       (n_182), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [6]));
  CDN_flop \smallest_idx_curr_reg[0][signature][7] (.clk (clk), .d
       (n_183), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [7]));
  CDN_flop \smallest_idx_curr_reg[0][signature][8] (.clk (clk), .d
       (n_184), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [8]));
  CDN_flop \smallest_idx_curr_reg[0][signature][9] (.clk (clk), .d
       (n_185), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [9]));
  CDN_flop \smallest_idx_curr_reg[0][signature][10] (.clk (clk), .d
       (n_186), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [10]));
  CDN_flop \smallest_idx_curr_reg[0][signature][11] (.clk (clk), .d
       (n_187), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [11]));
  CDN_flop \smallest_idx_curr_reg[0][signature][12] (.clk (clk), .d
       (n_188), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [12]));
  CDN_flop \smallest_idx_curr_reg[0][signature][13] (.clk (clk), .d
       (n_189), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [13]));
  CDN_flop \smallest_idx_curr_reg[0][signature][14] (.clk (clk), .d
       (n_190), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [14]));
  CDN_flop \smallest_idx_curr_reg[0][signature][15] (.clk (clk), .d
       (n_191), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [15]));
  CDN_flop \smallest_idx_curr_reg[0][signature][16] (.clk (clk), .d
       (n_192), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [16]));
  CDN_flop \smallest_idx_curr_reg[0][signature][17] (.clk (clk), .d
       (n_193), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [17]));
  CDN_flop \smallest_idx_curr_reg[0][signature][18] (.clk (clk), .d
       (n_194), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [18]));
  CDN_flop \smallest_idx_curr_reg[0][signature][19] (.clk (clk), .d
       (n_195), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [19]));
  CDN_flop \smallest_idx_curr_reg[0][signature][20] (.clk (clk), .d
       (n_196), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [20]));
  CDN_flop \smallest_idx_curr_reg[0][signature][21] (.clk (clk), .d
       (n_197), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [21]));
  CDN_flop \smallest_idx_curr_reg[0][signature][22] (.clk (clk), .d
       (n_198), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [22]));
  CDN_flop \smallest_idx_curr_reg[0][signature][23] (.clk (clk), .d
       (n_199), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [23]));
  CDN_flop \smallest_idx_curr_reg[0][signature][24] (.clk (clk), .d
       (n_200), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [24]));
  CDN_flop \smallest_idx_curr_reg[0][signature][25] (.clk (clk), .d
       (n_201), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [25]));
  CDN_flop \smallest_idx_curr_reg[0][signature][26] (.clk (clk), .d
       (n_202), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [26]));
  CDN_flop \smallest_idx_curr_reg[0][signature][27] (.clk (clk), .d
       (n_203), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [27]));
  CDN_flop \smallest_idx_curr_reg[0][signature][28] (.clk (clk), .d
       (n_204), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [28]));
  CDN_flop \smallest_idx_curr_reg[0][signature][29] (.clk (clk), .d
       (n_205), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [29]));
  CDN_flop \smallest_idx_curr_reg[0][signature][30] (.clk (clk), .d
       (n_206), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [30]));
  CDN_flop \smallest_idx_curr_reg[0][signature][31] (.clk (clk), .d
       (n_207), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[0][signature] [31]));
  CDN_flop \smallest_idx_curr_reg[1][index][0] (.clk (clk), .d (n_319),
       .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173), .srd
       (1'b0), .q (\out_smallest_idx[1] [0]));
  CDN_flop \smallest_idx_curr_reg[1][index][1] (.clk (clk), .d (n_320),
       .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173), .srd
       (1'b0), .q (\out_smallest_idx[1] [1]));
  CDN_flop \smallest_idx_curr_reg[1][index][2] (.clk (clk), .d (n_321),
       .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173), .srd
       (1'b0), .q (\out_smallest_idx[1] [2]));
  CDN_flop \smallest_idx_curr_reg[1][index][3] (.clk (clk), .d (n_322),
       .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173), .srd
       (1'b0), .q (\out_smallest_idx[1] [3]));
  CDN_flop \smallest_idx_curr_reg[1][index][4] (.clk (clk), .d (n_323),
       .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173), .srd
       (1'b0), .q (\out_smallest_idx[1] [4]));
  CDN_flop \smallest_idx_curr_reg[1][signature][0] (.clk (clk), .d
       (n_211), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [0]));
  CDN_flop \smallest_idx_curr_reg[1][signature][1] (.clk (clk), .d
       (n_212), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [1]));
  CDN_flop \smallest_idx_curr_reg[1][signature][2] (.clk (clk), .d
       (n_213), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [2]));
  CDN_flop \smallest_idx_curr_reg[1][signature][3] (.clk (clk), .d
       (n_214), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [3]));
  CDN_flop \smallest_idx_curr_reg[1][signature][4] (.clk (clk), .d
       (n_215), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [4]));
  CDN_flop \smallest_idx_curr_reg[1][signature][5] (.clk (clk), .d
       (n_216), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [5]));
  CDN_flop \smallest_idx_curr_reg[1][signature][6] (.clk (clk), .d
       (n_217), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [6]));
  CDN_flop \smallest_idx_curr_reg[1][signature][7] (.clk (clk), .d
       (n_218), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [7]));
  CDN_flop \smallest_idx_curr_reg[1][signature][8] (.clk (clk), .d
       (n_219), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [8]));
  CDN_flop \smallest_idx_curr_reg[1][signature][9] (.clk (clk), .d
       (n_220), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [9]));
  CDN_flop \smallest_idx_curr_reg[1][signature][10] (.clk (clk), .d
       (n_221), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [10]));
  CDN_flop \smallest_idx_curr_reg[1][signature][11] (.clk (clk), .d
       (n_222), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [11]));
  CDN_flop \smallest_idx_curr_reg[1][signature][12] (.clk (clk), .d
       (n_223), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [12]));
  CDN_flop \smallest_idx_curr_reg[1][signature][13] (.clk (clk), .d
       (n_224), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [13]));
  CDN_flop \smallest_idx_curr_reg[1][signature][14] (.clk (clk), .d
       (n_225), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [14]));
  CDN_flop \smallest_idx_curr_reg[1][signature][15] (.clk (clk), .d
       (n_226), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [15]));
  CDN_flop \smallest_idx_curr_reg[1][signature][16] (.clk (clk), .d
       (n_227), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [16]));
  CDN_flop \smallest_idx_curr_reg[1][signature][17] (.clk (clk), .d
       (n_228), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [17]));
  CDN_flop \smallest_idx_curr_reg[1][signature][18] (.clk (clk), .d
       (n_229), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [18]));
  CDN_flop \smallest_idx_curr_reg[1][signature][19] (.clk (clk), .d
       (n_230), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [19]));
  CDN_flop \smallest_idx_curr_reg[1][signature][20] (.clk (clk), .d
       (n_231), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [20]));
  CDN_flop \smallest_idx_curr_reg[1][signature][21] (.clk (clk), .d
       (n_232), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [21]));
  CDN_flop \smallest_idx_curr_reg[1][signature][22] (.clk (clk), .d
       (n_233), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [22]));
  CDN_flop \smallest_idx_curr_reg[1][signature][23] (.clk (clk), .d
       (n_234), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [23]));
  CDN_flop \smallest_idx_curr_reg[1][signature][24] (.clk (clk), .d
       (n_235), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [24]));
  CDN_flop \smallest_idx_curr_reg[1][signature][25] (.clk (clk), .d
       (n_236), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [25]));
  CDN_flop \smallest_idx_curr_reg[1][signature][26] (.clk (clk), .d
       (n_237), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [26]));
  CDN_flop \smallest_idx_curr_reg[1][signature][27] (.clk (clk), .d
       (n_238), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [27]));
  CDN_flop \smallest_idx_curr_reg[1][signature][28] (.clk (clk), .d
       (n_239), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [28]));
  CDN_flop \smallest_idx_curr_reg[1][signature][29] (.clk (clk), .d
       (n_240), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [29]));
  CDN_flop \smallest_idx_curr_reg[1][signature][30] (.clk (clk), .d
       (n_241), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [30]));
  CDN_flop \smallest_idx_curr_reg[1][signature][31] (.clk (clk), .d
       (n_242), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[1][signature] [31]));
  CDN_flop \smallest_idx_curr_reg[2][index][0] (.clk (clk), .d (n_324),
       .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173), .srd
       (1'b0), .q (\out_smallest_idx[2] [0]));
  CDN_flop \smallest_idx_curr_reg[2][index][1] (.clk (clk), .d (n_325),
       .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173), .srd
       (1'b0), .q (\out_smallest_idx[2] [1]));
  CDN_flop \smallest_idx_curr_reg[2][index][2] (.clk (clk), .d (n_326),
       .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173), .srd
       (1'b0), .q (\out_smallest_idx[2] [2]));
  CDN_flop \smallest_idx_curr_reg[2][index][3] (.clk (clk), .d (n_327),
       .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173), .srd
       (1'b0), .q (\out_smallest_idx[2] [3]));
  CDN_flop \smallest_idx_curr_reg[2][index][4] (.clk (clk), .d (n_328),
       .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173), .srd
       (1'b0), .q (\out_smallest_idx[2] [4]));
  CDN_flop \smallest_idx_curr_reg[2][signature][0] (.clk (clk), .d
       (n_246), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [0]));
  CDN_flop \smallest_idx_curr_reg[2][signature][1] (.clk (clk), .d
       (n_247), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [1]));
  CDN_flop \smallest_idx_curr_reg[2][signature][2] (.clk (clk), .d
       (n_248), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [2]));
  CDN_flop \smallest_idx_curr_reg[2][signature][3] (.clk (clk), .d
       (n_249), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [3]));
  CDN_flop \smallest_idx_curr_reg[2][signature][4] (.clk (clk), .d
       (n_250), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [4]));
  CDN_flop \smallest_idx_curr_reg[2][signature][5] (.clk (clk), .d
       (n_251), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [5]));
  CDN_flop \smallest_idx_curr_reg[2][signature][6] (.clk (clk), .d
       (n_252), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [6]));
  CDN_flop \smallest_idx_curr_reg[2][signature][7] (.clk (clk), .d
       (n_253), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [7]));
  CDN_flop \smallest_idx_curr_reg[2][signature][8] (.clk (clk), .d
       (n_254), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [8]));
  CDN_flop \smallest_idx_curr_reg[2][signature][9] (.clk (clk), .d
       (n_255), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [9]));
  CDN_flop \smallest_idx_curr_reg[2][signature][10] (.clk (clk), .d
       (n_256), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [10]));
  CDN_flop \smallest_idx_curr_reg[2][signature][11] (.clk (clk), .d
       (n_257), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [11]));
  CDN_flop \smallest_idx_curr_reg[2][signature][12] (.clk (clk), .d
       (n_258), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [12]));
  CDN_flop \smallest_idx_curr_reg[2][signature][13] (.clk (clk), .d
       (n_259), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [13]));
  CDN_flop \smallest_idx_curr_reg[2][signature][14] (.clk (clk), .d
       (n_260), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [14]));
  CDN_flop \smallest_idx_curr_reg[2][signature][15] (.clk (clk), .d
       (n_261), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [15]));
  CDN_flop \smallest_idx_curr_reg[2][signature][16] (.clk (clk), .d
       (n_262), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [16]));
  CDN_flop \smallest_idx_curr_reg[2][signature][17] (.clk (clk), .d
       (n_263), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [17]));
  CDN_flop \smallest_idx_curr_reg[2][signature][18] (.clk (clk), .d
       (n_264), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [18]));
  CDN_flop \smallest_idx_curr_reg[2][signature][19] (.clk (clk), .d
       (n_265), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [19]));
  CDN_flop \smallest_idx_curr_reg[2][signature][20] (.clk (clk), .d
       (n_266), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [20]));
  CDN_flop \smallest_idx_curr_reg[2][signature][21] (.clk (clk), .d
       (n_267), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [21]));
  CDN_flop \smallest_idx_curr_reg[2][signature][22] (.clk (clk), .d
       (n_268), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [22]));
  CDN_flop \smallest_idx_curr_reg[2][signature][23] (.clk (clk), .d
       (n_269), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [23]));
  CDN_flop \smallest_idx_curr_reg[2][signature][24] (.clk (clk), .d
       (n_270), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [24]));
  CDN_flop \smallest_idx_curr_reg[2][signature][25] (.clk (clk), .d
       (n_271), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [25]));
  CDN_flop \smallest_idx_curr_reg[2][signature][26] (.clk (clk), .d
       (n_272), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [26]));
  CDN_flop \smallest_idx_curr_reg[2][signature][27] (.clk (clk), .d
       (n_273), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [27]));
  CDN_flop \smallest_idx_curr_reg[2][signature][28] (.clk (clk), .d
       (n_274), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [28]));
  CDN_flop \smallest_idx_curr_reg[2][signature][29] (.clk (clk), .d
       (n_275), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [29]));
  CDN_flop \smallest_idx_curr_reg[2][signature][30] (.clk (clk), .d
       (n_276), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [30]));
  CDN_flop \smallest_idx_curr_reg[2][signature][31] (.clk (clk), .d
       (n_277), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[2][signature] [31]));
  CDN_flop \smallest_idx_curr_reg[3][index][0] (.clk (clk), .d (n_329),
       .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173), .srd
       (1'b0), .q (\out_smallest_idx[3] [0]));
  CDN_flop \smallest_idx_curr_reg[3][index][1] (.clk (clk), .d (n_330),
       .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173), .srd
       (1'b0), .q (\out_smallest_idx[3] [1]));
  CDN_flop \smallest_idx_curr_reg[3][index][2] (.clk (clk), .d (n_331),
       .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173), .srd
       (1'b0), .q (\out_smallest_idx[3] [2]));
  CDN_flop \smallest_idx_curr_reg[3][index][3] (.clk (clk), .d (n_332),
       .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173), .srd
       (1'b0), .q (\out_smallest_idx[3] [3]));
  CDN_flop \smallest_idx_curr_reg[3][index][4] (.clk (clk), .d (n_333),
       .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173), .srd
       (1'b0), .q (\out_smallest_idx[3] [4]));
  CDN_flop \smallest_idx_curr_reg[3][signature][0] (.clk (clk), .d
       (n_282), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [0]));
  CDN_flop \smallest_idx_curr_reg[3][signature][1] (.clk (clk), .d
       (n_283), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [1]));
  CDN_flop \smallest_idx_curr_reg[3][signature][2] (.clk (clk), .d
       (n_284), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [2]));
  CDN_flop \smallest_idx_curr_reg[3][signature][3] (.clk (clk), .d
       (n_285), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [3]));
  CDN_flop \smallest_idx_curr_reg[3][signature][4] (.clk (clk), .d
       (n_286), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [4]));
  CDN_flop \smallest_idx_curr_reg[3][signature][5] (.clk (clk), .d
       (n_287), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [5]));
  CDN_flop \smallest_idx_curr_reg[3][signature][6] (.clk (clk), .d
       (n_288), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [6]));
  CDN_flop \smallest_idx_curr_reg[3][signature][7] (.clk (clk), .d
       (n_289), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [7]));
  CDN_flop \smallest_idx_curr_reg[3][signature][8] (.clk (clk), .d
       (n_290), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [8]));
  CDN_flop \smallest_idx_curr_reg[3][signature][9] (.clk (clk), .d
       (n_291), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [9]));
  CDN_flop \smallest_idx_curr_reg[3][signature][10] (.clk (clk), .d
       (n_292), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [10]));
  CDN_flop \smallest_idx_curr_reg[3][signature][11] (.clk (clk), .d
       (n_293), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [11]));
  CDN_flop \smallest_idx_curr_reg[3][signature][12] (.clk (clk), .d
       (n_294), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [12]));
  CDN_flop \smallest_idx_curr_reg[3][signature][13] (.clk (clk), .d
       (n_295), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [13]));
  CDN_flop \smallest_idx_curr_reg[3][signature][14] (.clk (clk), .d
       (n_296), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [14]));
  CDN_flop \smallest_idx_curr_reg[3][signature][15] (.clk (clk), .d
       (n_297), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [15]));
  CDN_flop \smallest_idx_curr_reg[3][signature][16] (.clk (clk), .d
       (n_298), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [16]));
  CDN_flop \smallest_idx_curr_reg[3][signature][17] (.clk (clk), .d
       (n_299), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [17]));
  CDN_flop \smallest_idx_curr_reg[3][signature][18] (.clk (clk), .d
       (n_300), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [18]));
  CDN_flop \smallest_idx_curr_reg[3][signature][19] (.clk (clk), .d
       (n_301), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [19]));
  CDN_flop \smallest_idx_curr_reg[3][signature][20] (.clk (clk), .d
       (n_302), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [20]));
  CDN_flop \smallest_idx_curr_reg[3][signature][21] (.clk (clk), .d
       (n_303), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [21]));
  CDN_flop \smallest_idx_curr_reg[3][signature][22] (.clk (clk), .d
       (n_304), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [22]));
  CDN_flop \smallest_idx_curr_reg[3][signature][23] (.clk (clk), .d
       (n_305), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [23]));
  CDN_flop \smallest_idx_curr_reg[3][signature][24] (.clk (clk), .d
       (n_306), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [24]));
  CDN_flop \smallest_idx_curr_reg[3][signature][25] (.clk (clk), .d
       (n_307), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [25]));
  CDN_flop \smallest_idx_curr_reg[3][signature][26] (.clk (clk), .d
       (n_308), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [26]));
  CDN_flop \smallest_idx_curr_reg[3][signature][27] (.clk (clk), .d
       (n_309), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [27]));
  CDN_flop \smallest_idx_curr_reg[3][signature][28] (.clk (clk), .d
       (n_310), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [28]));
  CDN_flop \smallest_idx_curr_reg[3][signature][29] (.clk (clk), .d
       (n_311), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [29]));
  CDN_flop \smallest_idx_curr_reg[3][signature][30] (.clk (clk), .d
       (n_312), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [30]));
  CDN_flop \smallest_idx_curr_reg[3][signature][31] (.clk (clk), .d
       (n_313), .sena (1'b1), .aclr (1'b0), .apre (1'b0), .srl (n_173),
       .srd (1'b1), .q (\smallest_idx_curr[3][signature] [31]));
  not g34 (n_175, count_signatures_smaller_than[0]);
  not g36 (n_879, new_position_long[1]);
  nand g37 (n_880, n_878, n_879);
  not g38 (n_336, n_880);
  nor g40 (n_882, \position_smaller_than[2]_346 ,
       \position_smaller_than[1]_345 );
  nand g41 (n_883, n_882, n_881);
  not g42 (n_210, n_883);
  nor g44 (n_885, \position_smaller_than[2]_350 ,
       \position_smaller_than[1]_349 );
  nand g45 (n_886, n_885, n_884);
  not g46 (n_245, n_886);
  not g50 (n_281, n_337);
  nor g52 (n_888, \position_smaller_than[2]_354 ,
       \position_smaller_than[1]_353 );
  nand g53 (n_337, n_888, n_887);
  nand g56 (n_894, new_position_long[0], n_879);
  not g57 (n_338, n_894);
  nand g60 (n_897, new_position_long[1], n_878);
  not g61 (n_339, n_897);
  nand g64 (n_900, new_position_long[1], new_position_long[0]);
  not g65 (n_340, n_900);
  not g66 (n_878, new_position_long[0]);
  not g67 (n_887, \position_smaller_than[0]_352 );
  not g69 (n_881, position_smaller_than[0]);
  not g70 (n_884, \position_smaller_than[0]_348 );
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_latch(ena, d, aclr, apre, q);
  input ena, d, aclr, apre;
  output q;
  wire ena, d, aclr, apre;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(d or ena or apre or aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else begin
          if (ena) 
            qi <= d;
        end
  initial 
    qi <= 1'b0;
endmodule
`endif
`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_flop(clk, d, sena, aclr, apre, srl, srd, q);
  input clk, d, sena, aclr, apre, srl, srd;
  output q;
  wire clk, d, sena, aclr, apre, srl, srd;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(posedge clk or posedge apre or posedge aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else if (srl) 
            qi <= srd;
          else begin
            if (sena) 
              qi <= d;
          end
  initial 
    qi <= 1'b0;
endmodule
`endif
`ifdef RC_CDN_GENERIC_GATE
`else
`ifdef ONE_HOT_MUX
module CDN_bmux2(sel0, data0, data1, z);
  input sel0, data0, data1;
  output z;
  wire sel0, data0, data1;
  reg  z;
  always 
    @(sel0 or data0 or data1) 
      case ({sel0})
       1'b0: z = data0;
       1'b1: z = data1;
      endcase
endmodule
`else
module CDN_bmux2(sel0, data0, data1, z);
  input sel0, data0, data1;
  output z;
  wire sel0, data0, data1;
  wire z;
  wire inv_sel0, w_0, w_1;
  not i_0 (inv_sel0, sel0);
  and a_0 (w_0, inv_sel0, data0);
  and a_1 (w_1, sel0, data1);
  or org (z, w_0, w_1);
endmodule
`endif // ONE_HOT_MUX
`endif
