
// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Aug  8 2024 11:23:21 UTC (Aug  8 2024 11:23:21 UTC)

// Verification Directory fv/proj_sorter 

module lt_unsigned(A, B, Z);
  input [31:0] A, B;
  output Z;
  wire [31:0] A, B;
  wire Z;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_131, n_132, n_133, n_135, n_136, n_137, n_138, n_139;
  wire n_140, n_141, n_142, n_143, n_144, n_145, n_146, n_147;
  wire n_148, n_149, n_150, n_151, n_152, n_153, n_154, n_155;
  wire n_156, n_157, n_158, n_159, n_160, n_161, n_162, n_163;
  wire n_164, n_165, n_166, n_167, n_168, n_169, n_170, n_171;
  wire n_172, n_173, n_174, n_175, n_176, n_177, n_178, n_179;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_190, n_191, n_192, n_193, n_194, n_195;
  wire n_196, n_197, n_198, n_199, n_200, n_201, n_202, n_203;
  wire n_204, n_205, n_206, n_207, n_208, n_209, n_210, n_211;
  wire n_212, n_213, n_214, n_215, n_216, n_217, n_218, n_219;
  wire n_220, n_221, n_222, n_223, n_224, n_225, n_226, n_227;
  wire n_228, n_231, n_232, n_233, n_234, n_237, n_239, n_240;
  wire n_241, n_242, n_243, n_244, n_247, n_249, n_250, n_251;
  wire n_252, n_253, n_254, n_257, n_259, n_260, n_261, n_262;
  wire n_263, n_264, n_267, n_269, n_270, n_271, n_272, n_273;
  wire n_274, n_277, n_279, n_280, n_281, n_282, n_283, n_284;
  wire n_287, n_289, n_290, n_291, n_292, n_293, n_294, n_297;
  wire n_299, n_300, n_301, n_302, n_303, n_304, n_312, n_313;
  wire n_314, n_315, n_316, n_319, n_327, n_328, n_329, n_330;
  wire n_331, n_334, n_342, n_343, n_344, n_345, n_346, n_349;
  wire n_357, n_358, n_359, n_360, n_361, n_380, n_381, n_382;
  wire n_383, n_386, n_414, n_415, n_416, n_417, n_418, n_419;
  wire n_467, n_468, n_469, n_470;
  not g2 (n_99, B[31]);
  not g3 (n_100, B[30]);
  not g4 (n_101, B[29]);
  not g5 (n_102, B[28]);
  not g6 (n_103, B[27]);
  not g7 (n_104, B[26]);
  not g8 (n_105, B[25]);
  not g9 (n_106, B[24]);
  not g10 (n_107, B[23]);
  not g11 (n_108, B[22]);
  not g12 (n_109, B[21]);
  not g13 (n_110, B[20]);
  not g14 (n_111, B[19]);
  not g15 (n_112, B[18]);
  not g16 (n_113, B[17]);
  not g17 (n_114, B[16]);
  not g18 (n_115, B[15]);
  not g19 (n_116, B[14]);
  not g20 (n_117, B[13]);
  not g21 (n_118, B[12]);
  not g22 (n_119, B[11]);
  not g23 (n_120, B[10]);
  not g24 (n_121, B[9]);
  not g25 (n_122, B[8]);
  not g26 (n_123, B[7]);
  not g27 (n_124, B[6]);
  not g28 (n_125, B[5]);
  not g29 (n_126, B[4]);
  not g30 (n_127, B[3]);
  not g31 (n_128, B[2]);
  not g32 (n_129, B[1]);
  not g34 (Z, n_131);
  nand g35 (n_136, n_133, B[0]);
  nor g36 (n_135, A[1], n_129);
  nand g37 (n_138, A[1], n_129);
  nor g38 (n_145, A[2], n_128);
  nand g39 (n_140, A[2], n_128);
  nor g40 (n_141, A[3], n_127);
  nand g41 (n_142, A[3], n_127);
  nor g42 (n_151, A[4], n_126);
  nand g43 (n_146, A[4], n_126);
  nor g44 (n_147, A[5], n_125);
  nand g45 (n_148, A[5], n_125);
  nor g46 (n_157, A[6], n_124);
  nand g47 (n_152, A[6], n_124);
  nor g48 (n_153, A[7], n_123);
  nand g49 (n_154, A[7], n_123);
  nor g50 (n_163, A[8], n_122);
  nand g51 (n_158, A[8], n_122);
  nor g52 (n_159, A[9], n_121);
  nand g53 (n_160, A[9], n_121);
  nor g54 (n_168, A[10], n_120);
  nand g55 (n_164, A[10], n_120);
  nor g56 (n_98, A[11], n_119);
  nand g57 (n_165, A[11], n_119);
  nor g58 (n_174, A[12], n_118);
  nand g59 (n_169, A[12], n_118);
  nor g60 (n_170, A[13], n_117);
  nand g61 (n_171, A[13], n_117);
  nor g62 (n_180, A[14], n_116);
  nand g63 (n_175, A[14], n_116);
  nor g64 (n_176, A[15], n_115);
  nand g65 (n_177, A[15], n_115);
  nor g66 (n_186, A[16], n_114);
  nand g67 (n_181, A[16], n_114);
  nor g68 (n_182, A[17], n_113);
  nand g69 (n_183, A[17], n_113);
  nor g70 (n_192, A[18], n_112);
  nand g71 (n_187, A[18], n_112);
  nor g72 (n_188, A[19], n_111);
  nand g73 (n_189, A[19], n_111);
  nor g74 (n_132, A[20], n_110);
  nand g75 (n_193, A[20], n_110);
  nor g76 (n_194, A[21], n_109);
  nand g77 (n_195, A[21], n_109);
  nor g78 (n_203, A[22], n_108);
  nand g79 (n_198, A[22], n_108);
  nor g80 (n_199, A[23], n_107);
  nand g81 (n_200, A[23], n_107);
  nor g82 (n_209, A[24], n_106);
  nand g83 (n_204, A[24], n_106);
  nor g84 (n_205, A[25], n_105);
  nand g85 (n_206, A[25], n_105);
  nor g86 (n_215, A[26], n_104);
  nand g87 (n_210, A[26], n_104);
  nor g88 (n_211, A[27], n_103);
  nand g89 (n_212, A[27], n_103);
  nor g90 (n_221, A[28], n_102);
  nand g91 (n_216, A[28], n_102);
  nor g92 (n_217, A[29], n_101);
  nand g93 (n_218, A[29], n_101);
  nor g94 (n_227, A[30], n_100);
  nand g95 (n_222, A[30], n_100);
  nor g96 (n_223, A[31], n_99);
  nand g97 (n_224, A[31], n_99);
  not g98 (n_137, n_135);
  nand g99 (n_139, n_136, n_137);
  nand g100 (n_228, n_138, n_139);
  nor g101 (n_143, n_140, n_141);
  not g102 (n_144, n_142);
  nor g103 (n_232, n_143, n_144);
  nor g104 (n_231, n_145, n_141);
  nor g105 (n_149, n_146, n_147);
  not g106 (n_150, n_148);
  nor g107 (n_234, n_149, n_150);
  nor g108 (n_237, n_151, n_147);
  nor g109 (n_155, n_152, n_153);
  not g110 (n_156, n_154);
  nor g111 (n_241, n_155, n_156);
  nor g112 (n_239, n_157, n_153);
  nor g113 (n_161, n_158, n_159);
  not g114 (n_162, n_160);
  nor g115 (n_244, n_161, n_162);
  nor g116 (n_247, n_163, n_159);
  nor g117 (n_166, n_164, n_98);
  not g118 (n_167, n_165);
  nor g119 (n_251, n_166, n_167);
  nor g120 (n_249, n_168, n_98);
  nor g121 (n_172, n_169, n_170);
  not g122 (n_173, n_171);
  nor g123 (n_254, n_172, n_173);
  nor g124 (n_257, n_174, n_170);
  nor g125 (n_178, n_175, n_176);
  not g126 (n_179, n_177);
  nor g127 (n_261, n_178, n_179);
  nor g128 (n_259, n_180, n_176);
  nor g129 (n_184, n_181, n_182);
  not g130 (n_185, n_183);
  nor g131 (n_264, n_184, n_185);
  nor g132 (n_267, n_186, n_182);
  nor g133 (n_190, n_187, n_188);
  not g134 (n_191, n_189);
  nor g135 (n_271, n_190, n_191);
  nor g136 (n_269, n_192, n_188);
  nor g137 (n_196, n_193, n_194);
  not g138 (n_197, n_195);
  nor g139 (n_274, n_196, n_197);
  nor g140 (n_277, n_132, n_194);
  nor g141 (n_201, n_198, n_199);
  not g142 (n_202, n_200);
  nor g143 (n_281, n_201, n_202);
  nor g144 (n_279, n_203, n_199);
  nor g145 (n_207, n_204, n_205);
  not g146 (n_208, n_206);
  nor g147 (n_284, n_207, n_208);
  nor g148 (n_287, n_209, n_205);
  nor g149 (n_213, n_210, n_211);
  not g150 (n_214, n_212);
  nor g151 (n_291, n_213, n_214);
  nor g152 (n_289, n_215, n_211);
  nor g153 (n_219, n_216, n_217);
  not g154 (n_220, n_218);
  nor g155 (n_294, n_219, n_220);
  nor g156 (n_297, n_221, n_217);
  nor g157 (n_225, n_222, n_223);
  not g158 (n_226, n_224);
  nor g159 (n_301, n_225, n_226);
  nor g160 (n_299, n_227, n_223);
  nand g164 (n_233, n_231, n_228);
  nand g165 (n_304, n_232, n_233);
  not g171 (n_240, n_239);
  nor g172 (n_242, n_234, n_240);
  not g173 (n_243, n_241);
  nor g174 (n_314, n_242, n_243);
  nand g175 (n_312, n_237, n_239);
  not g181 (n_250, n_249);
  nor g182 (n_252, n_244, n_250);
  not g183 (n_253, n_251);
  nor g184 (n_316, n_252, n_253);
  nand g185 (n_319, n_247, n_249);
  not g191 (n_260, n_259);
  nor g192 (n_262, n_254, n_260);
  not g193 (n_263, n_261);
  nor g194 (n_328, n_262, n_263);
  nand g195 (n_327, n_257, n_259);
  not g201 (n_270, n_269);
  nor g202 (n_272, n_264, n_270);
  not g203 (n_273, n_271);
  nor g204 (n_331, n_272, n_273);
  nand g205 (n_334, n_267, n_269);
  not g211 (n_280, n_279);
  nor g212 (n_282, n_274, n_280);
  not g213 (n_283, n_281);
  nor g214 (n_343, n_282, n_283);
  nand g215 (n_342, n_277, n_279);
  not g221 (n_290, n_289);
  nor g222 (n_292, n_284, n_290);
  not g223 (n_293, n_291);
  nor g224 (n_346, n_292, n_293);
  nand g225 (n_349, n_287, n_289);
  not g231 (n_300, n_299);
  nor g232 (n_302, n_294, n_300);
  not g233 (n_303, n_301);
  nor g234 (n_358, n_302, n_303);
  nand g235 (n_357, n_297, n_299);
  not g244 (n_313, n_312);
  nand g245 (n_315, n_304, n_313);
  nand g246 (n_361, n_314, n_315);
  nor g260 (n_329, n_327, n_316);
  not g261 (n_330, n_328);
  nor g262 (n_381, n_329, n_330);
  nor g263 (n_380, n_319, n_327);
  nor g277 (n_344, n_342, n_331);
  not g278 (n_345, n_343);
  nor g279 (n_383, n_344, n_345);
  nor g280 (n_386, n_334, n_342);
  nor g294 (n_359, n_357, n_346);
  not g295 (n_360, n_358);
  nor g296 (n_416, n_359, n_360);
  nor g297 (n_414, n_349, n_357);
  nand g315 (n_382, n_380, n_361);
  nand g316 (n_419, n_381, n_382);
  not g352 (n_415, n_414);
  nor g353 (n_417, n_383, n_415);
  not g354 (n_418, n_416);
  nor g355 (n_469, n_417, n_418);
  nand g356 (n_467, n_386, n_414);
  not g397 (n_468, n_467);
  nand g398 (n_470, n_419, n_468);
  nand g399 (n_131, n_469, n_470);
  not g480 (n_133, A[0]);
endmodule

module gt_unsigned(A, B, Z);
  input [31:0] A, B;
  output Z;
  wire [31:0] A, B;
  wire Z;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_131, n_132, n_133, n_135, n_136, n_137, n_138, n_139;
  wire n_140, n_141, n_142, n_143, n_144, n_145, n_146, n_147;
  wire n_148, n_149, n_150, n_151, n_152, n_153, n_154, n_155;
  wire n_156, n_157, n_158, n_159, n_160, n_161, n_162, n_163;
  wire n_164, n_165, n_166, n_167, n_168, n_169, n_170, n_171;
  wire n_172, n_173, n_174, n_175, n_176, n_177, n_178, n_179;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_190, n_191, n_192, n_193, n_194, n_195;
  wire n_196, n_197, n_198, n_199, n_200, n_201, n_202, n_203;
  wire n_204, n_205, n_206, n_207, n_208, n_209, n_210, n_211;
  wire n_212, n_213, n_214, n_215, n_216, n_217, n_218, n_219;
  wire n_220, n_221, n_222, n_223, n_224, n_225, n_226, n_227;
  wire n_228, n_231, n_232, n_233, n_234, n_237, n_239, n_240;
  wire n_241, n_242, n_243, n_244, n_247, n_249, n_250, n_251;
  wire n_252, n_253, n_254, n_257, n_259, n_260, n_261, n_262;
  wire n_263, n_264, n_267, n_269, n_270, n_271, n_272, n_273;
  wire n_274, n_277, n_279, n_280, n_281, n_282, n_283, n_284;
  wire n_287, n_289, n_290, n_291, n_292, n_293, n_294, n_297;
  wire n_299, n_300, n_301, n_302, n_303, n_304, n_312, n_313;
  wire n_314, n_315, n_316, n_319, n_327, n_328, n_329, n_330;
  wire n_331, n_334, n_342, n_343, n_344, n_345, n_346, n_349;
  wire n_357, n_358, n_359, n_360, n_361, n_380, n_381, n_382;
  wire n_383, n_386, n_414, n_415, n_416, n_417, n_418, n_419;
  wire n_467, n_468, n_469, n_470;
  not g2 (n_99, A[31]);
  not g3 (n_100, A[30]);
  not g4 (n_101, A[29]);
  not g5 (n_102, A[28]);
  not g6 (n_103, A[27]);
  not g7 (n_104, A[26]);
  not g8 (n_105, A[25]);
  not g9 (n_106, A[24]);
  not g10 (n_107, A[23]);
  not g11 (n_108, A[22]);
  not g12 (n_109, A[21]);
  not g13 (n_110, A[20]);
  not g14 (n_111, A[19]);
  not g15 (n_112, A[18]);
  not g16 (n_113, A[17]);
  not g17 (n_114, A[16]);
  not g18 (n_115, A[15]);
  not g19 (n_116, A[14]);
  not g20 (n_117, A[13]);
  not g21 (n_118, A[12]);
  not g22 (n_119, A[11]);
  not g23 (n_120, A[10]);
  not g24 (n_121, A[9]);
  not g25 (n_122, A[8]);
  not g26 (n_123, A[7]);
  not g27 (n_124, A[6]);
  not g28 (n_125, A[5]);
  not g29 (n_126, A[4]);
  not g30 (n_127, A[3]);
  not g31 (n_128, A[2]);
  not g32 (n_129, A[1]);
  not g34 (Z, n_131);
  nand g35 (n_136, n_133, A[0]);
  nor g36 (n_135, B[1], n_129);
  nand g37 (n_138, B[1], n_129);
  nor g38 (n_145, B[2], n_128);
  nand g39 (n_140, B[2], n_128);
  nor g40 (n_141, B[3], n_127);
  nand g41 (n_142, B[3], n_127);
  nor g42 (n_151, B[4], n_126);
  nand g43 (n_146, B[4], n_126);
  nor g44 (n_147, B[5], n_125);
  nand g45 (n_148, B[5], n_125);
  nor g46 (n_157, B[6], n_124);
  nand g47 (n_152, B[6], n_124);
  nor g48 (n_153, B[7], n_123);
  nand g49 (n_154, B[7], n_123);
  nor g50 (n_163, B[8], n_122);
  nand g51 (n_158, B[8], n_122);
  nor g52 (n_159, B[9], n_121);
  nand g53 (n_160, B[9], n_121);
  nor g54 (n_168, B[10], n_120);
  nand g55 (n_164, B[10], n_120);
  nor g56 (n_98, B[11], n_119);
  nand g57 (n_165, B[11], n_119);
  nor g58 (n_174, B[12], n_118);
  nand g59 (n_169, B[12], n_118);
  nor g60 (n_170, B[13], n_117);
  nand g61 (n_171, B[13], n_117);
  nor g62 (n_180, B[14], n_116);
  nand g63 (n_175, B[14], n_116);
  nor g64 (n_176, B[15], n_115);
  nand g65 (n_177, B[15], n_115);
  nor g66 (n_186, B[16], n_114);
  nand g67 (n_181, B[16], n_114);
  nor g68 (n_182, B[17], n_113);
  nand g69 (n_183, B[17], n_113);
  nor g70 (n_192, B[18], n_112);
  nand g71 (n_187, B[18], n_112);
  nor g72 (n_188, B[19], n_111);
  nand g73 (n_189, B[19], n_111);
  nor g74 (n_132, B[20], n_110);
  nand g75 (n_193, B[20], n_110);
  nor g76 (n_194, B[21], n_109);
  nand g77 (n_195, B[21], n_109);
  nor g78 (n_203, B[22], n_108);
  nand g79 (n_198, B[22], n_108);
  nor g80 (n_199, B[23], n_107);
  nand g81 (n_200, B[23], n_107);
  nor g82 (n_209, B[24], n_106);
  nand g83 (n_204, B[24], n_106);
  nor g84 (n_205, B[25], n_105);
  nand g85 (n_206, B[25], n_105);
  nor g86 (n_215, B[26], n_104);
  nand g87 (n_210, B[26], n_104);
  nor g88 (n_211, B[27], n_103);
  nand g89 (n_212, B[27], n_103);
  nor g90 (n_221, B[28], n_102);
  nand g91 (n_216, B[28], n_102);
  nor g92 (n_217, B[29], n_101);
  nand g93 (n_218, B[29], n_101);
  nor g94 (n_227, B[30], n_100);
  nand g95 (n_222, B[30], n_100);
  nor g96 (n_223, B[31], n_99);
  nand g97 (n_224, B[31], n_99);
  not g98 (n_137, n_135);
  nand g99 (n_139, n_136, n_137);
  nand g100 (n_228, n_138, n_139);
  nor g101 (n_143, n_140, n_141);
  not g102 (n_144, n_142);
  nor g103 (n_232, n_143, n_144);
  nor g104 (n_231, n_145, n_141);
  nor g105 (n_149, n_146, n_147);
  not g106 (n_150, n_148);
  nor g107 (n_234, n_149, n_150);
  nor g108 (n_237, n_151, n_147);
  nor g109 (n_155, n_152, n_153);
  not g110 (n_156, n_154);
  nor g111 (n_241, n_155, n_156);
  nor g112 (n_239, n_157, n_153);
  nor g113 (n_161, n_158, n_159);
  not g114 (n_162, n_160);
  nor g115 (n_244, n_161, n_162);
  nor g116 (n_247, n_163, n_159);
  nor g117 (n_166, n_164, n_98);
  not g118 (n_167, n_165);
  nor g119 (n_251, n_166, n_167);
  nor g120 (n_249, n_168, n_98);
  nor g121 (n_172, n_169, n_170);
  not g122 (n_173, n_171);
  nor g123 (n_254, n_172, n_173);
  nor g124 (n_257, n_174, n_170);
  nor g125 (n_178, n_175, n_176);
  not g126 (n_179, n_177);
  nor g127 (n_261, n_178, n_179);
  nor g128 (n_259, n_180, n_176);
  nor g129 (n_184, n_181, n_182);
  not g130 (n_185, n_183);
  nor g131 (n_264, n_184, n_185);
  nor g132 (n_267, n_186, n_182);
  nor g133 (n_190, n_187, n_188);
  not g134 (n_191, n_189);
  nor g135 (n_271, n_190, n_191);
  nor g136 (n_269, n_192, n_188);
  nor g137 (n_196, n_193, n_194);
  not g138 (n_197, n_195);
  nor g139 (n_274, n_196, n_197);
  nor g140 (n_277, n_132, n_194);
  nor g141 (n_201, n_198, n_199);
  not g142 (n_202, n_200);
  nor g143 (n_281, n_201, n_202);
  nor g144 (n_279, n_203, n_199);
  nor g145 (n_207, n_204, n_205);
  not g146 (n_208, n_206);
  nor g147 (n_284, n_207, n_208);
  nor g148 (n_287, n_209, n_205);
  nor g149 (n_213, n_210, n_211);
  not g150 (n_214, n_212);
  nor g151 (n_291, n_213, n_214);
  nor g152 (n_289, n_215, n_211);
  nor g153 (n_219, n_216, n_217);
  not g154 (n_220, n_218);
  nor g155 (n_294, n_219, n_220);
  nor g156 (n_297, n_221, n_217);
  nor g157 (n_225, n_222, n_223);
  not g158 (n_226, n_224);
  nor g159 (n_301, n_225, n_226);
  nor g160 (n_299, n_227, n_223);
  nand g164 (n_233, n_231, n_228);
  nand g165 (n_304, n_232, n_233);
  not g171 (n_240, n_239);
  nor g172 (n_242, n_234, n_240);
  not g173 (n_243, n_241);
  nor g174 (n_314, n_242, n_243);
  nand g175 (n_312, n_237, n_239);
  not g181 (n_250, n_249);
  nor g182 (n_252, n_244, n_250);
  not g183 (n_253, n_251);
  nor g184 (n_316, n_252, n_253);
  nand g185 (n_319, n_247, n_249);
  not g191 (n_260, n_259);
  nor g192 (n_262, n_254, n_260);
  not g193 (n_263, n_261);
  nor g194 (n_328, n_262, n_263);
  nand g195 (n_327, n_257, n_259);
  not g201 (n_270, n_269);
  nor g202 (n_272, n_264, n_270);
  not g203 (n_273, n_271);
  nor g204 (n_331, n_272, n_273);
  nand g205 (n_334, n_267, n_269);
  not g211 (n_280, n_279);
  nor g212 (n_282, n_274, n_280);
  not g213 (n_283, n_281);
  nor g214 (n_343, n_282, n_283);
  nand g215 (n_342, n_277, n_279);
  not g221 (n_290, n_289);
  nor g222 (n_292, n_284, n_290);
  not g223 (n_293, n_291);
  nor g224 (n_346, n_292, n_293);
  nand g225 (n_349, n_287, n_289);
  not g231 (n_300, n_299);
  nor g232 (n_302, n_294, n_300);
  not g233 (n_303, n_301);
  nor g234 (n_358, n_302, n_303);
  nand g235 (n_357, n_297, n_299);
  not g244 (n_313, n_312);
  nand g245 (n_315, n_304, n_313);
  nand g246 (n_361, n_314, n_315);
  nor g260 (n_329, n_327, n_316);
  not g261 (n_330, n_328);
  nor g262 (n_381, n_329, n_330);
  nor g263 (n_380, n_319, n_327);
  nor g277 (n_344, n_342, n_331);
  not g278 (n_345, n_343);
  nor g279 (n_383, n_344, n_345);
  nor g280 (n_386, n_334, n_342);
  nor g294 (n_359, n_357, n_346);
  not g295 (n_360, n_358);
  nor g296 (n_416, n_359, n_360);
  nor g297 (n_414, n_349, n_357);
  nand g315 (n_382, n_380, n_361);
  nand g316 (n_419, n_381, n_382);
  not g352 (n_415, n_414);
  nor g353 (n_417, n_383, n_415);
  not g354 (n_418, n_416);
  nor g355 (n_469, n_417, n_418);
  nand g356 (n_467, n_386, n_414);
  not g397 (n_468, n_467);
  nand g398 (n_470, n_419, n_468);
  nand g399 (n_131, n_469, n_470);
  not g480 (n_133, B[0]);
endmodule

module bmux(ctl, in_0, in_1, z);
  input ctl;
  input [31:0] in_0, in_1;
  output [31:0] z;
  wire ctl;
  wire [31:0] in_0, in_1;
  wire [31:0] z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0[31]), .data1 (in_1[31]), .z
       (z[31]));
  CDN_bmux2 g2(.sel0 (ctl), .data0 (in_0[30]), .data1 (in_1[30]), .z
       (z[30]));
  CDN_bmux2 g3(.sel0 (ctl), .data0 (in_0[29]), .data1 (in_1[29]), .z
       (z[29]));
  CDN_bmux2 g4(.sel0 (ctl), .data0 (in_0[28]), .data1 (in_1[28]), .z
       (z[28]));
  CDN_bmux2 g5(.sel0 (ctl), .data0 (in_0[27]), .data1 (in_1[27]), .z
       (z[27]));
  CDN_bmux2 g6(.sel0 (ctl), .data0 (in_0[26]), .data1 (in_1[26]), .z
       (z[26]));
  CDN_bmux2 g7(.sel0 (ctl), .data0 (in_0[25]), .data1 (in_1[25]), .z
       (z[25]));
  CDN_bmux2 g8(.sel0 (ctl), .data0 (in_0[24]), .data1 (in_1[24]), .z
       (z[24]));
  CDN_bmux2 g9(.sel0 (ctl), .data0 (in_0[23]), .data1 (in_1[23]), .z
       (z[23]));
  CDN_bmux2 g10(.sel0 (ctl), .data0 (in_0[22]), .data1 (in_1[22]), .z
       (z[22]));
  CDN_bmux2 g11(.sel0 (ctl), .data0 (in_0[21]), .data1 (in_1[21]), .z
       (z[21]));
  CDN_bmux2 g12(.sel0 (ctl), .data0 (in_0[20]), .data1 (in_1[20]), .z
       (z[20]));
  CDN_bmux2 g13(.sel0 (ctl), .data0 (in_0[19]), .data1 (in_1[19]), .z
       (z[19]));
  CDN_bmux2 g14(.sel0 (ctl), .data0 (in_0[18]), .data1 (in_1[18]), .z
       (z[18]));
  CDN_bmux2 g15(.sel0 (ctl), .data0 (in_0[17]), .data1 (in_1[17]), .z
       (z[17]));
  CDN_bmux2 g16(.sel0 (ctl), .data0 (in_0[16]), .data1 (in_1[16]), .z
       (z[16]));
  CDN_bmux2 g17(.sel0 (ctl), .data0 (in_0[15]), .data1 (in_1[15]), .z
       (z[15]));
  CDN_bmux2 g18(.sel0 (ctl), .data0 (in_0[14]), .data1 (in_1[14]), .z
       (z[14]));
  CDN_bmux2 g19(.sel0 (ctl), .data0 (in_0[13]), .data1 (in_1[13]), .z
       (z[13]));
  CDN_bmux2 g20(.sel0 (ctl), .data0 (in_0[12]), .data1 (in_1[12]), .z
       (z[12]));
  CDN_bmux2 g21(.sel0 (ctl), .data0 (in_0[11]), .data1 (in_1[11]), .z
       (z[11]));
  CDN_bmux2 g22(.sel0 (ctl), .data0 (in_0[10]), .data1 (in_1[10]), .z
       (z[10]));
  CDN_bmux2 g23(.sel0 (ctl), .data0 (in_0[9]), .data1 (in_1[9]), .z
       (z[9]));
  CDN_bmux2 g24(.sel0 (ctl), .data0 (in_0[8]), .data1 (in_1[8]), .z
       (z[8]));
  CDN_bmux2 g25(.sel0 (ctl), .data0 (in_0[7]), .data1 (in_1[7]), .z
       (z[7]));
  CDN_bmux2 g26(.sel0 (ctl), .data0 (in_0[6]), .data1 (in_1[6]), .z
       (z[6]));
  CDN_bmux2 g27(.sel0 (ctl), .data0 (in_0[5]), .data1 (in_1[5]), .z
       (z[5]));
  CDN_bmux2 g28(.sel0 (ctl), .data0 (in_0[4]), .data1 (in_1[4]), .z
       (z[4]));
  CDN_bmux2 g29(.sel0 (ctl), .data0 (in_0[3]), .data1 (in_1[3]), .z
       (z[3]));
  CDN_bmux2 g30(.sel0 (ctl), .data0 (in_0[2]), .data1 (in_1[2]), .z
       (z[2]));
  CDN_bmux2 g31(.sel0 (ctl), .data0 (in_0[1]), .data1 (in_1[1]), .z
       (z[1]));
  CDN_bmux2 g32(.sel0 (ctl), .data0 (in_0[0]), .data1 (in_1[0]), .z
       (z[0]));
endmodule

module bmux_7(ctl, in_0, in_1, z);
  input ctl, in_0, in_1;
  output z;
  wire ctl, in_0, in_1;
  wire z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0), .data1 (in_1), .z (z));
endmodule

module bmux_8(ctl, in_0, in_1, z);
  input ctl;
  input [1:0] in_0, in_1;
  output [1:0] z;
  wire ctl;
  wire [1:0] in_0, in_1;
  wire [1:0] z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0[1]), .data1 (in_1[1]), .z
       (z[1]));
  CDN_bmux2 g2(.sel0 (ctl), .data0 (in_0[0]), .data1 (in_1[0]), .z
       (z[0]));
endmodule

module case_box(in_0, out_0);
  input [7:0] in_0;
  output [4:0] out_0;
  wire [7:0] in_0;
  wire [4:0] out_0;
  wire n_9, n_10, n_12, n_19, n_21, n_29, n_30, n_39;
  wire n_48, n_51, n_78, n_79, n_80;
  not g33 (n_51, in_0[7]);
  not g34 (n_12, in_0[6]);
  not g35 (n_21, in_0[5]);
  not g36 (n_30, in_0[4]);
  not g37 (n_39, in_0[3]);
  not g38 (n_48, in_0[2]);
  nand g1 (n_10, n_51, n_12, n_21, n_30);
  nand g2 (n_9, n_39, n_48, n_78, n_79);
  nor g3 (out_0[4], n_9, n_10);
  nand g5 (n_19, n_39, n_48, n_78, in_0[0]);
  nor g6 (out_0[3], n_19, n_10);
  nand g8 (n_29, n_39, n_48, in_0[1], n_79);
  nor g9 (out_0[2], n_29, n_10);
  nand g11 (n_80, n_39, n_48, in_0[1], in_0[0]);
  nor g12 (out_0[1], n_80, n_10);
  nor g13 (out_0[0], out_0[4], out_0[3], out_0[2], out_0[1]);
  not g14 (n_78, in_0[1]);
  not g15 (n_79, in_0[0]);
endmodule

module case_box_9(in_0, out_0);
  input [7:0] in_0;
  output [4:0] out_0;
  wire [7:0] in_0;
  wire [4:0] out_0;
  wire n_9, n_10, n_12, n_19, n_21, n_29, n_30, n_39;
  wire n_48, n_51, n_78, n_79, n_80;
  not g33 (n_51, in_0[7]);
  not g34 (n_12, in_0[6]);
  not g35 (n_21, in_0[5]);
  not g36 (n_30, in_0[4]);
  not g37 (n_39, in_0[3]);
  not g38 (n_48, in_0[2]);
  nand g1 (n_10, n_51, n_12, n_21, n_30);
  nand g2 (n_9, n_39, n_48, n_78, n_79);
  nor g3 (out_0[4], n_9, n_10);
  nand g5 (n_19, n_39, n_48, n_78, in_0[0]);
  nor g6 (out_0[3], n_19, n_10);
  nand g8 (n_29, n_39, n_48, in_0[1], n_79);
  nor g9 (out_0[2], n_29, n_10);
  nand g11 (n_80, n_39, n_48, in_0[1], in_0[0]);
  nor g12 (out_0[1], n_80, n_10);
  nor g13 (out_0[0], out_0[4], out_0[3], out_0[2], out_0[1]);
  not g14 (n_78, in_0[1]);
  not g15 (n_79, in_0[0]);
endmodule

module proj_sorter(clk, rst_n, in_signature, in_index,
     \out_smallest_idx[0] , \out_smallest_idx[1] , \out_smallest_idx[2]
     , \out_smallest_idx[3] );
  input clk, rst_n;
  input [31:0] in_signature;
  input [7:0] in_index;
  output [7:0] \out_smallest_idx[0] , \out_smallest_idx[1] ,
       \out_smallest_idx[2] , \out_smallest_idx[3] ;
  wire clk, rst_n;
  wire [31:0] in_signature;
  wire [7:0] in_index;
  wire [7:0] \out_smallest_idx[0] , \out_smallest_idx[1] ,
       \out_smallest_idx[2] , \out_smallest_idx[3] ;
  wire [31:0] largest_signature;
  wire [31:0] \signatures[3] ;
  wire [31:0] \signatures[2] ;
  wire [31:0] \signatures[1] ;
  wire [31:0] \signatures[0] ;
  wire [7:0] smallest_position;
  wire UNCONNECTED, UNCONNECTED0, n_233, n_234, n_235, n_236, n_237,
       n_238;
  wire n_239, n_240, n_241, n_242, n_243, n_244, n_245, n_246;
  wire n_247, n_248, n_249, n_250, n_251, n_252, n_253, n_254;
  wire n_255, n_256, n_257, n_258, n_259, n_260, n_261, n_262;
  wire n_263, n_264, n_265, n_266, n_267, n_268, n_269, n_270;
  wire n_271, n_272, n_273, n_274, n_275, n_276, n_277, n_278;
  wire n_279, n_280, n_281, n_282, n_283, n_284, n_285, n_286;
  wire n_287, n_288, n_289, n_290, n_291, n_292, n_293, n_294;
  wire n_295, n_296, n_297, n_298, n_299, n_300, n_301, n_302;
  wire n_303, n_304, n_305, n_306, n_307, n_308, n_309, n_310;
  wire n_311, n_312, n_313, n_314, n_315, n_316, n_317, n_318;
  wire n_319, n_320, n_321, n_322, n_323, n_324, n_325, n_326;
  wire n_327, n_328, n_329, n_330, n_331, n_332, n_333, n_334;
  wire n_335, n_336, n_337, n_338, n_340, n_342, n_343, n_344;
  wire n_345, n_346, n_347, n_348, n_349, n_350, n_351, n_352;
  wire n_353, n_354, n_355, n_356;
  lt_unsigned lt_40_24(.A (in_signature), .B (largest_signature), .Z
       (n_301));
  gt_unsigned gt_47_29_I3(.A (\signatures[3] ), .B (largest_signature),
       .Z (n_234));
  gt_unsigned gt_47_29_I2(.A (\signatures[2] ), .B (largest_signature),
       .Z (n_235));
  gt_unsigned gt_47_29_I1(.A (\signatures[1] ), .B (largest_signature),
       .Z (n_236));
  bmux mux_largest_signature_47_29(.ctl (n_236), .in_0 (\signatures[0]
       ), .in_1 (\signatures[1] ), .z ({n_268, n_267, n_266, n_265,
       n_264, n_263, n_262, n_261, n_260, n_259, n_258, n_257, n_256,
       n_255, n_254, n_253, n_252, n_251, n_250, n_249, n_248, n_247,
       n_246, n_245, n_244, n_243, n_242, n_241, n_240, n_239, n_238,
       n_237}));
  bmux mux_largest_signature_47_16(.ctl (n_235), .in_0 ({n_268, n_267,
       n_266, n_265, n_264, n_263, n_262, n_261, n_260, n_259, n_258,
       n_257, n_256, n_255, n_254, n_253, n_252, n_251, n_250, n_249,
       n_248, n_247, n_246, n_245, n_244, n_243, n_242, n_241, n_240,
       n_239, n_238, n_237}), .in_1 (\signatures[2] ), .z ({n_300,
       n_299, n_298, n_297, n_296, n_295, n_294, n_293, n_292, n_291,
       n_290, n_289, n_288, n_287, n_286, n_285, n_284, n_283, n_282,
       n_281, n_280, n_279, n_278, n_277, n_276, n_275, n_274, n_273,
       n_272, n_271, n_270, n_269}));
  bmux mux_largest_signature_47_17(.ctl (n_234), .in_0 ({n_300, n_299,
       n_298, n_297, n_296, n_295, n_294, n_293, n_292, n_291, n_290,
       n_289, n_288, n_287, n_286, n_285, n_284, n_283, n_282, n_281,
       n_280, n_279, n_278, n_277, n_276, n_275, n_274, n_273, n_272,
       n_271, n_270, n_269}), .in_1 (\signatures[3] ), .z ({n_338,
       n_337, n_336, n_335, n_334, n_333, n_332, n_331, n_330, n_329,
       n_328, n_327, n_326, n_325, n_324, n_323, n_322, n_321, n_320,
       n_319, n_318, n_317, n_316, n_315, n_314, n_313, n_312, n_311,
       n_310, n_309, n_308, n_307}));
  bmux_7 mux_smallest_position_47_29(.ctl (n_236), .in_0 (1'b0), .in_1
       (1'b1), .z (n_302));
  bmux_8 mux_smallest_position_47_19(.ctl (n_235), .in_0 ({1'b0,
       n_302}), .in_1 (2'b10), .z ({n_304, n_303}));
  bmux_8 mux_smallest_position_47_20(.ctl (n_234), .in_0 ({n_304,
       n_303}), .in_1 (2'b11), .z ({n_306, n_305}));
  case_box ctl_smallest_position_41_9(.in_0 (smallest_position), .out_0
       ({n_340, n_343, n_345, n_347, UNCONNECTED}));
  case_box_9 ctl_smallest_position_42_9(.in_0 (smallest_position),
       .out_0 ({n_349, n_351, n_353, n_355, UNCONNECTED0}));
  not g1 (n_233, rst_n);
  and g21 (n_342, n_340, n_301);
  and g22 (n_344, n_343, n_301);
  and g23 (n_346, n_345, n_301);
  and g24 (n_348, n_347, n_301);
  and g25 (n_350, n_349, n_301);
  and g26 (n_352, n_351, n_301);
  and g27 (n_354, n_353, n_301);
  and g28 (n_356, n_355, n_301);
  CDN_flop \signatures_reg[0][0] (.clk (clk), .d (in_signature[0]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [0]));
  CDN_flop \signatures_reg[0][1] (.clk (clk), .d (in_signature[1]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [1]));
  CDN_flop \signatures_reg[0][2] (.clk (clk), .d (in_signature[2]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [2]));
  CDN_flop \signatures_reg[0][3] (.clk (clk), .d (in_signature[3]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [3]));
  CDN_flop \signatures_reg[0][4] (.clk (clk), .d (in_signature[4]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [4]));
  CDN_flop \signatures_reg[0][5] (.clk (clk), .d (in_signature[5]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [5]));
  CDN_flop \signatures_reg[0][6] (.clk (clk), .d (in_signature[6]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [6]));
  CDN_flop \signatures_reg[0][7] (.clk (clk), .d (in_signature[7]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [7]));
  CDN_flop \signatures_reg[0][8] (.clk (clk), .d (in_signature[8]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [8]));
  CDN_flop \signatures_reg[0][9] (.clk (clk), .d (in_signature[9]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [9]));
  CDN_flop \signatures_reg[0][10] (.clk (clk), .d (in_signature[10]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [10]));
  CDN_flop \signatures_reg[0][11] (.clk (clk), .d (in_signature[11]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [11]));
  CDN_flop \signatures_reg[0][12] (.clk (clk), .d (in_signature[12]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [12]));
  CDN_flop \signatures_reg[0][13] (.clk (clk), .d (in_signature[13]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [13]));
  CDN_flop \signatures_reg[0][14] (.clk (clk), .d (in_signature[14]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [14]));
  CDN_flop \signatures_reg[0][15] (.clk (clk), .d (in_signature[15]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [15]));
  CDN_flop \signatures_reg[0][16] (.clk (clk), .d (in_signature[16]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [16]));
  CDN_flop \signatures_reg[0][17] (.clk (clk), .d (in_signature[17]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [17]));
  CDN_flop \signatures_reg[0][18] (.clk (clk), .d (in_signature[18]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [18]));
  CDN_flop \signatures_reg[0][19] (.clk (clk), .d (in_signature[19]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [19]));
  CDN_flop \signatures_reg[0][20] (.clk (clk), .d (in_signature[20]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [20]));
  CDN_flop \signatures_reg[0][21] (.clk (clk), .d (in_signature[21]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [21]));
  CDN_flop \signatures_reg[0][22] (.clk (clk), .d (in_signature[22]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [22]));
  CDN_flop \signatures_reg[0][23] (.clk (clk), .d (in_signature[23]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [23]));
  CDN_flop \signatures_reg[0][24] (.clk (clk), .d (in_signature[24]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [24]));
  CDN_flop \signatures_reg[0][25] (.clk (clk), .d (in_signature[25]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [25]));
  CDN_flop \signatures_reg[0][26] (.clk (clk), .d (in_signature[26]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [26]));
  CDN_flop \signatures_reg[0][27] (.clk (clk), .d (in_signature[27]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [27]));
  CDN_flop \signatures_reg[0][28] (.clk (clk), .d (in_signature[28]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [28]));
  CDN_flop \signatures_reg[0][29] (.clk (clk), .d (in_signature[29]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [29]));
  CDN_flop \signatures_reg[0][30] (.clk (clk), .d (in_signature[30]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [30]));
  CDN_flop \signatures_reg[0][31] (.clk (clk), .d (in_signature[31]),
       .sena (n_342), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[0] [31]));
  CDN_flop \signatures_reg[1][0] (.clk (clk), .d (in_signature[0]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [0]));
  CDN_flop \signatures_reg[1][1] (.clk (clk), .d (in_signature[1]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [1]));
  CDN_flop \signatures_reg[1][2] (.clk (clk), .d (in_signature[2]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [2]));
  CDN_flop \signatures_reg[1][3] (.clk (clk), .d (in_signature[3]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [3]));
  CDN_flop \signatures_reg[1][4] (.clk (clk), .d (in_signature[4]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [4]));
  CDN_flop \signatures_reg[1][5] (.clk (clk), .d (in_signature[5]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [5]));
  CDN_flop \signatures_reg[1][6] (.clk (clk), .d (in_signature[6]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [6]));
  CDN_flop \signatures_reg[1][7] (.clk (clk), .d (in_signature[7]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [7]));
  CDN_flop \signatures_reg[1][8] (.clk (clk), .d (in_signature[8]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [8]));
  CDN_flop \signatures_reg[1][9] (.clk (clk), .d (in_signature[9]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [9]));
  CDN_flop \signatures_reg[1][10] (.clk (clk), .d (in_signature[10]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [10]));
  CDN_flop \signatures_reg[1][11] (.clk (clk), .d (in_signature[11]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [11]));
  CDN_flop \signatures_reg[1][12] (.clk (clk), .d (in_signature[12]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [12]));
  CDN_flop \signatures_reg[1][13] (.clk (clk), .d (in_signature[13]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [13]));
  CDN_flop \signatures_reg[1][14] (.clk (clk), .d (in_signature[14]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [14]));
  CDN_flop \signatures_reg[1][15] (.clk (clk), .d (in_signature[15]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [15]));
  CDN_flop \signatures_reg[1][16] (.clk (clk), .d (in_signature[16]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [16]));
  CDN_flop \signatures_reg[1][17] (.clk (clk), .d (in_signature[17]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [17]));
  CDN_flop \signatures_reg[1][18] (.clk (clk), .d (in_signature[18]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [18]));
  CDN_flop \signatures_reg[1][19] (.clk (clk), .d (in_signature[19]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [19]));
  CDN_flop \signatures_reg[1][20] (.clk (clk), .d (in_signature[20]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [20]));
  CDN_flop \signatures_reg[1][21] (.clk (clk), .d (in_signature[21]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [21]));
  CDN_flop \signatures_reg[1][22] (.clk (clk), .d (in_signature[22]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [22]));
  CDN_flop \signatures_reg[1][23] (.clk (clk), .d (in_signature[23]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [23]));
  CDN_flop \signatures_reg[1][24] (.clk (clk), .d (in_signature[24]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [24]));
  CDN_flop \signatures_reg[1][25] (.clk (clk), .d (in_signature[25]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [25]));
  CDN_flop \signatures_reg[1][26] (.clk (clk), .d (in_signature[26]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [26]));
  CDN_flop \signatures_reg[1][27] (.clk (clk), .d (in_signature[27]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [27]));
  CDN_flop \signatures_reg[1][28] (.clk (clk), .d (in_signature[28]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [28]));
  CDN_flop \signatures_reg[1][29] (.clk (clk), .d (in_signature[29]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [29]));
  CDN_flop \signatures_reg[1][30] (.clk (clk), .d (in_signature[30]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [30]));
  CDN_flop \signatures_reg[1][31] (.clk (clk), .d (in_signature[31]),
       .sena (n_344), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[1] [31]));
  CDN_flop \signatures_reg[2][0] (.clk (clk), .d (in_signature[0]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [0]));
  CDN_flop \signatures_reg[2][1] (.clk (clk), .d (in_signature[1]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [1]));
  CDN_flop \signatures_reg[2][2] (.clk (clk), .d (in_signature[2]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [2]));
  CDN_flop \signatures_reg[2][3] (.clk (clk), .d (in_signature[3]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [3]));
  CDN_flop \signatures_reg[2][4] (.clk (clk), .d (in_signature[4]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [4]));
  CDN_flop \signatures_reg[2][5] (.clk (clk), .d (in_signature[5]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [5]));
  CDN_flop \signatures_reg[2][6] (.clk (clk), .d (in_signature[6]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [6]));
  CDN_flop \signatures_reg[2][7] (.clk (clk), .d (in_signature[7]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [7]));
  CDN_flop \signatures_reg[2][8] (.clk (clk), .d (in_signature[8]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [8]));
  CDN_flop \signatures_reg[2][9] (.clk (clk), .d (in_signature[9]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [9]));
  CDN_flop \signatures_reg[2][10] (.clk (clk), .d (in_signature[10]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [10]));
  CDN_flop \signatures_reg[2][11] (.clk (clk), .d (in_signature[11]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [11]));
  CDN_flop \signatures_reg[2][12] (.clk (clk), .d (in_signature[12]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [12]));
  CDN_flop \signatures_reg[2][13] (.clk (clk), .d (in_signature[13]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [13]));
  CDN_flop \signatures_reg[2][14] (.clk (clk), .d (in_signature[14]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [14]));
  CDN_flop \signatures_reg[2][15] (.clk (clk), .d (in_signature[15]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [15]));
  CDN_flop \signatures_reg[2][16] (.clk (clk), .d (in_signature[16]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [16]));
  CDN_flop \signatures_reg[2][17] (.clk (clk), .d (in_signature[17]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [17]));
  CDN_flop \signatures_reg[2][18] (.clk (clk), .d (in_signature[18]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [18]));
  CDN_flop \signatures_reg[2][19] (.clk (clk), .d (in_signature[19]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [19]));
  CDN_flop \signatures_reg[2][20] (.clk (clk), .d (in_signature[20]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [20]));
  CDN_flop \signatures_reg[2][21] (.clk (clk), .d (in_signature[21]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [21]));
  CDN_flop \signatures_reg[2][22] (.clk (clk), .d (in_signature[22]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [22]));
  CDN_flop \signatures_reg[2][23] (.clk (clk), .d (in_signature[23]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [23]));
  CDN_flop \signatures_reg[2][24] (.clk (clk), .d (in_signature[24]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [24]));
  CDN_flop \signatures_reg[2][25] (.clk (clk), .d (in_signature[25]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [25]));
  CDN_flop \signatures_reg[2][26] (.clk (clk), .d (in_signature[26]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [26]));
  CDN_flop \signatures_reg[2][27] (.clk (clk), .d (in_signature[27]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [27]));
  CDN_flop \signatures_reg[2][28] (.clk (clk), .d (in_signature[28]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [28]));
  CDN_flop \signatures_reg[2][29] (.clk (clk), .d (in_signature[29]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [29]));
  CDN_flop \signatures_reg[2][30] (.clk (clk), .d (in_signature[30]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [30]));
  CDN_flop \signatures_reg[2][31] (.clk (clk), .d (in_signature[31]),
       .sena (n_346), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[2] [31]));
  CDN_flop \signatures_reg[3][0] (.clk (clk), .d (in_signature[0]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [0]));
  CDN_flop \signatures_reg[3][1] (.clk (clk), .d (in_signature[1]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [1]));
  CDN_flop \signatures_reg[3][2] (.clk (clk), .d (in_signature[2]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [2]));
  CDN_flop \signatures_reg[3][3] (.clk (clk), .d (in_signature[3]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [3]));
  CDN_flop \signatures_reg[3][4] (.clk (clk), .d (in_signature[4]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [4]));
  CDN_flop \signatures_reg[3][5] (.clk (clk), .d (in_signature[5]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [5]));
  CDN_flop \signatures_reg[3][6] (.clk (clk), .d (in_signature[6]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [6]));
  CDN_flop \signatures_reg[3][7] (.clk (clk), .d (in_signature[7]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [7]));
  CDN_flop \signatures_reg[3][8] (.clk (clk), .d (in_signature[8]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [8]));
  CDN_flop \signatures_reg[3][9] (.clk (clk), .d (in_signature[9]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [9]));
  CDN_flop \signatures_reg[3][10] (.clk (clk), .d (in_signature[10]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [10]));
  CDN_flop \signatures_reg[3][11] (.clk (clk), .d (in_signature[11]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [11]));
  CDN_flop \signatures_reg[3][12] (.clk (clk), .d (in_signature[12]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [12]));
  CDN_flop \signatures_reg[3][13] (.clk (clk), .d (in_signature[13]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [13]));
  CDN_flop \signatures_reg[3][14] (.clk (clk), .d (in_signature[14]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [14]));
  CDN_flop \signatures_reg[3][15] (.clk (clk), .d (in_signature[15]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [15]));
  CDN_flop \signatures_reg[3][16] (.clk (clk), .d (in_signature[16]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [16]));
  CDN_flop \signatures_reg[3][17] (.clk (clk), .d (in_signature[17]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [17]));
  CDN_flop \signatures_reg[3][18] (.clk (clk), .d (in_signature[18]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [18]));
  CDN_flop \signatures_reg[3][19] (.clk (clk), .d (in_signature[19]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [19]));
  CDN_flop \signatures_reg[3][20] (.clk (clk), .d (in_signature[20]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [20]));
  CDN_flop \signatures_reg[3][21] (.clk (clk), .d (in_signature[21]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [21]));
  CDN_flop \signatures_reg[3][22] (.clk (clk), .d (in_signature[22]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [22]));
  CDN_flop \signatures_reg[3][23] (.clk (clk), .d (in_signature[23]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [23]));
  CDN_flop \signatures_reg[3][24] (.clk (clk), .d (in_signature[24]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [24]));
  CDN_flop \signatures_reg[3][25] (.clk (clk), .d (in_signature[25]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [25]));
  CDN_flop \signatures_reg[3][26] (.clk (clk), .d (in_signature[26]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [26]));
  CDN_flop \signatures_reg[3][27] (.clk (clk), .d (in_signature[27]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [27]));
  CDN_flop \signatures_reg[3][28] (.clk (clk), .d (in_signature[28]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [28]));
  CDN_flop \signatures_reg[3][29] (.clk (clk), .d (in_signature[29]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [29]));
  CDN_flop \signatures_reg[3][30] (.clk (clk), .d (in_signature[30]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [30]));
  CDN_flop \signatures_reg[3][31] (.clk (clk), .d (in_signature[31]),
       .sena (n_348), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd
       (1'b0), .q (\signatures[3] [31]));
  CDN_flop \indices_reg[0][0] (.clk (clk), .d (in_index[0]), .sena
       (n_350), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[0] [0]));
  CDN_flop \indices_reg[0][1] (.clk (clk), .d (in_index[1]), .sena
       (n_350), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[0] [1]));
  CDN_flop \indices_reg[0][2] (.clk (clk), .d (in_index[2]), .sena
       (n_350), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[0] [2]));
  CDN_flop \indices_reg[0][3] (.clk (clk), .d (in_index[3]), .sena
       (n_350), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[0] [3]));
  CDN_flop \indices_reg[0][4] (.clk (clk), .d (in_index[4]), .sena
       (n_350), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[0] [4]));
  CDN_flop \indices_reg[0][5] (.clk (clk), .d (in_index[5]), .sena
       (n_350), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[0] [5]));
  CDN_flop \indices_reg[0][6] (.clk (clk), .d (in_index[6]), .sena
       (n_350), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[0] [6]));
  CDN_flop \indices_reg[0][7] (.clk (clk), .d (in_index[7]), .sena
       (n_350), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[0] [7]));
  CDN_flop \indices_reg[1][0] (.clk (clk), .d (in_index[0]), .sena
       (n_352), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[1] [0]));
  CDN_flop \indices_reg[1][1] (.clk (clk), .d (in_index[1]), .sena
       (n_352), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[1] [1]));
  CDN_flop \indices_reg[1][2] (.clk (clk), .d (in_index[2]), .sena
       (n_352), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[1] [2]));
  CDN_flop \indices_reg[1][3] (.clk (clk), .d (in_index[3]), .sena
       (n_352), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[1] [3]));
  CDN_flop \indices_reg[1][4] (.clk (clk), .d (in_index[4]), .sena
       (n_352), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[1] [4]));
  CDN_flop \indices_reg[1][5] (.clk (clk), .d (in_index[5]), .sena
       (n_352), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[1] [5]));
  CDN_flop \indices_reg[1][6] (.clk (clk), .d (in_index[6]), .sena
       (n_352), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[1] [6]));
  CDN_flop \indices_reg[1][7] (.clk (clk), .d (in_index[7]), .sena
       (n_352), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[1] [7]));
  CDN_flop \indices_reg[2][0] (.clk (clk), .d (in_index[0]), .sena
       (n_354), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[2] [0]));
  CDN_flop \indices_reg[2][1] (.clk (clk), .d (in_index[1]), .sena
       (n_354), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[2] [1]));
  CDN_flop \indices_reg[2][2] (.clk (clk), .d (in_index[2]), .sena
       (n_354), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[2] [2]));
  CDN_flop \indices_reg[2][3] (.clk (clk), .d (in_index[3]), .sena
       (n_354), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[2] [3]));
  CDN_flop \indices_reg[2][4] (.clk (clk), .d (in_index[4]), .sena
       (n_354), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[2] [4]));
  CDN_flop \indices_reg[2][5] (.clk (clk), .d (in_index[5]), .sena
       (n_354), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[2] [5]));
  CDN_flop \indices_reg[2][6] (.clk (clk), .d (in_index[6]), .sena
       (n_354), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[2] [6]));
  CDN_flop \indices_reg[2][7] (.clk (clk), .d (in_index[7]), .sena
       (n_354), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[2] [7]));
  CDN_flop \indices_reg[3][0] (.clk (clk), .d (in_index[0]), .sena
       (n_356), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[3] [0]));
  CDN_flop \indices_reg[3][1] (.clk (clk), .d (in_index[1]), .sena
       (n_356), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[3] [1]));
  CDN_flop \indices_reg[3][2] (.clk (clk), .d (in_index[2]), .sena
       (n_356), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[3] [2]));
  CDN_flop \indices_reg[3][3] (.clk (clk), .d (in_index[3]), .sena
       (n_356), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[3] [3]));
  CDN_flop \indices_reg[3][4] (.clk (clk), .d (in_index[4]), .sena
       (n_356), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[3] [4]));
  CDN_flop \indices_reg[3][5] (.clk (clk), .d (in_index[5]), .sena
       (n_356), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[3] [5]));
  CDN_flop \indices_reg[3][6] (.clk (clk), .d (in_index[6]), .sena
       (n_356), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[3] [6]));
  CDN_flop \indices_reg[3][7] (.clk (clk), .d (in_index[7]), .sena
       (n_356), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\out_smallest_idx[3] [7]));
  CDN_flop \largest_signature_reg[0] (.clk (clk), .d (n_307), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[0]));
  CDN_flop \largest_signature_reg[1] (.clk (clk), .d (n_308), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[1]));
  CDN_flop \largest_signature_reg[2] (.clk (clk), .d (n_309), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[2]));
  CDN_flop \largest_signature_reg[3] (.clk (clk), .d (n_310), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[3]));
  CDN_flop \largest_signature_reg[4] (.clk (clk), .d (n_311), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[4]));
  CDN_flop \largest_signature_reg[5] (.clk (clk), .d (n_312), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[5]));
  CDN_flop \largest_signature_reg[6] (.clk (clk), .d (n_313), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[6]));
  CDN_flop \largest_signature_reg[7] (.clk (clk), .d (n_314), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[7]));
  CDN_flop \largest_signature_reg[8] (.clk (clk), .d (n_315), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[8]));
  CDN_flop \largest_signature_reg[9] (.clk (clk), .d (n_316), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[9]));
  CDN_flop \largest_signature_reg[10] (.clk (clk), .d (n_317), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[10]));
  CDN_flop \largest_signature_reg[11] (.clk (clk), .d (n_318), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[11]));
  CDN_flop \largest_signature_reg[12] (.clk (clk), .d (n_319), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[12]));
  CDN_flop \largest_signature_reg[13] (.clk (clk), .d (n_320), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[13]));
  CDN_flop \largest_signature_reg[14] (.clk (clk), .d (n_321), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[14]));
  CDN_flop \largest_signature_reg[15] (.clk (clk), .d (n_322), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[15]));
  CDN_flop \largest_signature_reg[16] (.clk (clk), .d (n_323), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[16]));
  CDN_flop \largest_signature_reg[17] (.clk (clk), .d (n_324), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[17]));
  CDN_flop \largest_signature_reg[18] (.clk (clk), .d (n_325), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[18]));
  CDN_flop \largest_signature_reg[19] (.clk (clk), .d (n_326), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[19]));
  CDN_flop \largest_signature_reg[20] (.clk (clk), .d (n_327), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[20]));
  CDN_flop \largest_signature_reg[21] (.clk (clk), .d (n_328), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[21]));
  CDN_flop \largest_signature_reg[22] (.clk (clk), .d (n_329), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[22]));
  CDN_flop \largest_signature_reg[23] (.clk (clk), .d (n_330), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[23]));
  CDN_flop \largest_signature_reg[24] (.clk (clk), .d (n_331), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[24]));
  CDN_flop \largest_signature_reg[25] (.clk (clk), .d (n_332), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[25]));
  CDN_flop \largest_signature_reg[26] (.clk (clk), .d (n_333), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[26]));
  CDN_flop \largest_signature_reg[27] (.clk (clk), .d (n_334), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[27]));
  CDN_flop \largest_signature_reg[28] (.clk (clk), .d (n_335), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[28]));
  CDN_flop \largest_signature_reg[29] (.clk (clk), .d (n_336), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[29]));
  CDN_flop \largest_signature_reg[30] (.clk (clk), .d (n_337), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[30]));
  CDN_flop \largest_signature_reg[31] (.clk (clk), .d (n_338), .sena
       (n_301), .aclr (1'b0), .apre (n_233), .srl (1'b0), .srd (1'b0),
       .q (largest_signature[31]));
  CDN_flop \smallest_position_reg[0] (.clk (clk), .d (n_305), .sena
       (n_301), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (smallest_position[0]));
  CDN_flop \smallest_position_reg[1] (.clk (clk), .d (n_306), .sena
       (n_301), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (smallest_position[1]));
  CDN_flop \smallest_position_reg[2] (.clk (clk), .d (1'b0), .sena
       (n_301), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (smallest_position[2]));
  CDN_flop \smallest_position_reg[3] (.clk (clk), .d (1'b0), .sena
       (n_301), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (smallest_position[3]));
  CDN_flop \smallest_position_reg[4] (.clk (clk), .d (1'b0), .sena
       (n_301), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (smallest_position[4]));
  CDN_flop \smallest_position_reg[5] (.clk (clk), .d (1'b0), .sena
       (n_301), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (smallest_position[5]));
  CDN_flop \smallest_position_reg[6] (.clk (clk), .d (1'b0), .sena
       (n_301), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (smallest_position[6]));
  CDN_flop \smallest_position_reg[7] (.clk (clk), .d (1'b0), .sena
       (n_301), .aclr (n_233), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (smallest_position[7]));
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_flop(clk, d, sena, aclr, apre, srl, srd, q);
  input clk, d, sena, aclr, apre, srl, srd;
  output q;
  wire clk, d, sena, aclr, apre, srl, srd;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(posedge clk or posedge apre or posedge aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else if (srl) 
            qi <= srd;
          else begin
            if (sena) 
              qi <= d;
          end
  initial 
    qi <= 1'b0;
endmodule
`endif
`ifdef RC_CDN_GENERIC_GATE
`else
`ifdef ONE_HOT_MUX
module CDN_bmux2(sel0, data0, data1, z);
  input sel0, data0, data1;
  output z;
  wire sel0, data0, data1;
  reg  z;
  always 
    @(sel0 or data0 or data1) 
      case ({sel0})
       1'b0: z = data0;
       1'b1: z = data1;
      endcase
endmodule
`else
module CDN_bmux2(sel0, data0, data1, z);
  input sel0, data0, data1;
  output z;
  wire sel0, data0, data1;
  wire z;
  wire inv_sel0, w_0, w_1;
  not i_0 (inv_sel0, sel0);
  and a_0 (w_0, inv_sel0, data0);
  and a_1 (w_1, sel0, data1);
  or org (z, w_0, w_1);
endmodule
`endif // ONE_HOT_MUX
`endif
