
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point in_signature[31] in_signature[31] -type PI PI
add mapped point in_signature[30] in_signature[30] -type PI PI
add mapped point in_signature[29] in_signature[29] -type PI PI
add mapped point in_signature[28] in_signature[28] -type PI PI
add mapped point in_signature[27] in_signature[27] -type PI PI
add mapped point in_signature[26] in_signature[26] -type PI PI
add mapped point in_signature[25] in_signature[25] -type PI PI
add mapped point in_signature[24] in_signature[24] -type PI PI
add mapped point in_signature[23] in_signature[23] -type PI PI
add mapped point in_signature[22] in_signature[22] -type PI PI
add mapped point in_signature[21] in_signature[21] -type PI PI
add mapped point in_signature[20] in_signature[20] -type PI PI
add mapped point in_signature[19] in_signature[19] -type PI PI
add mapped point in_signature[18] in_signature[18] -type PI PI
add mapped point in_signature[17] in_signature[17] -type PI PI
add mapped point in_signature[16] in_signature[16] -type PI PI
add mapped point in_signature[15] in_signature[15] -type PI PI
add mapped point in_signature[14] in_signature[14] -type PI PI
add mapped point in_signature[13] in_signature[13] -type PI PI
add mapped point in_signature[12] in_signature[12] -type PI PI
add mapped point in_signature[11] in_signature[11] -type PI PI
add mapped point in_signature[10] in_signature[10] -type PI PI
add mapped point in_signature[9] in_signature[9] -type PI PI
add mapped point in_signature[8] in_signature[8] -type PI PI
add mapped point in_signature[7] in_signature[7] -type PI PI
add mapped point in_signature[6] in_signature[6] -type PI PI
add mapped point in_signature[5] in_signature[5] -type PI PI
add mapped point in_signature[4] in_signature[4] -type PI PI
add mapped point in_signature[3] in_signature[3] -type PI PI
add mapped point in_signature[2] in_signature[2] -type PI PI
add mapped point in_signature[1] in_signature[1] -type PI PI
add mapped point in_signature[0] in_signature[0] -type PI PI
add mapped point in_index[7] in_index[7] -type PI PI
add mapped point in_index[6] in_index[6] -type PI PI
add mapped point in_index[5] in_index[5] -type PI PI
add mapped point in_index[4] in_index[4] -type PI PI
add mapped point in_index[3] in_index[3] -type PI PI
add mapped point in_index[2] in_index[2] -type PI PI
add mapped point in_index[1] in_index[1] -type PI PI
add mapped point in_index[0] in_index[0] -type PI PI

//output ports
add mapped point out_smallest_idx[0][7] out_smallest_idx[0][7] -type PO PO
add mapped point out_smallest_idx[0][6] out_smallest_idx[0][6] -type PO PO
add mapped point out_smallest_idx[0][5] out_smallest_idx[0][5] -type PO PO
add mapped point out_smallest_idx[0][4] out_smallest_idx[0][4] -type PO PO
add mapped point out_smallest_idx[0][3] out_smallest_idx[0][3] -type PO PO
add mapped point out_smallest_idx[0][2] out_smallest_idx[0][2] -type PO PO
add mapped point out_smallest_idx[0][1] out_smallest_idx[0][1] -type PO PO
add mapped point out_smallest_idx[0][0] out_smallest_idx[0][0] -type PO PO
add mapped point out_smallest_idx[1][7] out_smallest_idx[1][7] -type PO PO
add mapped point out_smallest_idx[1][6] out_smallest_idx[1][6] -type PO PO
add mapped point out_smallest_idx[1][5] out_smallest_idx[1][5] -type PO PO
add mapped point out_smallest_idx[1][4] out_smallest_idx[1][4] -type PO PO
add mapped point out_smallest_idx[1][3] out_smallest_idx[1][3] -type PO PO
add mapped point out_smallest_idx[1][2] out_smallest_idx[1][2] -type PO PO
add mapped point out_smallest_idx[1][1] out_smallest_idx[1][1] -type PO PO
add mapped point out_smallest_idx[1][0] out_smallest_idx[1][0] -type PO PO
add mapped point out_smallest_idx[2][7] out_smallest_idx[2][7] -type PO PO
add mapped point out_smallest_idx[2][6] out_smallest_idx[2][6] -type PO PO
add mapped point out_smallest_idx[2][5] out_smallest_idx[2][5] -type PO PO
add mapped point out_smallest_idx[2][4] out_smallest_idx[2][4] -type PO PO
add mapped point out_smallest_idx[2][3] out_smallest_idx[2][3] -type PO PO
add mapped point out_smallest_idx[2][2] out_smallest_idx[2][2] -type PO PO
add mapped point out_smallest_idx[2][1] out_smallest_idx[2][1] -type PO PO
add mapped point out_smallest_idx[2][0] out_smallest_idx[2][0] -type PO PO
add mapped point out_smallest_idx[3][7] out_smallest_idx[3][7] -type PO PO
add mapped point out_smallest_idx[3][6] out_smallest_idx[3][6] -type PO PO
add mapped point out_smallest_idx[3][5] out_smallest_idx[3][5] -type PO PO
add mapped point out_smallest_idx[3][4] out_smallest_idx[3][4] -type PO PO
add mapped point out_smallest_idx[3][3] out_smallest_idx[3][3] -type PO PO
add mapped point out_smallest_idx[3][2] out_smallest_idx[3][2] -type PO PO
add mapped point out_smallest_idx[3][1] out_smallest_idx[3][1] -type PO PO
add mapped point out_smallest_idx[3][0] out_smallest_idx[3][0] -type PO PO

//inout ports




//Sequential Pins
add mapped point indices[0][0]/q indices_reg[0][0]/Q -type DFF DFF
add mapped point indices[0][1]/q indices_reg[0][1]/Q -type DFF DFF
add mapped point indices[0][2]/q indices_reg[0][2]/Q -type DFF DFF
add mapped point indices[0][3]/q indices_reg[0][3]/Q -type DFF DFF
add mapped point indices[0][4]/q indices_reg[0][4]/Q -type DFF DFF
add mapped point indices[0][5]/q indices_reg[0][5]/Q -type DFF DFF
add mapped point indices[0][6]/q indices_reg[0][6]/Q -type DFF DFF
add mapped point indices[0][7]/q indices_reg[0][7]/Q -type DFF DFF
add mapped point indices[1][0]/q indices_reg[1][0]/Q -type DFF DFF
add mapped point indices[1][1]/q indices_reg[1][1]/Q -type DFF DFF
add mapped point indices[1][2]/q indices_reg[1][2]/Q -type DFF DFF
add mapped point indices[1][3]/q indices_reg[1][3]/Q -type DFF DFF
add mapped point indices[1][4]/q indices_reg[1][4]/Q -type DFF DFF
add mapped point indices[1][5]/q indices_reg[1][5]/Q -type DFF DFF
add mapped point indices[1][6]/q indices_reg[1][6]/Q -type DFF DFF
add mapped point indices[1][7]/q indices_reg[1][7]/Q -type DFF DFF
add mapped point indices[2][0]/q indices_reg[2][0]/Q -type DFF DFF
add mapped point indices[2][1]/q indices_reg[2][1]/Q -type DFF DFF
add mapped point indices[2][2]/q indices_reg[2][2]/Q -type DFF DFF
add mapped point indices[2][3]/q indices_reg[2][3]/Q -type DFF DFF
add mapped point indices[2][4]/q indices_reg[2][4]/Q -type DFF DFF
add mapped point indices[2][5]/q indices_reg[2][5]/Q -type DFF DFF
add mapped point indices[2][6]/q indices_reg[2][6]/Q -type DFF DFF
add mapped point indices[2][7]/q indices_reg[2][7]/Q -type DFF DFF
add mapped point indices[3][0]/q indices_reg[3][0]/Q -type DFF DFF
add mapped point indices[3][1]/q indices_reg[3][1]/Q -type DFF DFF
add mapped point indices[3][2]/q indices_reg[3][2]/Q -type DFF DFF
add mapped point indices[3][3]/q indices_reg[3][3]/Q -type DFF DFF
add mapped point indices[3][4]/q indices_reg[3][4]/Q -type DFF DFF
add mapped point indices[3][5]/q indices_reg[3][5]/Q -type DFF DFF
add mapped point indices[3][6]/q indices_reg[3][6]/Q -type DFF DFF
add mapped point indices[3][7]/q indices_reg[3][7]/Q -type DFF DFF
add mapped point largest_signature[0]/q largest_signature_reg[0]/Q -type DFF DFF
add mapped point largest_signature[1]/q largest_signature_reg[1]/Q -type DFF DFF
add mapped point largest_signature[2]/q largest_signature_reg[2]/Q -type DFF DFF
add mapped point largest_signature[3]/q largest_signature_reg[3]/Q -type DFF DFF
add mapped point largest_signature[4]/q largest_signature_reg[4]/Q -type DFF DFF
add mapped point largest_signature[5]/q largest_signature_reg[5]/Q -type DFF DFF
add mapped point largest_signature[6]/q largest_signature_reg[6]/Q -type DFF DFF
add mapped point largest_signature[7]/q largest_signature_reg[7]/Q -type DFF DFF
add mapped point largest_signature[8]/q largest_signature_reg[8]/Q -type DFF DFF
add mapped point largest_signature[9]/q largest_signature_reg[9]/Q -type DFF DFF
add mapped point largest_signature[10]/q largest_signature_reg[10]/Q -type DFF DFF
add mapped point largest_signature[11]/q largest_signature_reg[11]/Q -type DFF DFF
add mapped point largest_signature[12]/q largest_signature_reg[12]/Q -type DFF DFF
add mapped point largest_signature[13]/q largest_signature_reg[13]/Q -type DFF DFF
add mapped point largest_signature[14]/q largest_signature_reg[14]/Q -type DFF DFF
add mapped point largest_signature[15]/q largest_signature_reg[15]/Q -type DFF DFF
add mapped point largest_signature[16]/q largest_signature_reg[16]/Q -type DFF DFF
add mapped point largest_signature[17]/q largest_signature_reg[17]/Q -type DFF DFF
add mapped point largest_signature[18]/q largest_signature_reg[18]/Q -type DFF DFF
add mapped point largest_signature[19]/q largest_signature_reg[19]/Q -type DFF DFF
add mapped point largest_signature[20]/q largest_signature_reg[20]/Q -type DFF DFF
add mapped point largest_signature[21]/q largest_signature_reg[21]/Q -type DFF DFF
add mapped point largest_signature[22]/q largest_signature_reg[22]/Q -type DFF DFF
add mapped point largest_signature[23]/q largest_signature_reg[23]/Q -type DFF DFF
add mapped point largest_signature[24]/q largest_signature_reg[24]/Q -type DFF DFF
add mapped point largest_signature[25]/q largest_signature_reg[25]/Q -type DFF DFF
add mapped point largest_signature[26]/q largest_signature_reg[26]/Q -type DFF DFF
add mapped point largest_signature[27]/q largest_signature_reg[27]/Q -type DFF DFF
add mapped point largest_signature[28]/q largest_signature_reg[28]/Q -type DFF DFF
add mapped point largest_signature[29]/q largest_signature_reg[29]/Q -type DFF DFF
add mapped point largest_signature[30]/q largest_signature_reg[30]/Q -type DFF DFF
add mapped point largest_signature[31]/q largest_signature_reg[31]/Q -type DFF DFF
add mapped point signatures[0][0]/q signatures_reg[0][0]/QN -type DFF DFF
add mapped point signatures[0][1]/q signatures_reg[0][1]/QN -type DFF DFF
add mapped point signatures[0][2]/q signatures_reg[0][2]/QN -type DFF DFF
add mapped point signatures[0][3]/q signatures_reg[0][3]/QN -type DFF DFF
add mapped point signatures[0][4]/q signatures_reg[0][4]/QN -type DFF DFF
add mapped point signatures[0][5]/q signatures_reg[0][5]/QN -type DFF DFF
add mapped point signatures[0][6]/q signatures_reg[0][6]/QN -type DFF DFF
add mapped point signatures[0][7]/q signatures_reg[0][7]/QN -type DFF DFF
add mapped point signatures[0][8]/q signatures_reg[0][8]/QN -type DFF DFF
add mapped point signatures[0][9]/q signatures_reg[0][9]/QN -type DFF DFF
add mapped point signatures[0][10]/q signatures_reg[0][10]/QN -type DFF DFF
add mapped point signatures[0][11]/q signatures_reg[0][11]/QN -type DFF DFF
add mapped point signatures[0][12]/q signatures_reg[0][12]/QN -type DFF DFF
add mapped point signatures[0][13]/q signatures_reg[0][13]/QN -type DFF DFF
add mapped point signatures[0][14]/q signatures_reg[0][14]/QN -type DFF DFF
add mapped point signatures[0][15]/q signatures_reg[0][15]/QN -type DFF DFF
add mapped point signatures[0][16]/q signatures_reg[0][16]/QN -type DFF DFF
add mapped point signatures[0][17]/q signatures_reg[0][17]/QN -type DFF DFF
add mapped point signatures[0][18]/q signatures_reg[0][18]/QN -type DFF DFF
add mapped point signatures[0][19]/q signatures_reg[0][19]/QN -type DFF DFF
add mapped point signatures[0][20]/q signatures_reg[0][20]/QN -type DFF DFF
add mapped point signatures[0][21]/q signatures_reg[0][21]/QN -type DFF DFF
add mapped point signatures[0][22]/q signatures_reg[0][22]/QN -type DFF DFF
add mapped point signatures[0][23]/q signatures_reg[0][23]/QN -type DFF DFF
add mapped point signatures[0][24]/q signatures_reg[0][24]/QN -type DFF DFF
add mapped point signatures[0][25]/q signatures_reg[0][25]/QN -type DFF DFF
add mapped point signatures[0][26]/q signatures_reg[0][26]/QN -type DFF DFF
add mapped point signatures[0][27]/q signatures_reg[0][27]/QN -type DFF DFF
add mapped point signatures[0][28]/q signatures_reg[0][28]/QN -type DFF DFF
add mapped point signatures[0][29]/q signatures_reg[0][29]/QN -type DFF DFF
add mapped point signatures[0][30]/q signatures_reg[0][30]/QN -type DFF DFF
add mapped point signatures[0][31]/q signatures_reg[0][31]/QN -type DFF DFF
add mapped point signatures[1][0]/q signatures_reg[1][0]/QN -type DFF DFF
add mapped point signatures[1][1]/q signatures_reg[1][1]/QN -type DFF DFF
add mapped point signatures[1][2]/q signatures_reg[1][2]/QN -type DFF DFF
add mapped point signatures[1][3]/q signatures_reg[1][3]/QN -type DFF DFF
add mapped point signatures[1][4]/q signatures_reg[1][4]/QN -type DFF DFF
add mapped point signatures[1][5]/q signatures_reg[1][5]/QN -type DFF DFF
add mapped point signatures[1][6]/q signatures_reg[1][6]/QN -type DFF DFF
add mapped point signatures[1][7]/q signatures_reg[1][7]/QN -type DFF DFF
add mapped point signatures[1][8]/q signatures_reg[1][8]/QN -type DFF DFF
add mapped point signatures[1][9]/q signatures_reg[1][9]/QN -type DFF DFF
add mapped point signatures[1][10]/q signatures_reg[1][10]/QN -type DFF DFF
add mapped point signatures[1][11]/q signatures_reg[1][11]/QN -type DFF DFF
add mapped point signatures[1][12]/q signatures_reg[1][12]/QN -type DFF DFF
add mapped point signatures[1][13]/q signatures_reg[1][13]/QN -type DFF DFF
add mapped point signatures[1][14]/q signatures_reg[1][14]/QN -type DFF DFF
add mapped point signatures[1][15]/q signatures_reg[1][15]/QN -type DFF DFF
add mapped point signatures[1][16]/q signatures_reg[1][16]/QN -type DFF DFF
add mapped point signatures[1][17]/q signatures_reg[1][17]/QN -type DFF DFF
add mapped point signatures[1][18]/q signatures_reg[1][18]/QN -type DFF DFF
add mapped point signatures[1][19]/q signatures_reg[1][19]/QN -type DFF DFF
add mapped point signatures[1][20]/q signatures_reg[1][20]/QN -type DFF DFF
add mapped point signatures[1][21]/q signatures_reg[1][21]/QN -type DFF DFF
add mapped point signatures[1][22]/q signatures_reg[1][22]/QN -type DFF DFF
add mapped point signatures[1][23]/q signatures_reg[1][23]/QN -type DFF DFF
add mapped point signatures[1][24]/q signatures_reg[1][24]/QN -type DFF DFF
add mapped point signatures[1][25]/q signatures_reg[1][25]/QN -type DFF DFF
add mapped point signatures[1][26]/q signatures_reg[1][26]/QN -type DFF DFF
add mapped point signatures[1][27]/q signatures_reg[1][27]/QN -type DFF DFF
add mapped point signatures[1][28]/q signatures_reg[1][28]/QN -type DFF DFF
add mapped point signatures[1][29]/q signatures_reg[1][29]/QN -type DFF DFF
add mapped point signatures[1][30]/q signatures_reg[1][30]/QN -type DFF DFF
add mapped point signatures[1][31]/q signatures_reg[1][31]/QN -type DFF DFF
add mapped point signatures[2][0]/q signatures_reg[2][0]/Q -type DFF DFF
add mapped point signatures[2][1]/q signatures_reg[2][1]/Q -type DFF DFF
add mapped point signatures[2][2]/q signatures_reg[2][2]/Q -type DFF DFF
add mapped point signatures[2][3]/q signatures_reg[2][3]/Q -type DFF DFF
add mapped point signatures[2][4]/q signatures_reg[2][4]/Q -type DFF DFF
add mapped point signatures[2][5]/q signatures_reg[2][5]/Q -type DFF DFF
add mapped point signatures[2][6]/q signatures_reg[2][6]/Q -type DFF DFF
add mapped point signatures[2][7]/q signatures_reg[2][7]/Q -type DFF DFF
add mapped point signatures[2][8]/q signatures_reg[2][8]/Q -type DFF DFF
add mapped point signatures[2][9]/q signatures_reg[2][9]/Q -type DFF DFF
add mapped point signatures[2][10]/q signatures_reg[2][10]/Q -type DFF DFF
add mapped point signatures[2][11]/q signatures_reg[2][11]/Q -type DFF DFF
add mapped point signatures[2][12]/q signatures_reg[2][12]/Q -type DFF DFF
add mapped point signatures[2][13]/q signatures_reg[2][13]/Q -type DFF DFF
add mapped point signatures[2][14]/q signatures_reg[2][14]/Q -type DFF DFF
add mapped point signatures[2][15]/q signatures_reg[2][15]/Q -type DFF DFF
add mapped point signatures[2][16]/q signatures_reg[2][16]/Q -type DFF DFF
add mapped point signatures[2][17]/q signatures_reg[2][17]/Q -type DFF DFF
add mapped point signatures[2][18]/q signatures_reg[2][18]/Q -type DFF DFF
add mapped point signatures[2][19]/q signatures_reg[2][19]/Q -type DFF DFF
add mapped point signatures[2][20]/q signatures_reg[2][20]/Q -type DFF DFF
add mapped point signatures[2][21]/q signatures_reg[2][21]/Q -type DFF DFF
add mapped point signatures[2][22]/q signatures_reg[2][22]/Q -type DFF DFF
add mapped point signatures[2][23]/q signatures_reg[2][23]/Q -type DFF DFF
add mapped point signatures[2][24]/q signatures_reg[2][24]/Q -type DFF DFF
add mapped point signatures[2][25]/q signatures_reg[2][25]/Q -type DFF DFF
add mapped point signatures[2][26]/q signatures_reg[2][26]/Q -type DFF DFF
add mapped point signatures[2][27]/q signatures_reg[2][27]/Q -type DFF DFF
add mapped point signatures[2][28]/q signatures_reg[2][28]/Q -type DFF DFF
add mapped point signatures[2][29]/q signatures_reg[2][29]/Q -type DFF DFF
add mapped point signatures[2][30]/q signatures_reg[2][30]/Q -type DFF DFF
add mapped point signatures[2][31]/q signatures_reg[2][31]/Q -type DFF DFF
add mapped point signatures[3][0]/q signatures_reg[3][0]/Q -type DFF DFF
add mapped point signatures[3][1]/q signatures_reg[3][1]/Q -type DFF DFF
add mapped point signatures[3][2]/q signatures_reg[3][2]/Q -type DFF DFF
add mapped point signatures[3][3]/q signatures_reg[3][3]/Q -type DFF DFF
add mapped point signatures[3][4]/q signatures_reg[3][4]/Q -type DFF DFF
add mapped point signatures[3][5]/q signatures_reg[3][5]/Q -type DFF DFF
add mapped point signatures[3][6]/q signatures_reg[3][6]/Q -type DFF DFF
add mapped point signatures[3][7]/q signatures_reg[3][7]/Q -type DFF DFF
add mapped point signatures[3][8]/q signatures_reg[3][8]/Q -type DFF DFF
add mapped point signatures[3][9]/q signatures_reg[3][9]/Q -type DFF DFF
add mapped point signatures[3][10]/q signatures_reg[3][10]/Q -type DFF DFF
add mapped point signatures[3][11]/q signatures_reg[3][11]/Q -type DFF DFF
add mapped point signatures[3][12]/q signatures_reg[3][12]/Q -type DFF DFF
add mapped point signatures[3][13]/q signatures_reg[3][13]/Q -type DFF DFF
add mapped point signatures[3][14]/q signatures_reg[3][14]/Q -type DFF DFF
add mapped point signatures[3][15]/q signatures_reg[3][15]/Q -type DFF DFF
add mapped point signatures[3][16]/q signatures_reg[3][16]/Q -type DFF DFF
add mapped point signatures[3][17]/q signatures_reg[3][17]/Q -type DFF DFF
add mapped point signatures[3][18]/q signatures_reg[3][18]/Q -type DFF DFF
add mapped point signatures[3][19]/q signatures_reg[3][19]/Q -type DFF DFF
add mapped point signatures[3][20]/q signatures_reg[3][20]/Q -type DFF DFF
add mapped point signatures[3][21]/q signatures_reg[3][21]/Q -type DFF DFF
add mapped point signatures[3][22]/q signatures_reg[3][22]/Q -type DFF DFF
add mapped point signatures[3][23]/q signatures_reg[3][23]/Q -type DFF DFF
add mapped point signatures[3][24]/q signatures_reg[3][24]/Q -type DFF DFF
add mapped point signatures[3][25]/q signatures_reg[3][25]/Q -type DFF DFF
add mapped point signatures[3][26]/q signatures_reg[3][26]/Q -type DFF DFF
add mapped point signatures[3][27]/q signatures_reg[3][27]/Q -type DFF DFF
add mapped point signatures[3][28]/q signatures_reg[3][28]/Q -type DFF DFF
add mapped point signatures[3][29]/q signatures_reg[3][29]/Q -type DFF DFF
add mapped point signatures[3][30]/q signatures_reg[3][30]/Q -type DFF DFF
add mapped point signatures[3][31]/q signatures_reg[3][31]/Q -type DFF DFF
add mapped point smallest_position[0]/q smallest_position_reg[0]/Q -type DFF DFF
add mapped point smallest_position[1]/q smallest_position_reg[1]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
