
//input ports
add mapped point in_signature[31] in_signature[31] -type PI PI
add mapped point in_signature[30] in_signature[30] -type PI PI
add mapped point in_signature[29] in_signature[29] -type PI PI
add mapped point in_signature[28] in_signature[28] -type PI PI
add mapped point in_signature[27] in_signature[27] -type PI PI
add mapped point in_signature[26] in_signature[26] -type PI PI
add mapped point in_signature[25] in_signature[25] -type PI PI
add mapped point in_signature[24] in_signature[24] -type PI PI
add mapped point in_signature[23] in_signature[23] -type PI PI
add mapped point in_signature[22] in_signature[22] -type PI PI
add mapped point in_signature[21] in_signature[21] -type PI PI
add mapped point in_signature[20] in_signature[20] -type PI PI
add mapped point in_signature[19] in_signature[19] -type PI PI
add mapped point in_signature[18] in_signature[18] -type PI PI
add mapped point in_signature[17] in_signature[17] -type PI PI
add mapped point in_signature[16] in_signature[16] -type PI PI
add mapped point in_signature[15] in_signature[15] -type PI PI
add mapped point in_signature[14] in_signature[14] -type PI PI
add mapped point in_signature[13] in_signature[13] -type PI PI
add mapped point in_signature[12] in_signature[12] -type PI PI
add mapped point in_signature[11] in_signature[11] -type PI PI
add mapped point in_signature[10] in_signature[10] -type PI PI
add mapped point in_signature[9] in_signature[9] -type PI PI
add mapped point in_signature[8] in_signature[8] -type PI PI
add mapped point in_signature[7] in_signature[7] -type PI PI
add mapped point in_signature[6] in_signature[6] -type PI PI
add mapped point in_signature[5] in_signature[5] -type PI PI
add mapped point in_signature[4] in_signature[4] -type PI PI
add mapped point in_signature[3] in_signature[3] -type PI PI
add mapped point in_signature[2] in_signature[2] -type PI PI
add mapped point in_signature[1] in_signature[1] -type PI PI
add mapped point in_signature[0] in_signature[0] -type PI PI
add mapped point in_index[11] in_index[11] -type PI PI
add mapped point in_index[10] in_index[10] -type PI PI
add mapped point in_index[9] in_index[9] -type PI PI
add mapped point in_index[8] in_index[8] -type PI PI
add mapped point in_index[7] in_index[7] -type PI PI
add mapped point in_index[6] in_index[6] -type PI PI
add mapped point in_index[5] in_index[5] -type PI PI
add mapped point in_index[4] in_index[4] -type PI PI
add mapped point in_index[3] in_index[3] -type PI PI
add mapped point in_index[2] in_index[2] -type PI PI
add mapped point in_index[1] in_index[1] -type PI PI
add mapped point in_index[0] in_index[0] -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point end_sorting end_sorting -type PI PI
add mapped point clk clk -type PI PI

//output ports
add mapped point out_smallest_idx[0][11] out_smallest_idx[0][11] -type PO PO
add mapped point out_smallest_idx[0][10] out_smallest_idx[0][10] -type PO PO
add mapped point out_smallest_idx[0][9] out_smallest_idx[0][9] -type PO PO
add mapped point out_smallest_idx[0][8] out_smallest_idx[0][8] -type PO PO
add mapped point out_smallest_idx[0][7] out_smallest_idx[0][7] -type PO PO
add mapped point out_smallest_idx[0][6] out_smallest_idx[0][6] -type PO PO
add mapped point out_smallest_idx[0][5] out_smallest_idx[0][5] -type PO PO
add mapped point out_smallest_idx[0][4] out_smallest_idx[0][4] -type PO PO
add mapped point out_smallest_idx[0][3] out_smallest_idx[0][3] -type PO PO
add mapped point out_smallest_idx[0][2] out_smallest_idx[0][2] -type PO PO
add mapped point out_smallest_idx[0][1] out_smallest_idx[0][1] -type PO PO
add mapped point out_smallest_idx[0][0] out_smallest_idx[0][0] -type PO PO
add mapped point out_smallest_idx[1][11] out_smallest_idx[1][11] -type PO PO
add mapped point out_smallest_idx[1][10] out_smallest_idx[1][10] -type PO PO
add mapped point out_smallest_idx[1][9] out_smallest_idx[1][9] -type PO PO
add mapped point out_smallest_idx[1][8] out_smallest_idx[1][8] -type PO PO
add mapped point out_smallest_idx[1][7] out_smallest_idx[1][7] -type PO PO
add mapped point out_smallest_idx[1][6] out_smallest_idx[1][6] -type PO PO
add mapped point out_smallest_idx[1][5] out_smallest_idx[1][5] -type PO PO
add mapped point out_smallest_idx[1][4] out_smallest_idx[1][4] -type PO PO
add mapped point out_smallest_idx[1][3] out_smallest_idx[1][3] -type PO PO
add mapped point out_smallest_idx[1][2] out_smallest_idx[1][2] -type PO PO
add mapped point out_smallest_idx[1][1] out_smallest_idx[1][1] -type PO PO
add mapped point out_smallest_idx[1][0] out_smallest_idx[1][0] -type PO PO
add mapped point out_smallest_idx[2][11] out_smallest_idx[2][11] -type PO PO
add mapped point out_smallest_idx[2][10] out_smallest_idx[2][10] -type PO PO
add mapped point out_smallest_idx[2][9] out_smallest_idx[2][9] -type PO PO
add mapped point out_smallest_idx[2][8] out_smallest_idx[2][8] -type PO PO
add mapped point out_smallest_idx[2][7] out_smallest_idx[2][7] -type PO PO
add mapped point out_smallest_idx[2][6] out_smallest_idx[2][6] -type PO PO
add mapped point out_smallest_idx[2][5] out_smallest_idx[2][5] -type PO PO
add mapped point out_smallest_idx[2][4] out_smallest_idx[2][4] -type PO PO
add mapped point out_smallest_idx[2][3] out_smallest_idx[2][3] -type PO PO
add mapped point out_smallest_idx[2][2] out_smallest_idx[2][2] -type PO PO
add mapped point out_smallest_idx[2][1] out_smallest_idx[2][1] -type PO PO
add mapped point out_smallest_idx[2][0] out_smallest_idx[2][0] -type PO PO
add mapped point out_smallest_idx[3][11] out_smallest_idx[3][11] -type PO PO
add mapped point out_smallest_idx[3][10] out_smallest_idx[3][10] -type PO PO
add mapped point out_smallest_idx[3][9] out_smallest_idx[3][9] -type PO PO
add mapped point out_smallest_idx[3][8] out_smallest_idx[3][8] -type PO PO
add mapped point out_smallest_idx[3][7] out_smallest_idx[3][7] -type PO PO
add mapped point out_smallest_idx[3][6] out_smallest_idx[3][6] -type PO PO
add mapped point out_smallest_idx[3][5] out_smallest_idx[3][5] -type PO PO
add mapped point out_smallest_idx[3][4] out_smallest_idx[3][4] -type PO PO
add mapped point out_smallest_idx[3][3] out_smallest_idx[3][3] -type PO PO
add mapped point out_smallest_idx[3][2] out_smallest_idx[3][2] -type PO PO
add mapped point out_smallest_idx[3][1] out_smallest_idx[3][1] -type PO PO
add mapped point out_smallest_idx[3][0] out_smallest_idx[3][0] -type PO PO
add mapped point out_smallest_idx[4][11] out_smallest_idx[4][11] -type PO PO
add mapped point out_smallest_idx[4][10] out_smallest_idx[4][10] -type PO PO
add mapped point out_smallest_idx[4][9] out_smallest_idx[4][9] -type PO PO
add mapped point out_smallest_idx[4][8] out_smallest_idx[4][8] -type PO PO
add mapped point out_smallest_idx[4][7] out_smallest_idx[4][7] -type PO PO
add mapped point out_smallest_idx[4][6] out_smallest_idx[4][6] -type PO PO
add mapped point out_smallest_idx[4][5] out_smallest_idx[4][5] -type PO PO
add mapped point out_smallest_idx[4][4] out_smallest_idx[4][4] -type PO PO
add mapped point out_smallest_idx[4][3] out_smallest_idx[4][3] -type PO PO
add mapped point out_smallest_idx[4][2] out_smallest_idx[4][2] -type PO PO
add mapped point out_smallest_idx[4][1] out_smallest_idx[4][1] -type PO PO
add mapped point out_smallest_idx[4][0] out_smallest_idx[4][0] -type PO PO
add mapped point out_smallest_idx[5][11] out_smallest_idx[5][11] -type PO PO
add mapped point out_smallest_idx[5][10] out_smallest_idx[5][10] -type PO PO
add mapped point out_smallest_idx[5][9] out_smallest_idx[5][9] -type PO PO
add mapped point out_smallest_idx[5][8] out_smallest_idx[5][8] -type PO PO
add mapped point out_smallest_idx[5][7] out_smallest_idx[5][7] -type PO PO
add mapped point out_smallest_idx[5][6] out_smallest_idx[5][6] -type PO PO
add mapped point out_smallest_idx[5][5] out_smallest_idx[5][5] -type PO PO
add mapped point out_smallest_idx[5][4] out_smallest_idx[5][4] -type PO PO
add mapped point out_smallest_idx[5][3] out_smallest_idx[5][3] -type PO PO
add mapped point out_smallest_idx[5][2] out_smallest_idx[5][2] -type PO PO
add mapped point out_smallest_idx[5][1] out_smallest_idx[5][1] -type PO PO
add mapped point out_smallest_idx[5][0] out_smallest_idx[5][0] -type PO PO
add mapped point out_smallest_idx[6][11] out_smallest_idx[6][11] -type PO PO
add mapped point out_smallest_idx[6][10] out_smallest_idx[6][10] -type PO PO
add mapped point out_smallest_idx[6][9] out_smallest_idx[6][9] -type PO PO
add mapped point out_smallest_idx[6][8] out_smallest_idx[6][8] -type PO PO
add mapped point out_smallest_idx[6][7] out_smallest_idx[6][7] -type PO PO
add mapped point out_smallest_idx[6][6] out_smallest_idx[6][6] -type PO PO
add mapped point out_smallest_idx[6][5] out_smallest_idx[6][5] -type PO PO
add mapped point out_smallest_idx[6][4] out_smallest_idx[6][4] -type PO PO
add mapped point out_smallest_idx[6][3] out_smallest_idx[6][3] -type PO PO
add mapped point out_smallest_idx[6][2] out_smallest_idx[6][2] -type PO PO
add mapped point out_smallest_idx[6][1] out_smallest_idx[6][1] -type PO PO
add mapped point out_smallest_idx[6][0] out_smallest_idx[6][0] -type PO PO
add mapped point out_smallest_idx[7][11] out_smallest_idx[7][11] -type PO PO
add mapped point out_smallest_idx[7][10] out_smallest_idx[7][10] -type PO PO
add mapped point out_smallest_idx[7][9] out_smallest_idx[7][9] -type PO PO
add mapped point out_smallest_idx[7][8] out_smallest_idx[7][8] -type PO PO
add mapped point out_smallest_idx[7][7] out_smallest_idx[7][7] -type PO PO
add mapped point out_smallest_idx[7][6] out_smallest_idx[7][6] -type PO PO
add mapped point out_smallest_idx[7][5] out_smallest_idx[7][5] -type PO PO
add mapped point out_smallest_idx[7][4] out_smallest_idx[7][4] -type PO PO
add mapped point out_smallest_idx[7][3] out_smallest_idx[7][3] -type PO PO
add mapped point out_smallest_idx[7][2] out_smallest_idx[7][2] -type PO PO
add mapped point out_smallest_idx[7][1] out_smallest_idx[7][1] -type PO PO
add mapped point out_smallest_idx[7][0] out_smallest_idx[7][0] -type PO PO
add mapped point sort_valid sort_valid -type PO PO

//inout ports




//Sequential Pins
add mapped point smallest_idx_curr[0].index[0]/q smallest_idx_curr_reg[0][index][0]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].index[1]/q smallest_idx_curr_reg[0][index][1]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].index[2]/q smallest_idx_curr_reg[0][index][2]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].index[3]/q smallest_idx_curr_reg[0][index][3]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].index[4]/q smallest_idx_curr_reg[0][index][4]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].index[5]/q smallest_idx_curr_reg[0][index][5]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].index[6]/q smallest_idx_curr_reg[0][index][6]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].index[7]/q smallest_idx_curr_reg[0][index][7]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].index[8]/q smallest_idx_curr_reg[0][index][8]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].index[9]/q smallest_idx_curr_reg[0][index][9]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].index[10]/q smallest_idx_curr_reg[0][index][10]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].index[11]/q smallest_idx_curr_reg[0][index][11]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[0]/q smallest_idx_curr_reg[0][signature][0]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[1]/q smallest_idx_curr_reg[0][signature][1]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[2]/q smallest_idx_curr_reg[0][signature][2]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[3]/q smallest_idx_curr_reg[0][signature][3]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[4]/q smallest_idx_curr_reg[0][signature][4]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[5]/q smallest_idx_curr_reg[0][signature][5]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[6]/q smallest_idx_curr_reg[0][signature][6]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[7]/q smallest_idx_curr_reg[0][signature][7]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[8]/q smallest_idx_curr_reg[0][signature][8]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[9]/q smallest_idx_curr_reg[0][signature][9]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[10]/q smallest_idx_curr_reg[0][signature][10]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[11]/q smallest_idx_curr_reg[0][signature][11]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[12]/q smallest_idx_curr_reg[0][signature][12]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[13]/q smallest_idx_curr_reg[0][signature][13]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[14]/q smallest_idx_curr_reg[0][signature][14]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[15]/q smallest_idx_curr_reg[0][signature][15]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[16]/q smallest_idx_curr_reg[0][signature][16]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[17]/q smallest_idx_curr_reg[0][signature][17]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[18]/q smallest_idx_curr_reg[0][signature][18]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[19]/q smallest_idx_curr_reg[0][signature][19]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[20]/q smallest_idx_curr_reg[0][signature][20]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[21]/q smallest_idx_curr_reg[0][signature][21]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[22]/q smallest_idx_curr_reg[0][signature][22]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[23]/q smallest_idx_curr_reg[0][signature][23]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[24]/q smallest_idx_curr_reg[0][signature][24]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[25]/q smallest_idx_curr_reg[0][signature][25]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[26]/q smallest_idx_curr_reg[0][signature][26]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[27]/q smallest_idx_curr_reg[0][signature][27]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[28]/q smallest_idx_curr_reg[0][signature][28]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[29]/q smallest_idx_curr_reg[0][signature][29]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[30]/q smallest_idx_curr_reg[0][signature][30]/Q -type DFF DFF
add mapped point smallest_idx_curr[0].signature[31]/q smallest_idx_curr_reg[0][signature][31]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].index[0]/q smallest_idx_curr_reg[1][index][0]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].index[1]/q smallest_idx_curr_reg[1][index][1]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].index[2]/q smallest_idx_curr_reg[1][index][2]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].index[3]/q smallest_idx_curr_reg[1][index][3]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].index[4]/q smallest_idx_curr_reg[1][index][4]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].index[5]/q smallest_idx_curr_reg[1][index][5]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].index[6]/q smallest_idx_curr_reg[1][index][6]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].index[7]/q smallest_idx_curr_reg[1][index][7]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].index[8]/q smallest_idx_curr_reg[1][index][8]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].index[9]/q smallest_idx_curr_reg[1][index][9]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].index[10]/q smallest_idx_curr_reg[1][index][10]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].index[11]/q smallest_idx_curr_reg[1][index][11]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[0]/q smallest_idx_curr_reg[1][signature][0]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[1]/q smallest_idx_curr_reg[1][signature][1]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[2]/q smallest_idx_curr_reg[1][signature][2]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[3]/q smallest_idx_curr_reg[1][signature][3]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[4]/q smallest_idx_curr_reg[1][signature][4]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[5]/q smallest_idx_curr_reg[1][signature][5]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[6]/q smallest_idx_curr_reg[1][signature][6]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[7]/q smallest_idx_curr_reg[1][signature][7]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[8]/q smallest_idx_curr_reg[1][signature][8]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[9]/q smallest_idx_curr_reg[1][signature][9]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[10]/q smallest_idx_curr_reg[1][signature][10]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[11]/q smallest_idx_curr_reg[1][signature][11]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[12]/q smallest_idx_curr_reg[1][signature][12]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[13]/q smallest_idx_curr_reg[1][signature][13]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[14]/q smallest_idx_curr_reg[1][signature][14]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[15]/q smallest_idx_curr_reg[1][signature][15]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[16]/q smallest_idx_curr_reg[1][signature][16]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[17]/q smallest_idx_curr_reg[1][signature][17]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[18]/q smallest_idx_curr_reg[1][signature][18]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[19]/q smallest_idx_curr_reg[1][signature][19]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[20]/q smallest_idx_curr_reg[1][signature][20]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[21]/q smallest_idx_curr_reg[1][signature][21]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[22]/q smallest_idx_curr_reg[1][signature][22]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[23]/q smallest_idx_curr_reg[1][signature][23]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[24]/q smallest_idx_curr_reg[1][signature][24]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[25]/q smallest_idx_curr_reg[1][signature][25]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[26]/q smallest_idx_curr_reg[1][signature][26]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[27]/q smallest_idx_curr_reg[1][signature][27]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[28]/q smallest_idx_curr_reg[1][signature][28]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[29]/q smallest_idx_curr_reg[1][signature][29]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[30]/q smallest_idx_curr_reg[1][signature][30]/Q -type DFF DFF
add mapped point smallest_idx_curr[1].signature[31]/q smallest_idx_curr_reg[1][signature][31]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].index[0]/q smallest_idx_curr_reg[2][index][0]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].index[1]/q smallest_idx_curr_reg[2][index][1]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].index[2]/q smallest_idx_curr_reg[2][index][2]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].index[3]/q smallest_idx_curr_reg[2][index][3]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].index[4]/q smallest_idx_curr_reg[2][index][4]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].index[5]/q smallest_idx_curr_reg[2][index][5]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].index[6]/q smallest_idx_curr_reg[2][index][6]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].index[7]/q smallest_idx_curr_reg[2][index][7]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].index[8]/q smallest_idx_curr_reg[2][index][8]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].index[9]/q smallest_idx_curr_reg[2][index][9]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].index[10]/q smallest_idx_curr_reg[2][index][10]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].index[11]/q smallest_idx_curr_reg[2][index][11]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[0]/q smallest_idx_curr_reg[2][signature][0]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[1]/q smallest_idx_curr_reg[2][signature][1]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[2]/q smallest_idx_curr_reg[2][signature][2]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[3]/q smallest_idx_curr_reg[2][signature][3]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[4]/q smallest_idx_curr_reg[2][signature][4]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[5]/q smallest_idx_curr_reg[2][signature][5]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[6]/q smallest_idx_curr_reg[2][signature][6]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[7]/q smallest_idx_curr_reg[2][signature][7]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[8]/q smallest_idx_curr_reg[2][signature][8]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[9]/q smallest_idx_curr_reg[2][signature][9]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[10]/q smallest_idx_curr_reg[2][signature][10]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[11]/q smallest_idx_curr_reg[2][signature][11]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[12]/q smallest_idx_curr_reg[2][signature][12]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[13]/q smallest_idx_curr_reg[2][signature][13]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[14]/q smallest_idx_curr_reg[2][signature][14]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[15]/q smallest_idx_curr_reg[2][signature][15]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[16]/q smallest_idx_curr_reg[2][signature][16]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[17]/q smallest_idx_curr_reg[2][signature][17]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[18]/q smallest_idx_curr_reg[2][signature][18]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[19]/q smallest_idx_curr_reg[2][signature][19]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[20]/q smallest_idx_curr_reg[2][signature][20]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[21]/q smallest_idx_curr_reg[2][signature][21]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[22]/q smallest_idx_curr_reg[2][signature][22]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[23]/q smallest_idx_curr_reg[2][signature][23]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[24]/q smallest_idx_curr_reg[2][signature][24]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[25]/q smallest_idx_curr_reg[2][signature][25]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[26]/q smallest_idx_curr_reg[2][signature][26]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[27]/q smallest_idx_curr_reg[2][signature][27]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[28]/q smallest_idx_curr_reg[2][signature][28]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[29]/q smallest_idx_curr_reg[2][signature][29]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[30]/q smallest_idx_curr_reg[2][signature][30]/Q -type DFF DFF
add mapped point smallest_idx_curr[2].signature[31]/q smallest_idx_curr_reg[2][signature][31]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].index[0]/q smallest_idx_curr_reg[3][index][0]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].index[1]/q smallest_idx_curr_reg[3][index][1]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].index[2]/q smallest_idx_curr_reg[3][index][2]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].index[3]/q smallest_idx_curr_reg[3][index][3]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].index[4]/q smallest_idx_curr_reg[3][index][4]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].index[5]/q smallest_idx_curr_reg[3][index][5]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].index[6]/q smallest_idx_curr_reg[3][index][6]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].index[7]/q smallest_idx_curr_reg[3][index][7]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].index[8]/q smallest_idx_curr_reg[3][index][8]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].index[9]/q smallest_idx_curr_reg[3][index][9]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].index[10]/q smallest_idx_curr_reg[3][index][10]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].index[11]/q smallest_idx_curr_reg[3][index][11]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[0]/q smallest_idx_curr_reg[3][signature][0]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[1]/q smallest_idx_curr_reg[3][signature][1]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[2]/q smallest_idx_curr_reg[3][signature][2]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[3]/q smallest_idx_curr_reg[3][signature][3]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[4]/q smallest_idx_curr_reg[3][signature][4]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[5]/q smallest_idx_curr_reg[3][signature][5]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[6]/q smallest_idx_curr_reg[3][signature][6]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[7]/q smallest_idx_curr_reg[3][signature][7]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[8]/q smallest_idx_curr_reg[3][signature][8]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[9]/q smallest_idx_curr_reg[3][signature][9]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[10]/q smallest_idx_curr_reg[3][signature][10]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[11]/q smallest_idx_curr_reg[3][signature][11]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[12]/q smallest_idx_curr_reg[3][signature][12]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[13]/q smallest_idx_curr_reg[3][signature][13]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[14]/q smallest_idx_curr_reg[3][signature][14]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[15]/q smallest_idx_curr_reg[3][signature][15]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[16]/q smallest_idx_curr_reg[3][signature][16]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[17]/q smallest_idx_curr_reg[3][signature][17]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[18]/q smallest_idx_curr_reg[3][signature][18]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[19]/q smallest_idx_curr_reg[3][signature][19]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[20]/q smallest_idx_curr_reg[3][signature][20]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[21]/q smallest_idx_curr_reg[3][signature][21]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[22]/q smallest_idx_curr_reg[3][signature][22]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[23]/q smallest_idx_curr_reg[3][signature][23]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[24]/q smallest_idx_curr_reg[3][signature][24]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[25]/q smallest_idx_curr_reg[3][signature][25]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[26]/q smallest_idx_curr_reg[3][signature][26]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[27]/q smallest_idx_curr_reg[3][signature][27]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[28]/q smallest_idx_curr_reg[3][signature][28]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[29]/q smallest_idx_curr_reg[3][signature][29]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[30]/q smallest_idx_curr_reg[3][signature][30]/Q -type DFF DFF
add mapped point smallest_idx_curr[3].signature[31]/q smallest_idx_curr_reg[3][signature][31]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].index[0]/q smallest_idx_curr_reg[4][index][0]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].index[1]/q smallest_idx_curr_reg[4][index][1]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].index[2]/q smallest_idx_curr_reg[4][index][2]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].index[3]/q smallest_idx_curr_reg[4][index][3]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].index[4]/q smallest_idx_curr_reg[4][index][4]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].index[5]/q smallest_idx_curr_reg[4][index][5]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].index[6]/q smallest_idx_curr_reg[4][index][6]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].index[7]/q smallest_idx_curr_reg[4][index][7]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].index[8]/q smallest_idx_curr_reg[4][index][8]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].index[9]/q smallest_idx_curr_reg[4][index][9]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].index[10]/q smallest_idx_curr_reg[4][index][10]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].index[11]/q smallest_idx_curr_reg[4][index][11]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[0]/q smallest_idx_curr_reg[4][signature][0]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[1]/q smallest_idx_curr_reg[4][signature][1]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[2]/q smallest_idx_curr_reg[4][signature][2]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[3]/q smallest_idx_curr_reg[4][signature][3]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[4]/q smallest_idx_curr_reg[4][signature][4]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[5]/q smallest_idx_curr_reg[4][signature][5]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[6]/q smallest_idx_curr_reg[4][signature][6]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[7]/q smallest_idx_curr_reg[4][signature][7]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[8]/q smallest_idx_curr_reg[4][signature][8]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[9]/q smallest_idx_curr_reg[4][signature][9]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[10]/q smallest_idx_curr_reg[4][signature][10]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[11]/q smallest_idx_curr_reg[4][signature][11]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[12]/q smallest_idx_curr_reg[4][signature][12]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[13]/q smallest_idx_curr_reg[4][signature][13]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[14]/q smallest_idx_curr_reg[4][signature][14]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[15]/q smallest_idx_curr_reg[4][signature][15]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[16]/q smallest_idx_curr_reg[4][signature][16]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[17]/q smallest_idx_curr_reg[4][signature][17]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[18]/q smallest_idx_curr_reg[4][signature][18]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[19]/q smallest_idx_curr_reg[4][signature][19]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[20]/q smallest_idx_curr_reg[4][signature][20]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[21]/q smallest_idx_curr_reg[4][signature][21]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[22]/q smallest_idx_curr_reg[4][signature][22]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[23]/q smallest_idx_curr_reg[4][signature][23]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[24]/q smallest_idx_curr_reg[4][signature][24]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[25]/q smallest_idx_curr_reg[4][signature][25]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[26]/q smallest_idx_curr_reg[4][signature][26]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[27]/q smallest_idx_curr_reg[4][signature][27]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[28]/q smallest_idx_curr_reg[4][signature][28]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[29]/q smallest_idx_curr_reg[4][signature][29]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[30]/q smallest_idx_curr_reg[4][signature][30]/Q -type DFF DFF
add mapped point smallest_idx_curr[4].signature[31]/q smallest_idx_curr_reg[4][signature][31]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].index[0]/q smallest_idx_curr_reg[5][index][0]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].index[1]/q smallest_idx_curr_reg[5][index][1]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].index[2]/q smallest_idx_curr_reg[5][index][2]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].index[3]/q smallest_idx_curr_reg[5][index][3]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].index[4]/q smallest_idx_curr_reg[5][index][4]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].index[5]/q smallest_idx_curr_reg[5][index][5]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].index[6]/q smallest_idx_curr_reg[5][index][6]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].index[7]/q smallest_idx_curr_reg[5][index][7]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].index[8]/q smallest_idx_curr_reg[5][index][8]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].index[9]/q smallest_idx_curr_reg[5][index][9]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].index[10]/q smallest_idx_curr_reg[5][index][10]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].index[11]/q smallest_idx_curr_reg[5][index][11]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[0]/q smallest_idx_curr_reg[5][signature][0]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[1]/q smallest_idx_curr_reg[5][signature][1]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[2]/q smallest_idx_curr_reg[5][signature][2]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[3]/q smallest_idx_curr_reg[5][signature][3]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[4]/q smallest_idx_curr_reg[5][signature][4]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[5]/q smallest_idx_curr_reg[5][signature][5]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[6]/q smallest_idx_curr_reg[5][signature][6]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[7]/q smallest_idx_curr_reg[5][signature][7]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[8]/q smallest_idx_curr_reg[5][signature][8]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[9]/q smallest_idx_curr_reg[5][signature][9]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[10]/q smallest_idx_curr_reg[5][signature][10]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[11]/q smallest_idx_curr_reg[5][signature][11]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[12]/q smallest_idx_curr_reg[5][signature][12]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[13]/q smallest_idx_curr_reg[5][signature][13]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[14]/q smallest_idx_curr_reg[5][signature][14]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[15]/q smallest_idx_curr_reg[5][signature][15]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[16]/q smallest_idx_curr_reg[5][signature][16]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[17]/q smallest_idx_curr_reg[5][signature][17]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[18]/q smallest_idx_curr_reg[5][signature][18]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[19]/q smallest_idx_curr_reg[5][signature][19]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[20]/q smallest_idx_curr_reg[5][signature][20]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[21]/q smallest_idx_curr_reg[5][signature][21]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[22]/q smallest_idx_curr_reg[5][signature][22]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[23]/q smallest_idx_curr_reg[5][signature][23]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[24]/q smallest_idx_curr_reg[5][signature][24]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[25]/q smallest_idx_curr_reg[5][signature][25]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[26]/q smallest_idx_curr_reg[5][signature][26]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[27]/q smallest_idx_curr_reg[5][signature][27]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[28]/q smallest_idx_curr_reg[5][signature][28]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[29]/q smallest_idx_curr_reg[5][signature][29]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[30]/q smallest_idx_curr_reg[5][signature][30]/Q -type DFF DFF
add mapped point smallest_idx_curr[5].signature[31]/q smallest_idx_curr_reg[5][signature][31]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].index[0]/q smallest_idx_curr_reg[6][index][0]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].index[1]/q smallest_idx_curr_reg[6][index][1]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].index[2]/q smallest_idx_curr_reg[6][index][2]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].index[3]/q smallest_idx_curr_reg[6][index][3]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].index[4]/q smallest_idx_curr_reg[6][index][4]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].index[5]/q smallest_idx_curr_reg[6][index][5]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].index[6]/q smallest_idx_curr_reg[6][index][6]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].index[7]/q smallest_idx_curr_reg[6][index][7]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].index[8]/q smallest_idx_curr_reg[6][index][8]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].index[9]/q smallest_idx_curr_reg[6][index][9]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].index[10]/q smallest_idx_curr_reg[6][index][10]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].index[11]/q smallest_idx_curr_reg[6][index][11]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[0]/q smallest_idx_curr_reg[6][signature][0]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[1]/q smallest_idx_curr_reg[6][signature][1]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[2]/q smallest_idx_curr_reg[6][signature][2]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[3]/q smallest_idx_curr_reg[6][signature][3]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[4]/q smallest_idx_curr_reg[6][signature][4]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[5]/q smallest_idx_curr_reg[6][signature][5]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[6]/q smallest_idx_curr_reg[6][signature][6]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[7]/q smallest_idx_curr_reg[6][signature][7]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[8]/q smallest_idx_curr_reg[6][signature][8]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[9]/q smallest_idx_curr_reg[6][signature][9]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[10]/q smallest_idx_curr_reg[6][signature][10]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[11]/q smallest_idx_curr_reg[6][signature][11]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[12]/q smallest_idx_curr_reg[6][signature][12]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[13]/q smallest_idx_curr_reg[6][signature][13]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[14]/q smallest_idx_curr_reg[6][signature][14]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[15]/q smallest_idx_curr_reg[6][signature][15]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[16]/q smallest_idx_curr_reg[6][signature][16]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[17]/q smallest_idx_curr_reg[6][signature][17]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[18]/q smallest_idx_curr_reg[6][signature][18]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[19]/q smallest_idx_curr_reg[6][signature][19]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[20]/q smallest_idx_curr_reg[6][signature][20]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[21]/q smallest_idx_curr_reg[6][signature][21]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[22]/q smallest_idx_curr_reg[6][signature][22]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[23]/q smallest_idx_curr_reg[6][signature][23]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[24]/q smallest_idx_curr_reg[6][signature][24]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[25]/q smallest_idx_curr_reg[6][signature][25]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[26]/q smallest_idx_curr_reg[6][signature][26]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[27]/q smallest_idx_curr_reg[6][signature][27]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[28]/q smallest_idx_curr_reg[6][signature][28]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[29]/q smallest_idx_curr_reg[6][signature][29]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[30]/q smallest_idx_curr_reg[6][signature][30]/Q -type DFF DFF
add mapped point smallest_idx_curr[6].signature[31]/q smallest_idx_curr_reg[6][signature][31]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].index[0]/q smallest_idx_curr_reg[7][index][0]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].index[1]/q smallest_idx_curr_reg[7][index][1]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].index[2]/q smallest_idx_curr_reg[7][index][2]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].index[3]/q smallest_idx_curr_reg[7][index][3]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].index[4]/q smallest_idx_curr_reg[7][index][4]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].index[5]/q smallest_idx_curr_reg[7][index][5]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].index[6]/q smallest_idx_curr_reg[7][index][6]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].index[7]/q smallest_idx_curr_reg[7][index][7]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].index[8]/q smallest_idx_curr_reg[7][index][8]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].index[9]/q smallest_idx_curr_reg[7][index][9]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].index[10]/q smallest_idx_curr_reg[7][index][10]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].index[11]/q smallest_idx_curr_reg[7][index][11]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[0]/q smallest_idx_curr_reg[7][signature][0]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[1]/q smallest_idx_curr_reg[7][signature][1]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[2]/q smallest_idx_curr_reg[7][signature][2]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[3]/q smallest_idx_curr_reg[7][signature][3]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[4]/q smallest_idx_curr_reg[7][signature][4]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[5]/q smallest_idx_curr_reg[7][signature][5]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[6]/q smallest_idx_curr_reg[7][signature][6]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[7]/q smallest_idx_curr_reg[7][signature][7]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[8]/q smallest_idx_curr_reg[7][signature][8]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[9]/q smallest_idx_curr_reg[7][signature][9]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[10]/q smallest_idx_curr_reg[7][signature][10]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[11]/q smallest_idx_curr_reg[7][signature][11]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[12]/q smallest_idx_curr_reg[7][signature][12]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[13]/q smallest_idx_curr_reg[7][signature][13]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[14]/q smallest_idx_curr_reg[7][signature][14]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[15]/q smallest_idx_curr_reg[7][signature][15]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[16]/q smallest_idx_curr_reg[7][signature][16]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[17]/q smallest_idx_curr_reg[7][signature][17]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[18]/q smallest_idx_curr_reg[7][signature][18]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[19]/q smallest_idx_curr_reg[7][signature][19]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[20]/q smallest_idx_curr_reg[7][signature][20]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[21]/q smallest_idx_curr_reg[7][signature][21]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[22]/q smallest_idx_curr_reg[7][signature][22]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[23]/q smallest_idx_curr_reg[7][signature][23]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[24]/q smallest_idx_curr_reg[7][signature][24]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[25]/q smallest_idx_curr_reg[7][signature][25]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[26]/q smallest_idx_curr_reg[7][signature][26]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[27]/q smallest_idx_curr_reg[7][signature][27]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[28]/q smallest_idx_curr_reg[7][signature][28]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[29]/q smallest_idx_curr_reg[7][signature][29]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[30]/q smallest_idx_curr_reg[7][signature][30]/Q -type DFF DFF
add mapped point smallest_idx_curr[7].signature[31]/q smallest_idx_curr_reg[7][signature][31]/Q -type DFF DFF
add mapped point smallest_idx_next[0].index[0]/q smallest_idx_next_reg[0][index][0]/Q -type DLAT DLAT
add mapped point smallest_idx_next[0].index[1]/q smallest_idx_next_reg[0][index][1]/Q -type DLAT DLAT
add mapped point smallest_idx_next[0].index[2]/q smallest_idx_next_reg[0][index][2]/Q -type DLAT DLAT
add mapped point smallest_idx_next[0].index[3]/q smallest_idx_next_reg[0][index][3]/Q -type DLAT DLAT
add mapped point smallest_idx_next[0].index[4]/q smallest_idx_next_reg[0][index][4]/Q -type DLAT DLAT
add mapped point smallest_idx_next[0].index[5]/q smallest_idx_next_reg[0][index][5]/Q -type DLAT DLAT
add mapped point smallest_idx_next[0].index[6]/q smallest_idx_next_reg[0][index][6]/Q -type DLAT DLAT
add mapped point smallest_idx_next[0].index[7]/q smallest_idx_next_reg[0][index][7]/Q -type DLAT DLAT
add mapped point smallest_idx_next[0].index[8]/q smallest_idx_next_reg[0][index][8]/Q -type DLAT DLAT
add mapped point smallest_idx_next[0].index[9]/q smallest_idx_next_reg[0][index][9]/Q -type DLAT DLAT
add mapped point smallest_idx_next[0].index[10]/q smallest_idx_next_reg[0][index][10]/Q -type DLAT DLAT
add mapped point smallest_idx_next[0].index[11]/q smallest_idx_next_reg[0][index][11]/Q -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[0]/q smallest_idx_next_reg[0][signature][0]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[1]/q smallest_idx_next_reg[0][signature][1]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[2]/q smallest_idx_next_reg[0][signature][2]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[3]/q smallest_idx_next_reg[0][signature][3]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[4]/q smallest_idx_next_reg[0][signature][4]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[5]/q smallest_idx_next_reg[0][signature][5]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[6]/q smallest_idx_next_reg[0][signature][6]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[7]/q smallest_idx_next_reg[0][signature][7]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[8]/q smallest_idx_next_reg[0][signature][8]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[9]/q smallest_idx_next_reg[0][signature][9]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[10]/q smallest_idx_next_reg[0][signature][10]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[11]/q smallest_idx_next_reg[0][signature][11]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[12]/q smallest_idx_next_reg[0][signature][12]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[13]/q smallest_idx_next_reg[0][signature][13]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[14]/q smallest_idx_next_reg[0][signature][14]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[15]/q smallest_idx_next_reg[0][signature][15]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[16]/q smallest_idx_next_reg[0][signature][16]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[17]/q smallest_idx_next_reg[0][signature][17]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[18]/q smallest_idx_next_reg[0][signature][18]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[19]/q smallest_idx_next_reg[0][signature][19]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[20]/q smallest_idx_next_reg[0][signature][20]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[21]/q smallest_idx_next_reg[0][signature][21]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[22]/q smallest_idx_next_reg[0][signature][22]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[23]/q smallest_idx_next_reg[0][signature][23]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[24]/q smallest_idx_next_reg[0][signature][24]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[25]/q smallest_idx_next_reg[0][signature][25]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[26]/q smallest_idx_next_reg[0][signature][26]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[27]/q smallest_idx_next_reg[0][signature][27]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[28]/q smallest_idx_next_reg[0][signature][28]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[29]/q smallest_idx_next_reg[0][signature][29]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[30]/q smallest_idx_next_reg[0][signature][30]/QN -type DLAT DLAT
add mapped point smallest_idx_next[0].signature[31]/q smallest_idx_next_reg[0][signature][31]/QN -type DLAT DLAT



//Black Boxes



//Empty Modules as Blackboxes
