catch {set_db {port:proj_extender/in_fragment[7]} .original_name {in_fragment[7]}}
catch {set_db {port:proj_extender/in_fragment[6]} .original_name {in_fragment[6]}}
catch {set_db {port:proj_extender/in_fragment[5]} .original_name {in_fragment[5]}}
catch {set_db {port:proj_extender/in_fragment[4]} .original_name {in_fragment[4]}}
catch {set_db {port:proj_extender/in_fragment[3]} .original_name {in_fragment[3]}}
catch {set_db {port:proj_extender/in_fragment[2]} .original_name {in_fragment[2]}}
catch {set_db {port:proj_extender/in_fragment[1]} .original_name {in_fragment[1]}}
catch {set_db {port:proj_extender/in_fragment[0]} .original_name {in_fragment[0]}}
catch {set_db {port:proj_extender/in_kmer_indices[0][2]} .original_name {in_kmer_indices[0][2]}}
catch {set_db {port:proj_extender/in_kmer_indices[0][1]} .original_name {in_kmer_indices[0][1]}}
catch {set_db {port:proj_extender/in_kmer_indices[0][0]} .original_name {in_kmer_indices[0][0]}}
catch {set_db {port:proj_extender/in_kmer_indices[1][2]} .original_name {in_kmer_indices[1][2]}}
catch {set_db {port:proj_extender/in_kmer_indices[1][1]} .original_name {in_kmer_indices[1][1]}}
catch {set_db {port:proj_extender/in_kmer_indices[1][0]} .original_name {in_kmer_indices[1][0]}}
catch {set_db {port:proj_extender/in_kmer_indices[2][2]} .original_name {in_kmer_indices[2][2]}}
catch {set_db {port:proj_extender/in_kmer_indices[2][1]} .original_name {in_kmer_indices[2][1]}}
catch {set_db {port:proj_extender/in_kmer_indices[2][0]} .original_name {in_kmer_indices[2][0]}}
catch {set_db {port:proj_extender/in_kmer_indices[3][2]} .original_name {in_kmer_indices[3][2]}}
catch {set_db {port:proj_extender/in_kmer_indices[3][1]} .original_name {in_kmer_indices[3][1]}}
catch {set_db {port:proj_extender/in_kmer_indices[3][0]} .original_name {in_kmer_indices[3][0]}}
catch {set_db port:proj_extender/valid_indices .original_name valid_indices}
catch {set_db port:proj_extender/rst_n .original_name rst_n}
catch {set_db port:proj_extender/clk .original_name clk}
catch {set_db {port:proj_extender/out_index[3]} .original_name {out_index[3]}}
catch {set_db {port:proj_extender/out_index[2]} .original_name {out_index[2]}}
catch {set_db {port:proj_extender/out_index[1]} .original_name {out_index[1]}}
catch {set_db {port:proj_extender/out_index[0]} .original_name {out_index[0]}}
catch {set_db {port:proj_extender/out_gfm[7]} .original_name {out_gfm[7]}}
catch {set_db {port:proj_extender/out_gfm[6]} .original_name {out_gfm[6]}}
catch {set_db {port:proj_extender/out_gfm[5]} .original_name {out_gfm[5]}}
catch {set_db {port:proj_extender/out_gfm[4]} .original_name {out_gfm[4]}}
catch {set_db {port:proj_extender/out_gfm[3]} .original_name {out_gfm[3]}}
catch {set_db {port:proj_extender/out_gfm[2]} .original_name {out_gfm[2]}}
catch {set_db {port:proj_extender/out_gfm[1]} .original_name {out_gfm[1]}}
catch {set_db {port:proj_extender/out_gfm[0]} .original_name {out_gfm[0]}}
catch {set_db {pin:proj_extender/indices_idx_reg[1]/Q} .original_name {indices_idx[1]/q}}
catch {set_db {pin:proj_extender/in_kmer_indices_r_reg[2][0]/Q} .original_name {in_kmer_indices_r[2][0]/q}}
catch {set_db {pin:proj_extender/in_kmer_indices_r_reg[0][2]/Q} .original_name {in_kmer_indices_r[0][2]/q}}
catch {set_db {pin:proj_extender/in_kmer_indices_r_reg[1][0]/Q} .original_name {in_kmer_indices_r[1][0]/q}}
catch {set_db {pin:proj_extender/in_kmer_indices_r_reg[1][1]/Q} .original_name {in_kmer_indices_r[1][1]/q}}
catch {set_db {pin:proj_extender/in_kmer_indices_r_reg[3][1]/Q} .original_name {in_kmer_indices_r[3][1]/q}}
catch {set_db {pin:proj_extender/in_kmer_indices_r_reg[1][2]/Q} .original_name {in_kmer_indices_r[1][2]/q}}
catch {set_db {pin:proj_extender/indices_idx_reg[0]/QN} .original_name {indices_idx[0]/q}}
catch {set_db {pin:proj_extender/in_kmer_indices_r_reg[2][2]/Q} .original_name {in_kmer_indices_r[2][2]/q}}
catch {set_db {pin:proj_extender/in_kmer_indices_r_reg[3][0]/Q} .original_name {in_kmer_indices_r[3][0]/q}}
catch {set_db {pin:proj_extender/in_kmer_indices_r_reg[0][1]/Q} .original_name {in_kmer_indices_r[0][1]/q}}
catch {set_db {pin:proj_extender/in_kmer_indices_r_reg[3][2]/Q} .original_name {in_kmer_indices_r[3][2]/q}}
catch {set_db {pin:proj_extender/in_kmer_indices_r_reg[2][1]/Q} .original_name {in_kmer_indices_r[2][1]/q}}
catch {set_db {pin:proj_extender/in_kmer_indices_r_reg[0][0]/Q} .original_name {in_kmer_indices_r[0][0]/q}}
catch {set_db {inst:proj_extender/indices_idx_reg[1]} .original_name {{indices_idx[1]}}}
catch {set_db {inst:proj_extender/in_kmer_indices_r_reg[2][0]} .original_name {{in_kmer_indices_r[2][0]}}}
catch {set_db {inst:proj_extender/in_kmer_indices_r_reg[0][2]} .original_name {{in_kmer_indices_r[0][2]}}}
catch {set_db {inst:proj_extender/in_kmer_indices_r_reg[1][0]} .original_name {{in_kmer_indices_r[1][0]}}}
catch {set_db {inst:proj_extender/in_kmer_indices_r_reg[1][1]} .original_name {{in_kmer_indices_r[1][1]}}}
catch {set_db {inst:proj_extender/in_kmer_indices_r_reg[3][1]} .original_name {{in_kmer_indices_r[3][1]}}}
catch {set_db {inst:proj_extender/in_kmer_indices_r_reg[1][2]} .original_name {{in_kmer_indices_r[1][2]}}}
catch {set_db {inst:proj_extender/indices_idx_reg[0]} .original_name {{indices_idx[0]}}}
catch {set_db {inst:proj_extender/in_kmer_indices_r_reg[2][2]} .original_name {{in_kmer_indices_r[2][2]}}}
catch {set_db {inst:proj_extender/in_kmer_indices_r_reg[3][0]} .original_name {{in_kmer_indices_r[3][0]}}}
catch {set_db {inst:proj_extender/in_kmer_indices_r_reg[0][1]} .original_name {{in_kmer_indices_r[0][1]}}}
catch {set_db {inst:proj_extender/in_kmer_indices_r_reg[3][2]} .original_name {{in_kmer_indices_r[3][2]}}}
catch {set_db {inst:proj_extender/in_kmer_indices_r_reg[2][1]} .original_name {{in_kmer_indices_r[2][1]}}}
catch {set_db {inst:proj_extender/in_kmer_indices_r_reg[0][0]} .original_name {{in_kmer_indices_r[0][0]}}}
