
// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Aug  9 2024 09:21:21 UTC (Aug  9 2024 09:21:21 UTC)

// Verification Directory fv/proj_extender 

module RC_CG_MOD(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  PREICG_X0P5B_A9TR RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test),
       .ECK (ck_out));
endmodule

module proj_extender(in_fragment, \in_kmer_indices[0] ,
     \in_kmer_indices[1] , \in_kmer_indices[2] , \in_kmer_indices[3] ,
     valid_indices, rst_n, clk, out_index, out_gfm);
  input [7:0] in_fragment;
  input [2:0] \in_kmer_indices[0] , \in_kmer_indices[1] ,
       \in_kmer_indices[2] , \in_kmer_indices[3] ;
  input valid_indices, rst_n, clk;
  output [3:0] out_index;
  output [7:0] out_gfm;
  wire [7:0] in_fragment;
  wire [2:0] \in_kmer_indices[0] , \in_kmer_indices[1] ,
       \in_kmer_indices[2] , \in_kmer_indices[3] ;
  wire valid_indices, rst_n, clk;
  wire [3:0] out_index;
  wire [7:0] out_gfm;
  wire [2:0] \in_kmer_indices_r[2] ;
  wire [2:0] \in_kmer_indices_r[0] ;
  wire [2:0] \in_kmer_indices_r[3] ;
  wire [2:0] \in_kmer_indices_r[1] ;
  wire [1:0] indices_idx;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_17, n_18, rc_gclk;
  RC_CG_MOD RC_CG_HIER_INST0(.enable (valid_indices), .ck_in (clk),
       .ck_out (rc_gclk), .test (1'b0));
  INV_X1M_A9TL g266(.A (n_15), .Y (out_index[2]));
  ADDH_X1M_A9TL g267__2398(.A (out_index[1]), .B (n_14), .CO
       (out_index[3]), .S (n_15));
  AND2_X2M_A9TL g268__5107(.A (n_8), .B (n_10), .Y (out_index[1]));
  NAND2_X1A_A9TL g269__6260(.A (n_13), .B (n_12), .Y (out_index[0]));
  AND2_X2M_A9TL g270__4319(.A (n_11), .B (n_9), .Y (n_14));
  AOI2XB1_X1M_A9TL g271__8428(.A0 (\in_kmer_indices_r[2] [0]), .A1N
       (n_17), .B0 (n_7), .Y (n_13));
  AOI22_X1M_A9TL g272__5526(.A0 (\in_kmer_indices_r[0] [0]), .A1 (n_5),
       .B0 (\in_kmer_indices_r[3] [0]), .B1 (n_4), .Y (n_12));
  AOI22_X1M_A9TL g273__6783(.A0 (\in_kmer_indices_r[2] [2]), .A1 (n_3),
       .B0 (\in_kmer_indices_r[3] [2]), .B1 (n_4), .Y (n_11));
  AOI22_X1M_A9TL g274__3680(.A0 (\in_kmer_indices_r[0] [1]), .A1 (n_5),
       .B0 (\in_kmer_indices_r[1] [1]), .B1 (n_6), .Y (n_10));
  AOI22_X1M_A9TL g275__1617(.A0 (\in_kmer_indices_r[0] [2]), .A1 (n_5),
       .B0 (\in_kmer_indices_r[1] [2]), .B1 (n_6), .Y (n_9));
  AOI22_X2M_A9TL g276__2802(.A0 (\in_kmer_indices_r[2] [1]), .A1 (n_3),
       .B0 (\in_kmer_indices_r[3] [1]), .B1 (n_4), .Y (n_8));
  NOR2XB_X1M_A9TL g277__1705(.A (n_18), .BN (\in_kmer_indices_r[1]
       [0]), .Y (n_7));
  INV_X2M_A9TL g278(.A (n_3), .Y (n_17));
  INV_X1M_A9TL g279(.A (n_6), .Y (n_18));
  NOR2B_X2M_A9TL g281__5122(.AN (indices_idx[0]), .B (indices_idx[1]),
       .Y (n_6));
  NOR2_X1P4A_A9TL g282__8246(.A (indices_idx[0]), .B (indices_idx[1]),
       .Y (n_5));
  AND2_X1M_A9TL g283__7098(.A (indices_idx[0]), .B (indices_idx[1]), .Y
       (n_4));
  NOR2B_X3M_A9TL g2__6131(.AN (indices_idx[1]), .B (indices_idx[0]), .Y
       (n_3));
  DFFRPQ_X2M_A9TL \indices_idx_reg[1] (.R (n_0), .CK (clk), .D (n_1),
       .Q (indices_idx[1]));
  DFFQ_X1M_A9TL \in_kmer_indices_r_reg[2][0] (.CK (rc_gclk), .D
       (\in_kmer_indices[2] [0]), .Q (\in_kmer_indices_r[2] [0]));
  DFFQ_X1M_A9TL \in_kmer_indices_r_reg[0][2] (.CK (rc_gclk), .D
       (\in_kmer_indices[0] [2]), .Q (\in_kmer_indices_r[0] [2]));
  DFFQ_X1M_A9TL \in_kmer_indices_r_reg[1][0] (.CK (rc_gclk), .D
       (\in_kmer_indices[1] [0]), .Q (\in_kmer_indices_r[1] [0]));
  DFFQ_X1M_A9TL \in_kmer_indices_r_reg[1][1] (.CK (rc_gclk), .D
       (\in_kmer_indices[1] [1]), .Q (\in_kmer_indices_r[1] [1]));
  DFFQ_X1M_A9TL \in_kmer_indices_r_reg[3][1] (.CK (rc_gclk), .D
       (\in_kmer_indices[3] [1]), .Q (\in_kmer_indices_r[3] [1]));
  DFFQ_X1M_A9TL \in_kmer_indices_r_reg[1][2] (.CK (rc_gclk), .D
       (\in_kmer_indices[1] [2]), .Q (\in_kmer_indices_r[1] [2]));
  DFFRPQN_X3M_A9TL \indices_idx_reg[0] (.R (n_0), .CK (clk), .D (n_2),
       .QN (n_2));
  NAND2_X1A_A9TL g224__1881(.A (n_18), .B (n_17), .Y (n_1));
  DFFQ_X1M_A9TL \in_kmer_indices_r_reg[2][2] (.CK (rc_gclk), .D
       (\in_kmer_indices[2] [2]), .Q (\in_kmer_indices_r[2] [2]));
  DFFQ_X1M_A9TL \in_kmer_indices_r_reg[3][0] (.CK (rc_gclk), .D
       (\in_kmer_indices[3] [0]), .Q (\in_kmer_indices_r[3] [0]));
  DFFQ_X1M_A9TL \in_kmer_indices_r_reg[0][1] (.CK (rc_gclk), .D
       (\in_kmer_indices[0] [1]), .Q (\in_kmer_indices_r[0] [1]));
  DFFQ_X1M_A9TL \in_kmer_indices_r_reg[3][2] (.CK (rc_gclk), .D
       (\in_kmer_indices[3] [2]), .Q (\in_kmer_indices_r[3] [2]));
  DFFQ_X1M_A9TL \in_kmer_indices_r_reg[2][1] (.CK (rc_gclk), .D
       (\in_kmer_indices[2] [1]), .Q (\in_kmer_indices_r[2] [1]));
  DFFQ_X1M_A9TL \in_kmer_indices_r_reg[0][0] (.CK (rc_gclk), .D
       (\in_kmer_indices[0] [0]), .Q (\in_kmer_indices_r[0] [0]));
  INV_X0P5M_A9TL g231(.A (rst_n), .Y (n_0));
  INV_X4M_A9TL g233(.A (n_2), .Y (indices_idx[0]));
  NOR2B_X1M_A9TL g240__5115(.AN (in_fragment[3]), .B (in_fragment[2]),
       .Y (out_gfm[6]));
  NOR2B_X1M_A9TL g241__7482(.AN (in_fragment[2]), .B (in_fragment[3]),
       .Y (out_gfm[5]));
  AND2_X1M_A9TL g242__4733(.A (in_fragment[3]), .B (in_fragment[2]), .Y
       (out_gfm[7]));
  NOR2_X1B_A9TL g243__6161(.A (in_fragment[3]), .B (in_fragment[2]), .Y
       (out_gfm[4]));
  NOR2B_X1M_A9TL g285__9315(.AN (in_fragment[1]), .B (in_fragment[0]),
       .Y (out_gfm[2]));
  NOR2B_X1M_A9TL g286__9945(.AN (in_fragment[0]), .B (in_fragment[1]),
       .Y (out_gfm[1]));
  AND2_X1M_A9TL g287__2883(.A (in_fragment[1]), .B (in_fragment[0]), .Y
       (out_gfm[3]));
  NOR2_X1B_A9TL g288__2346(.A (in_fragment[1]), .B (in_fragment[0]), .Y
       (out_gfm[0]));
endmodule

