catch {set_db port:proj_counter/clk .original_name clk}
catch {set_db port:proj_counter/rst_n .original_name rst_n}
catch {set_db {port:proj_counter/index[31]} .original_name {index[31]}}
catch {set_db {port:proj_counter/index[30]} .original_name {index[30]}}
catch {set_db {port:proj_counter/index[29]} .original_name {index[29]}}
catch {set_db {port:proj_counter/index[28]} .original_name {index[28]}}
catch {set_db {port:proj_counter/index[27]} .original_name {index[27]}}
catch {set_db {port:proj_counter/index[26]} .original_name {index[26]}}
catch {set_db {port:proj_counter/index[25]} .original_name {index[25]}}
catch {set_db {port:proj_counter/index[24]} .original_name {index[24]}}
catch {set_db {port:proj_counter/index[23]} .original_name {index[23]}}
catch {set_db {port:proj_counter/index[22]} .original_name {index[22]}}
catch {set_db {port:proj_counter/index[21]} .original_name {index[21]}}
catch {set_db {port:proj_counter/index[20]} .original_name {index[20]}}
catch {set_db {port:proj_counter/index[19]} .original_name {index[19]}}
catch {set_db {port:proj_counter/index[18]} .original_name {index[18]}}
catch {set_db {port:proj_counter/index[17]} .original_name {index[17]}}
catch {set_db {port:proj_counter/index[16]} .original_name {index[16]}}
catch {set_db {port:proj_counter/index[15]} .original_name {index[15]}}
catch {set_db {port:proj_counter/index[14]} .original_name {index[14]}}
catch {set_db {port:proj_counter/index[13]} .original_name {index[13]}}
catch {set_db {port:proj_counter/index[12]} .original_name {index[12]}}
catch {set_db {port:proj_counter/index[11]} .original_name {index[11]}}
catch {set_db {port:proj_counter/index[10]} .original_name {index[10]}}
catch {set_db {port:proj_counter/index[9]} .original_name {index[9]}}
catch {set_db {port:proj_counter/index[8]} .original_name {index[8]}}
catch {set_db {port:proj_counter/index[7]} .original_name {index[7]}}
catch {set_db {port:proj_counter/index[6]} .original_name {index[6]}}
catch {set_db {port:proj_counter/index[5]} .original_name {index[5]}}
catch {set_db {port:proj_counter/index[4]} .original_name {index[4]}}
catch {set_db {port:proj_counter/index[3]} .original_name {index[3]}}
catch {set_db {port:proj_counter/index[2]} .original_name {index[2]}}
catch {set_db {port:proj_counter/index[1]} .original_name {index[1]}}
catch {set_db {port:proj_counter/index[0]} .original_name {index[0]}}
catch {set_db port:proj_counter/finished_count .original_name finished_count}
catch {set_db {pin:proj_counter/out_index_reg[5]/Q} .original_name {out_index[5]/q}}
catch {set_db {pin:proj_counter/out_index_reg[1]/Q} .original_name {out_index[1]/q}}
catch {set_db {pin:proj_counter/out_index_reg[2]/Q} .original_name {out_index[2]/q}}
catch {set_db {pin:proj_counter/out_index_reg[20]/Q} .original_name {out_index[20]/q}}
catch {set_db {pin:proj_counter/out_index_reg[21]/Q} .original_name {out_index[21]/q}}
catch {set_db {pin:proj_counter/out_index_reg[22]/Q} .original_name {out_index[22]/q}}
catch {set_db {pin:proj_counter/out_index_reg[23]/Q} .original_name {out_index[23]/q}}
catch {set_db {pin:proj_counter/out_index_reg[24]/Q} .original_name {out_index[24]/q}}
catch {set_db {pin:proj_counter/out_index_reg[3]/Q} .original_name {out_index[3]/q}}
catch {set_db {pin:proj_counter/out_index_reg[25]/Q} .original_name {out_index[25]/q}}
catch {set_db {pin:proj_counter/out_index_reg[26]/Q} .original_name {out_index[26]/q}}
catch {set_db {pin:proj_counter/out_index_reg[27]/Q} .original_name {out_index[27]/q}}
catch {set_db {pin:proj_counter/out_index_reg[28]/Q} .original_name {out_index[28]/q}}
catch {set_db {pin:proj_counter/out_index_reg[29]/Q} .original_name {out_index[29]/q}}
catch {set_db {pin:proj_counter/out_index_reg[4]/Q} .original_name {out_index[4]/q}}
catch {set_db {pin:proj_counter/out_index_reg[0]/QN} .original_name {out_index[0]/q}}
catch {set_db {pin:proj_counter/out_index_reg[19]/Q} .original_name {out_index[19]/q}}
catch {set_db {pin:proj_counter/out_index_reg[31]/Q} .original_name {out_index[31]/q}}
catch {set_db {pin:proj_counter/out_index_reg[6]/Q} .original_name {out_index[6]/q}}
catch {set_db {pin:proj_counter/out_index_reg[7]/Q} .original_name {out_index[7]/q}}
catch {set_db {pin:proj_counter/out_index_reg[8]/Q} .original_name {out_index[8]/q}}
catch {set_db {pin:proj_counter/out_index_reg[9]/Q} .original_name {out_index[9]/q}}
catch {set_db {pin:proj_counter/out_index_reg[10]/Q} .original_name {out_index[10]/q}}
catch {set_db {pin:proj_counter/out_index_reg[11]/Q} .original_name {out_index[11]/q}}
catch {set_db {pin:proj_counter/out_index_reg[12]/Q} .original_name {out_index[12]/q}}
catch {set_db {pin:proj_counter/out_index_reg[13]/Q} .original_name {out_index[13]/q}}
catch {set_db {pin:proj_counter/out_index_reg[14]/Q} .original_name {out_index[14]/q}}
catch {set_db {pin:proj_counter/out_index_reg[15]/Q} .original_name {out_index[15]/q}}
catch {set_db {pin:proj_counter/out_index_reg[16]/Q} .original_name {out_index[16]/q}}
catch {set_db {pin:proj_counter/out_index_reg[17]/Q} .original_name {out_index[17]/q}}
catch {set_db {pin:proj_counter/out_index_reg[18]/Q} .original_name {out_index[18]/q}}
catch {set_db {pin:proj_counter/out_index_reg[30]/Q} .original_name {out_index[30]/q}}
catch {set_db {inst:proj_counter/out_index_reg[5]} .original_name {{out_index[5]}}}
catch {set_db {inst:proj_counter/out_index_reg[1]} .original_name {{out_index[1]}}}
catch {set_db {inst:proj_counter/out_index_reg[2]} .original_name {{out_index[2]}}}
catch {set_db {inst:proj_counter/out_index_reg[20]} .original_name {{out_index[20]}}}
catch {set_db {inst:proj_counter/out_index_reg[21]} .original_name {{out_index[21]}}}
catch {set_db {inst:proj_counter/out_index_reg[22]} .original_name {{out_index[22]}}}
catch {set_db {inst:proj_counter/out_index_reg[23]} .original_name {{out_index[23]}}}
catch {set_db {inst:proj_counter/out_index_reg[24]} .original_name {{out_index[24]}}}
catch {set_db {inst:proj_counter/out_index_reg[3]} .original_name {{out_index[3]}}}
catch {set_db {inst:proj_counter/out_index_reg[25]} .original_name {{out_index[25]}}}
catch {set_db {inst:proj_counter/out_index_reg[26]} .original_name {{out_index[26]}}}
catch {set_db {inst:proj_counter/out_index_reg[27]} .original_name {{out_index[27]}}}
catch {set_db {inst:proj_counter/out_index_reg[28]} .original_name {{out_index[28]}}}
catch {set_db {inst:proj_counter/out_index_reg[29]} .original_name {{out_index[29]}}}
catch {set_db {inst:proj_counter/out_index_reg[4]} .original_name {{out_index[4]}}}
catch {set_db {inst:proj_counter/out_index_reg[0]} .original_name {{out_index[0]}}}
catch {set_db {inst:proj_counter/out_index_reg[19]} .original_name {{out_index[19]}}}
catch {set_db {inst:proj_counter/out_index_reg[31]} .original_name {{out_index[31]}}}
catch {set_db {inst:proj_counter/out_index_reg[6]} .original_name {{out_index[6]}}}
catch {set_db {inst:proj_counter/out_index_reg[7]} .original_name {{out_index[7]}}}
catch {set_db {inst:proj_counter/out_index_reg[8]} .original_name {{out_index[8]}}}
catch {set_db {inst:proj_counter/out_index_reg[9]} .original_name {{out_index[9]}}}
catch {set_db {inst:proj_counter/out_index_reg[10]} .original_name {{out_index[10]}}}
catch {set_db {inst:proj_counter/out_index_reg[11]} .original_name {{out_index[11]}}}
catch {set_db {inst:proj_counter/out_index_reg[12]} .original_name {{out_index[12]}}}
catch {set_db {inst:proj_counter/out_index_reg[13]} .original_name {{out_index[13]}}}
catch {set_db {inst:proj_counter/out_index_reg[14]} .original_name {{out_index[14]}}}
catch {set_db {inst:proj_counter/out_index_reg[15]} .original_name {{out_index[15]}}}
catch {set_db {inst:proj_counter/out_index_reg[16]} .original_name {{out_index[16]}}}
catch {set_db {inst:proj_counter/out_index_reg[17]} .original_name {{out_index[17]}}}
catch {set_db {inst:proj_counter/out_index_reg[18]} .original_name {{out_index[18]}}}
catch {set_db {inst:proj_counter/out_index_reg[30]} .original_name {{out_index[30]}}}
