
// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Aug  8 2024 16:38:26 UTC (Aug  8 2024 16:38:26 UTC)

// Verification Directory fv/proj_fm 

module proj_fm(clk, rst_n, in_wdata, chg_idx, frag_idx, out_rdata,
     out_wait);
  input clk, rst_n, chg_idx;
  input [1:0] in_wdata;
  input [2:0] frag_idx;
  output [1:0] out_rdata;
  output out_wait;
  wire clk, rst_n, chg_idx;
  wire [1:0] in_wdata;
  wire [2:0] frag_idx;
  wire [1:0] out_rdata;
  wire out_wait;
  wire [4:0] waddr;
  wire [1:0] \FMbuffers[1][2] ;
  wire [1:0] \FMbuffers[1][0] ;
  wire [1:0] \FMbuffers[0][1] ;
  wire [1:0] \FMbuffers[0][0] ;
  wire [1:0] \FMbuffers[1][3] ;
  wire [1:0] \FMbuffers[1][1] ;
  wire [1:0] \FMbuffers[0][3] ;
  wire [1:0] \FMbuffers[0][2] ;
  wire [1:0] \FMbuffers[0][31] ;
  wire [1:0] \FMbuffers[1][31] ;
  wire \FMbuffers[rd_idx] , n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_19, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_32, n_33, n_34, n_35;
  wire n_41, n_42, n_43, n_44, n_45, n_47, n_48, n_49;
  wire n_50, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_76, n_77, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, wr_idx;
  assign out_rdata[0] = 1'b0;
  assign out_rdata[1] = 1'b0;
  INV_X1B_A9TL g2316(.A (n_77), .Y (out_wait));
  INV_X1B_A9TL g2317(.A (waddr[1]), .Y (n_69));
  INV_X1B_A9TL g2319(.A (waddr[4]), .Y (n_68));
  INV_X1B_A9TL g2318(.A (waddr[3]), .Y (n_67));
  OAI2XB1_X0P5M_A9TR g2412__2398(.A0 (n_93), .A1N (out_rdata[0]), .B0
       (n_66), .Y (out_rdata[0]));
  OAI2XB1_X0P5M_A9TR g2413__5107(.A0 (n_93), .A1N (out_rdata[1]), .B0
       (n_65), .Y (\FMbuffers[rd_idx] ));
  OAI211_X0P5M_A9TL g2414__6260(.A0 (wr_idx), .A1 (n_61), .B0 (n_63),
       .C0 (n_93), .Y (n_66));
  OAI211_X0P5M_A9TL g2415__4319(.A0 (wr_idx), .A1 (n_62), .B0 (n_64),
       .C0 (n_93), .Y (n_65));
  NAND3_X0P5A_A9TL g2416__8428(.A (wr_idx), .B (n_53), .C (n_52), .Y
       (n_64));
  NAND3_X0P5A_A9TL g2417__5526(.A (wr_idx), .B (n_58), .C (n_56), .Y
       (n_63));
  NAND2_X0P7B_A9TL g2418__6783(.A (n_59), .B (n_57), .Y (n_62));
  NAND2_X0P7B_A9TL g2419__3680(.A (n_54), .B (n_55), .Y (n_61));
  AOI22_X0P5M_A9TL g2420__1617(.A0 (\FMbuffers[1][2] [1]), .A1 (n_48),
       .B0 (\FMbuffers[1][0] [1]), .B1 (n_49), .Y (n_59));
  AOI22_X0P5M_A9TL g2421__2802(.A0 (\FMbuffers[0][1] [0]), .A1 (n_47),
       .B0 (\FMbuffers[0][0] [0]), .B1 (n_49), .Y (n_58));
  OR2_X3M_A9TL g2422__1705(.A (chg_idx), .B (n_76), .Y (n_77));
  AOI22_X0P5M_A9TL g2423__5122(.A0 (\FMbuffers[1][3] [1]), .A1 (n_50),
       .B0 (\FMbuffers[1][1] [1]), .B1 (n_47), .Y (n_57));
  AOI22_X0P5M_A9TL g2425__7098(.A0 (\FMbuffers[0][3] [0]), .A1 (n_50),
       .B0 (\FMbuffers[0][2] [0]), .B1 (n_48), .Y (n_56));
  AOI22_X0P5M_A9TL g2426__6131(.A0 (\FMbuffers[1][3] [0]), .A1 (n_50),
       .B0 (\FMbuffers[1][2] [0]), .B1 (n_48), .Y (n_55));
  AOI22_X0P5M_A9TL g2427__1881(.A0 (\FMbuffers[1][1] [0]), .A1 (n_47),
       .B0 (\FMbuffers[1][0] [0]), .B1 (n_49), .Y (n_54));
  AOI22_X0P5M_A9TL g2428__5115(.A0 (\FMbuffers[0][1] [1]), .A1 (n_47),
       .B0 (\FMbuffers[0][0] [1]), .B1 (n_49), .Y (n_53));
  AOI22_X0P5M_A9TL g2429__7482(.A0 (\FMbuffers[0][3] [1]), .A1 (n_50),
       .B0 (\FMbuffers[0][2] [1]), .B1 (n_48), .Y (n_52));
  OR4_X3M_A9TL g2430__4733(.A (n_41), .B (n_69), .C (n_68), .D (n_67),
       .Y (n_76));
  NOR2_X0P7B_A9TL g2432__6161(.A (n_45), .B (n_43), .Y (n_50));
  NOR2_X0P7B_A9TL g2433__9315(.A (n_44), .B (n_42), .Y (n_49));
  NOR2_X0P7B_A9TL g2435__2883(.A (n_42), .B (n_45), .Y (n_48));
  NOR2_X0P7B_A9TL g2436__2346(.A (n_44), .B (n_43), .Y (n_47));
  INV_X1M_A9TL g2437(.A (n_45), .Y (n_44));
  INV_X1M_A9TL g2439(.A (n_43), .Y (n_42));
  NAND2_X1A_A9TL g2440__1666(.A (waddr[0]), .B (waddr[2]), .Y (n_41));
  DFFRPQ_X3M_A9TL \waddr_reg[4] (.R (n_2), .CK (clk), .D (n_94), .Q
       (waddr[4]));
  SDFFQ_X1M_A9TL \FMbuffers_reg[0][1][0] (.CK (clk), .D (n_32), .SI
       (\FMbuffers[0][1] [0]), .SE (n_24), .Q (\FMbuffers[0][1] [0]));
  SDFFQ_X1M_A9TL \FMbuffers_reg[0][0][0] (.CK (clk), .D (n_32), .SI
       (\FMbuffers[0][0] [0]), .SE (n_34), .Q (\FMbuffers[0][0] [0]));
  SDFFQ_X1M_A9TL \FMbuffers_reg[0][1][1] (.CK (clk), .D (n_33), .SI
       (\FMbuffers[0][1] [1]), .SE (n_24), .Q (\FMbuffers[0][1] [1]));
  SDFFQ_X1M_A9TL \FMbuffers_reg[1][1][0] (.CK (clk), .D (n_32), .SI
       (\FMbuffers[1][1] [0]), .SE (n_26), .Q (\FMbuffers[1][1] [0]));
  SDFFQ_X1M_A9TL \FMbuffers_reg[1][1][1] (.CK (clk), .D (n_33), .SI
       (\FMbuffers[1][1] [1]), .SE (n_26), .Q (\FMbuffers[1][1] [1]));
  SDFFQ_X1M_A9TL \FMbuffers_reg[1][2][1] (.CK (clk), .D (n_33), .SI
       (\FMbuffers[1][2] [1]), .SE (n_25), .Q (\FMbuffers[1][2] [1]));
  SDFFQ_X1M_A9TL \FMbuffers_reg[0][0][1] (.CK (clk), .D (n_33), .SI
       (\FMbuffers[0][0] [1]), .SE (n_34), .Q (\FMbuffers[0][0] [1]));
  SDFFQ_X1M_A9TL \FMbuffers_reg[1][0][0] (.CK (clk), .D (n_32), .SI
       (\FMbuffers[1][0] [0]), .SE (n_27), .Q (\FMbuffers[1][0] [0]));
  SDFFQ_X1M_A9TL \FMbuffers_reg[1][0][1] (.CK (clk), .D (n_33), .SI
       (\FMbuffers[1][0] [1]), .SE (n_27), .Q (\FMbuffers[1][0] [1]));
  SDFFQ_X1M_A9TL \FMbuffers_reg[1][2][0] (.CK (clk), .D (n_32), .SI
       (\FMbuffers[1][2] [0]), .SE (n_25), .Q (\FMbuffers[1][2] [0]));
  DFFRPQ_X3M_A9TL \waddr_reg[3] (.R (n_2), .CK (clk), .D (n_95), .Q
       (waddr[3]));
  SDFFQ_X1M_A9TL \FMbuffers_reg[1][3][1] (.CK (clk), .D (n_33), .SI
       (\FMbuffers[1][3] [1]), .SE (n_28), .Q (\FMbuffers[1][3] [1]));
  SDFFQ_X1M_A9TL \FMbuffers_reg[0][2][1] (.CK (clk), .D (n_33), .SI
       (\FMbuffers[0][2] [1]), .SE (n_35), .Q (\FMbuffers[0][2] [1]));
  SDFFQ_X1M_A9TL \FMbuffers_reg[0][2][0] (.CK (clk), .D (n_32), .SI
       (\FMbuffers[0][2] [0]), .SE (n_35), .Q (\FMbuffers[0][2] [0]));
  SDFFQ_X1M_A9TL \FMbuffers_reg[0][3][0] (.CK (clk), .D (n_32), .SI
       (\FMbuffers[0][3] [0]), .SE (n_23), .Q (\FMbuffers[0][3] [0]));
  SDFFQ_X1M_A9TL \FMbuffers_reg[1][3][0] (.CK (clk), .D (n_32), .SI
       (\FMbuffers[1][3] [0]), .SE (n_28), .Q (\FMbuffers[1][3] [0]));
  SDFFQ_X1M_A9TL \FMbuffers_reg[0][31][0] (.CK (clk), .D (n_32), .SI
       (\FMbuffers[0][31] [0]), .SE (n_21), .Q (\FMbuffers[0][31] [0]));
  SDFFQ_X1M_A9TL \FMbuffers_reg[0][31][1] (.CK (clk), .D (n_33), .SI
       (\FMbuffers[0][31] [1]), .SE (n_21), .Q (\FMbuffers[0][31] [1]));
  SDFFQ_X1M_A9TL \FMbuffers_reg[1][31][0] (.CK (clk), .D (n_32), .SI
       (\FMbuffers[1][31] [0]), .SE (n_22), .Q (\FMbuffers[1][31] [0]));
  SDFFQ_X1M_A9TL \FMbuffers_reg[1][31][1] (.CK (clk), .D (n_33), .SI
       (\FMbuffers[1][31] [1]), .SE (n_22), .Q (\FMbuffers[1][31] [1]));
  SDFFQ_X1M_A9TL \FMbuffers_reg[0][3][1] (.CK (clk), .D (n_33), .SI
       (\FMbuffers[0][3] [1]), .SE (n_23), .Q (\FMbuffers[0][3] [1]));
  DFFRPQ_X4M_A9TL \waddr_reg[2] (.R (n_2), .CK (clk), .D (n_98), .Q
       (waddr[2]));
  DFFRPQ_X4M_A9TL \waddr_reg[1] (.R (n_2), .CK (clk), .D (n_100), .Q
       (waddr[1]));
  OR4_X1M_A9TL g2548__8428(.A (n_1), .B (wr_idx), .C (n_2), .D (n_10),
       .Y (n_35));
  OR4_X1M_A9TL g2549__5526(.A (n_1), .B (wr_idx), .C (n_2), .D (n_13),
       .Y (n_34));
  AO21B_X2M_A9TL g2550__6783(.A0 (\FMbuffers[0][31] [1]), .A1 (n_8),
       .B0N (n_16), .Y (n_33));
  AO21B_X2M_A9TL g2551__3680(.A0 (\FMbuffers[1][31] [0]), .A1 (n_9),
       .B0N (n_17), .Y (n_32));
  NAND4B_X1M_A9TL g2552__1617(.AN (n_10), .B (n_1), .C (wr_idx), .D
       (rst_n), .Y (n_28));
  NAND4B_X1M_A9TL g2553__2802(.AN (n_13), .B (wr_idx), .C (n_0), .D
       (rst_n), .Y (n_27));
  NAND4B_X1M_A9TL g2554__1705(.AN (n_13), .B (n_1), .C (wr_idx), .D
       (rst_n), .Y (n_26));
  NAND4B_X1M_A9TL g2555__5122(.AN (n_10), .B (wr_idx), .C (n_0), .D
       (rst_n), .Y (n_25));
  NAND4B_X1M_A9TL g2556__8246(.AN (n_13), .B (n_1), .C (n_5), .D
       (rst_n), .Y (n_24));
  NAND4B_X1M_A9TL g2557__7098(.AN (n_10), .B (n_1), .C (n_5), .D
       (rst_n), .Y (n_23));
  NAND4B_X1M_A9TL g2558__6131(.AN (n_11), .B (n_1), .C (wr_idx), .D
       (rst_n), .Y (n_22));
  NAND4XXXB_X1M_A9TL g2559__1881(.A (rst_n), .B (n_12), .C (n_1), .DN
       (wr_idx), .Y (n_21));
  NAND2_X1M_A9TL g2561__5115(.A (waddr[3]), .B (n_14), .Y (n_19));
  SDFFRPQ_X4M_A9TL \waddr_reg[0] (.R (n_2), .CK (clk), .D (n_3), .SI
       (n_76), .SE (n_0), .Q (waddr[0]));
  SDFFRPQ_X3M_A9TL wr_idx_reg(.R (n_2), .CK (clk), .D (wr_idx), .SI
       (n_5), .SE (chg_idx), .Q (wr_idx));
  AOI22_X1M_A9TL g2565__4733(.A0 (\FMbuffers[0][31] [0]), .A1 (n_8),
       .B0 (in_wdata[0]), .B1 (n_77), .Y (n_17));
  AOI22_X1M_A9TL g2566__6161(.A0 (\FMbuffers[1][31] [1]), .A1 (n_9),
       .B0 (in_wdata[1]), .B1 (n_77), .Y (n_16));
  INV_X1M_A9TL g2567(.A (n_14), .Y (n_15));
  NOR2XB_X2M_A9TL g2568__9315(.A (n_7), .BN (waddr[2]), .Y (n_14));
  OR4_X1M_A9TL g2569__9945(.A (waddr[1]), .B (waddr[2]), .C (waddr[3]),
       .D (waddr[4]), .Y (n_13));
  INV_X1M_A9TL g2570(.A (n_11), .Y (n_12));
  NAND4_X1A_A9TL g2571__2883(.A (waddr[1]), .B (waddr[2]), .C
       (waddr[3]), .D (waddr[4]), .Y (n_11));
  OR4_X1M_A9TL g2572__2346(.A (n_4), .B (waddr[2]), .C (waddr[3]), .D
       (waddr[4]), .Y (n_10));
  NOR2_X1A_A9TL g2573__1666(.A (n_5), .B (n_77), .Y (n_9));
  INV_X1M_A9TL g2574(.A (n_7), .Y (n_6));
  NOR2_X1A_A9TL g2575__7410(.A (wr_idx), .B (n_77), .Y (n_8));
  NAND2_X1P4M_A9TL g2576__6417(.A (n_1), .B (waddr[1]), .Y (n_7));
  INV_X2M_A9TL g2578(.A (wr_idx), .Y (n_5));
  INV_X2M_A9TL g2580(.A (waddr[1]), .Y (n_4));
  INV_X1M_A9TL g2583(.A (n_77), .Y (n_3));
  INV_X2M_A9TL g2585(.A (rst_n), .Y (n_2));
  INV_X1M_A9TL fopt3(.A (n_1), .Y (n_0));
  BUF_X2P5M_A9TL fopt5(.A (waddr[0]), .Y (n_1));
  BUFH_X16M_A9TL g2586(.A (\FMbuffers[rd_idx] ), .Y (out_rdata[1]));
  INV_X1M_A9TL g2589(.A (frag_idx[0]), .Y (n_43));
  INV_X1M_A9TL g2590(.A (frag_idx[1]), .Y (n_45));
  OAI21_X1M_A9TL g2(.A0 (frag_idx[0]), .A1 (frag_idx[1]), .B0
       (frag_idx[2]), .Y (n_93));
  NAND2_X1B_A9TL g2593(.A (n_77), .B (n_96), .Y (n_94));
  NAND2_X1B_A9TL g2594(.A (n_77), .B (n_97), .Y (n_95));
  OAI2XB1_X1M_A9TL g2595(.A0 (waddr[4]), .A1N (n_19), .B0 (n_76), .Y
       (n_96));
  OAI21_X1M_A9TL g2596(.A0 (waddr[3]), .A1 (n_14), .B0 (n_19), .Y
       (n_97));
  NAND2_X1B_A9TL g2597(.A (n_77), .B (n_99), .Y (n_98));
  OAI21_X1M_A9TL g2598(.A0 (waddr[2]), .A1 (n_6), .B0 (n_15), .Y
       (n_99));
  NAND2_X1B_A9TL g2599(.A (n_77), .B (n_101), .Y (n_100));
  OAI21_X1M_A9TL g2600(.A0 (n_1), .A1 (waddr[1]), .B0 (n_7), .Y
       (n_101));
endmodule

