catch {set_db port:proj_fm/clk .original_name clk}
catch {set_db port:proj_fm/rst_n .original_name rst_n}
catch {set_db {port:proj_fm/in_wdata[1]} .original_name {in_wdata[1]}}
catch {set_db {port:proj_fm/in_wdata[0]} .original_name {in_wdata[0]}}
catch {set_db port:proj_fm/chg_idx .original_name chg_idx}
catch {set_db {port:proj_fm/frag_idx[2]} .original_name {frag_idx[2]}}
catch {set_db {port:proj_fm/frag_idx[1]} .original_name {frag_idx[1]}}
catch {set_db {port:proj_fm/frag_idx[0]} .original_name {frag_idx[0]}}
catch {set_db {port:proj_fm/out_rdata[1]} .original_name {out_rdata[1]}}
catch {set_db {port:proj_fm/out_rdata[0]} .original_name {out_rdata[0]}}
catch {set_db port:proj_fm/out_wait .original_name out_wait}
catch {set_db {pin:proj_fm/waddr_reg[4]/Q} .original_name {waddr[4]/q}}
catch {set_db {pin:proj_fm/FMbuffers_reg[0][1][0]/Q} .original_name {FMbuffers[0][1][0]/q}}
catch {set_db {pin:proj_fm/FMbuffers_reg[0][0][0]/Q} .original_name {FMbuffers[0][0][0]/q}}
catch {set_db {pin:proj_fm/FMbuffers_reg[0][1][1]/Q} .original_name {FMbuffers[0][1][1]/q}}
catch {set_db {pin:proj_fm/FMbuffers_reg[1][1][0]/Q} .original_name {FMbuffers[1][1][0]/q}}
catch {set_db {pin:proj_fm/FMbuffers_reg[1][1][1]/Q} .original_name {FMbuffers[1][1][1]/q}}
catch {set_db {pin:proj_fm/FMbuffers_reg[1][2][1]/Q} .original_name {FMbuffers[1][2][1]/q}}
catch {set_db {pin:proj_fm/FMbuffers_reg[0][0][1]/Q} .original_name {FMbuffers[0][0][1]/q}}
catch {set_db {pin:proj_fm/FMbuffers_reg[1][0][0]/Q} .original_name {FMbuffers[1][0][0]/q}}
catch {set_db {pin:proj_fm/FMbuffers_reg[1][0][1]/Q} .original_name {FMbuffers[1][0][1]/q}}
catch {set_db {pin:proj_fm/FMbuffers_reg[1][2][0]/Q} .original_name {FMbuffers[1][2][0]/q}}
catch {set_db {pin:proj_fm/waddr_reg[3]/Q} .original_name {waddr[3]/q}}
catch {set_db {pin:proj_fm/FMbuffers_reg[1][3][1]/Q} .original_name {FMbuffers[1][3][1]/q}}
catch {set_db {pin:proj_fm/FMbuffers_reg[0][2][1]/Q} .original_name {FMbuffers[0][2][1]/q}}
catch {set_db {pin:proj_fm/FMbuffers_reg[0][2][0]/Q} .original_name {FMbuffers[0][2][0]/q}}
catch {set_db {pin:proj_fm/FMbuffers_reg[0][3][0]/Q} .original_name {FMbuffers[0][3][0]/q}}
catch {set_db {pin:proj_fm/FMbuffers_reg[1][3][0]/Q} .original_name {FMbuffers[1][3][0]/q}}
catch {set_db {pin:proj_fm/FMbuffers_reg[0][31][0]/Q} .original_name {FMbuffers[0][31][0]/q}}
catch {set_db {pin:proj_fm/FMbuffers_reg[0][31][1]/Q} .original_name {FMbuffers[0][31][1]/q}}
catch {set_db {pin:proj_fm/FMbuffers_reg[1][31][0]/Q} .original_name {FMbuffers[1][31][0]/q}}
catch {set_db {pin:proj_fm/FMbuffers_reg[1][31][1]/Q} .original_name {FMbuffers[1][31][1]/q}}
catch {set_db {pin:proj_fm/FMbuffers_reg[0][3][1]/Q} .original_name {FMbuffers[0][3][1]/q}}
catch {set_db {pin:proj_fm/waddr_reg[2]/Q} .original_name {waddr[2]/q}}
catch {set_db {pin:proj_fm/waddr_reg[1]/Q} .original_name {waddr[1]/q}}
catch {set_db {pin:proj_fm/waddr_reg[0]/Q} .original_name {waddr[0]/q}}
catch {set_db pin:proj_fm/wr_idx_reg/Q .original_name wr_idx/q}
catch {set_db {inst:proj_fm/waddr_reg[4]} .original_name {{waddr[4]}}}
catch {set_db {inst:proj_fm/FMbuffers_reg[0][1][0]} .original_name {{FMbuffers[0][1][0]}}}
catch {set_db {inst:proj_fm/FMbuffers_reg[0][0][0]} .original_name {{FMbuffers[0][0][0]}}}
catch {set_db {inst:proj_fm/FMbuffers_reg[0][1][1]} .original_name {{FMbuffers[0][1][1]}}}
catch {set_db {inst:proj_fm/FMbuffers_reg[1][1][0]} .original_name {{FMbuffers[1][1][0]}}}
catch {set_db {inst:proj_fm/FMbuffers_reg[1][1][1]} .original_name {{FMbuffers[1][1][1]}}}
catch {set_db {inst:proj_fm/FMbuffers_reg[1][2][1]} .original_name {{FMbuffers[1][2][1]}}}
catch {set_db {inst:proj_fm/FMbuffers_reg[0][0][1]} .original_name {{FMbuffers[0][0][1]}}}
catch {set_db {inst:proj_fm/FMbuffers_reg[1][0][0]} .original_name {{FMbuffers[1][0][0]}}}
catch {set_db {inst:proj_fm/FMbuffers_reg[1][0][1]} .original_name {{FMbuffers[1][0][1]}}}
catch {set_db {inst:proj_fm/FMbuffers_reg[1][2][0]} .original_name {{FMbuffers[1][2][0]}}}
catch {set_db {inst:proj_fm/waddr_reg[3]} .original_name {{waddr[3]}}}
catch {set_db {inst:proj_fm/FMbuffers_reg[1][3][1]} .original_name {{FMbuffers[1][3][1]}}}
catch {set_db {inst:proj_fm/FMbuffers_reg[0][2][1]} .original_name {{FMbuffers[0][2][1]}}}
catch {set_db {inst:proj_fm/FMbuffers_reg[0][2][0]} .original_name {{FMbuffers[0][2][0]}}}
catch {set_db {inst:proj_fm/FMbuffers_reg[0][3][0]} .original_name {{FMbuffers[0][3][0]}}}
catch {set_db {inst:proj_fm/FMbuffers_reg[1][3][0]} .original_name {{FMbuffers[1][3][0]}}}
catch {set_db {inst:proj_fm/FMbuffers_reg[0][31][0]} .original_name {{FMbuffers[0][31][0]}}}
catch {set_db {inst:proj_fm/FMbuffers_reg[0][31][1]} .original_name {{FMbuffers[0][31][1]}}}
catch {set_db {inst:proj_fm/FMbuffers_reg[1][31][0]} .original_name {{FMbuffers[1][31][0]}}}
catch {set_db {inst:proj_fm/FMbuffers_reg[1][31][1]} .original_name {{FMbuffers[1][31][1]}}}
catch {set_db {inst:proj_fm/FMbuffers_reg[0][3][1]} .original_name {{FMbuffers[0][3][1]}}}
catch {set_db {inst:proj_fm/waddr_reg[2]} .original_name {{waddr[2]}}}
catch {set_db {inst:proj_fm/waddr_reg[1]} .original_name {{waddr[1]}}}
catch {set_db {inst:proj_fm/waddr_reg[0]} .original_name {{waddr[0]}}}
catch {set_db inst:proj_fm/wr_idx_reg .original_name wr_idx}
