catch {set_db port:proj_kmer_buffer/clk .original_name clk}
catch {set_db port:proj_kmer_buffer/rst_n .original_name rst_n}
catch {set_db {port:proj_kmer_buffer/in_data[1]} .original_name {in_data[1]}}
catch {set_db {port:proj_kmer_buffer/in_data[0]} .original_name {in_data[0]}}
catch {set_db port:proj_kmer_buffer/start_over .original_name start_over}
catch {set_db {port:proj_kmer_buffer/seed[31]} .original_name {seed[31]}}
catch {set_db {port:proj_kmer_buffer/seed[30]} .original_name {seed[30]}}
catch {set_db {port:proj_kmer_buffer/seed[29]} .original_name {seed[29]}}
catch {set_db {port:proj_kmer_buffer/seed[28]} .original_name {seed[28]}}
catch {set_db {port:proj_kmer_buffer/seed[27]} .original_name {seed[27]}}
catch {set_db {port:proj_kmer_buffer/seed[26]} .original_name {seed[26]}}
catch {set_db {port:proj_kmer_buffer/seed[25]} .original_name {seed[25]}}
catch {set_db {port:proj_kmer_buffer/seed[24]} .original_name {seed[24]}}
catch {set_db {port:proj_kmer_buffer/seed[23]} .original_name {seed[23]}}
catch {set_db {port:proj_kmer_buffer/seed[22]} .original_name {seed[22]}}
catch {set_db {port:proj_kmer_buffer/seed[21]} .original_name {seed[21]}}
catch {set_db {port:proj_kmer_buffer/seed[20]} .original_name {seed[20]}}
catch {set_db {port:proj_kmer_buffer/seed[19]} .original_name {seed[19]}}
catch {set_db {port:proj_kmer_buffer/seed[18]} .original_name {seed[18]}}
catch {set_db {port:proj_kmer_buffer/seed[17]} .original_name {seed[17]}}
catch {set_db {port:proj_kmer_buffer/seed[16]} .original_name {seed[16]}}
catch {set_db {port:proj_kmer_buffer/seed[15]} .original_name {seed[15]}}
catch {set_db {port:proj_kmer_buffer/seed[14]} .original_name {seed[14]}}
catch {set_db {port:proj_kmer_buffer/seed[13]} .original_name {seed[13]}}
catch {set_db {port:proj_kmer_buffer/seed[12]} .original_name {seed[12]}}
catch {set_db {port:proj_kmer_buffer/seed[11]} .original_name {seed[11]}}
catch {set_db {port:proj_kmer_buffer/seed[10]} .original_name {seed[10]}}
catch {set_db {port:proj_kmer_buffer/seed[9]} .original_name {seed[9]}}
catch {set_db {port:proj_kmer_buffer/seed[8]} .original_name {seed[8]}}
catch {set_db {port:proj_kmer_buffer/seed[7]} .original_name {seed[7]}}
catch {set_db {port:proj_kmer_buffer/seed[6]} .original_name {seed[6]}}
catch {set_db {port:proj_kmer_buffer/seed[5]} .original_name {seed[5]}}
catch {set_db {port:proj_kmer_buffer/seed[4]} .original_name {seed[4]}}
catch {set_db {port:proj_kmer_buffer/seed[3]} .original_name {seed[3]}}
catch {set_db {port:proj_kmer_buffer/seed[2]} .original_name {seed[2]}}
catch {set_db {port:proj_kmer_buffer/seed[1]} .original_name {seed[1]}}
catch {set_db {port:proj_kmer_buffer/seed[0]} .original_name {seed[0]}}
catch {set_db port:proj_kmer_buffer/full .original_name full}
catch {set_db {port:proj_kmer_buffer/signature[31]} .original_name {signature[31]}}
catch {set_db {port:proj_kmer_buffer/signature[30]} .original_name {signature[30]}}
catch {set_db {port:proj_kmer_buffer/signature[29]} .original_name {signature[29]}}
catch {set_db {port:proj_kmer_buffer/signature[28]} .original_name {signature[28]}}
catch {set_db {port:proj_kmer_buffer/signature[27]} .original_name {signature[27]}}
catch {set_db {port:proj_kmer_buffer/signature[26]} .original_name {signature[26]}}
catch {set_db {port:proj_kmer_buffer/signature[25]} .original_name {signature[25]}}
catch {set_db {port:proj_kmer_buffer/signature[24]} .original_name {signature[24]}}
catch {set_db {port:proj_kmer_buffer/signature[23]} .original_name {signature[23]}}
catch {set_db {port:proj_kmer_buffer/signature[22]} .original_name {signature[22]}}
catch {set_db {port:proj_kmer_buffer/signature[21]} .original_name {signature[21]}}
catch {set_db {port:proj_kmer_buffer/signature[20]} .original_name {signature[20]}}
catch {set_db {port:proj_kmer_buffer/signature[19]} .original_name {signature[19]}}
catch {set_db {port:proj_kmer_buffer/signature[18]} .original_name {signature[18]}}
catch {set_db {port:proj_kmer_buffer/signature[17]} .original_name {signature[17]}}
catch {set_db {port:proj_kmer_buffer/signature[16]} .original_name {signature[16]}}
catch {set_db {port:proj_kmer_buffer/signature[15]} .original_name {signature[15]}}
catch {set_db {port:proj_kmer_buffer/signature[14]} .original_name {signature[14]}}
catch {set_db {port:proj_kmer_buffer/signature[13]} .original_name {signature[13]}}
catch {set_db {port:proj_kmer_buffer/signature[12]} .original_name {signature[12]}}
catch {set_db {port:proj_kmer_buffer/signature[11]} .original_name {signature[11]}}
catch {set_db {port:proj_kmer_buffer/signature[10]} .original_name {signature[10]}}
catch {set_db {port:proj_kmer_buffer/signature[9]} .original_name {signature[9]}}
catch {set_db {port:proj_kmer_buffer/signature[8]} .original_name {signature[8]}}
catch {set_db {port:proj_kmer_buffer/signature[7]} .original_name {signature[7]}}
catch {set_db {port:proj_kmer_buffer/signature[6]} .original_name {signature[6]}}
catch {set_db {port:proj_kmer_buffer/signature[5]} .original_name {signature[5]}}
catch {set_db {port:proj_kmer_buffer/signature[4]} .original_name {signature[4]}}
catch {set_db {port:proj_kmer_buffer/signature[3]} .original_name {signature[3]}}
catch {set_db {port:proj_kmer_buffer/signature[2]} .original_name {signature[2]}}
catch {set_db {port:proj_kmer_buffer/signature[1]} .original_name {signature[1]}}
catch {set_db {port:proj_kmer_buffer/signature[0]} .original_name {signature[0]}}
catch {set_db {pin:proj_kmer_buffer/buffer_count_reg[3]/Q} .original_name {buffer_count[3]/q}}
catch {set_db {pin:proj_kmer_buffer/buffer_count_reg[2]/Q} .original_name {buffer_count[2]/q}}
catch {set_db {pin:proj_kmer_buffer/buffer_count_reg[1]/Q} .original_name {buffer_count[1]/q}}
catch {set_db {pin:proj_kmer_buffer/buffer_count_reg[0]/Q} .original_name {buffer_count[0]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[0]/Q} .original_name {kmer_buffer[0]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[1]/Q} .original_name {kmer_buffer[1]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[2]/Q} .original_name {kmer_buffer[2]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[3]/Q} .original_name {kmer_buffer[3]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[4]/Q} .original_name {kmer_buffer[4]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[5]/Q} .original_name {kmer_buffer[5]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[6]/Q} .original_name {kmer_buffer[6]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[7]/Q} .original_name {kmer_buffer[7]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[8]/Q} .original_name {kmer_buffer[8]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[9]/Q} .original_name {kmer_buffer[9]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[10]/Q} .original_name {kmer_buffer[10]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[11]/Q} .original_name {kmer_buffer[11]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[12]/Q} .original_name {kmer_buffer[12]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[13]/Q} .original_name {kmer_buffer[13]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[14]/Q} .original_name {kmer_buffer[14]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[15]/Q} .original_name {kmer_buffer[15]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[31]/Q} .original_name {kmer_buffer[31]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[25]/Q} .original_name {kmer_buffer[25]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[19]/Q} .original_name {kmer_buffer[19]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[20]/Q} .original_name {kmer_buffer[20]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[21]/Q} .original_name {kmer_buffer[21]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[22]/Q} .original_name {kmer_buffer[22]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[23]/Q} .original_name {kmer_buffer[23]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[24]/Q} .original_name {kmer_buffer[24]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[18]/Q} .original_name {kmer_buffer[18]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[26]/Q} .original_name {kmer_buffer[26]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[27]/Q} .original_name {kmer_buffer[27]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[28]/Q} .original_name {kmer_buffer[28]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[29]/Q} .original_name {kmer_buffer[29]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[30]/Q} .original_name {kmer_buffer[30]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[16]/Q} .original_name {kmer_buffer[16]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[17]/Q} .original_name {kmer_buffer[17]/q}}
catch {set_db {inst:proj_kmer_buffer/buffer_count_reg[3]} .original_name {{buffer_count[3]}}}
catch {set_db {inst:proj_kmer_buffer/buffer_count_reg[2]} .original_name {{buffer_count[2]}}}
catch {set_db {inst:proj_kmer_buffer/buffer_count_reg[1]} .original_name {{buffer_count[1]}}}
catch {set_db {inst:proj_kmer_buffer/buffer_count_reg[0]} .original_name {{buffer_count[0]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[0]} .original_name {{kmer_buffer[0]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[1]} .original_name {{kmer_buffer[1]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[2]} .original_name {{kmer_buffer[2]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[3]} .original_name {{kmer_buffer[3]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[4]} .original_name {{kmer_buffer[4]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[5]} .original_name {{kmer_buffer[5]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[6]} .original_name {{kmer_buffer[6]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[7]} .original_name {{kmer_buffer[7]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[8]} .original_name {{kmer_buffer[8]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[9]} .original_name {{kmer_buffer[9]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[10]} .original_name {{kmer_buffer[10]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[11]} .original_name {{kmer_buffer[11]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[12]} .original_name {{kmer_buffer[12]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[13]} .original_name {{kmer_buffer[13]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[14]} .original_name {{kmer_buffer[14]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[15]} .original_name {{kmer_buffer[15]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[31]} .original_name {{kmer_buffer[31]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[25]} .original_name {{kmer_buffer[25]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[19]} .original_name {{kmer_buffer[19]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[20]} .original_name {{kmer_buffer[20]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[21]} .original_name {{kmer_buffer[21]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[22]} .original_name {{kmer_buffer[22]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[23]} .original_name {{kmer_buffer[23]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[24]} .original_name {{kmer_buffer[24]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[18]} .original_name {{kmer_buffer[18]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[26]} .original_name {{kmer_buffer[26]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[27]} .original_name {{kmer_buffer[27]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[28]} .original_name {{kmer_buffer[28]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[29]} .original_name {{kmer_buffer[29]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[30]} .original_name {{kmer_buffer[30]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[16]} .original_name {{kmer_buffer[16]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[17]} .original_name {{kmer_buffer[17]}}}
