
//input ports
add mapped point in_fragment[63] in_fragment[63] -type PI PI
add mapped point in_fragment[62] in_fragment[62] -type PI PI
add mapped point in_fragment[61] in_fragment[61] -type PI PI
add mapped point in_fragment[60] in_fragment[60] -type PI PI
add mapped point in_fragment[59] in_fragment[59] -type PI PI
add mapped point in_fragment[58] in_fragment[58] -type PI PI
add mapped point in_fragment[57] in_fragment[57] -type PI PI
add mapped point in_fragment[56] in_fragment[56] -type PI PI
add mapped point in_fragment[55] in_fragment[55] -type PI PI
add mapped point in_fragment[54] in_fragment[54] -type PI PI
add mapped point in_fragment[53] in_fragment[53] -type PI PI
add mapped point in_fragment[52] in_fragment[52] -type PI PI
add mapped point in_fragment[51] in_fragment[51] -type PI PI
add mapped point in_fragment[50] in_fragment[50] -type PI PI
add mapped point in_fragment[49] in_fragment[49] -type PI PI
add mapped point in_fragment[48] in_fragment[48] -type PI PI
add mapped point in_fragment[47] in_fragment[47] -type PI PI
add mapped point in_fragment[46] in_fragment[46] -type PI PI
add mapped point in_fragment[45] in_fragment[45] -type PI PI
add mapped point in_fragment[44] in_fragment[44] -type PI PI
add mapped point in_fragment[43] in_fragment[43] -type PI PI
add mapped point in_fragment[42] in_fragment[42] -type PI PI
add mapped point in_fragment[41] in_fragment[41] -type PI PI
add mapped point in_fragment[40] in_fragment[40] -type PI PI
add mapped point in_fragment[39] in_fragment[39] -type PI PI
add mapped point in_fragment[38] in_fragment[38] -type PI PI
add mapped point in_fragment[37] in_fragment[37] -type PI PI
add mapped point in_fragment[36] in_fragment[36] -type PI PI
add mapped point in_fragment[35] in_fragment[35] -type PI PI
add mapped point in_fragment[34] in_fragment[34] -type PI PI
add mapped point in_fragment[33] in_fragment[33] -type PI PI
add mapped point in_fragment[32] in_fragment[32] -type PI PI
add mapped point in_fragment[31] in_fragment[31] -type PI PI
add mapped point in_fragment[30] in_fragment[30] -type PI PI
add mapped point in_fragment[29] in_fragment[29] -type PI PI
add mapped point in_fragment[28] in_fragment[28] -type PI PI
add mapped point in_fragment[27] in_fragment[27] -type PI PI
add mapped point in_fragment[26] in_fragment[26] -type PI PI
add mapped point in_fragment[25] in_fragment[25] -type PI PI
add mapped point in_fragment[24] in_fragment[24] -type PI PI
add mapped point in_fragment[23] in_fragment[23] -type PI PI
add mapped point in_fragment[22] in_fragment[22] -type PI PI
add mapped point in_fragment[21] in_fragment[21] -type PI PI
add mapped point in_fragment[20] in_fragment[20] -type PI PI
add mapped point in_fragment[19] in_fragment[19] -type PI PI
add mapped point in_fragment[18] in_fragment[18] -type PI PI
add mapped point in_fragment[17] in_fragment[17] -type PI PI
add mapped point in_fragment[16] in_fragment[16] -type PI PI
add mapped point in_fragment[15] in_fragment[15] -type PI PI
add mapped point in_fragment[14] in_fragment[14] -type PI PI
add mapped point in_fragment[13] in_fragment[13] -type PI PI
add mapped point in_fragment[12] in_fragment[12] -type PI PI
add mapped point in_fragment[11] in_fragment[11] -type PI PI
add mapped point in_fragment[10] in_fragment[10] -type PI PI
add mapped point in_fragment[9] in_fragment[9] -type PI PI
add mapped point in_fragment[8] in_fragment[8] -type PI PI
add mapped point in_fragment[7] in_fragment[7] -type PI PI
add mapped point in_fragment[6] in_fragment[6] -type PI PI
add mapped point in_fragment[5] in_fragment[5] -type PI PI
add mapped point in_fragment[4] in_fragment[4] -type PI PI
add mapped point in_fragment[3] in_fragment[3] -type PI PI
add mapped point in_fragment[2] in_fragment[2] -type PI PI
add mapped point in_fragment[1] in_fragment[1] -type PI PI
add mapped point in_fragment[0] in_fragment[0] -type PI PI
add mapped point in_kmer_indices[0][8] in_kmer_indices[0][8] -type PI PI
add mapped point in_kmer_indices[0][7] in_kmer_indices[0][7] -type PI PI
add mapped point in_kmer_indices[0][6] in_kmer_indices[0][6] -type PI PI
add mapped point in_kmer_indices[0][5] in_kmer_indices[0][5] -type PI PI
add mapped point in_kmer_indices[0][4] in_kmer_indices[0][4] -type PI PI
add mapped point in_kmer_indices[0][3] in_kmer_indices[0][3] -type PI PI
add mapped point in_kmer_indices[0][2] in_kmer_indices[0][2] -type PI PI
add mapped point in_kmer_indices[0][1] in_kmer_indices[0][1] -type PI PI
add mapped point in_kmer_indices[0][0] in_kmer_indices[0][0] -type PI PI
add mapped point in_kmer_indices[1][8] in_kmer_indices[1][8] -type PI PI
add mapped point in_kmer_indices[1][7] in_kmer_indices[1][7] -type PI PI
add mapped point in_kmer_indices[1][6] in_kmer_indices[1][6] -type PI PI
add mapped point in_kmer_indices[1][5] in_kmer_indices[1][5] -type PI PI
add mapped point in_kmer_indices[1][4] in_kmer_indices[1][4] -type PI PI
add mapped point in_kmer_indices[1][3] in_kmer_indices[1][3] -type PI PI
add mapped point in_kmer_indices[1][2] in_kmer_indices[1][2] -type PI PI
add mapped point in_kmer_indices[1][1] in_kmer_indices[1][1] -type PI PI
add mapped point in_kmer_indices[1][0] in_kmer_indices[1][0] -type PI PI
add mapped point in_kmer_indices[2][8] in_kmer_indices[2][8] -type PI PI
add mapped point in_kmer_indices[2][7] in_kmer_indices[2][7] -type PI PI
add mapped point in_kmer_indices[2][6] in_kmer_indices[2][6] -type PI PI
add mapped point in_kmer_indices[2][5] in_kmer_indices[2][5] -type PI PI
add mapped point in_kmer_indices[2][4] in_kmer_indices[2][4] -type PI PI
add mapped point in_kmer_indices[2][3] in_kmer_indices[2][3] -type PI PI
add mapped point in_kmer_indices[2][2] in_kmer_indices[2][2] -type PI PI
add mapped point in_kmer_indices[2][1] in_kmer_indices[2][1] -type PI PI
add mapped point in_kmer_indices[2][0] in_kmer_indices[2][0] -type PI PI
add mapped point in_kmer_indices[3][8] in_kmer_indices[3][8] -type PI PI
add mapped point in_kmer_indices[3][7] in_kmer_indices[3][7] -type PI PI
add mapped point in_kmer_indices[3][6] in_kmer_indices[3][6] -type PI PI
add mapped point in_kmer_indices[3][5] in_kmer_indices[3][5] -type PI PI
add mapped point in_kmer_indices[3][4] in_kmer_indices[3][4] -type PI PI
add mapped point in_kmer_indices[3][3] in_kmer_indices[3][3] -type PI PI
add mapped point in_kmer_indices[3][2] in_kmer_indices[3][2] -type PI PI
add mapped point in_kmer_indices[3][1] in_kmer_indices[3][1] -type PI PI
add mapped point in_kmer_indices[3][0] in_kmer_indices[3][0] -type PI PI
add mapped point in_kmer_indices[4][8] in_kmer_indices[4][8] -type PI PI
add mapped point in_kmer_indices[4][7] in_kmer_indices[4][7] -type PI PI
add mapped point in_kmer_indices[4][6] in_kmer_indices[4][6] -type PI PI
add mapped point in_kmer_indices[4][5] in_kmer_indices[4][5] -type PI PI
add mapped point in_kmer_indices[4][4] in_kmer_indices[4][4] -type PI PI
add mapped point in_kmer_indices[4][3] in_kmer_indices[4][3] -type PI PI
add mapped point in_kmer_indices[4][2] in_kmer_indices[4][2] -type PI PI
add mapped point in_kmer_indices[4][1] in_kmer_indices[4][1] -type PI PI
add mapped point in_kmer_indices[4][0] in_kmer_indices[4][0] -type PI PI
add mapped point in_kmer_indices[5][8] in_kmer_indices[5][8] -type PI PI
add mapped point in_kmer_indices[5][7] in_kmer_indices[5][7] -type PI PI
add mapped point in_kmer_indices[5][6] in_kmer_indices[5][6] -type PI PI
add mapped point in_kmer_indices[5][5] in_kmer_indices[5][5] -type PI PI
add mapped point in_kmer_indices[5][4] in_kmer_indices[5][4] -type PI PI
add mapped point in_kmer_indices[5][3] in_kmer_indices[5][3] -type PI PI
add mapped point in_kmer_indices[5][2] in_kmer_indices[5][2] -type PI PI
add mapped point in_kmer_indices[5][1] in_kmer_indices[5][1] -type PI PI
add mapped point in_kmer_indices[5][0] in_kmer_indices[5][0] -type PI PI
add mapped point in_kmer_indices[6][8] in_kmer_indices[6][8] -type PI PI
add mapped point in_kmer_indices[6][7] in_kmer_indices[6][7] -type PI PI
add mapped point in_kmer_indices[6][6] in_kmer_indices[6][6] -type PI PI
add mapped point in_kmer_indices[6][5] in_kmer_indices[6][5] -type PI PI
add mapped point in_kmer_indices[6][4] in_kmer_indices[6][4] -type PI PI
add mapped point in_kmer_indices[6][3] in_kmer_indices[6][3] -type PI PI
add mapped point in_kmer_indices[6][2] in_kmer_indices[6][2] -type PI PI
add mapped point in_kmer_indices[6][1] in_kmer_indices[6][1] -type PI PI
add mapped point in_kmer_indices[6][0] in_kmer_indices[6][0] -type PI PI
add mapped point in_kmer_indices[7][8] in_kmer_indices[7][8] -type PI PI
add mapped point in_kmer_indices[7][7] in_kmer_indices[7][7] -type PI PI
add mapped point in_kmer_indices[7][6] in_kmer_indices[7][6] -type PI PI
add mapped point in_kmer_indices[7][5] in_kmer_indices[7][5] -type PI PI
add mapped point in_kmer_indices[7][4] in_kmer_indices[7][4] -type PI PI
add mapped point in_kmer_indices[7][3] in_kmer_indices[7][3] -type PI PI
add mapped point in_kmer_indices[7][2] in_kmer_indices[7][2] -type PI PI
add mapped point in_kmer_indices[7][1] in_kmer_indices[7][1] -type PI PI
add mapped point in_kmer_indices[7][0] in_kmer_indices[7][0] -type PI PI
add mapped point in_kmer_indices[8][8] in_kmer_indices[8][8] -type PI PI
add mapped point in_kmer_indices[8][7] in_kmer_indices[8][7] -type PI PI
add mapped point in_kmer_indices[8][6] in_kmer_indices[8][6] -type PI PI
add mapped point in_kmer_indices[8][5] in_kmer_indices[8][5] -type PI PI
add mapped point in_kmer_indices[8][4] in_kmer_indices[8][4] -type PI PI
add mapped point in_kmer_indices[8][3] in_kmer_indices[8][3] -type PI PI
add mapped point in_kmer_indices[8][2] in_kmer_indices[8][2] -type PI PI
add mapped point in_kmer_indices[8][1] in_kmer_indices[8][1] -type PI PI
add mapped point in_kmer_indices[8][0] in_kmer_indices[8][0] -type PI PI
add mapped point in_kmer_indices[9][8] in_kmer_indices[9][8] -type PI PI
add mapped point in_kmer_indices[9][7] in_kmer_indices[9][7] -type PI PI
add mapped point in_kmer_indices[9][6] in_kmer_indices[9][6] -type PI PI
add mapped point in_kmer_indices[9][5] in_kmer_indices[9][5] -type PI PI
add mapped point in_kmer_indices[9][4] in_kmer_indices[9][4] -type PI PI
add mapped point in_kmer_indices[9][3] in_kmer_indices[9][3] -type PI PI
add mapped point in_kmer_indices[9][2] in_kmer_indices[9][2] -type PI PI
add mapped point in_kmer_indices[9][1] in_kmer_indices[9][1] -type PI PI
add mapped point in_kmer_indices[9][0] in_kmer_indices[9][0] -type PI PI
add mapped point in_kmer_indices[10][8] in_kmer_indices[10][8] -type PI PI
add mapped point in_kmer_indices[10][7] in_kmer_indices[10][7] -type PI PI
add mapped point in_kmer_indices[10][6] in_kmer_indices[10][6] -type PI PI
add mapped point in_kmer_indices[10][5] in_kmer_indices[10][5] -type PI PI
add mapped point in_kmer_indices[10][4] in_kmer_indices[10][4] -type PI PI
add mapped point in_kmer_indices[10][3] in_kmer_indices[10][3] -type PI PI
add mapped point in_kmer_indices[10][2] in_kmer_indices[10][2] -type PI PI
add mapped point in_kmer_indices[10][1] in_kmer_indices[10][1] -type PI PI
add mapped point in_kmer_indices[10][0] in_kmer_indices[10][0] -type PI PI
add mapped point in_kmer_indices[11][8] in_kmer_indices[11][8] -type PI PI
add mapped point in_kmer_indices[11][7] in_kmer_indices[11][7] -type PI PI
add mapped point in_kmer_indices[11][6] in_kmer_indices[11][6] -type PI PI
add mapped point in_kmer_indices[11][5] in_kmer_indices[11][5] -type PI PI
add mapped point in_kmer_indices[11][4] in_kmer_indices[11][4] -type PI PI
add mapped point in_kmer_indices[11][3] in_kmer_indices[11][3] -type PI PI
add mapped point in_kmer_indices[11][2] in_kmer_indices[11][2] -type PI PI
add mapped point in_kmer_indices[11][1] in_kmer_indices[11][1] -type PI PI
add mapped point in_kmer_indices[11][0] in_kmer_indices[11][0] -type PI PI
add mapped point in_kmer_indices[12][8] in_kmer_indices[12][8] -type PI PI
add mapped point in_kmer_indices[12][7] in_kmer_indices[12][7] -type PI PI
add mapped point in_kmer_indices[12][6] in_kmer_indices[12][6] -type PI PI
add mapped point in_kmer_indices[12][5] in_kmer_indices[12][5] -type PI PI
add mapped point in_kmer_indices[12][4] in_kmer_indices[12][4] -type PI PI
add mapped point in_kmer_indices[12][3] in_kmer_indices[12][3] -type PI PI
add mapped point in_kmer_indices[12][2] in_kmer_indices[12][2] -type PI PI
add mapped point in_kmer_indices[12][1] in_kmer_indices[12][1] -type PI PI
add mapped point in_kmer_indices[12][0] in_kmer_indices[12][0] -type PI PI
add mapped point in_kmer_indices[13][8] in_kmer_indices[13][8] -type PI PI
add mapped point in_kmer_indices[13][7] in_kmer_indices[13][7] -type PI PI
add mapped point in_kmer_indices[13][6] in_kmer_indices[13][6] -type PI PI
add mapped point in_kmer_indices[13][5] in_kmer_indices[13][5] -type PI PI
add mapped point in_kmer_indices[13][4] in_kmer_indices[13][4] -type PI PI
add mapped point in_kmer_indices[13][3] in_kmer_indices[13][3] -type PI PI
add mapped point in_kmer_indices[13][2] in_kmer_indices[13][2] -type PI PI
add mapped point in_kmer_indices[13][1] in_kmer_indices[13][1] -type PI PI
add mapped point in_kmer_indices[13][0] in_kmer_indices[13][0] -type PI PI
add mapped point in_kmer_indices[14][8] in_kmer_indices[14][8] -type PI PI
add mapped point in_kmer_indices[14][7] in_kmer_indices[14][7] -type PI PI
add mapped point in_kmer_indices[14][6] in_kmer_indices[14][6] -type PI PI
add mapped point in_kmer_indices[14][5] in_kmer_indices[14][5] -type PI PI
add mapped point in_kmer_indices[14][4] in_kmer_indices[14][4] -type PI PI
add mapped point in_kmer_indices[14][3] in_kmer_indices[14][3] -type PI PI
add mapped point in_kmer_indices[14][2] in_kmer_indices[14][2] -type PI PI
add mapped point in_kmer_indices[14][1] in_kmer_indices[14][1] -type PI PI
add mapped point in_kmer_indices[14][0] in_kmer_indices[14][0] -type PI PI
add mapped point in_kmer_indices[15][8] in_kmer_indices[15][8] -type PI PI
add mapped point in_kmer_indices[15][7] in_kmer_indices[15][7] -type PI PI
add mapped point in_kmer_indices[15][6] in_kmer_indices[15][6] -type PI PI
add mapped point in_kmer_indices[15][5] in_kmer_indices[15][5] -type PI PI
add mapped point in_kmer_indices[15][4] in_kmer_indices[15][4] -type PI PI
add mapped point in_kmer_indices[15][3] in_kmer_indices[15][3] -type PI PI
add mapped point in_kmer_indices[15][2] in_kmer_indices[15][2] -type PI PI
add mapped point in_kmer_indices[15][1] in_kmer_indices[15][1] -type PI PI
add mapped point in_kmer_indices[15][0] in_kmer_indices[15][0] -type PI PI
add mapped point in_kmer_indices[16][8] in_kmer_indices[16][8] -type PI PI
add mapped point in_kmer_indices[16][7] in_kmer_indices[16][7] -type PI PI
add mapped point in_kmer_indices[16][6] in_kmer_indices[16][6] -type PI PI
add mapped point in_kmer_indices[16][5] in_kmer_indices[16][5] -type PI PI
add mapped point in_kmer_indices[16][4] in_kmer_indices[16][4] -type PI PI
add mapped point in_kmer_indices[16][3] in_kmer_indices[16][3] -type PI PI
add mapped point in_kmer_indices[16][2] in_kmer_indices[16][2] -type PI PI
add mapped point in_kmer_indices[16][1] in_kmer_indices[16][1] -type PI PI
add mapped point in_kmer_indices[16][0] in_kmer_indices[16][0] -type PI PI
add mapped point in_kmer_indices[17][8] in_kmer_indices[17][8] -type PI PI
add mapped point in_kmer_indices[17][7] in_kmer_indices[17][7] -type PI PI
add mapped point in_kmer_indices[17][6] in_kmer_indices[17][6] -type PI PI
add mapped point in_kmer_indices[17][5] in_kmer_indices[17][5] -type PI PI
add mapped point in_kmer_indices[17][4] in_kmer_indices[17][4] -type PI PI
add mapped point in_kmer_indices[17][3] in_kmer_indices[17][3] -type PI PI
add mapped point in_kmer_indices[17][2] in_kmer_indices[17][2] -type PI PI
add mapped point in_kmer_indices[17][1] in_kmer_indices[17][1] -type PI PI
add mapped point in_kmer_indices[17][0] in_kmer_indices[17][0] -type PI PI
add mapped point in_kmer_indices[18][8] in_kmer_indices[18][8] -type PI PI
add mapped point in_kmer_indices[18][7] in_kmer_indices[18][7] -type PI PI
add mapped point in_kmer_indices[18][6] in_kmer_indices[18][6] -type PI PI
add mapped point in_kmer_indices[18][5] in_kmer_indices[18][5] -type PI PI
add mapped point in_kmer_indices[18][4] in_kmer_indices[18][4] -type PI PI
add mapped point in_kmer_indices[18][3] in_kmer_indices[18][3] -type PI PI
add mapped point in_kmer_indices[18][2] in_kmer_indices[18][2] -type PI PI
add mapped point in_kmer_indices[18][1] in_kmer_indices[18][1] -type PI PI
add mapped point in_kmer_indices[18][0] in_kmer_indices[18][0] -type PI PI
add mapped point in_kmer_indices[19][8] in_kmer_indices[19][8] -type PI PI
add mapped point in_kmer_indices[19][7] in_kmer_indices[19][7] -type PI PI
add mapped point in_kmer_indices[19][6] in_kmer_indices[19][6] -type PI PI
add mapped point in_kmer_indices[19][5] in_kmer_indices[19][5] -type PI PI
add mapped point in_kmer_indices[19][4] in_kmer_indices[19][4] -type PI PI
add mapped point in_kmer_indices[19][3] in_kmer_indices[19][3] -type PI PI
add mapped point in_kmer_indices[19][2] in_kmer_indices[19][2] -type PI PI
add mapped point in_kmer_indices[19][1] in_kmer_indices[19][1] -type PI PI
add mapped point in_kmer_indices[19][0] in_kmer_indices[19][0] -type PI PI
add mapped point in_kmer_indices[20][8] in_kmer_indices[20][8] -type PI PI
add mapped point in_kmer_indices[20][7] in_kmer_indices[20][7] -type PI PI
add mapped point in_kmer_indices[20][6] in_kmer_indices[20][6] -type PI PI
add mapped point in_kmer_indices[20][5] in_kmer_indices[20][5] -type PI PI
add mapped point in_kmer_indices[20][4] in_kmer_indices[20][4] -type PI PI
add mapped point in_kmer_indices[20][3] in_kmer_indices[20][3] -type PI PI
add mapped point in_kmer_indices[20][2] in_kmer_indices[20][2] -type PI PI
add mapped point in_kmer_indices[20][1] in_kmer_indices[20][1] -type PI PI
add mapped point in_kmer_indices[20][0] in_kmer_indices[20][0] -type PI PI
add mapped point in_kmer_indices[21][8] in_kmer_indices[21][8] -type PI PI
add mapped point in_kmer_indices[21][7] in_kmer_indices[21][7] -type PI PI
add mapped point in_kmer_indices[21][6] in_kmer_indices[21][6] -type PI PI
add mapped point in_kmer_indices[21][5] in_kmer_indices[21][5] -type PI PI
add mapped point in_kmer_indices[21][4] in_kmer_indices[21][4] -type PI PI
add mapped point in_kmer_indices[21][3] in_kmer_indices[21][3] -type PI PI
add mapped point in_kmer_indices[21][2] in_kmer_indices[21][2] -type PI PI
add mapped point in_kmer_indices[21][1] in_kmer_indices[21][1] -type PI PI
add mapped point in_kmer_indices[21][0] in_kmer_indices[21][0] -type PI PI
add mapped point in_kmer_indices[22][8] in_kmer_indices[22][8] -type PI PI
add mapped point in_kmer_indices[22][7] in_kmer_indices[22][7] -type PI PI
add mapped point in_kmer_indices[22][6] in_kmer_indices[22][6] -type PI PI
add mapped point in_kmer_indices[22][5] in_kmer_indices[22][5] -type PI PI
add mapped point in_kmer_indices[22][4] in_kmer_indices[22][4] -type PI PI
add mapped point in_kmer_indices[22][3] in_kmer_indices[22][3] -type PI PI
add mapped point in_kmer_indices[22][2] in_kmer_indices[22][2] -type PI PI
add mapped point in_kmer_indices[22][1] in_kmer_indices[22][1] -type PI PI
add mapped point in_kmer_indices[22][0] in_kmer_indices[22][0] -type PI PI
add mapped point in_kmer_indices[23][8] in_kmer_indices[23][8] -type PI PI
add mapped point in_kmer_indices[23][7] in_kmer_indices[23][7] -type PI PI
add mapped point in_kmer_indices[23][6] in_kmer_indices[23][6] -type PI PI
add mapped point in_kmer_indices[23][5] in_kmer_indices[23][5] -type PI PI
add mapped point in_kmer_indices[23][4] in_kmer_indices[23][4] -type PI PI
add mapped point in_kmer_indices[23][3] in_kmer_indices[23][3] -type PI PI
add mapped point in_kmer_indices[23][2] in_kmer_indices[23][2] -type PI PI
add mapped point in_kmer_indices[23][1] in_kmer_indices[23][1] -type PI PI
add mapped point in_kmer_indices[23][0] in_kmer_indices[23][0] -type PI PI
add mapped point in_kmer_indices[24][8] in_kmer_indices[24][8] -type PI PI
add mapped point in_kmer_indices[24][7] in_kmer_indices[24][7] -type PI PI
add mapped point in_kmer_indices[24][6] in_kmer_indices[24][6] -type PI PI
add mapped point in_kmer_indices[24][5] in_kmer_indices[24][5] -type PI PI
add mapped point in_kmer_indices[24][4] in_kmer_indices[24][4] -type PI PI
add mapped point in_kmer_indices[24][3] in_kmer_indices[24][3] -type PI PI
add mapped point in_kmer_indices[24][2] in_kmer_indices[24][2] -type PI PI
add mapped point in_kmer_indices[24][1] in_kmer_indices[24][1] -type PI PI
add mapped point in_kmer_indices[24][0] in_kmer_indices[24][0] -type PI PI
add mapped point in_kmer_indices[25][8] in_kmer_indices[25][8] -type PI PI
add mapped point in_kmer_indices[25][7] in_kmer_indices[25][7] -type PI PI
add mapped point in_kmer_indices[25][6] in_kmer_indices[25][6] -type PI PI
add mapped point in_kmer_indices[25][5] in_kmer_indices[25][5] -type PI PI
add mapped point in_kmer_indices[25][4] in_kmer_indices[25][4] -type PI PI
add mapped point in_kmer_indices[25][3] in_kmer_indices[25][3] -type PI PI
add mapped point in_kmer_indices[25][2] in_kmer_indices[25][2] -type PI PI
add mapped point in_kmer_indices[25][1] in_kmer_indices[25][1] -type PI PI
add mapped point in_kmer_indices[25][0] in_kmer_indices[25][0] -type PI PI
add mapped point in_kmer_indices[26][8] in_kmer_indices[26][8] -type PI PI
add mapped point in_kmer_indices[26][7] in_kmer_indices[26][7] -type PI PI
add mapped point in_kmer_indices[26][6] in_kmer_indices[26][6] -type PI PI
add mapped point in_kmer_indices[26][5] in_kmer_indices[26][5] -type PI PI
add mapped point in_kmer_indices[26][4] in_kmer_indices[26][4] -type PI PI
add mapped point in_kmer_indices[26][3] in_kmer_indices[26][3] -type PI PI
add mapped point in_kmer_indices[26][2] in_kmer_indices[26][2] -type PI PI
add mapped point in_kmer_indices[26][1] in_kmer_indices[26][1] -type PI PI
add mapped point in_kmer_indices[26][0] in_kmer_indices[26][0] -type PI PI
add mapped point in_kmer_indices[27][8] in_kmer_indices[27][8] -type PI PI
add mapped point in_kmer_indices[27][7] in_kmer_indices[27][7] -type PI PI
add mapped point in_kmer_indices[27][6] in_kmer_indices[27][6] -type PI PI
add mapped point in_kmer_indices[27][5] in_kmer_indices[27][5] -type PI PI
add mapped point in_kmer_indices[27][4] in_kmer_indices[27][4] -type PI PI
add mapped point in_kmer_indices[27][3] in_kmer_indices[27][3] -type PI PI
add mapped point in_kmer_indices[27][2] in_kmer_indices[27][2] -type PI PI
add mapped point in_kmer_indices[27][1] in_kmer_indices[27][1] -type PI PI
add mapped point in_kmer_indices[27][0] in_kmer_indices[27][0] -type PI PI
add mapped point in_kmer_indices[28][8] in_kmer_indices[28][8] -type PI PI
add mapped point in_kmer_indices[28][7] in_kmer_indices[28][7] -type PI PI
add mapped point in_kmer_indices[28][6] in_kmer_indices[28][6] -type PI PI
add mapped point in_kmer_indices[28][5] in_kmer_indices[28][5] -type PI PI
add mapped point in_kmer_indices[28][4] in_kmer_indices[28][4] -type PI PI
add mapped point in_kmer_indices[28][3] in_kmer_indices[28][3] -type PI PI
add mapped point in_kmer_indices[28][2] in_kmer_indices[28][2] -type PI PI
add mapped point in_kmer_indices[28][1] in_kmer_indices[28][1] -type PI PI
add mapped point in_kmer_indices[28][0] in_kmer_indices[28][0] -type PI PI
add mapped point in_kmer_indices[29][8] in_kmer_indices[29][8] -type PI PI
add mapped point in_kmer_indices[29][7] in_kmer_indices[29][7] -type PI PI
add mapped point in_kmer_indices[29][6] in_kmer_indices[29][6] -type PI PI
add mapped point in_kmer_indices[29][5] in_kmer_indices[29][5] -type PI PI
add mapped point in_kmer_indices[29][4] in_kmer_indices[29][4] -type PI PI
add mapped point in_kmer_indices[29][3] in_kmer_indices[29][3] -type PI PI
add mapped point in_kmer_indices[29][2] in_kmer_indices[29][2] -type PI PI
add mapped point in_kmer_indices[29][1] in_kmer_indices[29][1] -type PI PI
add mapped point in_kmer_indices[29][0] in_kmer_indices[29][0] -type PI PI
add mapped point in_kmer_indices[30][8] in_kmer_indices[30][8] -type PI PI
add mapped point in_kmer_indices[30][7] in_kmer_indices[30][7] -type PI PI
add mapped point in_kmer_indices[30][6] in_kmer_indices[30][6] -type PI PI
add mapped point in_kmer_indices[30][5] in_kmer_indices[30][5] -type PI PI
add mapped point in_kmer_indices[30][4] in_kmer_indices[30][4] -type PI PI
add mapped point in_kmer_indices[30][3] in_kmer_indices[30][3] -type PI PI
add mapped point in_kmer_indices[30][2] in_kmer_indices[30][2] -type PI PI
add mapped point in_kmer_indices[30][1] in_kmer_indices[30][1] -type PI PI
add mapped point in_kmer_indices[30][0] in_kmer_indices[30][0] -type PI PI
add mapped point in_kmer_indices[31][8] in_kmer_indices[31][8] -type PI PI
add mapped point in_kmer_indices[31][7] in_kmer_indices[31][7] -type PI PI
add mapped point in_kmer_indices[31][6] in_kmer_indices[31][6] -type PI PI
add mapped point in_kmer_indices[31][5] in_kmer_indices[31][5] -type PI PI
add mapped point in_kmer_indices[31][4] in_kmer_indices[31][4] -type PI PI
add mapped point in_kmer_indices[31][3] in_kmer_indices[31][3] -type PI PI
add mapped point in_kmer_indices[31][2] in_kmer_indices[31][2] -type PI PI
add mapped point in_kmer_indices[31][1] in_kmer_indices[31][1] -type PI PI
add mapped point in_kmer_indices[31][0] in_kmer_indices[31][0] -type PI PI
add mapped point valid_indices valid_indices -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point clk clk -type PI PI

//output ports
add mapped point out_index[9] out_index[9] -type PO PO
add mapped point out_index[8] out_index[8] -type PO PO
add mapped point out_index[7] out_index[7] -type PO PO
add mapped point out_index[6] out_index[6] -type PO PO
add mapped point out_index[5] out_index[5] -type PO PO
add mapped point out_index[4] out_index[4] -type PO PO
add mapped point out_index[3] out_index[3] -type PO PO
add mapped point out_index[2] out_index[2] -type PO PO
add mapped point out_index[1] out_index[1] -type PO PO
add mapped point out_index[0] out_index[0] -type PO PO
add mapped point out_gfm[7] out_gfm[7] -type PO PO
add mapped point out_gfm[6] out_gfm[6] -type PO PO
add mapped point out_gfm[5] out_gfm[5] -type PO PO
add mapped point out_gfm[4] out_gfm[4] -type PO PO
add mapped point out_gfm[3] out_gfm[3] -type PO PO
add mapped point out_gfm[2] out_gfm[2] -type PO PO
add mapped point out_gfm[1] out_gfm[1] -type PO PO
add mapped point out_gfm[0] out_gfm[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point frag_parts_idx[0]/q frag_parts_idx_reg[0]/Q -type DFF DFF
add mapped point frag_parts_idx[1]/q frag_parts_idx_reg[1]/Q -type DFF DFF
add mapped point frag_parts_idx[2]/q frag_parts_idx_reg[2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[0][0]/q in_kmer_indices_r_reg[0][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[0][1]/q in_kmer_indices_r_reg[0][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[0][2]/q in_kmer_indices_r_reg[0][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[0][3]/q in_kmer_indices_r_reg[0][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[0][4]/q in_kmer_indices_r_reg[0][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[0][5]/q in_kmer_indices_r_reg[0][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[0][6]/q in_kmer_indices_r_reg[0][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[0][7]/q in_kmer_indices_r_reg[0][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[0][8]/q in_kmer_indices_r_reg[0][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[1][0]/q in_kmer_indices_r_reg[1][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[1][1]/q in_kmer_indices_r_reg[1][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[1][2]/q in_kmer_indices_r_reg[1][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[1][3]/q in_kmer_indices_r_reg[1][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[1][4]/q in_kmer_indices_r_reg[1][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[1][5]/q in_kmer_indices_r_reg[1][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[1][6]/q in_kmer_indices_r_reg[1][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[1][7]/q in_kmer_indices_r_reg[1][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[1][8]/q in_kmer_indices_r_reg[1][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[2][0]/q in_kmer_indices_r_reg[2][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[2][1]/q in_kmer_indices_r_reg[2][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[2][2]/q in_kmer_indices_r_reg[2][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[2][3]/q in_kmer_indices_r_reg[2][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[2][4]/q in_kmer_indices_r_reg[2][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[2][5]/q in_kmer_indices_r_reg[2][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[2][6]/q in_kmer_indices_r_reg[2][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[2][7]/q in_kmer_indices_r_reg[2][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[2][8]/q in_kmer_indices_r_reg[2][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[3][0]/q in_kmer_indices_r_reg[3][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[3][1]/q in_kmer_indices_r_reg[3][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[3][2]/q in_kmer_indices_r_reg[3][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[3][3]/q in_kmer_indices_r_reg[3][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[3][4]/q in_kmer_indices_r_reg[3][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[3][5]/q in_kmer_indices_r_reg[3][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[3][6]/q in_kmer_indices_r_reg[3][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[3][7]/q in_kmer_indices_r_reg[3][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[3][8]/q in_kmer_indices_r_reg[3][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[4][0]/q in_kmer_indices_r_reg[4][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[4][1]/q in_kmer_indices_r_reg[4][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[4][2]/q in_kmer_indices_r_reg[4][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[4][3]/q in_kmer_indices_r_reg[4][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[4][4]/q in_kmer_indices_r_reg[4][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[4][5]/q in_kmer_indices_r_reg[4][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[4][6]/q in_kmer_indices_r_reg[4][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[4][7]/q in_kmer_indices_r_reg[4][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[4][8]/q in_kmer_indices_r_reg[4][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[5][0]/q in_kmer_indices_r_reg[5][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[5][1]/q in_kmer_indices_r_reg[5][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[5][2]/q in_kmer_indices_r_reg[5][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[5][3]/q in_kmer_indices_r_reg[5][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[5][4]/q in_kmer_indices_r_reg[5][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[5][5]/q in_kmer_indices_r_reg[5][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[5][6]/q in_kmer_indices_r_reg[5][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[5][7]/q in_kmer_indices_r_reg[5][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[5][8]/q in_kmer_indices_r_reg[5][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[6][0]/q in_kmer_indices_r_reg[6][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[6][1]/q in_kmer_indices_r_reg[6][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[6][2]/q in_kmer_indices_r_reg[6][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[6][3]/q in_kmer_indices_r_reg[6][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[6][4]/q in_kmer_indices_r_reg[6][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[6][5]/q in_kmer_indices_r_reg[6][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[6][6]/q in_kmer_indices_r_reg[6][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[6][7]/q in_kmer_indices_r_reg[6][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[6][8]/q in_kmer_indices_r_reg[6][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[7][0]/q in_kmer_indices_r_reg[7][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[7][1]/q in_kmer_indices_r_reg[7][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[7][2]/q in_kmer_indices_r_reg[7][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[7][3]/q in_kmer_indices_r_reg[7][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[7][4]/q in_kmer_indices_r_reg[7][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[7][5]/q in_kmer_indices_r_reg[7][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[7][6]/q in_kmer_indices_r_reg[7][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[7][7]/q in_kmer_indices_r_reg[7][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[7][8]/q in_kmer_indices_r_reg[7][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[8][0]/q in_kmer_indices_r_reg[8][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[8][1]/q in_kmer_indices_r_reg[8][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[8][2]/q in_kmer_indices_r_reg[8][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[8][3]/q in_kmer_indices_r_reg[8][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[8][4]/q in_kmer_indices_r_reg[8][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[8][5]/q in_kmer_indices_r_reg[8][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[8][6]/q in_kmer_indices_r_reg[8][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[8][7]/q in_kmer_indices_r_reg[8][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[8][8]/q in_kmer_indices_r_reg[8][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[9][0]/q in_kmer_indices_r_reg[9][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[9][1]/q in_kmer_indices_r_reg[9][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[9][2]/q in_kmer_indices_r_reg[9][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[9][3]/q in_kmer_indices_r_reg[9][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[9][4]/q in_kmer_indices_r_reg[9][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[9][5]/q in_kmer_indices_r_reg[9][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[9][6]/q in_kmer_indices_r_reg[9][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[9][7]/q in_kmer_indices_r_reg[9][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[9][8]/q in_kmer_indices_r_reg[9][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[10][0]/q in_kmer_indices_r_reg[10][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[10][1]/q in_kmer_indices_r_reg[10][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[10][2]/q in_kmer_indices_r_reg[10][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[10][3]/q in_kmer_indices_r_reg[10][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[10][4]/q in_kmer_indices_r_reg[10][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[10][5]/q in_kmer_indices_r_reg[10][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[10][6]/q in_kmer_indices_r_reg[10][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[10][7]/q in_kmer_indices_r_reg[10][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[10][8]/q in_kmer_indices_r_reg[10][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[11][0]/q in_kmer_indices_r_reg[11][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[11][1]/q in_kmer_indices_r_reg[11][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[11][2]/q in_kmer_indices_r_reg[11][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[11][3]/q in_kmer_indices_r_reg[11][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[11][4]/q in_kmer_indices_r_reg[11][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[11][5]/q in_kmer_indices_r_reg[11][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[11][6]/q in_kmer_indices_r_reg[11][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[11][7]/q in_kmer_indices_r_reg[11][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[11][8]/q in_kmer_indices_r_reg[11][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[12][0]/q in_kmer_indices_r_reg[12][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[12][1]/q in_kmer_indices_r_reg[12][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[12][2]/q in_kmer_indices_r_reg[12][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[12][3]/q in_kmer_indices_r_reg[12][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[12][4]/q in_kmer_indices_r_reg[12][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[12][5]/q in_kmer_indices_r_reg[12][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[12][6]/q in_kmer_indices_r_reg[12][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[12][7]/q in_kmer_indices_r_reg[12][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[12][8]/q in_kmer_indices_r_reg[12][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[13][0]/q in_kmer_indices_r_reg[13][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[13][1]/q in_kmer_indices_r_reg[13][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[13][2]/q in_kmer_indices_r_reg[13][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[13][3]/q in_kmer_indices_r_reg[13][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[13][4]/q in_kmer_indices_r_reg[13][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[13][5]/q in_kmer_indices_r_reg[13][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[13][6]/q in_kmer_indices_r_reg[13][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[13][7]/q in_kmer_indices_r_reg[13][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[13][8]/q in_kmer_indices_r_reg[13][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[14][0]/q in_kmer_indices_r_reg[14][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[14][1]/q in_kmer_indices_r_reg[14][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[14][2]/q in_kmer_indices_r_reg[14][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[14][3]/q in_kmer_indices_r_reg[14][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[14][4]/q in_kmer_indices_r_reg[14][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[14][5]/q in_kmer_indices_r_reg[14][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[14][6]/q in_kmer_indices_r_reg[14][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[14][7]/q in_kmer_indices_r_reg[14][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[14][8]/q in_kmer_indices_r_reg[14][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[15][0]/q in_kmer_indices_r_reg[15][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[15][1]/q in_kmer_indices_r_reg[15][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[15][2]/q in_kmer_indices_r_reg[15][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[15][3]/q in_kmer_indices_r_reg[15][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[15][4]/q in_kmer_indices_r_reg[15][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[15][5]/q in_kmer_indices_r_reg[15][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[15][6]/q in_kmer_indices_r_reg[15][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[15][7]/q in_kmer_indices_r_reg[15][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[15][8]/q in_kmer_indices_r_reg[15][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[16][0]/q in_kmer_indices_r_reg[16][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[16][1]/q in_kmer_indices_r_reg[16][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[16][2]/q in_kmer_indices_r_reg[16][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[16][3]/q in_kmer_indices_r_reg[16][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[16][4]/q in_kmer_indices_r_reg[16][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[16][5]/q in_kmer_indices_r_reg[16][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[16][6]/q in_kmer_indices_r_reg[16][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[16][7]/q in_kmer_indices_r_reg[16][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[16][8]/q in_kmer_indices_r_reg[16][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[17][0]/q in_kmer_indices_r_reg[17][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[17][1]/q in_kmer_indices_r_reg[17][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[17][2]/q in_kmer_indices_r_reg[17][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[17][3]/q in_kmer_indices_r_reg[17][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[17][4]/q in_kmer_indices_r_reg[17][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[17][5]/q in_kmer_indices_r_reg[17][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[17][6]/q in_kmer_indices_r_reg[17][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[17][7]/q in_kmer_indices_r_reg[17][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[17][8]/q in_kmer_indices_r_reg[17][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[18][0]/q in_kmer_indices_r_reg[18][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[18][1]/q in_kmer_indices_r_reg[18][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[18][2]/q in_kmer_indices_r_reg[18][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[18][3]/q in_kmer_indices_r_reg[18][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[18][4]/q in_kmer_indices_r_reg[18][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[18][5]/q in_kmer_indices_r_reg[18][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[18][6]/q in_kmer_indices_r_reg[18][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[18][7]/q in_kmer_indices_r_reg[18][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[18][8]/q in_kmer_indices_r_reg[18][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[19][0]/q in_kmer_indices_r_reg[19][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[19][1]/q in_kmer_indices_r_reg[19][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[19][2]/q in_kmer_indices_r_reg[19][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[19][3]/q in_kmer_indices_r_reg[19][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[19][4]/q in_kmer_indices_r_reg[19][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[19][5]/q in_kmer_indices_r_reg[19][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[19][6]/q in_kmer_indices_r_reg[19][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[19][7]/q in_kmer_indices_r_reg[19][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[19][8]/q in_kmer_indices_r_reg[19][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[20][0]/q in_kmer_indices_r_reg[20][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[20][1]/q in_kmer_indices_r_reg[20][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[20][2]/q in_kmer_indices_r_reg[20][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[20][3]/q in_kmer_indices_r_reg[20][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[20][4]/q in_kmer_indices_r_reg[20][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[20][5]/q in_kmer_indices_r_reg[20][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[20][6]/q in_kmer_indices_r_reg[20][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[20][7]/q in_kmer_indices_r_reg[20][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[20][8]/q in_kmer_indices_r_reg[20][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[21][0]/q in_kmer_indices_r_reg[21][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[21][1]/q in_kmer_indices_r_reg[21][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[21][2]/q in_kmer_indices_r_reg[21][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[21][3]/q in_kmer_indices_r_reg[21][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[21][4]/q in_kmer_indices_r_reg[21][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[21][5]/q in_kmer_indices_r_reg[21][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[21][6]/q in_kmer_indices_r_reg[21][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[21][7]/q in_kmer_indices_r_reg[21][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[21][8]/q in_kmer_indices_r_reg[21][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[22][0]/q in_kmer_indices_r_reg[22][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[22][1]/q in_kmer_indices_r_reg[22][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[22][2]/q in_kmer_indices_r_reg[22][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[22][3]/q in_kmer_indices_r_reg[22][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[22][4]/q in_kmer_indices_r_reg[22][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[22][5]/q in_kmer_indices_r_reg[22][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[22][6]/q in_kmer_indices_r_reg[22][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[22][7]/q in_kmer_indices_r_reg[22][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[22][8]/q in_kmer_indices_r_reg[22][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[23][0]/q in_kmer_indices_r_reg[23][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[23][1]/q in_kmer_indices_r_reg[23][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[23][2]/q in_kmer_indices_r_reg[23][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[23][3]/q in_kmer_indices_r_reg[23][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[23][4]/q in_kmer_indices_r_reg[23][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[23][5]/q in_kmer_indices_r_reg[23][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[23][6]/q in_kmer_indices_r_reg[23][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[23][7]/q in_kmer_indices_r_reg[23][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[23][8]/q in_kmer_indices_r_reg[23][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[24][0]/q in_kmer_indices_r_reg[24][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[24][1]/q in_kmer_indices_r_reg[24][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[24][2]/q in_kmer_indices_r_reg[24][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[24][3]/q in_kmer_indices_r_reg[24][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[24][4]/q in_kmer_indices_r_reg[24][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[24][5]/q in_kmer_indices_r_reg[24][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[24][6]/q in_kmer_indices_r_reg[24][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[24][7]/q in_kmer_indices_r_reg[24][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[24][8]/q in_kmer_indices_r_reg[24][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[25][0]/q in_kmer_indices_r_reg[25][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[25][1]/q in_kmer_indices_r_reg[25][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[25][2]/q in_kmer_indices_r_reg[25][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[25][3]/q in_kmer_indices_r_reg[25][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[25][4]/q in_kmer_indices_r_reg[25][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[25][5]/q in_kmer_indices_r_reg[25][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[25][6]/q in_kmer_indices_r_reg[25][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[25][7]/q in_kmer_indices_r_reg[25][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[25][8]/q in_kmer_indices_r_reg[25][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[26][0]/q in_kmer_indices_r_reg[26][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[26][1]/q in_kmer_indices_r_reg[26][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[26][2]/q in_kmer_indices_r_reg[26][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[26][3]/q in_kmer_indices_r_reg[26][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[26][4]/q in_kmer_indices_r_reg[26][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[26][5]/q in_kmer_indices_r_reg[26][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[26][6]/q in_kmer_indices_r_reg[26][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[26][7]/q in_kmer_indices_r_reg[26][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[26][8]/q in_kmer_indices_r_reg[26][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[27][0]/q in_kmer_indices_r_reg[27][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[27][1]/q in_kmer_indices_r_reg[27][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[27][2]/q in_kmer_indices_r_reg[27][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[27][3]/q in_kmer_indices_r_reg[27][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[27][4]/q in_kmer_indices_r_reg[27][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[27][5]/q in_kmer_indices_r_reg[27][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[27][6]/q in_kmer_indices_r_reg[27][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[27][7]/q in_kmer_indices_r_reg[27][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[27][8]/q in_kmer_indices_r_reg[27][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[28][0]/q in_kmer_indices_r_reg[28][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[28][1]/q in_kmer_indices_r_reg[28][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[28][2]/q in_kmer_indices_r_reg[28][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[28][3]/q in_kmer_indices_r_reg[28][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[28][4]/q in_kmer_indices_r_reg[28][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[28][5]/q in_kmer_indices_r_reg[28][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[28][6]/q in_kmer_indices_r_reg[28][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[28][7]/q in_kmer_indices_r_reg[28][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[28][8]/q in_kmer_indices_r_reg[28][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[29][0]/q in_kmer_indices_r_reg[29][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[29][1]/q in_kmer_indices_r_reg[29][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[29][2]/q in_kmer_indices_r_reg[29][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[29][3]/q in_kmer_indices_r_reg[29][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[29][4]/q in_kmer_indices_r_reg[29][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[29][5]/q in_kmer_indices_r_reg[29][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[29][6]/q in_kmer_indices_r_reg[29][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[29][7]/q in_kmer_indices_r_reg[29][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[29][8]/q in_kmer_indices_r_reg[29][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[30][0]/q in_kmer_indices_r_reg[30][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[30][1]/q in_kmer_indices_r_reg[30][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[30][2]/q in_kmer_indices_r_reg[30][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[30][3]/q in_kmer_indices_r_reg[30][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[30][4]/q in_kmer_indices_r_reg[30][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[30][5]/q in_kmer_indices_r_reg[30][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[30][6]/q in_kmer_indices_r_reg[30][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[30][7]/q in_kmer_indices_r_reg[30][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[30][8]/q in_kmer_indices_r_reg[30][8]/Q -type DFF DFF
add mapped point in_kmer_indices_r[31][0]/q in_kmer_indices_r_reg[31][0]/Q -type DFF DFF
add mapped point in_kmer_indices_r[31][1]/q in_kmer_indices_r_reg[31][1]/Q -type DFF DFF
add mapped point in_kmer_indices_r[31][2]/q in_kmer_indices_r_reg[31][2]/Q -type DFF DFF
add mapped point in_kmer_indices_r[31][3]/q in_kmer_indices_r_reg[31][3]/Q -type DFF DFF
add mapped point in_kmer_indices_r[31][4]/q in_kmer_indices_r_reg[31][4]/Q -type DFF DFF
add mapped point in_kmer_indices_r[31][5]/q in_kmer_indices_r_reg[31][5]/Q -type DFF DFF
add mapped point in_kmer_indices_r[31][6]/q in_kmer_indices_r_reg[31][6]/Q -type DFF DFF
add mapped point in_kmer_indices_r[31][7]/q in_kmer_indices_r_reg[31][7]/Q -type DFF DFF
add mapped point in_kmer_indices_r[31][8]/q in_kmer_indices_r_reg[31][8]/Q -type DFF DFF
add mapped point indices_idx[0]/q indices_idx_reg[0]/Q -type DFF DFF
add mapped point indices_idx[1]/q indices_idx_reg[1]/Q -type DFF DFF
add mapped point indices_idx[2]/q indices_idx_reg[2]/Q -type DFF DFF
add mapped point indices_idx[3]/q indices_idx_reg[3]/Q -type DFF DFF
add mapped point indices_idx[4]/q indices_idx_reg[4]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
