
// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Aug 11 2024 13:41:26 UTC (Aug 11 2024 13:41:26 UTC)

// Verification Directory fv/proj_counter 

module proj_counter(index, finished_count, clk, rst_n, start);
  input clk, rst_n, start;
  output [6:0] index;
  output finished_count;
  wire clk, rst_n, start;
  wire [6:0] index;
  wire finished_count;
  wire count_enabled, n_0, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, start_prev;
  DFFRPQ_X1M_A9TL \out_index_reg[6] (.R (n_35), .CK (clk), .D (n_36),
       .Q (index[6]));
  NOR2_X1B_A9TL g414__2398(.A (n_32), .B (n_34), .Y (n_36));
  DFFRPQ_X1M_A9TL \out_index_reg[5] (.R (n_35), .CK (clk), .D (n_33),
       .Q (index[5]));
  AOI32_X1M_A9TL g416__5107(.A0 (n_30), .A1 (n_29), .A2 (n_27), .B0
       (index[6]), .B1 (n_28), .Y (n_34));
  NOR2_X1A_A9TL g417__6260(.A (n_32), .B (n_31), .Y (n_33));
  AOI32_X1M_A9TL g418__4319(.A0 (n_30), .A1 (n_29), .A2 (n_25), .B0
       (index[5]), .B1 (n_28), .Y (n_31));
  DFFRPQ_X1M_A9TL \out_index_reg[4] (.R (n_35), .CK (clk), .D (n_26),
       .Q (index[4]));
  XOR2_X0P7M_A9TL g420__8428(.A (n_24), .B (index[6]), .Y (n_27));
  NOR2_X1A_A9TL g421__5526(.A (n_32), .B (n_23), .Y (n_26));
  ADDH_X1M_A9TL g422__6783(.A (index[5]), .B (n_20), .CO (n_24), .S
       (n_25));
  AOI32_X1M_A9TL g423__3680(.A0 (n_30), .A1 (n_29), .A2 (n_21), .B0
       (index[4]), .B1 (n_28), .Y (n_23));
  DFFRPQ_X1M_A9TL \out_index_reg[3] (.R (n_35), .CK (clk), .D (n_22),
       .Q (index[3]));
  NOR2_X1A_A9TL g425__1617(.A (n_32), .B (n_19), .Y (n_22));
  ADDH_X1M_A9TL g426__2802(.A (index[4]), .B (n_16), .CO (n_20), .S
       (n_21));
  AOI32_X1M_A9TL g427__1705(.A0 (n_30), .A1 (n_29), .A2 (n_17), .B0
       (index[3]), .B1 (n_28), .Y (n_19));
  DFFRPQ_X1M_A9TL \out_index_reg[2] (.R (n_35), .CK (clk), .D (n_18),
       .Q (index[2]));
  NOR2_X1A_A9TL g429__5122(.A (n_32), .B (n_15), .Y (n_18));
  ADDH_X1M_A9TL g430__8246(.A (index[3]), .B (n_12), .CO (n_16), .S
       (n_17));
  AOI32_X1M_A9TL g431__7098(.A0 (n_30), .A1 (n_29), .A2 (n_13), .B0
       (index[2]), .B1 (n_28), .Y (n_15));
  DFFRPQ_X1M_A9TL \out_index_reg[1] (.R (n_35), .CK (clk), .D (n_14),
       .Q (index[1]));
  NOR2_X1A_A9TL g433__6131(.A (n_32), .B (n_11), .Y (n_14));
  ADDH_X1M_A9TL g434__1881(.A (index[2]), .B (n_8), .CO (n_12), .S
       (n_13));
  DFFRPQ_X1M_A9TL \out_index_reg[0] (.R (n_35), .CK (clk), .D (n_10),
       .Q (index[0]));
  AOI32_X1M_A9TL g435__5115(.A0 (n_30), .A1 (n_29), .A2 (n_9), .B0
       (index[1]), .B1 (n_28), .Y (n_11));
  NOR2_X1A_A9TL g437__7482(.A (n_32), .B (n_7), .Y (n_10));
  ADDH_X1M_A9TL g438__4733(.A (index[1]), .B (n_5), .CO (n_8), .S
       (n_9));
  AOI32_X1M_A9TL g439__6161(.A0 (n_30), .A1 (n_29), .A2 (n_6), .B0
       (index[0]), .B1 (n_28), .Y (n_7));
  SDFFRPQ_X1M_A9TL count_enabled_reg(.R (n_35), .CK (clk), .D (n_3),
       .SI (count_enabled), .SE (n_4), .Q (count_enabled));
  ADDH_X1M_A9TL g441__9315(.A (index[0]), .B (n_2), .CO (n_5), .S
       (n_6));
  AND2_X1M_A9TL g442__9945(.A (n_29), .B (n_3), .Y (n_4));
  INV_X1M_A9TL g444(.A (n_3), .Y (n_32));
  NOR2XB_X1M_A9TL g443__2883(.A (finished_count), .BN (count_enabled),
       .Y (n_2));
  NOR2_X1M_A9TL g445__2346(.A (n_35), .B (finished_count), .Y (n_3));
  AND4_X0P5M_A9TL g446__1666(.A (index[4]), .B (index[5]), .C
       (index[6]), .D (n_0), .Y (finished_count));
  INV_X1M_A9TL g447(.A (n_28), .Y (n_30));
  NOR2B_X2M_A9TL g448__7410(.AN (n_29), .B (count_enabled), .Y (n_28));
  DFFRPQN_X1M_A9TL start_prev_reg(.R (n_35), .CK (clk), .D (start), .QN
       (start_prev));
  AND4_X0P5M_A9TL g449__6417(.A (index[0]), .B (index[1]), .C
       (index[2]), .D (index[3]), .Y (n_0));
  NAND2_X1P4M_A9TL g451__5477(.A (start), .B (start_prev), .Y (n_29));
  INV_X1M_A9TL g452(.A (rst_n), .Y (n_35));
endmodule

