
// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Aug 10 2024 23:40:24 UTC (Aug 10 2024 23:40:24 UTC)

// Verification Directory fv/proj_top 

module RC_CG_MOD(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  PREICG_X0P5B_A9TR RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test),
       .ECK (ck_out));
endmodule

module proj_counter(index, finished_count, clk, rst_n, start);
  input clk, rst_n, start;
  output [14:0] index;
  output finished_count;
  wire clk, rst_n, start;
  wire [14:0] index;
  wire finished_count;
  wire [14:0] out_index;
  wire count_enabled, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_57, n_58, n_62, rc_gclk, rst_index, start_prev;
  RC_CG_MOD RC_CG_HIER_INST0(.enable (n_57), .ck_in (clk), .ck_out
       (rc_gclk), .test (1'b0));
  INV_X1M_A9TL g386(.A (n_62), .Y (finished_count));
  NAND3XXB_X1M_A9TL g417__2398(.A (n_58), .B (n_54), .CN
       (count_enabled), .Y (n_57));
  INV_X1M_A9TL g418(.A (rst_index), .Y (n_54));
  NAND2_X1A_A9TL g419__5107(.A (rst_n), .B (n_62), .Y (rst_index));
  NAND3_X1A_A9TL g420__6260(.A (n_53), .B (out_index[13]), .C
       (out_index[14]), .Y (n_62));
  AND4_X0P5M_A9TL g421__4319(.A (out_index[12]), .B (n_52), .C (n_50),
       .D (n_51), .Y (n_53));
  AND4_X0P5M_A9TL g422__8428(.A (out_index[0]), .B (out_index[1]), .C
       (out_index[2]), .D (out_index[3]), .Y (n_52));
  AND4_X0P5M_A9TL g423__5526(.A (out_index[8]), .B (out_index[9]), .C
       (out_index[10]), .D (out_index[11]), .Y (n_51));
  AND4_X0P5M_A9TL g424__6783(.A (out_index[4]), .B (out_index[5]), .C
       (out_index[6]), .D (out_index[7]), .Y (n_50));
  NAND2XB_X3M_A9TL g425__3680(.A (start), .BN (start_prev), .Y (n_58));
  DFFRPQ_X1M_A9TL \out_index_reg[14] (.R (n_0), .CK (rc_gclk), .D
       (n_49), .Q (out_index[14]));
  NOR3_X1M_A9TL g741__1617(.A (rst_index), .B (n_1), .C (n_47), .Y
       (n_49));
  DFFRPQ_X1M_A9TL \out_index_reg[13] (.R (n_0), .CK (rc_gclk), .D
       (n_48), .Q (out_index[13]));
  AND3_X1M_A9TL g743__2802(.A (n_2), .B (n_58), .C (n_46), .Y (n_48));
  XNOR2_X0P7M_A9TL g744__1705(.A (n_45), .B (out_index[14]), .Y (n_47));
  ADDH_X1M_A9TL g745__5122(.A (out_index[13]), .B (n_42), .CO (n_45),
       .S (n_46));
  DFFRPQ_X1M_A9TL \out_index_reg[12] (.R (n_0), .CK (rc_gclk), .D
       (n_44), .Q (out_index[12]));
  AND3_X1M_A9TL g747__8246(.A (n_2), .B (n_58), .C (n_43), .Y (n_44));
  ADDH_X1M_A9TL g748__7098(.A (out_index[12]), .B (n_39), .CO (n_42),
       .S (n_43));
  DFFRPQ_X1M_A9TL \out_index_reg[11] (.R (n_0), .CK (rc_gclk), .D
       (n_41), .Q (out_index[11]));
  AND3_X1M_A9TL g750__6131(.A (n_2), .B (n_58), .C (n_40), .Y (n_41));
  DFFRPQ_X1M_A9TL \out_index_reg[9] (.R (n_0), .CK (rc_gclk), .D
       (n_38), .Q (out_index[9]));
  ADDH_X1M_A9TL g752__1881(.A (out_index[11]), .B (n_33), .CO (n_39),
       .S (n_40));
  DFFRPQ_X1M_A9TL \out_index_reg[10] (.R (n_0), .CK (rc_gclk), .D
       (n_37), .Q (out_index[10]));
  NOR3_X1M_A9TL g754__5115(.A (rst_index), .B (n_1), .C (n_35), .Y
       (n_38));
  DFFRPQ_X1M_A9TL \out_index_reg[8] (.R (n_0), .CK (rc_gclk), .D
       (n_36), .Q (out_index[8]));
  AND3_X1M_A9TL g756__7482(.A (n_2), .B (n_58), .C (n_34), .Y (n_37));
  AND3_X1M_A9TL g757__4733(.A (n_2), .B (n_58), .C (n_32), .Y (n_36));
  XNOR2_X0P7M_A9TL g758__6161(.A (n_31), .B (out_index[9]), .Y (n_35));
  ADDH_X1M_A9TL g759__9315(.A (out_index[10]), .B (n_29), .CO (n_33),
       .S (n_34));
  ADDH_X1M_A9TL g760__9945(.A (out_index[8]), .B (n_28), .CO (n_31), .S
       (n_32));
  DFFRPQ_X1M_A9TL \out_index_reg[7] (.R (n_0), .CK (rc_gclk), .D
       (n_30), .Q (out_index[7]));
  AND3_X1M_A9TL g762__2883(.A (n_2), .B (n_58), .C (n_27), .Y (n_30));
  AND3_X1M_A9TL g763__2346(.A (n_28), .B (out_index[8]), .C
       (out_index[9]), .Y (n_29));
  ADDH_X1M_A9TL g764__1666(.A (out_index[7]), .B (n_24), .CO (n_28), .S
       (n_27));
  DFFRPQ_X1M_A9TL \out_index_reg[6] (.R (n_0), .CK (rc_gclk), .D
       (n_26), .Q (out_index[6]));
  AND3_X1M_A9TL g766__7410(.A (n_2), .B (n_58), .C (n_25), .Y (n_26));
  DFFRPQ_X1M_A9TL \out_index_reg[5] (.R (n_0), .CK (rc_gclk), .D
       (n_23), .Q (out_index[5]));
  ADDH_X1M_A9TL g768__6417(.A (out_index[6]), .B (n_20), .CO (n_24), .S
       (n_25));
  NOR3_X1M_A9TL g769__5477(.A (rst_index), .B (n_1), .C (n_21), .Y
       (n_23));
  DFFRPQ_X1M_A9TL \out_index_reg[4] (.R (n_0), .CK (rc_gclk), .D
       (n_22), .Q (out_index[4]));
  AND3_X1M_A9TL g771__2398(.A (n_2), .B (n_58), .C (n_19), .Y (n_22));
  XNOR2_X0P7M_A9TL g772__5107(.A (n_18), .B (out_index[5]), .Y (n_21));
  AND2_X1M_A9TL g773__6260(.A (out_index[5]), .B (n_16), .Y (n_20));
  ADDH_X1M_A9TL g774__4319(.A (out_index[4]), .B (n_15), .CO (n_18), .S
       (n_19));
  DFFRPQ_X1M_A9TL \out_index_reg[3] (.R (n_0), .CK (rc_gclk), .D
       (n_17), .Q (out_index[3]));
  AND3_X1M_A9TL g776__8428(.A (n_2), .B (n_58), .C (n_14), .Y (n_17));
  AND2_X1M_A9TL g777__5526(.A (out_index[4]), .B (n_15), .Y (n_16));
  ADDH_X1M_A9TL g778__6783(.A (out_index[3]), .B (n_11), .CO (n_15), .S
       (n_14));
  DFFRPQ_X1M_A9TL \out_index_reg[2] (.R (n_0), .CK (rc_gclk), .D
       (n_13), .Q (out_index[2]));
  AND3_X1M_A9TL g780__3680(.A (n_2), .B (n_58), .C (n_12), .Y (n_13));
  ADDH_X1M_A9TL g781__1617(.A (out_index[2]), .B (n_8), .CO (n_11), .S
       (n_12));
  DFFRPQ_X1M_A9TL \out_index_reg[1] (.R (n_0), .CK (rc_gclk), .D
       (n_10), .Q (out_index[1]));
  AND3_X1M_A9TL g783__2802(.A (n_2), .B (n_58), .C (n_9), .Y (n_10));
  ADDH_X1M_A9TL g784__1705(.A (out_index[1]), .B (n_5), .CO (n_8), .S
       (n_9));
  DFFRPQ_X1M_A9TL \out_index_reg[0] (.R (n_0), .CK (rc_gclk), .D (n_7),
       .Q (out_index[0]));
  AND3_X1M_A9TL g786__5122(.A (n_2), .B (n_58), .C (n_6), .Y (n_7));
  ADDH_X1M_A9TL g787__8246(.A (out_index[0]), .B (n_3), .CO (n_5), .S
       (n_6));
  SDFFRPQ_X1M_A9TL count_enabled_reg(.R (n_0), .CK (clk), .D
       (count_enabled), .SI (n_2), .SE (n_4), .Q (count_enabled));
  DFFRPQ_X1M_A9TL start_prev_reg(.R (n_0), .CK (clk), .D (start), .Q
       (start_prev));
  NAND2_X1B_A9TL g790__7098(.A (n_58), .B (n_2), .Y (n_4));
  AND2_X1M_A9TL g791__6131(.A (count_enabled), .B (n_62), .Y (n_3));
  INV_X2M_A9TL g792(.A (rst_index), .Y (n_2));
  INV_X2M_A9TL g793(.A (n_58), .Y (n_1));
  INV_X0P5M_A9TL g794(.A (rst_n), .Y (n_0));
endmodule

module proj_fm(clk, rst_n, in_wdata, chg_idx, frag_idx, out_rdata,
     out_wait);
  input clk, rst_n, chg_idx;
  input [1:0] in_wdata;
  input [15:0] frag_idx;
  output [511:0] out_rdata;
  output out_wait;
  wire clk, rst_n, chg_idx;
  wire [1:0] in_wdata;
  wire [15:0] frag_idx;
  wire [511:0] out_rdata;
  wire out_wait;
  wire [4:0] waddr;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_8, n_9;
  wire n_10, n_15, n_37, n_38, n_39, n_40, n_41, n_42;
  INV_X1M_A9TL g90061(.A (n_38), .Y (out_wait));
  OR2_X0P5M_A9TL g90062__1881(.A (chg_idx), .B (n_15), .Y (n_38));
  NAND4XXXB_X3M_A9TL g90063__5115(.A (waddr[3]), .B (waddr[4]), .C
       (waddr[2]), .DN (n_37), .Y (n_15));
  NAND2_X1A_A9TL g90064__7482(.A (waddr[1]), .B (waddr[0]), .Y (n_37));
  DFFRPQ_X1M_A9TL \waddr_reg[4] (.R (n_0), .CK (clk), .D (n_39), .Q
       (waddr[4]));
  DFFRPQ_X1M_A9TL \waddr_reg[3] (.R (n_0), .CK (clk), .D (n_40), .Q
       (waddr[3]));
  XOR2_X0P7M_A9TL g90170__9315(.A (n_8), .B (waddr[4]), .Y (n_10));
  ADDH_X1M_A9TL g90171__9945(.A (waddr[3]), .B (n_4), .CO (n_8), .S
       (n_9));
  DFFRPQ_X1M_A9TL \waddr_reg[2] (.R (n_0), .CK (clk), .D (n_41), .Q
       (waddr[2]));
  DFFRPQ_X1M_A9TL \waddr_reg[1] (.R (n_0), .CK (clk), .D (n_42), .Q
       (waddr[1]));
  ADDH_X1M_A9TL g90176__1666(.A (waddr[2]), .B (n_2), .CO (n_4), .S
       (n_5));
  SDFFRPQ_X1M_A9TL \waddr_reg[0] (.R (n_0), .CK (clk), .D (n_15), .SI
       (n_1), .SE (waddr[0]), .Q (waddr[0]));
  XOR2_X0P7M_A9TL g90178__7410(.A (waddr[1]), .B (waddr[0]), .Y (n_3));
  INV_X1M_A9TL g90179(.A (n_37), .Y (n_2));
  INV_X2M_A9TL g90180(.A (n_38), .Y (n_1));
  INV_X0P5M_A9TL g90181(.A (rst_n), .Y (n_0));
  AO21_X1M_A9TL g2(.A0 (n_15), .A1 (n_10), .B0 (n_1), .Y (n_39));
  AO21_X1M_A9TL g90182(.A0 (n_15), .A1 (n_9), .B0 (n_1), .Y (n_40));
  AO21_X1M_A9TL g90183(.A0 (n_15), .A1 (n_5), .B0 (n_1), .Y (n_41));
  OR2_X1P4M_A9TL g90184(.A (n_3), .B (n_1), .Y (n_42));
endmodule

module proj_top(clk, rst_n, in_data, start, out_fragment, out_wait);
  input clk, rst_n, start;
  input [1:0] in_data;
  output [255:0] out_fragment;
  output out_wait;
  wire clk, rst_n, start;
  wire [1:0] in_data;
  wire [255:0] out_fragment;
  wire out_wait;
  wire [14:0] counter_index;
  wire [511:0] fm_fragment;
  wire UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1,
       UNCONNECTED_HIER_Z2, UNCONNECTED_HIER_Z3, UNCONNECTED_HIER_Z4,
       UNCONNECTED_HIER_Z5, UNCONNECTED_HIER_Z6;
  wire UNCONNECTED_HIER_Z7, UNCONNECTED_HIER_Z8, UNCONNECTED_HIER_Z9,
       UNCONNECTED_HIER_Z10, UNCONNECTED_HIER_Z11,
       UNCONNECTED_HIER_Z12, UNCONNECTED_HIER_Z13, UNCONNECTED_HIER_Z14;
  wire UNCONNECTED_HIER_Z15, UNCONNECTED_HIER_Z16, counter_finished;
  assign out_fragment[0] = 1'b0;
  assign out_fragment[1] = 1'b0;
  assign out_fragment[2] = 1'b0;
  assign out_fragment[3] = 1'b0;
  assign out_fragment[4] = 1'b0;
  assign out_fragment[5] = 1'b0;
  assign out_fragment[6] = 1'b0;
  assign out_fragment[7] = 1'b0;
  assign out_fragment[8] = 1'b0;
  assign out_fragment[9] = 1'b0;
  assign out_fragment[10] = 1'b0;
  assign out_fragment[11] = 1'b0;
  assign out_fragment[12] = 1'b0;
  assign out_fragment[13] = 1'b0;
  assign out_fragment[14] = 1'b0;
  assign out_fragment[15] = 1'b0;
  assign out_fragment[16] = 1'b0;
  assign out_fragment[17] = 1'b0;
  assign out_fragment[18] = 1'b0;
  assign out_fragment[19] = 1'b0;
  assign out_fragment[20] = 1'b0;
  assign out_fragment[21] = 1'b0;
  assign out_fragment[22] = 1'b0;
  assign out_fragment[23] = 1'b0;
  assign out_fragment[24] = 1'b0;
  assign out_fragment[25] = 1'b0;
  assign out_fragment[26] = 1'b0;
  assign out_fragment[27] = 1'b0;
  assign out_fragment[28] = 1'b0;
  assign out_fragment[29] = 1'b0;
  assign out_fragment[30] = 1'b0;
  assign out_fragment[31] = 1'b0;
  assign out_fragment[32] = 1'b0;
  assign out_fragment[33] = 1'b0;
  assign out_fragment[34] = 1'b0;
  assign out_fragment[35] = 1'b0;
  assign out_fragment[36] = 1'b0;
  assign out_fragment[37] = 1'b0;
  assign out_fragment[38] = 1'b0;
  assign out_fragment[39] = 1'b0;
  assign out_fragment[40] = 1'b0;
  assign out_fragment[41] = 1'b0;
  assign out_fragment[42] = 1'b0;
  assign out_fragment[43] = 1'b0;
  assign out_fragment[44] = 1'b0;
  assign out_fragment[45] = 1'b0;
  assign out_fragment[46] = 1'b0;
  assign out_fragment[47] = 1'b0;
  assign out_fragment[48] = 1'b0;
  assign out_fragment[49] = 1'b0;
  assign out_fragment[50] = 1'b0;
  assign out_fragment[51] = 1'b0;
  assign out_fragment[52] = 1'b0;
  assign out_fragment[53] = 1'b0;
  assign out_fragment[54] = 1'b0;
  assign out_fragment[55] = 1'b0;
  assign out_fragment[56] = 1'b0;
  assign out_fragment[57] = 1'b0;
  assign out_fragment[58] = 1'b0;
  assign out_fragment[59] = 1'b0;
  assign out_fragment[60] = 1'b0;
  assign out_fragment[61] = 1'b0;
  assign out_fragment[62] = 1'b0;
  assign out_fragment[63] = 1'b0;
  assign out_fragment[64] = 1'b0;
  assign out_fragment[65] = 1'b0;
  assign out_fragment[66] = 1'b0;
  assign out_fragment[67] = 1'b0;
  assign out_fragment[68] = 1'b0;
  assign out_fragment[69] = 1'b0;
  assign out_fragment[70] = 1'b0;
  assign out_fragment[71] = 1'b0;
  assign out_fragment[72] = 1'b0;
  assign out_fragment[73] = 1'b0;
  assign out_fragment[74] = 1'b0;
  assign out_fragment[75] = 1'b0;
  assign out_fragment[76] = 1'b0;
  assign out_fragment[77] = 1'b0;
  assign out_fragment[78] = 1'b0;
  assign out_fragment[79] = 1'b0;
  assign out_fragment[80] = 1'b0;
  assign out_fragment[81] = 1'b0;
  assign out_fragment[82] = 1'b0;
  assign out_fragment[83] = 1'b0;
  assign out_fragment[84] = 1'b0;
  assign out_fragment[85] = 1'b0;
  assign out_fragment[86] = 1'b0;
  assign out_fragment[87] = 1'b0;
  assign out_fragment[88] = 1'b0;
  assign out_fragment[89] = 1'b0;
  assign out_fragment[90] = 1'b0;
  assign out_fragment[91] = 1'b0;
  assign out_fragment[92] = 1'b0;
  assign out_fragment[93] = 1'b0;
  assign out_fragment[94] = 1'b0;
  assign out_fragment[95] = 1'b0;
  assign out_fragment[96] = 1'b0;
  assign out_fragment[97] = 1'b0;
  assign out_fragment[98] = 1'b0;
  assign out_fragment[99] = 1'b0;
  assign out_fragment[100] = 1'b0;
  assign out_fragment[101] = 1'b0;
  assign out_fragment[102] = 1'b0;
  assign out_fragment[103] = 1'b0;
  assign out_fragment[104] = 1'b0;
  assign out_fragment[105] = 1'b0;
  assign out_fragment[106] = 1'b0;
  assign out_fragment[107] = 1'b0;
  assign out_fragment[108] = 1'b0;
  assign out_fragment[109] = 1'b0;
  assign out_fragment[110] = 1'b0;
  assign out_fragment[111] = 1'b0;
  assign out_fragment[112] = 1'b0;
  assign out_fragment[113] = 1'b0;
  assign out_fragment[114] = 1'b0;
  assign out_fragment[115] = 1'b0;
  assign out_fragment[116] = 1'b0;
  assign out_fragment[117] = 1'b0;
  assign out_fragment[118] = 1'b0;
  assign out_fragment[119] = 1'b0;
  assign out_fragment[120] = 1'b0;
  assign out_fragment[121] = 1'b0;
  assign out_fragment[122] = 1'b0;
  assign out_fragment[123] = 1'b0;
  assign out_fragment[124] = 1'b0;
  assign out_fragment[125] = 1'b0;
  assign out_fragment[126] = 1'b0;
  assign out_fragment[127] = 1'b0;
  assign out_fragment[128] = 1'b0;
  assign out_fragment[129] = 1'b0;
  assign out_fragment[130] = 1'b0;
  assign out_fragment[131] = 1'b0;
  assign out_fragment[132] = 1'b0;
  assign out_fragment[133] = 1'b0;
  assign out_fragment[134] = 1'b0;
  assign out_fragment[135] = 1'b0;
  assign out_fragment[136] = 1'b0;
  assign out_fragment[137] = 1'b0;
  assign out_fragment[138] = 1'b0;
  assign out_fragment[139] = 1'b0;
  assign out_fragment[140] = 1'b0;
  assign out_fragment[141] = 1'b0;
  assign out_fragment[142] = 1'b0;
  assign out_fragment[143] = 1'b0;
  assign out_fragment[144] = 1'b0;
  assign out_fragment[145] = 1'b0;
  assign out_fragment[146] = 1'b0;
  assign out_fragment[147] = 1'b0;
  assign out_fragment[148] = 1'b0;
  assign out_fragment[149] = 1'b0;
  assign out_fragment[150] = 1'b0;
  assign out_fragment[151] = 1'b0;
  assign out_fragment[152] = 1'b0;
  assign out_fragment[153] = 1'b0;
  assign out_fragment[154] = 1'b0;
  assign out_fragment[155] = 1'b0;
  assign out_fragment[156] = 1'b0;
  assign out_fragment[157] = 1'b0;
  assign out_fragment[158] = 1'b0;
  assign out_fragment[159] = 1'b0;
  assign out_fragment[160] = 1'b0;
  assign out_fragment[161] = 1'b0;
  assign out_fragment[162] = 1'b0;
  assign out_fragment[163] = 1'b0;
  assign out_fragment[164] = 1'b0;
  assign out_fragment[165] = 1'b0;
  assign out_fragment[166] = 1'b0;
  assign out_fragment[167] = 1'b0;
  assign out_fragment[168] = 1'b0;
  assign out_fragment[169] = 1'b0;
  assign out_fragment[170] = 1'b0;
  assign out_fragment[171] = 1'b0;
  assign out_fragment[172] = 1'b0;
  assign out_fragment[173] = 1'b0;
  assign out_fragment[174] = 1'b0;
  assign out_fragment[175] = 1'b0;
  assign out_fragment[176] = 1'b0;
  assign out_fragment[177] = 1'b0;
  assign out_fragment[178] = 1'b0;
  assign out_fragment[179] = 1'b0;
  assign out_fragment[180] = 1'b0;
  assign out_fragment[181] = 1'b0;
  assign out_fragment[182] = 1'b0;
  assign out_fragment[183] = 1'b0;
  assign out_fragment[184] = 1'b0;
  assign out_fragment[185] = 1'b0;
  assign out_fragment[186] = 1'b0;
  assign out_fragment[187] = 1'b0;
  assign out_fragment[188] = 1'b0;
  assign out_fragment[189] = 1'b0;
  assign out_fragment[190] = 1'b0;
  assign out_fragment[191] = 1'b0;
  assign out_fragment[192] = 1'b0;
  assign out_fragment[193] = 1'b0;
  assign out_fragment[194] = 1'b0;
  assign out_fragment[195] = 1'b0;
  assign out_fragment[196] = 1'b0;
  assign out_fragment[197] = 1'b0;
  assign out_fragment[198] = 1'b0;
  assign out_fragment[199] = 1'b0;
  assign out_fragment[200] = 1'b0;
  assign out_fragment[201] = 1'b0;
  assign out_fragment[202] = 1'b0;
  assign out_fragment[203] = 1'b0;
  assign out_fragment[204] = 1'b0;
  assign out_fragment[205] = 1'b0;
  assign out_fragment[206] = 1'b0;
  assign out_fragment[207] = 1'b0;
  assign out_fragment[208] = 1'b0;
  assign out_fragment[209] = 1'b0;
  assign out_fragment[210] = 1'b0;
  assign out_fragment[211] = 1'b0;
  assign out_fragment[212] = 1'b0;
  assign out_fragment[213] = 1'b0;
  assign out_fragment[214] = 1'b0;
  assign out_fragment[215] = 1'b0;
  assign out_fragment[216] = 1'b0;
  assign out_fragment[217] = 1'b0;
  assign out_fragment[218] = 1'b0;
  assign out_fragment[219] = 1'b0;
  assign out_fragment[220] = 1'b0;
  assign out_fragment[221] = 1'b0;
  assign out_fragment[222] = 1'b0;
  assign out_fragment[223] = 1'b0;
  assign out_fragment[224] = 1'b0;
  assign out_fragment[225] = 1'b0;
  assign out_fragment[226] = 1'b0;
  assign out_fragment[227] = 1'b0;
  assign out_fragment[228] = 1'b0;
  assign out_fragment[229] = 1'b0;
  assign out_fragment[230] = 1'b0;
  assign out_fragment[231] = 1'b0;
  assign out_fragment[232] = 1'b0;
  assign out_fragment[233] = 1'b0;
  assign out_fragment[234] = 1'b0;
  assign out_fragment[235] = 1'b0;
  assign out_fragment[236] = 1'b0;
  assign out_fragment[237] = 1'b0;
  assign out_fragment[238] = 1'b0;
  assign out_fragment[239] = 1'b0;
  assign out_fragment[240] = 1'b0;
  assign out_fragment[241] = 1'b0;
  assign out_fragment[242] = 1'b0;
  assign out_fragment[243] = 1'b0;
  assign out_fragment[244] = 1'b0;
  assign out_fragment[245] = 1'b0;
  assign out_fragment[246] = 1'b0;
  assign out_fragment[247] = 1'b0;
  assign out_fragment[248] = 1'b0;
  assign out_fragment[249] = 1'b0;
  assign out_fragment[250] = 1'b0;
  assign out_fragment[251] = 1'b0;
  assign out_fragment[252] = 1'b0;
  assign out_fragment[253] = 1'b0;
  assign out_fragment[254] = 1'b0;
  assign out_fragment[255] = 1'b0;
  proj_counter u_counter(.index (counter_index), .finished_count
       (counter_finished), .clk (clk), .rst_n (rst_n), .start (start));
  proj_fm u_fm(.clk (clk), .rst_n (rst_n), .in_wdata
       ({UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z}), .chg_idx
       (counter_finished), .frag_idx ({UNCONNECTED_HIER_Z16,
       UNCONNECTED_HIER_Z15, UNCONNECTED_HIER_Z14,
       UNCONNECTED_HIER_Z13, UNCONNECTED_HIER_Z12,
       UNCONNECTED_HIER_Z11, UNCONNECTED_HIER_Z10, UNCONNECTED_HIER_Z9,
       UNCONNECTED_HIER_Z8, UNCONNECTED_HIER_Z7, UNCONNECTED_HIER_Z6,
       UNCONNECTED_HIER_Z5, UNCONNECTED_HIER_Z4, UNCONNECTED_HIER_Z3,
       UNCONNECTED_HIER_Z2, UNCONNECTED_HIER_Z1}), .out_rdata
       (fm_fragment), .out_wait (out_wait));
endmodule

