catch {set_db port:proj_top/clk .original_name clk}
catch {set_db port:proj_top/rst_n .original_name rst_n}
catch {set_db {port:proj_top/in_data[1]} .original_name {in_data[1]}}
catch {set_db {port:proj_top/in_data[0]} .original_name {in_data[0]}}
catch {set_db port:proj_top/start .original_name start}
catch {set_db {port:proj_top/out_fragment[255]} .original_name {out_fragment[255]}}
catch {set_db {port:proj_top/out_fragment[254]} .original_name {out_fragment[254]}}
catch {set_db {port:proj_top/out_fragment[253]} .original_name {out_fragment[253]}}
catch {set_db {port:proj_top/out_fragment[252]} .original_name {out_fragment[252]}}
catch {set_db {port:proj_top/out_fragment[251]} .original_name {out_fragment[251]}}
catch {set_db {port:proj_top/out_fragment[250]} .original_name {out_fragment[250]}}
catch {set_db {port:proj_top/out_fragment[249]} .original_name {out_fragment[249]}}
catch {set_db {port:proj_top/out_fragment[248]} .original_name {out_fragment[248]}}
catch {set_db {port:proj_top/out_fragment[247]} .original_name {out_fragment[247]}}
catch {set_db {port:proj_top/out_fragment[246]} .original_name {out_fragment[246]}}
catch {set_db {port:proj_top/out_fragment[245]} .original_name {out_fragment[245]}}
catch {set_db {port:proj_top/out_fragment[244]} .original_name {out_fragment[244]}}
catch {set_db {port:proj_top/out_fragment[243]} .original_name {out_fragment[243]}}
catch {set_db {port:proj_top/out_fragment[242]} .original_name {out_fragment[242]}}
catch {set_db {port:proj_top/out_fragment[241]} .original_name {out_fragment[241]}}
catch {set_db {port:proj_top/out_fragment[240]} .original_name {out_fragment[240]}}
catch {set_db {port:proj_top/out_fragment[239]} .original_name {out_fragment[239]}}
catch {set_db {port:proj_top/out_fragment[238]} .original_name {out_fragment[238]}}
catch {set_db {port:proj_top/out_fragment[237]} .original_name {out_fragment[237]}}
catch {set_db {port:proj_top/out_fragment[236]} .original_name {out_fragment[236]}}
catch {set_db {port:proj_top/out_fragment[235]} .original_name {out_fragment[235]}}
catch {set_db {port:proj_top/out_fragment[234]} .original_name {out_fragment[234]}}
catch {set_db {port:proj_top/out_fragment[233]} .original_name {out_fragment[233]}}
catch {set_db {port:proj_top/out_fragment[232]} .original_name {out_fragment[232]}}
catch {set_db {port:proj_top/out_fragment[231]} .original_name {out_fragment[231]}}
catch {set_db {port:proj_top/out_fragment[230]} .original_name {out_fragment[230]}}
catch {set_db {port:proj_top/out_fragment[229]} .original_name {out_fragment[229]}}
catch {set_db {port:proj_top/out_fragment[228]} .original_name {out_fragment[228]}}
catch {set_db {port:proj_top/out_fragment[227]} .original_name {out_fragment[227]}}
catch {set_db {port:proj_top/out_fragment[226]} .original_name {out_fragment[226]}}
catch {set_db {port:proj_top/out_fragment[225]} .original_name {out_fragment[225]}}
catch {set_db {port:proj_top/out_fragment[224]} .original_name {out_fragment[224]}}
catch {set_db {port:proj_top/out_fragment[223]} .original_name {out_fragment[223]}}
catch {set_db {port:proj_top/out_fragment[222]} .original_name {out_fragment[222]}}
catch {set_db {port:proj_top/out_fragment[221]} .original_name {out_fragment[221]}}
catch {set_db {port:proj_top/out_fragment[220]} .original_name {out_fragment[220]}}
catch {set_db {port:proj_top/out_fragment[219]} .original_name {out_fragment[219]}}
catch {set_db {port:proj_top/out_fragment[218]} .original_name {out_fragment[218]}}
catch {set_db {port:proj_top/out_fragment[217]} .original_name {out_fragment[217]}}
catch {set_db {port:proj_top/out_fragment[216]} .original_name {out_fragment[216]}}
catch {set_db {port:proj_top/out_fragment[215]} .original_name {out_fragment[215]}}
catch {set_db {port:proj_top/out_fragment[214]} .original_name {out_fragment[214]}}
catch {set_db {port:proj_top/out_fragment[213]} .original_name {out_fragment[213]}}
catch {set_db {port:proj_top/out_fragment[212]} .original_name {out_fragment[212]}}
catch {set_db {port:proj_top/out_fragment[211]} .original_name {out_fragment[211]}}
catch {set_db {port:proj_top/out_fragment[210]} .original_name {out_fragment[210]}}
catch {set_db {port:proj_top/out_fragment[209]} .original_name {out_fragment[209]}}
catch {set_db {port:proj_top/out_fragment[208]} .original_name {out_fragment[208]}}
catch {set_db {port:proj_top/out_fragment[207]} .original_name {out_fragment[207]}}
catch {set_db {port:proj_top/out_fragment[206]} .original_name {out_fragment[206]}}
catch {set_db {port:proj_top/out_fragment[205]} .original_name {out_fragment[205]}}
catch {set_db {port:proj_top/out_fragment[204]} .original_name {out_fragment[204]}}
catch {set_db {port:proj_top/out_fragment[203]} .original_name {out_fragment[203]}}
catch {set_db {port:proj_top/out_fragment[202]} .original_name {out_fragment[202]}}
catch {set_db {port:proj_top/out_fragment[201]} .original_name {out_fragment[201]}}
catch {set_db {port:proj_top/out_fragment[200]} .original_name {out_fragment[200]}}
catch {set_db {port:proj_top/out_fragment[199]} .original_name {out_fragment[199]}}
catch {set_db {port:proj_top/out_fragment[198]} .original_name {out_fragment[198]}}
catch {set_db {port:proj_top/out_fragment[197]} .original_name {out_fragment[197]}}
catch {set_db {port:proj_top/out_fragment[196]} .original_name {out_fragment[196]}}
catch {set_db {port:proj_top/out_fragment[195]} .original_name {out_fragment[195]}}
catch {set_db {port:proj_top/out_fragment[194]} .original_name {out_fragment[194]}}
catch {set_db {port:proj_top/out_fragment[193]} .original_name {out_fragment[193]}}
catch {set_db {port:proj_top/out_fragment[192]} .original_name {out_fragment[192]}}
catch {set_db {port:proj_top/out_fragment[191]} .original_name {out_fragment[191]}}
catch {set_db {port:proj_top/out_fragment[190]} .original_name {out_fragment[190]}}
catch {set_db {port:proj_top/out_fragment[189]} .original_name {out_fragment[189]}}
catch {set_db {port:proj_top/out_fragment[188]} .original_name {out_fragment[188]}}
catch {set_db {port:proj_top/out_fragment[187]} .original_name {out_fragment[187]}}
catch {set_db {port:proj_top/out_fragment[186]} .original_name {out_fragment[186]}}
catch {set_db {port:proj_top/out_fragment[185]} .original_name {out_fragment[185]}}
catch {set_db {port:proj_top/out_fragment[184]} .original_name {out_fragment[184]}}
catch {set_db {port:proj_top/out_fragment[183]} .original_name {out_fragment[183]}}
catch {set_db {port:proj_top/out_fragment[182]} .original_name {out_fragment[182]}}
catch {set_db {port:proj_top/out_fragment[181]} .original_name {out_fragment[181]}}
catch {set_db {port:proj_top/out_fragment[180]} .original_name {out_fragment[180]}}
catch {set_db {port:proj_top/out_fragment[179]} .original_name {out_fragment[179]}}
catch {set_db {port:proj_top/out_fragment[178]} .original_name {out_fragment[178]}}
catch {set_db {port:proj_top/out_fragment[177]} .original_name {out_fragment[177]}}
catch {set_db {port:proj_top/out_fragment[176]} .original_name {out_fragment[176]}}
catch {set_db {port:proj_top/out_fragment[175]} .original_name {out_fragment[175]}}
catch {set_db {port:proj_top/out_fragment[174]} .original_name {out_fragment[174]}}
catch {set_db {port:proj_top/out_fragment[173]} .original_name {out_fragment[173]}}
catch {set_db {port:proj_top/out_fragment[172]} .original_name {out_fragment[172]}}
catch {set_db {port:proj_top/out_fragment[171]} .original_name {out_fragment[171]}}
catch {set_db {port:proj_top/out_fragment[170]} .original_name {out_fragment[170]}}
catch {set_db {port:proj_top/out_fragment[169]} .original_name {out_fragment[169]}}
catch {set_db {port:proj_top/out_fragment[168]} .original_name {out_fragment[168]}}
catch {set_db {port:proj_top/out_fragment[167]} .original_name {out_fragment[167]}}
catch {set_db {port:proj_top/out_fragment[166]} .original_name {out_fragment[166]}}
catch {set_db {port:proj_top/out_fragment[165]} .original_name {out_fragment[165]}}
catch {set_db {port:proj_top/out_fragment[164]} .original_name {out_fragment[164]}}
catch {set_db {port:proj_top/out_fragment[163]} .original_name {out_fragment[163]}}
catch {set_db {port:proj_top/out_fragment[162]} .original_name {out_fragment[162]}}
catch {set_db {port:proj_top/out_fragment[161]} .original_name {out_fragment[161]}}
catch {set_db {port:proj_top/out_fragment[160]} .original_name {out_fragment[160]}}
catch {set_db {port:proj_top/out_fragment[159]} .original_name {out_fragment[159]}}
catch {set_db {port:proj_top/out_fragment[158]} .original_name {out_fragment[158]}}
catch {set_db {port:proj_top/out_fragment[157]} .original_name {out_fragment[157]}}
catch {set_db {port:proj_top/out_fragment[156]} .original_name {out_fragment[156]}}
catch {set_db {port:proj_top/out_fragment[155]} .original_name {out_fragment[155]}}
catch {set_db {port:proj_top/out_fragment[154]} .original_name {out_fragment[154]}}
catch {set_db {port:proj_top/out_fragment[153]} .original_name {out_fragment[153]}}
catch {set_db {port:proj_top/out_fragment[152]} .original_name {out_fragment[152]}}
catch {set_db {port:proj_top/out_fragment[151]} .original_name {out_fragment[151]}}
catch {set_db {port:proj_top/out_fragment[150]} .original_name {out_fragment[150]}}
catch {set_db {port:proj_top/out_fragment[149]} .original_name {out_fragment[149]}}
catch {set_db {port:proj_top/out_fragment[148]} .original_name {out_fragment[148]}}
catch {set_db {port:proj_top/out_fragment[147]} .original_name {out_fragment[147]}}
catch {set_db {port:proj_top/out_fragment[146]} .original_name {out_fragment[146]}}
catch {set_db {port:proj_top/out_fragment[145]} .original_name {out_fragment[145]}}
catch {set_db {port:proj_top/out_fragment[144]} .original_name {out_fragment[144]}}
catch {set_db {port:proj_top/out_fragment[143]} .original_name {out_fragment[143]}}
catch {set_db {port:proj_top/out_fragment[142]} .original_name {out_fragment[142]}}
catch {set_db {port:proj_top/out_fragment[141]} .original_name {out_fragment[141]}}
catch {set_db {port:proj_top/out_fragment[140]} .original_name {out_fragment[140]}}
catch {set_db {port:proj_top/out_fragment[139]} .original_name {out_fragment[139]}}
catch {set_db {port:proj_top/out_fragment[138]} .original_name {out_fragment[138]}}
catch {set_db {port:proj_top/out_fragment[137]} .original_name {out_fragment[137]}}
catch {set_db {port:proj_top/out_fragment[136]} .original_name {out_fragment[136]}}
catch {set_db {port:proj_top/out_fragment[135]} .original_name {out_fragment[135]}}
catch {set_db {port:proj_top/out_fragment[134]} .original_name {out_fragment[134]}}
catch {set_db {port:proj_top/out_fragment[133]} .original_name {out_fragment[133]}}
catch {set_db {port:proj_top/out_fragment[132]} .original_name {out_fragment[132]}}
catch {set_db {port:proj_top/out_fragment[131]} .original_name {out_fragment[131]}}
catch {set_db {port:proj_top/out_fragment[130]} .original_name {out_fragment[130]}}
catch {set_db {port:proj_top/out_fragment[129]} .original_name {out_fragment[129]}}
catch {set_db {port:proj_top/out_fragment[128]} .original_name {out_fragment[128]}}
catch {set_db {port:proj_top/out_fragment[127]} .original_name {out_fragment[127]}}
catch {set_db {port:proj_top/out_fragment[126]} .original_name {out_fragment[126]}}
catch {set_db {port:proj_top/out_fragment[125]} .original_name {out_fragment[125]}}
catch {set_db {port:proj_top/out_fragment[124]} .original_name {out_fragment[124]}}
catch {set_db {port:proj_top/out_fragment[123]} .original_name {out_fragment[123]}}
catch {set_db {port:proj_top/out_fragment[122]} .original_name {out_fragment[122]}}
catch {set_db {port:proj_top/out_fragment[121]} .original_name {out_fragment[121]}}
catch {set_db {port:proj_top/out_fragment[120]} .original_name {out_fragment[120]}}
catch {set_db {port:proj_top/out_fragment[119]} .original_name {out_fragment[119]}}
catch {set_db {port:proj_top/out_fragment[118]} .original_name {out_fragment[118]}}
catch {set_db {port:proj_top/out_fragment[117]} .original_name {out_fragment[117]}}
catch {set_db {port:proj_top/out_fragment[116]} .original_name {out_fragment[116]}}
catch {set_db {port:proj_top/out_fragment[115]} .original_name {out_fragment[115]}}
catch {set_db {port:proj_top/out_fragment[114]} .original_name {out_fragment[114]}}
catch {set_db {port:proj_top/out_fragment[113]} .original_name {out_fragment[113]}}
catch {set_db {port:proj_top/out_fragment[112]} .original_name {out_fragment[112]}}
catch {set_db {port:proj_top/out_fragment[111]} .original_name {out_fragment[111]}}
catch {set_db {port:proj_top/out_fragment[110]} .original_name {out_fragment[110]}}
catch {set_db {port:proj_top/out_fragment[109]} .original_name {out_fragment[109]}}
catch {set_db {port:proj_top/out_fragment[108]} .original_name {out_fragment[108]}}
catch {set_db {port:proj_top/out_fragment[107]} .original_name {out_fragment[107]}}
catch {set_db {port:proj_top/out_fragment[106]} .original_name {out_fragment[106]}}
catch {set_db {port:proj_top/out_fragment[105]} .original_name {out_fragment[105]}}
catch {set_db {port:proj_top/out_fragment[104]} .original_name {out_fragment[104]}}
catch {set_db {port:proj_top/out_fragment[103]} .original_name {out_fragment[103]}}
catch {set_db {port:proj_top/out_fragment[102]} .original_name {out_fragment[102]}}
catch {set_db {port:proj_top/out_fragment[101]} .original_name {out_fragment[101]}}
catch {set_db {port:proj_top/out_fragment[100]} .original_name {out_fragment[100]}}
catch {set_db {port:proj_top/out_fragment[99]} .original_name {out_fragment[99]}}
catch {set_db {port:proj_top/out_fragment[98]} .original_name {out_fragment[98]}}
catch {set_db {port:proj_top/out_fragment[97]} .original_name {out_fragment[97]}}
catch {set_db {port:proj_top/out_fragment[96]} .original_name {out_fragment[96]}}
catch {set_db {port:proj_top/out_fragment[95]} .original_name {out_fragment[95]}}
catch {set_db {port:proj_top/out_fragment[94]} .original_name {out_fragment[94]}}
catch {set_db {port:proj_top/out_fragment[93]} .original_name {out_fragment[93]}}
catch {set_db {port:proj_top/out_fragment[92]} .original_name {out_fragment[92]}}
catch {set_db {port:proj_top/out_fragment[91]} .original_name {out_fragment[91]}}
catch {set_db {port:proj_top/out_fragment[90]} .original_name {out_fragment[90]}}
catch {set_db {port:proj_top/out_fragment[89]} .original_name {out_fragment[89]}}
catch {set_db {port:proj_top/out_fragment[88]} .original_name {out_fragment[88]}}
catch {set_db {port:proj_top/out_fragment[87]} .original_name {out_fragment[87]}}
catch {set_db {port:proj_top/out_fragment[86]} .original_name {out_fragment[86]}}
catch {set_db {port:proj_top/out_fragment[85]} .original_name {out_fragment[85]}}
catch {set_db {port:proj_top/out_fragment[84]} .original_name {out_fragment[84]}}
catch {set_db {port:proj_top/out_fragment[83]} .original_name {out_fragment[83]}}
catch {set_db {port:proj_top/out_fragment[82]} .original_name {out_fragment[82]}}
catch {set_db {port:proj_top/out_fragment[81]} .original_name {out_fragment[81]}}
catch {set_db {port:proj_top/out_fragment[80]} .original_name {out_fragment[80]}}
catch {set_db {port:proj_top/out_fragment[79]} .original_name {out_fragment[79]}}
catch {set_db {port:proj_top/out_fragment[78]} .original_name {out_fragment[78]}}
catch {set_db {port:proj_top/out_fragment[77]} .original_name {out_fragment[77]}}
catch {set_db {port:proj_top/out_fragment[76]} .original_name {out_fragment[76]}}
catch {set_db {port:proj_top/out_fragment[75]} .original_name {out_fragment[75]}}
catch {set_db {port:proj_top/out_fragment[74]} .original_name {out_fragment[74]}}
catch {set_db {port:proj_top/out_fragment[73]} .original_name {out_fragment[73]}}
catch {set_db {port:proj_top/out_fragment[72]} .original_name {out_fragment[72]}}
catch {set_db {port:proj_top/out_fragment[71]} .original_name {out_fragment[71]}}
catch {set_db {port:proj_top/out_fragment[70]} .original_name {out_fragment[70]}}
catch {set_db {port:proj_top/out_fragment[69]} .original_name {out_fragment[69]}}
catch {set_db {port:proj_top/out_fragment[68]} .original_name {out_fragment[68]}}
catch {set_db {port:proj_top/out_fragment[67]} .original_name {out_fragment[67]}}
catch {set_db {port:proj_top/out_fragment[66]} .original_name {out_fragment[66]}}
catch {set_db {port:proj_top/out_fragment[65]} .original_name {out_fragment[65]}}
catch {set_db {port:proj_top/out_fragment[64]} .original_name {out_fragment[64]}}
catch {set_db {port:proj_top/out_fragment[63]} .original_name {out_fragment[63]}}
catch {set_db {port:proj_top/out_fragment[62]} .original_name {out_fragment[62]}}
catch {set_db {port:proj_top/out_fragment[61]} .original_name {out_fragment[61]}}
catch {set_db {port:proj_top/out_fragment[60]} .original_name {out_fragment[60]}}
catch {set_db {port:proj_top/out_fragment[59]} .original_name {out_fragment[59]}}
catch {set_db {port:proj_top/out_fragment[58]} .original_name {out_fragment[58]}}
catch {set_db {port:proj_top/out_fragment[57]} .original_name {out_fragment[57]}}
catch {set_db {port:proj_top/out_fragment[56]} .original_name {out_fragment[56]}}
catch {set_db {port:proj_top/out_fragment[55]} .original_name {out_fragment[55]}}
catch {set_db {port:proj_top/out_fragment[54]} .original_name {out_fragment[54]}}
catch {set_db {port:proj_top/out_fragment[53]} .original_name {out_fragment[53]}}
catch {set_db {port:proj_top/out_fragment[52]} .original_name {out_fragment[52]}}
catch {set_db {port:proj_top/out_fragment[51]} .original_name {out_fragment[51]}}
catch {set_db {port:proj_top/out_fragment[50]} .original_name {out_fragment[50]}}
catch {set_db {port:proj_top/out_fragment[49]} .original_name {out_fragment[49]}}
catch {set_db {port:proj_top/out_fragment[48]} .original_name {out_fragment[48]}}
catch {set_db {port:proj_top/out_fragment[47]} .original_name {out_fragment[47]}}
catch {set_db {port:proj_top/out_fragment[46]} .original_name {out_fragment[46]}}
catch {set_db {port:proj_top/out_fragment[45]} .original_name {out_fragment[45]}}
catch {set_db {port:proj_top/out_fragment[44]} .original_name {out_fragment[44]}}
catch {set_db {port:proj_top/out_fragment[43]} .original_name {out_fragment[43]}}
catch {set_db {port:proj_top/out_fragment[42]} .original_name {out_fragment[42]}}
catch {set_db {port:proj_top/out_fragment[41]} .original_name {out_fragment[41]}}
catch {set_db {port:proj_top/out_fragment[40]} .original_name {out_fragment[40]}}
catch {set_db {port:proj_top/out_fragment[39]} .original_name {out_fragment[39]}}
catch {set_db {port:proj_top/out_fragment[38]} .original_name {out_fragment[38]}}
catch {set_db {port:proj_top/out_fragment[37]} .original_name {out_fragment[37]}}
catch {set_db {port:proj_top/out_fragment[36]} .original_name {out_fragment[36]}}
catch {set_db {port:proj_top/out_fragment[35]} .original_name {out_fragment[35]}}
catch {set_db {port:proj_top/out_fragment[34]} .original_name {out_fragment[34]}}
catch {set_db {port:proj_top/out_fragment[33]} .original_name {out_fragment[33]}}
catch {set_db {port:proj_top/out_fragment[32]} .original_name {out_fragment[32]}}
catch {set_db {port:proj_top/out_fragment[31]} .original_name {out_fragment[31]}}
catch {set_db {port:proj_top/out_fragment[30]} .original_name {out_fragment[30]}}
catch {set_db {port:proj_top/out_fragment[29]} .original_name {out_fragment[29]}}
catch {set_db {port:proj_top/out_fragment[28]} .original_name {out_fragment[28]}}
catch {set_db {port:proj_top/out_fragment[27]} .original_name {out_fragment[27]}}
catch {set_db {port:proj_top/out_fragment[26]} .original_name {out_fragment[26]}}
catch {set_db {port:proj_top/out_fragment[25]} .original_name {out_fragment[25]}}
catch {set_db {port:proj_top/out_fragment[24]} .original_name {out_fragment[24]}}
catch {set_db {port:proj_top/out_fragment[23]} .original_name {out_fragment[23]}}
catch {set_db {port:proj_top/out_fragment[22]} .original_name {out_fragment[22]}}
catch {set_db {port:proj_top/out_fragment[21]} .original_name {out_fragment[21]}}
catch {set_db {port:proj_top/out_fragment[20]} .original_name {out_fragment[20]}}
catch {set_db {port:proj_top/out_fragment[19]} .original_name {out_fragment[19]}}
catch {set_db {port:proj_top/out_fragment[18]} .original_name {out_fragment[18]}}
catch {set_db {port:proj_top/out_fragment[17]} .original_name {out_fragment[17]}}
catch {set_db {port:proj_top/out_fragment[16]} .original_name {out_fragment[16]}}
catch {set_db {port:proj_top/out_fragment[15]} .original_name {out_fragment[15]}}
catch {set_db {port:proj_top/out_fragment[14]} .original_name {out_fragment[14]}}
catch {set_db {port:proj_top/out_fragment[13]} .original_name {out_fragment[13]}}
catch {set_db {port:proj_top/out_fragment[12]} .original_name {out_fragment[12]}}
catch {set_db {port:proj_top/out_fragment[11]} .original_name {out_fragment[11]}}
catch {set_db {port:proj_top/out_fragment[10]} .original_name {out_fragment[10]}}
catch {set_db {port:proj_top/out_fragment[9]} .original_name {out_fragment[9]}}
catch {set_db {port:proj_top/out_fragment[8]} .original_name {out_fragment[8]}}
catch {set_db {port:proj_top/out_fragment[7]} .original_name {out_fragment[7]}}
catch {set_db {port:proj_top/out_fragment[6]} .original_name {out_fragment[6]}}
catch {set_db {port:proj_top/out_fragment[5]} .original_name {out_fragment[5]}}
catch {set_db {port:proj_top/out_fragment[4]} .original_name {out_fragment[4]}}
catch {set_db {port:proj_top/out_fragment[3]} .original_name {out_fragment[3]}}
catch {set_db {port:proj_top/out_fragment[2]} .original_name {out_fragment[2]}}
catch {set_db {port:proj_top/out_fragment[1]} .original_name {out_fragment[1]}}
catch {set_db {port:proj_top/out_fragment[0]} .original_name {out_fragment[0]}}
catch {set_db port:proj_top/out_wait .original_name out_wait}
catch {set_db {pin:proj_top/u_counter/out_index_reg[14]/Q} .original_name {u_counter/out_index[14]/q}}
catch {set_db {pin:proj_top/u_counter/out_index_reg[13]/Q} .original_name {u_counter/out_index[13]/q}}
catch {set_db {pin:proj_top/u_counter/out_index_reg[12]/Q} .original_name {u_counter/out_index[12]/q}}
catch {set_db {pin:proj_top/u_counter/out_index_reg[11]/Q} .original_name {u_counter/out_index[11]/q}}
catch {set_db {pin:proj_top/u_counter/out_index_reg[9]/Q} .original_name {u_counter/out_index[9]/q}}
catch {set_db {pin:proj_top/u_counter/out_index_reg[10]/Q} .original_name {u_counter/out_index[10]/q}}
catch {set_db {pin:proj_top/u_counter/out_index_reg[8]/Q} .original_name {u_counter/out_index[8]/q}}
catch {set_db {pin:proj_top/u_counter/out_index_reg[7]/Q} .original_name {u_counter/out_index[7]/q}}
catch {set_db {pin:proj_top/u_counter/out_index_reg[6]/Q} .original_name {u_counter/out_index[6]/q}}
catch {set_db {pin:proj_top/u_counter/out_index_reg[5]/Q} .original_name {u_counter/out_index[5]/q}}
catch {set_db {pin:proj_top/u_counter/out_index_reg[4]/Q} .original_name {u_counter/out_index[4]/q}}
catch {set_db {pin:proj_top/u_counter/out_index_reg[3]/Q} .original_name {u_counter/out_index[3]/q}}
catch {set_db {pin:proj_top/u_counter/out_index_reg[2]/Q} .original_name {u_counter/out_index[2]/q}}
catch {set_db {pin:proj_top/u_counter/out_index_reg[1]/Q} .original_name {u_counter/out_index[1]/q}}
catch {set_db {pin:proj_top/u_counter/out_index_reg[0]/Q} .original_name {u_counter/out_index[0]/q}}
catch {set_db pin:proj_top/u_counter/count_enabled_reg/Q .original_name u_counter/count_enabled/q}
catch {set_db pin:proj_top/u_counter/start_prev_reg/Q .original_name u_counter/start_prev/q}
catch {set_db {pin:proj_top/u_fm/waddr_reg[4]/Q} .original_name {u_fm/waddr[4]/q}}
catch {set_db {pin:proj_top/u_fm/waddr_reg[3]/Q} .original_name {u_fm/waddr[3]/q}}
catch {set_db {pin:proj_top/u_fm/waddr_reg[2]/Q} .original_name {u_fm/waddr[2]/q}}
catch {set_db {pin:proj_top/u_fm/waddr_reg[1]/Q} .original_name {u_fm/waddr[1]/q}}
catch {set_db {pin:proj_top/u_fm/waddr_reg[0]/Q} .original_name {u_fm/waddr[0]/q}}
catch {set_db {inst:proj_top/u_counter/out_index_reg[14]} .original_name {{u_counter/out_index[14]}}}
catch {set_db {inst:proj_top/u_counter/out_index_reg[13]} .original_name {{u_counter/out_index[13]}}}
catch {set_db {inst:proj_top/u_counter/out_index_reg[12]} .original_name {{u_counter/out_index[12]}}}
catch {set_db {inst:proj_top/u_counter/out_index_reg[11]} .original_name {{u_counter/out_index[11]}}}
catch {set_db {inst:proj_top/u_counter/out_index_reg[9]} .original_name {{u_counter/out_index[9]}}}
catch {set_db {inst:proj_top/u_counter/out_index_reg[10]} .original_name {{u_counter/out_index[10]}}}
catch {set_db {inst:proj_top/u_counter/out_index_reg[8]} .original_name {{u_counter/out_index[8]}}}
catch {set_db {inst:proj_top/u_counter/out_index_reg[7]} .original_name {{u_counter/out_index[7]}}}
catch {set_db {inst:proj_top/u_counter/out_index_reg[6]} .original_name {{u_counter/out_index[6]}}}
catch {set_db {inst:proj_top/u_counter/out_index_reg[5]} .original_name {{u_counter/out_index[5]}}}
catch {set_db {inst:proj_top/u_counter/out_index_reg[4]} .original_name {{u_counter/out_index[4]}}}
catch {set_db {inst:proj_top/u_counter/out_index_reg[3]} .original_name {{u_counter/out_index[3]}}}
catch {set_db {inst:proj_top/u_counter/out_index_reg[2]} .original_name {{u_counter/out_index[2]}}}
catch {set_db {inst:proj_top/u_counter/out_index_reg[1]} .original_name {{u_counter/out_index[1]}}}
catch {set_db {inst:proj_top/u_counter/out_index_reg[0]} .original_name {{u_counter/out_index[0]}}}
catch {set_db inst:proj_top/u_counter/count_enabled_reg .original_name u_counter/count_enabled}
catch {set_db inst:proj_top/u_counter/start_prev_reg .original_name u_counter/start_prev}
catch {set_db {inst:proj_top/u_fm/waddr_reg[4]} .original_name {{u_fm/waddr[4]}}}
catch {set_db {inst:proj_top/u_fm/waddr_reg[3]} .original_name {{u_fm/waddr[3]}}}
catch {set_db {inst:proj_top/u_fm/waddr_reg[2]} .original_name {{u_fm/waddr[2]}}}
catch {set_db {inst:proj_top/u_fm/waddr_reg[1]} .original_name {{u_fm/waddr[1]}}}
catch {set_db {inst:proj_top/u_fm/waddr_reg[0]} .original_name {{u_fm/waddr[0]}}}
