
// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Aug  8 2024 16:20:31 UTC (Aug  8 2024 16:20:31 UTC)

// Verification Directory fv/proj_counter 

module proj_counter(index, finished_count, clk, rst_n);
  input clk, rst_n;
  output [7:0] index;
  output finished_count;
  wire clk, rst_n;
  wire [7:0] index;
  wire finished_count;
  wire n_0, n_1, n_2, n_3, n_4, n_6, n_7;
  assign index[3] = 1'b0;
  assign index[4] = 1'b0;
  assign index[5] = 1'b0;
  assign index[6] = 1'b0;
  assign index[7] = 1'b0;
  A2DFFQ_X2M_A9TL \out_index_reg[2] (.CK (clk), .A (n_7), .B (n_6), .Q
       (index[2]));
  A2DFFQ_X2M_A9TL \out_index_reg[1] (.CK (clk), .A (n_7), .B (n_3), .Q
       (index[1]));
  NOR2_X1A_A9TL g157__2398(.A (finished_count), .B (n_4), .Y (n_6));
  A2DFFQ_X4M_A9TL \out_index_reg[0] (.CK (clk), .A (n_0), .B (n_7), .Q
       (index[0]));
  XNOR2_X0P7M_A9TL g160__5107(.A (n_1), .B (index[2]), .Y (n_4));
  NOR2B_X1M_A9TL g159__6260(.AN (n_2), .B (finished_count), .Y (n_3));
  NOR2XB_X1M_A9TL g158__4319(.A (finished_count), .BN (rst_n), .Y
       (n_7));
  ADDH_X1M_A9TL g162__8428(.A (index[0]), .B (index[1]), .CO (n_1), .S
       (n_2));
  AND3_X1M_A9TL g161__5526(.A (index[2]), .B (index[0]), .C (index[1]),
       .Y (finished_count));
  INV_X1M_A9TL g163(.A (index[0]), .Y (n_0));
endmodule

