
// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Aug 11 2024 19:14:39 UTC (Aug 11 2024 19:14:39 UTC)

// Verification Directory fv/proj_kmer_buffer 

module proj_kmer_buffer(clk, rst_n, in_data, \out_kmer[0] ,
     \out_kmer[1] , \out_kmer[2] , \out_kmer[3] , \out_kmer[4] ,
     \out_kmer[5] , \out_kmer[6] , \out_kmer[7] , \out_kmer[8] ,
     \out_kmer[9] , \out_kmer[10] , \out_kmer[11] , \out_kmer[12] ,
     \out_kmer[13] , \out_kmer[14] , \out_kmer[15] , start_over, full);
  input clk, rst_n, start_over;
  input [1:0] in_data;
  output [1:0] \out_kmer[0] , \out_kmer[1] , \out_kmer[2] ,
       \out_kmer[3] , \out_kmer[4] , \out_kmer[5] , \out_kmer[6] ,
       \out_kmer[7] , \out_kmer[8] , \out_kmer[9] , \out_kmer[10] ,
       \out_kmer[11] , \out_kmer[12] , \out_kmer[13] , \out_kmer[14] ,
       \out_kmer[15] ;
  output full;
  wire clk, rst_n, start_over;
  wire [1:0] in_data;
  wire [1:0] \out_kmer[0] , \out_kmer[1] , \out_kmer[2] , \out_kmer[3]
       , \out_kmer[4] , \out_kmer[5] , \out_kmer[6] , \out_kmer[7] ,
       \out_kmer[8] , \out_kmer[9] , \out_kmer[10] , \out_kmer[11] ,
       \out_kmer[12] , \out_kmer[13] , \out_kmer[14] , \out_kmer[15] ;
  wire full;
  wire [3:0] buffer_count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_37;
  assign \out_kmer[15] [0] = 1'b0;
  assign \out_kmer[15] [1] = 1'b0;
  assign \out_kmer[14] [0] = 1'b0;
  assign \out_kmer[14] [1] = 1'b0;
  assign \out_kmer[13] [0] = 1'b0;
  assign \out_kmer[13] [1] = 1'b0;
  assign \out_kmer[12] [0] = 1'b0;
  assign \out_kmer[12] [1] = 1'b0;
  assign \out_kmer[11] [0] = 1'b0;
  assign \out_kmer[11] [1] = 1'b0;
  assign \out_kmer[10] [0] = 1'b0;
  assign \out_kmer[10] [1] = 1'b0;
  assign \out_kmer[9] [0] = 1'b0;
  assign \out_kmer[9] [1] = 1'b0;
  assign \out_kmer[8] [0] = 1'b0;
  assign \out_kmer[8] [1] = 1'b0;
  DFFRPQN_X1M_A9TL \buffer_count_reg[3] (.R (n_31), .CK (clk), .D
       (n_32), .QN (buffer_count[3]));
  NOR2_X1M_A9TL g151__2398(.A (start_over), .B (n_30), .Y (n_32));
  DFFRPQN_X1M_A9TL \buffer_count_reg[2] (.R (n_31), .CK (clk), .D
       (n_29), .QN (buffer_count[2]));
  XOR2_X0P7M_A9TL g153__5107(.A (n_27), .B (buffer_count[3]), .Y
       (n_30));
  AND2_X1M_A9TL g154__6260(.A (n_1), .B (n_28), .Y (n_29));
  ADDH_X1M_A9TL g155__4319(.A (n_0), .B (n_24), .CO (n_27), .S (n_28));
  DFFRPQN_X1M_A9TL \buffer_count_reg[1] (.R (n_31), .CK (clk), .D
       (n_26), .QN (buffer_count[1]));
  AND2_X1M_A9TL g157__8428(.A (n_19), .B (n_25), .Y (n_26));
  DFFRPQN_X1M_A9TL \buffer_count_reg[0] (.R (n_31), .CK (clk), .D
       (n_37), .QN (buffer_count[0]));
  ADDH_X1M_A9TL g158__5526(.A (n_2), .B (n_21), .CO (n_24), .S (n_25));
  NOR2_X1M_A9TL g161__3680(.A (buffer_count[0]), .B (full), .Y (n_21));
  DFFRPQ_X1M_A9TL \kmer_buffer_reg[15] (.R (n_31), .CK (clk), .D (n_7),
       .Q (\out_kmer[7] [1]));
  DFFRPQ_X1M_A9TL \kmer_buffer_reg[4] (.R (n_31), .CK (clk), .D (n_12),
       .Q (\out_kmer[2] [0]));
  DFFRPQ_X1M_A9TL \kmer_buffer_reg[10] (.R (n_31), .CK (clk), .D
       (n_13), .Q (\out_kmer[5] [0]));
  DFFRPQ_X1M_A9TL \kmer_buffer_reg[8] (.R (n_31), .CK (clk), .D (n_16),
       .Q (\out_kmer[4] [0]));
  DFFRPQ_X1M_A9TL \kmer_buffer_reg[12] (.R (n_31), .CK (clk), .D
       (n_15), .Q (\out_kmer[6] [0]));
  DFFRPQ_X1M_A9TL \kmer_buffer_reg[9] (.R (n_31), .CK (clk), .D (n_17),
       .Q (\out_kmer[4] [1]));
  DFFRPQ_X1M_A9TL \kmer_buffer_reg[7] (.R (n_31), .CK (clk), .D (n_14),
       .Q (\out_kmer[3] [1]));
  DFFRPQ_X1M_A9TL \kmer_buffer_reg[13] (.R (n_31), .CK (clk), .D (n_9),
       .Q (\out_kmer[6] [1]));
  DFFRPQ_X1M_A9TL \kmer_buffer_reg[0] (.R (n_31), .CK (clk), .D (n_8),
       .Q (\out_kmer[0] [0]));
  DFFRPQ_X1M_A9TL \kmer_buffer_reg[5] (.R (n_31), .CK (clk), .D (n_4),
       .Q (\out_kmer[2] [1]));
  DFFRPQ_X1M_A9TL \kmer_buffer_reg[1] (.R (n_31), .CK (clk), .D (n_11),
       .Q (\out_kmer[0] [1]));
  DFFRPQ_X1M_A9TL \kmer_buffer_reg[3] (.R (n_31), .CK (clk), .D (n_5),
       .Q (\out_kmer[1] [1]));
  DFFRPQ_X1M_A9TL \kmer_buffer_reg[11] (.R (n_31), .CK (clk), .D
       (n_18), .Q (\out_kmer[5] [1]));
  DFFRPQ_X1M_A9TL \kmer_buffer_reg[6] (.R (n_31), .CK (clk), .D (n_20),
       .Q (\out_kmer[3] [0]));
  DFFRPQ_X1M_A9TL \kmer_buffer_reg[14] (.R (n_31), .CK (clk), .D
       (n_10), .Q (\out_kmer[7] [0]));
  DFFRPQ_X1M_A9TL \kmer_buffer_reg[2] (.R (n_31), .CK (clk), .D (n_6),
       .Q (\out_kmer[1] [0]));
  NOR3_X2M_A9TL g178__1617(.A (n_3), .B (buffer_count[2]), .C
       (buffer_count[3]), .Y (full));
  AND2_X1M_A9TL g181__2802(.A (\out_kmer[2] [1]), .B (n_19), .Y (n_20));
  AND2_X1M_A9TL g185__1705(.A (\out_kmer[5] [0]), .B (n_19), .Y (n_18));
  AND2_X1M_A9TL g179__5122(.A (\out_kmer[4] [0]), .B (n_19), .Y (n_17));
  AND2_X1M_A9TL g180__8246(.A (\out_kmer[3] [1]), .B (n_19), .Y (n_16));
  AND2_X1M_A9TL g195__7098(.A (\out_kmer[5] [1]), .B (n_19), .Y (n_15));
  AND2_X1M_A9TL g183__6131(.A (\out_kmer[3] [0]), .B (n_19), .Y (n_14));
  AND2_X1M_A9TL g184__1881(.A (\out_kmer[4] [1]), .B (n_19), .Y (n_13));
  AND2_X1M_A9TL g182__5115(.A (\out_kmer[1] [1]), .B (n_19), .Y (n_12));
  AND2_X1M_A9TL g191__7482(.A (in_data[1]), .B (n_19), .Y (n_11));
  AND2_X1M_A9TL g188__4733(.A (\out_kmer[6] [1]), .B (n_19), .Y (n_10));
  AND2_X1M_A9TL g189__6161(.A (\out_kmer[6] [0]), .B (n_19), .Y (n_9));
  AND2_X1M_A9TL g190__9315(.A (in_data[0]), .B (n_19), .Y (n_8));
  AND2_X1M_A9TL g186__9945(.A (\out_kmer[7] [0]), .B (n_19), .Y (n_7));
  AND2_X1M_A9TL g192__2883(.A (\out_kmer[0] [1]), .B (n_19), .Y (n_6));
  AND2_X1M_A9TL g193__2346(.A (\out_kmer[1] [0]), .B (n_19), .Y (n_5));
  AND2_X1M_A9TL g194__1666(.A (\out_kmer[2] [0]), .B (n_19), .Y (n_4));
  OR2_X0P5M_A9TL g187__7410(.A (buffer_count[0]), .B (buffer_count[1]),
       .Y (n_3));
  INV_X1B_A9TL g196(.A (buffer_count[1]), .Y (n_2));
  INV_X2M_A9TL g200(.A (start_over), .Y (n_19));
  INV_X1B_A9TL g199(.A (start_over), .Y (n_1));
  INV_X1B_A9TL g197(.A (buffer_count[2]), .Y (n_0));
  INV_X0P5B_A9TH g198(.A (rst_n), .Y (n_31));
  NOR2_X1A_A9TL g2(.A (start_over), .B (n_21), .Y (n_37));
endmodule

