
// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Aug 11 2024 13:43:34 UTC (Aug 11 2024 13:43:34 UTC)

// Verification Directory fv/proj_kmer_buffer 

module proj_kmer_buffer(clk, rst_n, in_data, \out_kmer[0] ,
     \out_kmer[1] , \out_kmer[2] , \out_kmer[3] , start_over, full);
  input clk, rst_n, start_over;
  input [1:0] in_data;
  output [1:0] \out_kmer[0] , \out_kmer[1] , \out_kmer[2] ,
       \out_kmer[3] ;
  output full;
  wire clk, rst_n, start_over;
  wire [1:0] in_data;
  wire [1:0] \out_kmer[0] , \out_kmer[1] , \out_kmer[2] , \out_kmer[3] ;
  wire full;
  wire [1:0] buffer_count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_12, n_13, n_17;
  DFFRPQN_X1M_A9TL \buffer_count_reg[1] (.R (n_13), .CK (clk), .D
       (n_12), .QN (buffer_count[1]));
  DFFRPQN_X1M_A9TL \buffer_count_reg[0] (.R (n_13), .CK (clk), .D
       (n_17), .QN (buffer_count[0]));
  NOR2_X1B_A9TL g80__2398(.A (start_over), .B (n_9), .Y (n_12));
  XOR2_X0P7M_A9TL g82__6260(.A (n_8), .B (buffer_count[1]), .Y (n_9));
  DFFRPQ_X1M_A9TL \kmer_buffer_reg[2][0] (.R (n_13), .CK (clk), .D
       (n_5), .Q (\out_kmer[2] [0]));
  DFFRPQ_X1M_A9TL \kmer_buffer_reg[2][1] (.R (n_13), .CK (clk), .D
       (n_3), .Q (\out_kmer[2] [1]));
  NOR2_X1M_A9TL g92__4319(.A (buffer_count[0]), .B (full), .Y (n_8));
  DFFRPQ_X1M_A9TL \kmer_buffer_reg[1][1] (.R (n_13), .CK (clk), .D
       (n_6), .Q (\out_kmer[1] [1]));
  DFFRPQ_X1M_A9TL \kmer_buffer_reg[3][0] (.R (n_13), .CK (clk), .D
       (n_4), .Q (\out_kmer[3] [0]));
  DFFRPQ_X1M_A9TL \kmer_buffer_reg[3][1] (.R (n_13), .CK (clk), .D
       (n_2), .Q (\out_kmer[3] [1]));
  DFFRPQ_X1M_A9TL \kmer_buffer_reg[0][0] (.R (n_13), .CK (clk), .D
       (n_1), .Q (\out_kmer[0] [0]));
  DFFRPQ_X1M_A9TL \kmer_buffer_reg[0][1] (.R (n_13), .CK (clk), .D
       (n_0), .Q (\out_kmer[0] [1]));
  DFFRPQ_X1M_A9TL \kmer_buffer_reg[1][0] (.R (n_13), .CK (clk), .D
       (n_7), .Q (\out_kmer[1] [0]));
  NOR2XB_X1M_A9TL g95__8428(.A (start_over), .BN (\out_kmer[0] [0]), .Y
       (n_7));
  NOR2XB_X1M_A9TL g94__5526(.A (start_over), .BN (\out_kmer[0] [1]), .Y
       (n_6));
  NOR2XB_X1M_A9TL g93__6783(.A (start_over), .BN (\out_kmer[1] [0]), .Y
       (n_5));
  NOR2XB_X1M_A9TL g96__3680(.A (start_over), .BN (\out_kmer[2] [0]), .Y
       (n_4));
  NOR2XB_X1M_A9TL g99__1617(.A (start_over), .BN (\out_kmer[1] [1]), .Y
       (n_3));
  NOR2XB_X1M_A9TL g98__2802(.A (start_over), .BN (\out_kmer[2] [1]), .Y
       (n_2));
  NOR2B_X1M_A9TL g97__1705(.AN (in_data[0]), .B (start_over), .Y (n_1));
  NOR2B_X1M_A9TL g100__5122(.AN (in_data[1]), .B (start_over), .Y
       (n_0));
  NOR2_X1B_A9TL g101__8246(.A (buffer_count[0]), .B (buffer_count[1]),
       .Y (full));
  INV_X0P5B_A9TH g102(.A (rst_n), .Y (n_13));
  NOR2_X1A_A9TL g2(.A (start_over), .B (n_8), .Y (n_17));
endmodule

