catch {set_db port:proj_kmer_buffer/clk .original_name clk}
catch {set_db port:proj_kmer_buffer/rst_n .original_name rst_n}
catch {set_db {port:proj_kmer_buffer/in_data[1]} .original_name {in_data[1]}}
catch {set_db {port:proj_kmer_buffer/in_data[0]} .original_name {in_data[0]}}
catch {set_db port:proj_kmer_buffer/start_over .original_name start_over}
catch {set_db {port:proj_kmer_buffer/out_kmer[0][1]} .original_name {out_kmer[0][1]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[0][0]} .original_name {out_kmer[0][0]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[1][1]} .original_name {out_kmer[1][1]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[1][0]} .original_name {out_kmer[1][0]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[2][1]} .original_name {out_kmer[2][1]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[2][0]} .original_name {out_kmer[2][0]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[3][1]} .original_name {out_kmer[3][1]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[3][0]} .original_name {out_kmer[3][0]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[4][1]} .original_name {out_kmer[4][1]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[4][0]} .original_name {out_kmer[4][0]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[5][1]} .original_name {out_kmer[5][1]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[5][0]} .original_name {out_kmer[5][0]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[6][1]} .original_name {out_kmer[6][1]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[6][0]} .original_name {out_kmer[6][0]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[7][1]} .original_name {out_kmer[7][1]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[7][0]} .original_name {out_kmer[7][0]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[8][1]} .original_name {out_kmer[8][1]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[8][0]} .original_name {out_kmer[8][0]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[9][1]} .original_name {out_kmer[9][1]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[9][0]} .original_name {out_kmer[9][0]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[10][1]} .original_name {out_kmer[10][1]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[10][0]} .original_name {out_kmer[10][0]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[11][1]} .original_name {out_kmer[11][1]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[11][0]} .original_name {out_kmer[11][0]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[12][1]} .original_name {out_kmer[12][1]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[12][0]} .original_name {out_kmer[12][0]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[13][1]} .original_name {out_kmer[13][1]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[13][0]} .original_name {out_kmer[13][0]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[14][1]} .original_name {out_kmer[14][1]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[14][0]} .original_name {out_kmer[14][0]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[15][1]} .original_name {out_kmer[15][1]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[15][0]} .original_name {out_kmer[15][0]}}
catch {set_db port:proj_kmer_buffer/full .original_name full}
catch {set_db {pin:proj_kmer_buffer/buffer_count_reg[3]/QN} .original_name {buffer_count[3]/q}}
catch {set_db {pin:proj_kmer_buffer/buffer_count_reg[2]/QN} .original_name {buffer_count[2]/q}}
catch {set_db {pin:proj_kmer_buffer/buffer_count_reg[1]/QN} .original_name {buffer_count[1]/q}}
catch {set_db {pin:proj_kmer_buffer/buffer_count_reg[0]/QN} .original_name {buffer_count[0]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[15]/Q} .original_name {kmer_buffer[15]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[4]/Q} .original_name {kmer_buffer[4]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[10]/Q} .original_name {kmer_buffer[10]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[8]/Q} .original_name {kmer_buffer[8]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[12]/Q} .original_name {kmer_buffer[12]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[9]/Q} .original_name {kmer_buffer[9]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[7]/Q} .original_name {kmer_buffer[7]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[13]/Q} .original_name {kmer_buffer[13]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[0]/Q} .original_name {kmer_buffer[0]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[5]/Q} .original_name {kmer_buffer[5]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[1]/Q} .original_name {kmer_buffer[1]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[3]/Q} .original_name {kmer_buffer[3]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[11]/Q} .original_name {kmer_buffer[11]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[6]/Q} .original_name {kmer_buffer[6]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[14]/Q} .original_name {kmer_buffer[14]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[2]/Q} .original_name {kmer_buffer[2]/q}}
catch {set_db {inst:proj_kmer_buffer/buffer_count_reg[3]} .original_name {{buffer_count[3]}}}
catch {set_db {inst:proj_kmer_buffer/buffer_count_reg[2]} .original_name {{buffer_count[2]}}}
catch {set_db {inst:proj_kmer_buffer/buffer_count_reg[1]} .original_name {{buffer_count[1]}}}
catch {set_db {inst:proj_kmer_buffer/buffer_count_reg[0]} .original_name {{buffer_count[0]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[15]} .original_name {{kmer_buffer[15]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[4]} .original_name {{kmer_buffer[4]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[10]} .original_name {{kmer_buffer[10]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[8]} .original_name {{kmer_buffer[8]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[12]} .original_name {{kmer_buffer[12]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[9]} .original_name {{kmer_buffer[9]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[7]} .original_name {{kmer_buffer[7]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[13]} .original_name {{kmer_buffer[13]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[0]} .original_name {{kmer_buffer[0]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[5]} .original_name {{kmer_buffer[5]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[1]} .original_name {{kmer_buffer[1]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[3]} .original_name {{kmer_buffer[3]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[11]} .original_name {{kmer_buffer[11]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[6]} .original_name {{kmer_buffer[6]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[14]} .original_name {{kmer_buffer[14]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[2]} .original_name {{kmer_buffer[2]}}}
