catch {set_db port:proj_kmer_buffer/clk .original_name clk}
catch {set_db port:proj_kmer_buffer/rst_n .original_name rst_n}
catch {set_db {port:proj_kmer_buffer/in_data[1]} .original_name {in_data[1]}}
catch {set_db {port:proj_kmer_buffer/in_data[0]} .original_name {in_data[0]}}
catch {set_db port:proj_kmer_buffer/start_over .original_name start_over}
catch {set_db {port:proj_kmer_buffer/out_kmer[0][1]} .original_name {out_kmer[0][1]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[0][0]} .original_name {out_kmer[0][0]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[1][1]} .original_name {out_kmer[1][1]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[1][0]} .original_name {out_kmer[1][0]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[2][1]} .original_name {out_kmer[2][1]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[2][0]} .original_name {out_kmer[2][0]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[3][1]} .original_name {out_kmer[3][1]}}
catch {set_db {port:proj_kmer_buffer/out_kmer[3][0]} .original_name {out_kmer[3][0]}}
catch {set_db port:proj_kmer_buffer/full .original_name full}
catch {set_db {pin:proj_kmer_buffer/buffer_count_reg[1]/QN} .original_name {buffer_count[1]/q}}
catch {set_db {pin:proj_kmer_buffer/buffer_count_reg[0]/QN} .original_name {buffer_count[0]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[2][0]/Q} .original_name {kmer_buffer[2][0]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[2][1]/Q} .original_name {kmer_buffer[2][1]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[1][1]/Q} .original_name {kmer_buffer[1][1]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[3][0]/Q} .original_name {kmer_buffer[3][0]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[3][1]/Q} .original_name {kmer_buffer[3][1]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[0][0]/Q} .original_name {kmer_buffer[0][0]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[0][1]/Q} .original_name {kmer_buffer[0][1]/q}}
catch {set_db {pin:proj_kmer_buffer/kmer_buffer_reg[1][0]/Q} .original_name {kmer_buffer[1][0]/q}}
catch {set_db {inst:proj_kmer_buffer/buffer_count_reg[1]} .original_name {{buffer_count[1]}}}
catch {set_db {inst:proj_kmer_buffer/buffer_count_reg[0]} .original_name {{buffer_count[0]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[2][0]} .original_name {{kmer_buffer[2][0]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[2][1]} .original_name {{kmer_buffer[2][1]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[1][1]} .original_name {{kmer_buffer[1][1]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[3][0]} .original_name {{kmer_buffer[3][0]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[3][1]} .original_name {{kmer_buffer[3][1]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[0][0]} .original_name {{kmer_buffer[0][0]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[0][1]} .original_name {{kmer_buffer[0][1]}}}
catch {set_db {inst:proj_kmer_buffer/kmer_buffer_reg[1][0]} .original_name {{kmer_buffer[1][0]}}}
